// Mirrors the live WPF PartyRoomTagCatalog v3. The parity test guards every ID,
// label, parent and legacy alias. Runtime selectable IDs still come from the Host.
const roomGameplayDefinitions = <(String, String, String?)>[
  ("combat", "战斗", null),
  ("pve", "PVE", "combat"),
  ("pve_bounty", "飞船赏金", "pve"),
  ("pve_ship_combat_mission", "飞船战斗任务", "pve"),
  ("pve_outlaw_bounty", "违法飞船赏金", "pve"),
  ("pve_bunker", "地堡清剿", "pve"),
  ("pve_settlement_clearance", "定居点清剿", "pve"),
  ("pve_combined_combat", "综合战斗任务", "pve"),
  ("pvp", "PVP", "combat"),
  ("pvp_dogfight", "舰船狗斗", "pvp"),
  ("pvp_fleet_combat", "多舰对抗", "pvp"),
  ("pvp_fps", "FPS 对抗", "pvp"),
  ("pvp_player_bounty", "玩家赏金", "pvp"),
  ("pvp_piracy", "海盗劫掠", "pvp"),
  ("combat_pve_pvp", "PVE/PVP", "combat"),
  ("combat_pyro_contested_zone", "派罗争夺区", "combat_pve_pvp"),
  ("combat_security_post_raid", "突袭安保站", "combat_pve_pvp"),
  ("industry", "工业", null),
  ("industry_mining", "采矿与精炼", "industry"),
  ("industry_hand_mining", "徒手采矿", "industry_mining"),
  ("industry_vehicle_mining", "地面载具采矿", "industry_mining"),
  ("industry_ship_mining", "单舰采矿", "industry_mining"),
  ("industry_cooperative_mining", "多舰协同采矿", "industry_mining"),
  ("industry_salvage", "打捞", "industry"),
  ("industry_hull_scraping", "船体刮取", "industry_salvage"),
  ("industry_structural_salvage", "结构打捞", "industry_salvage"),
  ("industry_component_recovery", "部件回收", "industry_salvage"),
  ("industry_cooperative_salvage", "多船协同打捞", "industry_salvage"),
  ("industry_repair_engineering", "维修与工程", "industry"),
  ("industry_hull_repair", "船体维修", "industry_repair_engineering"),
  ("industry_ship_engineering", "船内工程", "industry_repair_engineering"),
  ("industry_combat_repair", "战损抢修", "industry_repair_engineering"),
  ("industry_engineering_cooperation", "工程协作", "industry_repair_engineering"),
  ("logistics", "物流与贸易", null),
  ("logistics_contract", "货运合约", "logistics"),
  ("logistics_local_cargo", "本地货运", "logistics_contract"),
  ("logistics_multi_stop_cargo", "多站点货运", "logistics_contract"),
  ("logistics_interstellar_cargo", "跨星系货运", "logistics_contract"),
  ("logistics_industrial_cargo", "工业货运", "logistics_contract"),
  ("logistics_trade", "商品贸易", "logistics"),
  ("logistics_legal_trade", "合法贸易", "logistics_trade"),
  ("logistics_high_value_trade", "高价值贸易", "logistics_trade"),
  ("logistics_grey_trade", "灰色贸易", "logistics_trade"),
  ("logistics_smuggling", "走私", "logistics_trade"),
  ("logistics_cargo_operations", "货物作业", "logistics"),
  ("logistics_loading", "装卸协作", "logistics_cargo_operations"),
  ("logistics_convoy", "商队运输", "logistics_cargo_operations"),
  ("logistics_vehicle_transport", "载具运输", "logistics_cargo_operations"),
  ("logistics_delivery", "配送任务", "logistics"),
  ("logistics_box_delivery", "箱件配送", "logistics_delivery"),
  ("logistics_multi_point_delivery", "多点配送", "logistics_delivery"),
  ("logistics_recovery_delivery", "回收与交付", "logistics_delivery"),
  ("support", "救援与支援", null),
  ("support_medical", "医疗", "support"),
  ("support_field_treatment", "现场救治", "support_medical"),
  ("support_combat_medic", "战地医疗", "support_medical"),
  ("support_casualty_transport", "伤员转运", "support_medical"),
  ("support_search_rescue", "搜索救援", "support"),
  ("support_player_rescue_beacon", "玩家救援信标", "support_search_rescue"),
  ("support_rescue_mission", "搜救任务", "support_search_rescue"),
  ("support_stranded_rescue", "受困人员救援", "support_search_rescue"),
  ("support_personnel_recovery", "人员回收", "support_search_rescue"),
  ("support_ship_service", "舰船服务", "support"),
  ("support_refueling", "舰船加油", "support_ship_service"),
  ("support_towing", "牵引回收", "support_ship_service"),
  ("support_field_repair", "现场维修", "support_ship_service"),
  ("support_ammo_resupply", "弹药与物资补给", "support_ship_service"),
  ("support_escort_security", "护航安保", "support"),
  ("support_cargo_escort", "货运护航", "support_escort_security"),
  ("support_industry_escort", "工业护航", "support_escort_security"),
  ("support_fleet_security", "舰队安保", "support_escort_security"),
  ("support_anti_piracy_patrol", "反海盗巡逻", "support_escort_security"),
  ("exploration", "探索与调查", null),
  ("exploration_exploration", "探索", "exploration"),
  ("exploration_space", "太空探索", "exploration_exploration"),
  ("exploration_planetary", "行星探索", "exploration_exploration"),
  ("exploration_interstellar", "跨星系远征", "exploration_exploration"),
  ("exploration_landmark", "地标探索", "exploration_exploration"),
  ("exploration_recon", "侦察", "exploration"),
  ("exploration_route_recon", "路线勘察", "exploration_recon"),
  ("exploration_frontier_recon", "前沿侦察", "exploration_recon"),
  ("exploration_target_recon", "目标侦察", "exploration_recon"),
  ("exploration_resource_recon", "资源侦察", "exploration_recon"),
  ("exploration_investigation", "调查", "exploration"),
  ("exploration_missing_person", "失踪人员调查", "exploration_investigation"),
  ("exploration_wreck", "残骸调查", "exploration_investigation"),
  ("exploration_cave_search", "洞穴搜索", "exploration_investigation"),
  ("exploration_evidence_recovery", "证据回收", "exploration_investigation"),
  ("arena", "竞技场 AC", null),
  ("arena_pve", "PVE", "arena"),
  ("arena_pirate_swarm", "海盗潮", "arena_pve"),
  ("arena_endless_vanduul_swarm", "无尽剜度潮", "arena_pve"),
  ("arena_ship", "舰船竞技", "arena"),
  ("arena_duel", "单挑", "arena_ship"),
  ("arena_duo", "双人对抗", "arena_ship"),
  ("arena_squadron_battle", "中队战", "arena_ship"),
  ("arena_ship_battle_royale", "舰船大逃杀", "arena_ship"),
  ("arena_fps", "FPS 竞技", "arena"),
  ("arena_elimination", "歼灭战", "arena_fps"),
  ("arena_control_point", "控制点", "arena_fps"),
  ("arena_gun_game", "武器晋级", "arena_fps"),
  ("arena_kill_collect", "击杀收集", "arena_fps"),
  ("arena_racing", "竞速", "arena"),
  ("arena_ship_racing", "舰船竞速", "arena_racing"),
  ("arena_hover_racing", "悬浮载具竞速", "arena_racing"),
  ("arena_free_training", "自由训练", "arena"),
  ("arena_free_flight", "自由飞行", "arena_free_training"),
  ("arena_ship_familiarization", "舰船熟悉", "arena_free_training"),
  ("arena_loadout_test", "武器配装测试", "arena_free_training"),
  ("arena_multicrew_training", "多人船员训练", "arena_free_training"),
  ("social", "社交与休闲", null),
  ("social_sightseeing", "观光摄影", "social"),
  ("social_city_sightseeing", "城市观光", "social_sightseeing"),
  ("social_space_sightseeing", "太空观光", "social_sightseeing"),
  ("social_screenshot_photography", "截图摄影", "social_sightseeing"),
  ("social_gathering", "玩家聚会", "social"),
  ("social_ship_show", "舰船展会", "social_gathering"),
  ("social_vehicle_meet", "载具聚会", "social_gathering"),
  ("social_free_gathering", "自由聚会", "social_gathering"),
  ("social_roleplay", "角色扮演", "social"),
  ("social_fleet_roleplay", "舰队角色扮演", "social_roleplay"),
  ("social_law_roleplay", "执法角色扮演", "social_roleplay"),
  ("social_outlaw_roleplay", "法外角色扮演", "social_roleplay"),
  ("social_beginner", "新手活动", "social"),
  ("social_first_flight", "首次飞行", "social_beginner"),
  ("social_basic_mission", "基础任务", "social_beginner"),
  ("social_mechanics_tutorial", "机制教学", "social_beginner"),
  ("social_ship_experience", "舰船体验", "social_beginner"),
  ("special", "特殊任务与活动", null),
  ("special_stanton", "斯坦顿星系", "special"),
  ("special_stanton_asd_onyx", "ASD玛瑙设施", "special_stanton"),
  ("special_stanton_laser_mining_station", "激光采矿站", "special_stanton"),
  ("special_stanton_siege_orison", "奥里森之围（尚未开始）", "special_stanton"),
  ("special_pyro", "派罗星系", "special"),
  ("special_pyro_asd_stormbreaker", "ASD风暴突破者", "special_pyro"),
  ("special_nyx", "尼克斯星系", "special"),
  ("special_nyx_qv_station", "QV空间站", "special_nyx"),
  ("special_nyx_qv_breaker_yard", "QV碎岩站", "special_nyx"),
  ("special_nyx_strike_group", "战术打击群", "special_nyx"),
  ("undecided", "不知道玩啥", null),
];
const roomContextDefinitions = <(String, String, String)>[
  ("pace_departing_now", "马上出发", "pace"),
  ("pace_casual", "休闲慢玩", "pace"),
  ("pace_efficient", "高效推进", "pace"),
  ("pace_short_session", "短时任务", "pace"),
  ("pace_long_session", "长线游玩", "pace"),
  ("experience_beginner_friendly", "新手友好", "experience"),
  ("experience_teaching", "带新教学", "experience"),
  ("experience_first_try", "首次尝试", "experience"),
  ("experience_familiar", "熟悉机制", "experience"),
  ("experience_hardcore", "硬核协作", "experience"),
  ("experience_roleplay", "角色扮演", "experience"),
  ("need_pilot", "缺飞行员", "need"),
  ("need_gunner", "缺炮手", "need"),
  ("need_ground", "缺地面战斗", "need"),
  ("need_medic", "缺医疗", "need"),
  ("need_engineer", "缺工程", "need"),
  ("need_escort", "缺护航", "need"),
  ("need_cargo", "缺运输", "need"),
  ("need_scout", "缺侦察", "need"),
];
const roomLegacyGameplayIds = <String, String>{
  "pve_space_combat": "pve_ship_combat_mission",
  "pve_beacon": "support_player_rescue_beacon",
  "pve_mercenary": "pve_combined_combat",
  "pve_ground_combat": "pve_bunker",
  "pve_clearance": "pve_settlement_clearance",
  "pve_defense": "pve_bunker",
  "pve_combined_mission": "pve_combined_combat",
  "pve_multistage": "pve_combined_combat",
  "pve_space_ground": "pve_combined_combat",
  "pvp_space_combat": "pvp",
  "pvp_interdiction": "pvp_fleet_combat",
  "pvp_ground_combat": "pvp_fps",
  "pvp_control_point": "arena_control_point",
  "pvp_outlaw": "pvp_piracy",
  "pvp_privateering": "pvp_piracy",
  "industry_gathering": "industry_mining",
  "industry_maintenance": "industry_repair_engineering",
  "industry_engineering": "industry_ship_engineering",
  "industry_repair": "industry_hull_repair",
  "industry_resupply": "support_ammo_resupply",
  "logistics_cargo": "logistics_contract",
  "logistics_hauling": "logistics_local_cargo",
  "logistics_trading": "logistics_legal_trade",
  "logistics_passenger": "logistics_vehicle_transport",
  "logistics_transport": "logistics_vehicle_transport",
  "logistics_shuttle": "logistics_vehicle_transport",
  "support_exploration": "exploration_exploration",
  "support_deep_space": "exploration_space",
  "support_scouting": "exploration_recon",
  "support_route_survey": "exploration_route_recon",
  "support_rescue": "support_search_rescue",
  "support_recovery": "support_personnel_recovery",
  "mixed": "combat_pve_pvp",
  "mixed_security": "support_escort_security",
  "mixed_escort": "support_cargo_escort",
  "mixed_guard": "support_fleet_security",
  "mixed_anti_piracy": "support_anti_piracy_patrol",
  "mixed_large_operation": "combat_pve_pvp",
  "mixed_fleet_operation": "combat_pve_pvp",
  "mixed_multi_party": "combat_pve_pvp",
  "mixed_campaign": "combat_pve_pvp",
  "mixed_open_conflict": "combat_pve_pvp",
  "mixed_pve_pvp": "combat_pve_pvp",
  "mixed_resource_conflict": "combat_pyro_contested_zone",
  "other": "social",
  "other_competition": "arena",
  "other_racing": "arena_racing",
  "other_arena": "arena",
  "other_social": "social",
  "other_free_play": "social_free_gathering",
  "other_roleplay": "social_roleplay",
  "other_sightseeing": "social_sightseeing",
  "other_beginner": "social_beginner",
  "other_beginner_mission": "social_basic_mission",
  "other_first_experience": "social_mechanics_tutorial",
};
