<Project>
  <PropertyGroup>
    <StarBridgeVersion>0.7.0.2</StarBridgeVersion>
    <Version>$(StarBridgeVersion)</Version>
    <FileVersion>$(StarBridgeVersion)</FileVersion>
    <AssemblyVersion>$(StarBridgeVersion)</AssemblyVersion>
    <Authors>StarBridge contributors</Authors>
    <Copyright>Copyright 2026 StarBridge contributors</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Domino-L/StarBridge-OpenCore</RepositoryUrl>
    <StarBridgeIncludeRestrictedGameData>false</StarBridgeIncludeRestrictedGameData>
    <StarBridgeIncludeCommercialAppearances>false</StarBridgeIncludeCommercialAppearances>
    <StarBridgeIncludeThirdPartyMedia>false</StarBridgeIncludeThirdPartyMedia>
  </PropertyGroup>
</Project>
