import 'package:flutter/widgets.dart';

/// Chinese body mirrors MainWindow.Authentication.cs; acknowledgement is unchanged.
String testBuildNoticeBody(Locale locale) => locale.languageCode == 'en'
    ? _english
    : locale.countryCode == 'TW' || locale.scriptCode == 'Hant'
    ? _traditional
    : _simplified;

const _simplified =
    "当前版本仍处于测试阶段。请只从星海舰桥官网或官方 GitHub Release 下载，并在安装前核对 Windows 数字签名和官方公布的 SHA-256。如果安装程序显示“未知发布者”、签名无效或文件哈希不一致，请不要继续安装。\n\n功能、界面、本地设置和联网服务可能继续调整，也可能因游戏、日志、网络、Windows、驱动或安全软件变化而出现中断、延迟、误判或无法使用。\n\n星海舰桥是玩家独立开发的非官方社区工具，未获得 Cloud Imperium Games 或 Roberts Space Industries 针对本应用的书面许可、合规认证或特别豁免。只读 Game.log、使用独立 Windows 浮层且不注入游戏，是当前实现方式，不代表官方认可，也不能完全排除反作弊误报或账号相关风险。\n\n应用提供的舰船、地点、在线状态和事件信息仅供协作参考。请自行判断是否安装和使用，并遵守当时有效的游戏及平台规则；若官方要求与本应用发生冲突，请停止使用受影响功能。\n\n当前测试版不会随包提供来源与再分发授权尚未完成核实的第三方图片，相关位置可能显示占位图。只有完成权利核验并通过发布审计的媒体，才会进入后续正式载荷。\n\n在适用法律允许的最大范围内，作者、维护者和贡献者不对因安装、使用或无法使用本应用而产生的账号措施、游戏内损失、数据损失、软件冲突、协作失误或间接损失承担责任。本声明不排除适用法律不能排除的责任。\n\n继续使用前，请阅读随应用提供的《完整客户端许可条款》。完整条款与上述说明可随时在“帮助与反馈 → 说明与声明”中查看。如果你不接受这些事项，请关闭应用。";

const _traditional =
    "目前版本仍處於測試階段。請只從星海艦橋官網或官方 GitHub Release 下載，並在安裝前核對 Windows 數位簽章和官方公布的 SHA-256。如果安裝程式顯示「未知發行者」、簽章無效或檔案雜湊不一致，請不要繼續安裝。\n\n功能、介面、本機設定和連線服務可能繼續調整，也可能因遊戲、日誌、網路、Windows、驅動程式或安全軟體變化而出現中斷、延遲、誤判或無法使用。\n\n星海艦橋是玩家獨立開發的非官方社群工具，未獲得 Cloud Imperium Games 或 Roberts Space Industries 針對本應用程式的書面許可、合規認證或特別豁免。唯讀 Game.log、使用獨立 Windows 浮層且不注入遊戲，是目前實作方式，不代表官方認可，也不能完全排除反作弊誤報或帳號相關風險。\n\n應用程式提供的艦船、地點、在線狀態和事件資訊僅供協作參考。請自行判斷是否安裝和使用，並遵守當時有效的遊戲及平台規則；若官方要求與本應用程式發生衝突，請停止使用受影響功能。\n\n目前測試版不會隨附來源與再散布授權尚未完成核實的第三方圖片，相關位置可能顯示預留圖。只有完成權利核驗並通過發行稽核的媒體，才會進入後續正式發行套件。\n\n在適用法律允許的最大範圍內，作者、維護者和貢獻者不對因安裝、使用或無法使用本應用程式而產生的帳號措施、遊戲內損失、資料損失、軟體衝突、協作失誤或間接損失承擔責任。本聲明不排除適用法律不能排除的責任。\n\n繼續使用前，請閱讀隨應用程式提供的《完整用戶端授權條款》。完整條款與上述說明可隨時在「幫助與回饋 → 說明與聲明」中查看。如果你不接受這些事項，請關閉應用程式。";

const _english =
    "This version is still in testing. Download only from the StarBridge website or official GitHub Releases, and verify the Windows digital signature and published SHA-256 before installation. Do not continue if the installer shows an unknown publisher, the signature is invalid, or the file hash does not match.\n\nFeatures, the interface, local settings and online services may continue to change. Changes to the game, logs, network, Windows, drivers or security software may cause interruptions, delays, incorrect results or loss of functionality.\n\nStarBridge is an unofficial community tool independently developed by players. It has not received written permission, compliance certification or a special exemption from Cloud Imperium Games or Roberts Space Industries for this application. Reading Game.log without modifying it, using a separate Windows overlay and not injecting into the game describe the current implementation; they do not imply official approval or eliminate the possibility of anti-cheat false positives or account-related risks.\n\nShip, location, presence and event information is provided only as a reference for collaboration. Decide for yourself whether to install and use the application, and comply with the game and platform rules in effect at the time. If official requirements conflict with the application, stop using the affected features.\n\nThis test version does not bundle third-party images whose provenance and redistribution rights have not been verified; placeholders may appear instead. Only media that passes rights verification and release review will be included in subsequent official packages.\n\nTo the maximum extent permitted by applicable law, the authors, maintainers and contributors are not liable for account actions, in-game losses, data loss, software conflicts, collaboration errors or indirect losses arising from installing, using or being unable to use this application. This notice does not exclude liability that cannot be excluded under applicable law.\n\nBefore continuing, read the full client license terms supplied with the application. The terms and this notice are also available under Help & Feedback → Information & Notices. Close the application if you do not accept these matters.";
