import 'package:flutter/widgets.dart';

String applicationSupportCopy(BuildContext context, String key) {
  final locale = Localizations.localeOf(context);
  final values = locale.languageCode == 'en'
      ? _english
      : locale.countryCode == 'TW' || locale.scriptCode == 'Hant'
      ? _traditional
      : _simplified;
  return values[key] ?? key;
}

const _simplified = <String, String>{
  'checkedAt': '最近检查：',
  'item.connection': '服务器连接',
  'detail.connectionHealthy': '当前配置的服务可以连接。',
  'detail.connectionFailed': '服务返回异常状态，请稍后重新检查。',
  'detail.connectionUnavailable': '暂时无法确认连接，本地检查结果仍然有效。',
  'title': '诊断与维护',
  'description': '检查当前设备的本地数据、游戏日志、开机启动和安装状态。',
  'summary.healthy': '当前检查项目均正常',
  'summary.issues': '有项目需要处理',
  'summary.partial': '部分项目暂时无法检查',
  'item.dataDirectory': '本地数据',
  'item.gameLog': '游戏日志',
  'item.startup': '开机启动',
  'item.installation': '安装状态',
  'state.healthy': '正常',
  'state.actionRequired': '需要处理',
  'state.unavailable': '暂时无法检查',
  'detail.writable': '数据目录可以正常写入。',
  'detail.pathNotConfigured': '尚未配置数据目录。',
  'detail.pathMissing': '数据目录不存在。',
  'detail.accessDenied': 'Windows 拒绝访问，请检查文件夹权限。',
  'detail.writeFailed': '无法写入数据目录。',
  'detail.notConfigured': '尚未选择 Game.log。',
  'detail.fileMissing': '已选择的 Game.log 不存在。',
  'detail.selectionUnavailable': '暂时无法读取游戏日志选择。',
  'detail.readable': 'Game.log 存在且可以读取。',
  'detail.readFailed': '当前文件或注册信息无法读取。',
  'detail.notEnabled': '当前未启用开机启动。',
  'detail.invalidCommand': '开机启动项格式无效。',
  'detail.enabled': '开机启动项指向当前客户端。',
  'detail.targetMismatch': '开机启动项指向其他客户端副本。',
  'detail.targetMissing': '开机启动项指向的程序不存在。',
  'detail.portable': '当前是便携运行方式，未发现安装残留。',
  'detail.installed': '当前正式安装状态正常。',
  'detail.scanPartial': '部分 Windows 安装信息无法读取。',
  'detail.duplicateInstallations': '发现其他或重复安装。',
  'detail.staleRegistrations': '发现失效的安装记录。',
  'detail.currentInstallationMissing': '未找到当前客户端对应的安装记录。',
  'count.otherInstallations': '其他安装',
  'count.orphanedRegistrations': '失效记录',
  'count.scanWarnings': '未完成检查',
  'action.refresh': '重新检查',
  'action.copy': '复制安全摘要',
  'action.openDataDirectory': '打开数据目录',
  'copied': '诊断摘要已复制',
  'openedDataDirectory': '已打开数据目录',
  'openDataDirectoryFailed': '未能打开数据目录，请稍后重试。',
  'openDataDirectoryHostUnavailable': '后台服务暂时不可用，请稍后重试。',
  'error.title': '暂时无法完成检查',
  'error.hostUnavailable': '后台服务暂时不可用，请稍后重试。',
  'error.timeout': '检查等待超时，请重试。',
  'error.inspectionFailed': '检查没有完成，请稍后重试。',
  'error.invalidResponse': '检查结果与当前客户端不兼容。',
};

const _traditional = <String, String>{
  'checkedAt': '最近檢查：',
  'item.connection': '伺服器連線',
  'detail.connectionHealthy': '目前設定的服務可以連線。',
  'detail.connectionFailed': '服務回傳異常狀態，請稍後重新檢查。',
  'detail.connectionUnavailable': '暫時無法確認連線，本機檢查結果仍然有效。',
  'title': '診斷與維護',
  'description': '檢查目前裝置的本機資料、遊戲記錄、開機啟動與安裝狀態。',
  'summary.healthy': '目前檢查項目均正常',
  'summary.issues': '有項目需要處理',
  'summary.partial': '部分項目暫時無法檢查',
  'item.dataDirectory': '本機資料',
  'item.gameLog': '遊戲記錄',
  'item.startup': '開機啟動',
  'item.installation': '安裝狀態',
  'state.healthy': '正常',
  'state.actionRequired': '需要處理',
  'state.unavailable': '暫時無法檢查',
  'detail.writable': '資料目錄可以正常寫入。',
  'detail.pathNotConfigured': '尚未設定資料目錄。',
  'detail.pathMissing': '資料目錄不存在。',
  'detail.accessDenied': 'Windows 拒絕存取，請檢查資料夾權限。',
  'detail.writeFailed': '無法寫入資料目錄。',
  'detail.notConfigured': '尚未選擇 Game.log。',
  'detail.fileMissing': '已選擇的 Game.log 不存在。',
  'detail.selectionUnavailable': '暫時無法讀取遊戲記錄選擇。',
  'detail.readable': 'Game.log 存在且可以讀取。',
  'detail.readFailed': '目前檔案或登錄資訊無法讀取。',
  'detail.notEnabled': '目前未啟用開機啟動。',
  'detail.invalidCommand': '開機啟動項目格式無效。',
  'detail.enabled': '開機啟動項目指向目前客戶端。',
  'detail.targetMismatch': '開機啟動項目指向其他客戶端副本。',
  'detail.targetMissing': '開機啟動項目指向的程式不存在。',
  'detail.portable': '目前是可攜式執行方式，未發現安裝殘留。',
  'detail.installed': '目前正式安裝狀態正常。',
  'detail.scanPartial': '部分 Windows 安裝資訊無法讀取。',
  'detail.duplicateInstallations': '發現其他或重複安裝。',
  'detail.staleRegistrations': '發現失效的安裝記錄。',
  'detail.currentInstallationMissing': '未找到目前客戶端對應的安裝記錄。',
  'count.otherInstallations': '其他安裝',
  'count.orphanedRegistrations': '失效記錄',
  'count.scanWarnings': '未完成檢查',
  'action.refresh': '重新檢查',
  'action.copy': '複製安全摘要',
  'action.openDataDirectory': '開啟資料目錄',
  'copied': '診斷摘要已複製',
  'openedDataDirectory': '已開啟資料目錄',
  'openDataDirectoryFailed': '未能開啟資料目錄，請稍後再試。',
  'openDataDirectoryHostUnavailable': '背景服務暫時無法使用，請稍後再試。',
  'error.title': '暫時無法完成檢查',
  'error.hostUnavailable': '背景服務暫時無法使用，請稍後再試。',
  'error.timeout': '檢查等待逾時，請重試。',
  'error.inspectionFailed': '檢查未完成，請稍後再試。',
  'error.invalidResponse': '檢查結果與目前客戶端不相容。',
};

const _english = <String, String>{
  'checkedAt': 'Last checked:',
  'item.connection': 'Server connection',
  'detail.connectionHealthy': 'The configured service is reachable.',
  'detail.connectionFailed': 'The service reported a problem. Check again later.',
  'detail.connectionUnavailable': 'Connection could not be checked. Local results remain valid.',
  'title': 'Diagnostics & maintenance',
  'description': 'Check local data, Game.log, Windows startup, and installation status on this device.',
  'summary.healthy': 'All checked items look good',
  'summary.issues': 'Some items need attention',
  'summary.partial': 'Some items could not be checked',
  'item.dataDirectory': 'Local data',
  'item.gameLog': 'Game log',
  'item.startup': 'Windows startup',
  'item.installation': 'Installation',
  'state.healthy': 'Normal',
  'state.actionRequired': 'Needs attention',
  'state.unavailable': 'Could not check',
  'detail.writable': 'The data folder is writable.',
  'detail.pathNotConfigured': 'No data folder is configured.',
  'detail.pathMissing': 'The data folder does not exist.',
  'detail.accessDenied': 'Windows denied access. Check the folder permissions.',
  'detail.writeFailed': 'The data folder could not be written.',
  'detail.notConfigured': 'Game.log has not been selected.',
  'detail.fileMissing': 'The selected Game.log does not exist.',
  'detail.selectionUnavailable': 'The Game.log selection could not be read.',
  'detail.readable': 'Game.log exists and can be read.',
  'detail.readFailed': 'The file or registry information could not be read.',
  'detail.notEnabled': 'Start with Windows is off.',
  'detail.invalidCommand': 'The Windows startup entry is invalid.',
  'detail.enabled': 'The Windows startup entry points to this client.',
  'detail.targetMismatch': 'The Windows startup entry points to another copy.',
  'detail.targetMissing':
      'The program referenced by Windows startup is missing.',
  'detail.portable':
      'This is a portable copy and no installation residue was found.',
  'detail.installed': 'The installed application looks healthy.',
  'detail.scanPartial':
      'Some Windows installation information could not be read.',
  'detail.duplicateInstallations':
      'Another or duplicate installation was found.',
  'detail.staleRegistrations': 'A stale installation record was found.',
  'detail.currentInstallationMissing':
      'No installation record matches this client.',
  'count.otherInstallations': 'Other installations',
  'count.orphanedRegistrations': 'Stale records',
  'count.scanWarnings': 'Unchecked sources',
  'action.refresh': 'Check again',
  'action.copy': 'Copy safe summary',
  'action.openDataDirectory': 'Open data folder',
  'copied': 'Diagnostic summary copied',
  'openedDataDirectory': 'Data folder opened',
  'openDataDirectoryFailed': 'The data folder could not be opened. Try again.',
  'openDataDirectoryHostUnavailable':
      'The background service is unavailable. Try again shortly.',
  'error.title': 'The check could not be completed',
  'error.hostUnavailable':
      'The background service is unavailable. Try again shortly.',
  'error.timeout': 'The check timed out. Try again.',
  'error.inspectionFailed': 'The check did not finish. Try again shortly.',
  'error.invalidResponse': 'The result is not compatible with this client.',
};
