import 'package:flutter/foundation.dart';

enum OverlayWorkspaceFieldKind {
  toggle,
  choice,
  readOnlyChoice,
  numberChoice,
  number,
  color,
  eventTypes,
  eventDurations,
}

@immutable
final class OverlayWorkspaceFieldSpec {
  const OverlayWorkspaceFieldSpec(
    this.field,
    this.group,
    this.kind,
    this.labelZh, {
    this.options = const [],
    this.selectableOptions = const [],
    this.numberOptions = const [],
    this.minimum = 0,
    this.maximum = 1,
    this.divisions,
    this.userVisible = true,
  });

  final String field;
  final String group;
  final OverlayWorkspaceFieldKind kind;
  final String labelZh;
  final List<String> options;
  final List<String> selectableOptions;
  final List<num> numberOptions;
  final double minimum;
  final double maximum;
  final int? divisions;
  final bool userVisible;
}

const overlayWorkspaceGroupOrder = <String>[
  'notice',
  'fleetOverview',
  'members',
  'chat',
  'events',
  'crosshair',
  'appearance',
  'startup',
];

const overlayWorkspaceNavigationGroupOrder = <String>[
  'notice',
  'fleetOverview',
  'members',
  'chat',
  'events',
  'crosshair',
  'startup',
];

const overlayWorkspaceFieldSpecs = <OverlayWorkspaceFieldSpec>[
  OverlayWorkspaceFieldSpec(
    'memberNameMode',
    'members',
    OverlayWorkspaceFieldKind.choice,
    '成员名称',
    options: ['CallsignAndGameName', 'CallsignOnly', 'GameNameOnly'],
  ),
  OverlayWorkspaceFieldSpec(
    'hideOfflineMembers',
    'members',
    OverlayWorkspaceFieldKind.toggle,
    '隐藏离线成员',
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'hideSquadIcons',
    'fleetOverview',
    OverlayWorkspaceFieldKind.toggle,
    '隐藏小队图标',
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'enableTrayMode',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '启用托盘模式',
  ),
  OverlayWorkspaceFieldSpec(
    'opacity',
    'appearance',
    OverlayWorkspaceFieldKind.number,
    '浮层整体透明度',
    minimum: 0.15,
    maximum: 1,
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'showNotice',
    'notice',
    OverlayWorkspaceFieldKind.toggle,
    '显示公告',
  ),
  OverlayWorkspaceFieldSpec(
    'showSquads',
    'fleetOverview',
    OverlayWorkspaceFieldKind.toggle,
    '显示舰队总览',
  ),
  OverlayWorkspaceFieldSpec(
    'showMembers',
    'members',
    OverlayWorkspaceFieldKind.toggle,
    '显示成员',
  ),
  OverlayWorkspaceFieldSpec(
    'hideMemberOnlineStatus',
    'members',
    OverlayWorkspaceFieldKind.toggle,
    '隐藏成员在线状态',
  ),
  OverlayWorkspaceFieldSpec(
    'squadStatusDisplayMode',
    'fleetOverview',
    OverlayWorkspaceFieldKind.choice,
    '小队状态显示',
    options: ['Auto', 'Compact', 'Detailed'],
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'hideSelfMember',
    'members',
    OverlayWorkspaceFieldKind.toggle,
    '在成员列表中隐藏自己',
  ),
  OverlayWorkspaceFieldSpec(
    'memberPriorityMode',
    'members',
    OverlayWorkspaceFieldKind.choice,
    '成员排序优先项',
    options: ['Default', 'Self', 'SquadCommander'],
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'memberScopeMode',
    'members',
    OverlayWorkspaceFieldKind.choice,
    '成员显示范围',
    options: ['CurrentSquad', 'AllFleet', 'OtherSquads'],
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'memberNameColumnRatio',
    'members',
    OverlayWorkspaceFieldKind.number,
    '成员名称列宽',
    minimum: 0.18,
    maximum: 0.82,
    divisions: 64,
  ),
  OverlayWorkspaceFieldSpec(
    'scenePreference',
    'startup',
    OverlayWorkspaceFieldKind.choice,
    '默认信息场景',
    options: ['Auto', 'Fleet', 'PartyRoom'],
  ),

  OverlayWorkspaceFieldSpec(
    'skin',
    'appearance',
    OverlayWorkspaceFieldKind.choice,
    '界面皮肤',
    options: ['Default', 'NightShadow', 'LagrangeWeave', 'Verdict'],
    selectableOptions: ['Default', 'NightShadow', 'Verdict'],
  ),
  OverlayWorkspaceFieldSpec(
    'theme',
    'appearance',
    OverlayWorkspaceFieldKind.choice,
    '主题色',
    options: [
      'Default',
      'Anvil',
      'Drake',
      'Argo',
      'Mirai',
      'Crusader',
      'Aegis',
      'Rsi',
      'Origin',
      'Aopoa',
      'Esperia',
      'Gatac',
      'Musashi',
      'NightShadow',
      'LagrangeWeave',
      'Verdict',
    ],
    selectableOptions: [
      'Default',
      'Anvil',
      'Drake',
      'Argo',
      'Musashi',
      'Mirai',
      'Crusader',
      'Aegis',
      'Rsi',
      'Origin',
      'Aopoa',
      'Esperia',
      'Gatac',
    ],
  ),
  OverlayWorkspaceFieldSpec(
    'autoThemeByShip',
    'appearance',
    OverlayWorkspaceFieldKind.toggle,
    '根据当前舰船自动切换主题',
  ),
  OverlayWorkspaceFieldSpec(
    'nightShadowBloom',
    'appearance',
    OverlayWorkspaceFieldKind.choice,
    '暗影主题辉光',
    options: ['Off', 'Standard', 'Strong'],
  ),
  OverlayWorkspaceFieldSpec(
    'animationFrameRate',
    'appearance',
    OverlayWorkspaceFieldKind.choice,
    '浮层动画帧率',
    options: ['Off', 'Fps30', 'Fps60', 'Fps120'],
  ),
  OverlayWorkspaceFieldSpec(
    'requestedSkin',
    'appearance',
    OverlayWorkspaceFieldKind.choice,
    '指定皮肤',
    options: ['Default', 'NightShadow', 'LagrangeWeave', 'Verdict'],
    userVisible: false,
  ),

  OverlayWorkspaceFieldSpec(
    'showCrosshair',
    'crosshair',
    OverlayWorkspaceFieldKind.toggle,
    '显示准星',
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairMode',
    'crosshair',
    OverlayWorkspaceFieldKind.choice,
    '准星样式',
    options: ['Cross', 'Dot', 'Circle', 'TShape'],
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairUseThemeColor',
    'crosshair',
    OverlayWorkspaceFieldKind.toggle,
    '准星跟随主题色',
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairColor',
    'crosshair',
    OverlayWorkspaceFieldKind.color,
    '准星颜色',
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairSize',
    'crosshair',
    OverlayWorkspaceFieldKind.number,
    '准星尺寸',
    minimum: 8,
    maximum: 240,
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairThickness',
    'crosshair',
    OverlayWorkspaceFieldKind.number,
    '准星线宽',
    minimum: 1,
    maximum: 8,
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairOpacity',
    'crosshair',
    OverlayWorkspaceFieldKind.number,
    '准星透明度',
    minimum: 0.2,
    maximum: 1,
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairShowCenterMark',
    'crosshair',
    OverlayWorkspaceFieldKind.toggle,
    '显示准星中心点',
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairCenterMarkSize',
    'crosshair',
    OverlayWorkspaceFieldKind.number,
    '中心点尺寸',
    maximum: 18,
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairGap',
    'crosshair',
    OverlayWorkspaceFieldKind.number,
    '准星中心间距',
    minimum: 6,
    maximum: 28,
  ),
  OverlayWorkspaceFieldSpec(
    'crosshairOutlineOpacity',
    'crosshair',
    OverlayWorkspaceFieldKind.number,
    '准星描边透明度',
    maximum: 0.8,
  ),

  OverlayWorkspaceFieldSpec(
    'enableStartupTransition',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '显示浮层启动效果',
  ),
  OverlayWorkspaceFieldSpec(
    'startupTransitionStyle',
    'startup',
    OverlayWorkspaceFieldKind.readOnlyChoice,
    '启动效果样式',
    options: [
      'BridgeTerminal',
      'NightShadowFlowField',
      'NightShadowSilentAssassination',
      'NightShadowBlackCurtainTear',
      'NightShadowBladeCurtainUnfold',
      'NightShadowCrimsonFold',
      'LagrangeWeaveEquilibrium',
      'VerdictProtocol',
    ],
  ),
  OverlayWorkspaceFieldSpec(
    'autoFocusGameWindowOnOpen',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '打开浮层后返回游戏',
  ),
  OverlayWorkspaceFieldSpec(
    'startupTransitionFollowOverlayTheme',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '启动效果跟随浮层主题',
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'startupTransitionFrameRate',
    'startup',
    OverlayWorkspaceFieldKind.choice,
    '启动效果帧率',
    options: ['Fps30', 'Fps45', 'Fps60', 'Fps120'],
  ),
  OverlayWorkspaceFieldSpec(
    'autoOpenOverlayOnGameStart',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '游戏启动时自动打开浮层',
  ),
  OverlayWorkspaceFieldSpec(
    'autoOpenOverlayOnGameForeground',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '进入游戏窗口时自动打开浮层',
  ),
  OverlayWorkspaceFieldSpec(
    'autoCloseOverlayOnGameBackground',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '离开游戏窗口时自动关闭浮层',
  ),
  OverlayWorkspaceFieldSpec(
    'skipStartupTransitionWhenGameForeground',
    'startup',
    OverlayWorkspaceFieldKind.toggle,
    '游戏已在前台时跳过启动效果',
  ),

  OverlayWorkspaceFieldSpec(
    'showEventNotifications',
    'events',
    OverlayWorkspaceFieldKind.toggle,
    '显示事件通知',
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationSide',
    'events',
    OverlayWorkspaceFieldKind.choice,
    '通知出现位置',
    options: ['Left', 'Right'],
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationDurationSeconds',
    'events',
    OverlayWorkspaceFieldKind.number,
    '默认通知时长',
    minimum: 1,
    maximum: 12,
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationY',
    'events',
    OverlayWorkspaceFieldKind.number,
    '通知垂直位置',
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationTypes',
    'events',
    OverlayWorkspaceFieldKind.eventTypes,
    '通知事件',
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationMaxVisibleCount',
    'events',
    OverlayWorkspaceFieldKind.numberChoice,
    '同时显示通知数',
    numberOptions: [1, 2, 3, 4, 5],
    minimum: 1,
    maximum: 5,
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationPinImportant',
    'events',
    OverlayWorkspaceFieldKind.toggle,
    '优先保留重要通知',
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationAnimationSpeed',
    'events',
    OverlayWorkspaceFieldKind.choice,
    '通知动画速度',
    options: ['Slow', 'Normal', 'Fast'],
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationDurations',
    'events',
    OverlayWorkspaceFieldKind.eventDurations,
    '各类通知时长',
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationTextOpacity',
    'events',
    OverlayWorkspaceFieldKind.number,
    '通知文字透明度',
    minimum: 0.15,
    maximum: 1,
    divisions: 85,
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationBackgroundOpacity',
    'events',
    OverlayWorkspaceFieldKind.number,
    '通知背景透明度',
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'eventNotificationDecorationOpacity',
    'events',
    OverlayWorkspaceFieldKind.number,
    '外观装饰透明度',
    userVisible: false,
  ),

  OverlayWorkspaceFieldSpec(
    'showChat',
    'chat',
    OverlayWorkspaceFieldKind.toggle,
    '显示聊天',
  ),
  OverlayWorkspaceFieldSpec(
    'chatDisplayMode',
    'chat',
    OverlayWorkspaceFieldKind.choice,
    '聊天显示方式',
    options: ['MessageList', 'FullScreenBarrage'],
  ),
  OverlayWorkspaceFieldSpec(
    'chatSide',
    'chat',
    OverlayWorkspaceFieldKind.choice,
    '聊天出现位置',
    options: ['Left', 'Right'],
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'chatMaxVisibleCount',
    'chat',
    OverlayWorkspaceFieldKind.number,
    '同时显示消息数',
    minimum: 1,
    maximum: 8,
    divisions: 7,
    userVisible: false,
  ),
  OverlayWorkspaceFieldSpec(
    'chatDurationSeconds',
    'chat',
    OverlayWorkspaceFieldKind.numberChoice,
    '弹幕速度',
    numberOptions: [6, 8, 12, 16, 20],
    minimum: 6,
    maximum: 20,
  ),
  OverlayWorkspaceFieldSpec(
    'chatShowSender',
    'chat',
    OverlayWorkspaceFieldKind.toggle,
    '显示发送者',
  ),
  OverlayWorkspaceFieldSpec(
    'chatShowTimestamp',
    'chat',
    OverlayWorkspaceFieldKind.toggle,
    '显示发送时间',
  ),
  OverlayWorkspaceFieldSpec(
    'chatShowSystemMessages',
    'chat',
    OverlayWorkspaceFieldKind.toggle,
    '显示系统消息',
  ),
  OverlayWorkspaceFieldSpec(
    'chatHideSelfMessages',
    'chat',
    OverlayWorkspaceFieldKind.toggle,
    '隐藏自己发送的消息',
  ),
  OverlayWorkspaceFieldSpec(
    'chatBarrageFontSize',
    'chat',
    OverlayWorkspaceFieldKind.numberChoice,
    '弹幕字号',
    numberOptions: [14, 16, 20, 24],
    minimum: 14,
    maximum: 24,
  ),
  OverlayWorkspaceFieldSpec(
    'chatBarrageRegion',
    'chat',
    OverlayWorkspaceFieldKind.choice,
    '弹幕区域',
    options: ['Upper', 'UpperMiddle', 'FullScreen'],
  ),
  OverlayWorkspaceFieldSpec(
    'chatBarrageDensity',
    'chat',
    OverlayWorkspaceFieldKind.choice,
    '弹幕密度',
    options: ['Sparse', 'Standard', 'Dense'],
  ),
  OverlayWorkspaceFieldSpec(
    'chatBarrageAvoidCenter',
    'chat',
    OverlayWorkspaceFieldKind.toggle,
    '弹幕避开屏幕中心',
  ),
  OverlayWorkspaceFieldSpec(
    'chatTextEdgeStrength',
    'chat',
    OverlayWorkspaceFieldKind.choice,
    '聊天文字描边',
    options: ['Off', 'Light', 'Standard', 'Strong'],
  ),

  OverlayWorkspaceFieldSpec(
    'communicationFriendEvents',
    'notice',
    OverlayWorkspaceFieldKind.toggle,
    '显示好友动态',
  ),
  OverlayWorkspaceFieldSpec(
    'communicationMessagePreview',
    'notice',
    OverlayWorkspaceFieldKind.toggle,
    '显示消息内容预览',
  ),
  OverlayWorkspaceFieldSpec(
    'communicationEventDurationSeconds',
    'notice',
    OverlayWorkspaceFieldKind.number,
    '通讯提醒时长',
    minimum: 2,
    maximum: 12,
    divisions: 40,
  ),
  OverlayWorkspaceFieldSpec(
    'fleetChatScope',
    'notice',
    OverlayWorkspaceFieldKind.choice,
    '舰队聊天范围',
    options: ['Fleet'],
    userVisible: false,
  ),
];

const overlayWorkspaceRetiredFields = <String>{
  'hideMissionWhenIdle',
  'showMission',
};

const overlayEventTypes = <(int, String)>[
  (1, '成员上线与离线'),
  (2, '成员服务器变化'),
  (4, '进入相同服务器'),
  (8, '舰船变化'),
  (16, '位置变化'),
  (128, '在线成员汇总'),
  (256, '主服务器变化'),
  (512, '死亡与重生'),
];

const overlayDurationFields = <(String, String)>[
  ('memberPresence', '成员上线与离线'),
  ('memberServer', '成员服务器变化'),
  ('sameServer', '进入相同服务器'),
  ('shipChange', '舰船变化'),
  ('locationChange', '位置变化'),
  ('onlineSummary', '在线成员汇总'),
  ('primaryServer', '主服务器变化'),
  ('deathAndRespawn', '死亡与重生'),
  ('localPlayReminder', '本地游玩提醒'),
];
