import 'general_settings_strings.dart';
import 'notification_settings_strings.dart';
import 'notification_audio_strings.dart';
import 'profile_settings_strings.dart';
import 'official_fleet_strings.dart';
import 'party_rooms_strings.dart';
import 'friends_strings.dart';
import 'communities_strings.dart';
import 'settings_capability_strings.dart';
import 'sync_privacy_strings.dart';
import 'local_privacy_strings.dart';
import 'privacy_scope_settings_strings.dart';
import 'legacy_migration_strings.dart';
import 'local_profile_strings.dart';
import 'startup_strings.dart';
import 'gameplay_time_strings.dart';
import 'game_log_strings.dart';
import 'help_support_strings.dart';
import 'overlay_settings_strings.dart';
import 'home_strings.dart';

const simplifiedAppStrings = <String, String>{
  'app.name': '星海舰桥',
  'navigation.home': '首页',
  'navigation.home.description': '当前态势与下一步',
  'navigation.rooms': '房间',
  'navigation.rooms.description': '随性组队与即时协作',
  'navigation.operations': '行动',
  'navigation.operations.description': '组织与舰队的目标性协作',
  'navigation.officialFleet': '主舰队',
  'navigation.officialFleet.description': 'RSI 官网主舰队工作区',
  'navigation.marketplace': '交易大厅',
  'navigation.marketplace.description': '交易与服务入口（首发暂未开放）',
  'navigation.communities': '社区组织',
  'navigation.communities.description': '跨舰队长期协作组织',
  'navigation.hangar': '个人机库',
  'navigation.hangar.description': '舰船、配置与共享范围',
  'navigation.overlay': '浮层',
  'navigation.overlay.description': '游戏内信息场景与布局',
  'navigation.tools': '工具',
  'navigation.tools.description': '个人辅助工具（首发暂未开放）',
  'navigation.settings': '设置',
  'navigation.settings.description': '明暗、语言与客户端偏好',
  'navigation.friends': '好友',
  'navigation.friends.description': '好友、私信与最近玩过',
  'navigation.notifications': '通知',
  'navigation.notifications.description': '系统与协作更新',
  'navigation.account': '账号',
  'navigation.account.description': '身份与个人资料',
  'navigation.profile': '个人页面',
  'navigation.profile.description': '公开资料与主页展示',
  'navigation.personal': '个人空间',
  'deferredFeature.title': '该入口尚未开放',
  'deferredFeature.marketplace.body': '交易与服务能力将在 Flutter 客户端稳定后接入；首发仅保留这个固定入口。',
  'deferredFeature.tools.body': '个人辅助工具将在后续阶段逐项接入；首发不会提供无效按钮或模拟功能。',
  'top.overlayScene': '浮层场景',
  'top.friends': '好友',
  'top.notifications': '通知',
  'top.account': '账号',
  'exampleScene.open': '打开示例场景',
  'exampleScene.compact': '示例',
  'exampleScene.exit': '退出示例',
  'exampleScene.notice.title': '当前为示例场景',
  'exampleScene.notice.body': '演示账号与示例数据仅用于检查界面，不会读取或修改真实账号。',
  ...simplifiedProfileSettingsStrings,
  ...simplifiedGeneralSettingsStrings,
  ...simplifiedNotificationSettingsStrings,
  ...audioZh,
  ...simplifiedSettingsCapabilityStrings,
  ...simplifiedSyncPrivacyStrings,
  ...simplifiedLocalPrivacyStrings,
  ...simplifiedPrivacyScopeSettingsStrings,
  ...simplifiedOfficialFleetStrings,
  ...simplifiedPartyRoomsStrings,
  ...friendsZhCn,
  ...communitiesZhCn,
  ...simplifiedLegacyMigrationStrings,
  ...simplifiedLocalProfileStrings,
  ...simplifiedStartupStrings,
  ...gameplayTimeZhCn,
  ...gameLogZhCn,
  ...helpSupportZhCn,
  ...overlaySettingsZhCn,
  ...homeZhCn,
  'account.notSignedIn': '未登录',
  'account.loading': '正在读取账号状态…',
  'account.signedOut.title': '使用 SCM 账号继续',
  'account.signedOut.body': '授权在系统浏览器中完成。登录凭据由本机账号服务安全保管，不会进入界面页面。',
  'account.credentialUnavailable.title': 'SCM 暂时不可用',
  'account.credentialUnavailable.body':
      '检测到本机登录凭据仍安全保留，但当前无法连接 SCM。不会删除凭据，也不会自动启用旧账号。',
  'account.credentialUnavailable.retry': '重新检查连接',
  'account.credentialUnavailable.checking': '正在重新检查 SCM 连接…',
  'account.reauthorization.title': '重新授权 SCM 账号',
  'account.reauthorization.body':
      'SCM 已拒绝或撤销本机原有登录凭据。StarBridge 已停止使用无效凭据；重新授权前，账号资料与敏感操作保持暂停。',
  'account.reauthorization.action': '重新授权 SCM 账号',
  'account.login.action': '使用 SCM 账号登录',
  'account.login.menu': '登录',
  'account.login.waiting': '请在浏览器中完成授权；返回应用后会自动继续。',
  'account.login.cancel': '取消登录',
  'account.login.cancelling': '正在取消登录…',
  'account.login.cancelled': '登录已取消，可以随时重试。',
  'account.login.success': 'SCM 账号已连接。',
  'account.action.refresh': '刷新账号资料',
  'account.action.retry': '重试',
  'account.value.notSet': '未设置',
  'account.email.notShared': 'SCM 未提供邮箱',
  'account.source.live': 'SCM 最新',
  'account.source.cached': '离线缓存',
  'account.source.unavailable': '资料不可用',
  'account.preferences.title': '资料偏好',
  'account.preferences.body': '仅同步 SCM 当前支持的语言偏好与标准时区；客户端界面语言仍可单独选择。',
  'account.preferences.locale': 'SCM 语言偏好',
  'account.preferences.timeZone': 'SCM 时区',
  'account.preferences.save': '保存更改',
  'account.preferences.draft': '有未保存的更改；切换页面时会保留，退出账号后清除。',
  'account.preferences.discard': '放弃更改',
  'account.preferences.saving': '正在保存…',
  'account.preferences.authorizing': '请在浏览器中完成授权，完成后将继续保存。',
  'account.preferences.cancelled': '已取消保存，你的选择仍保留在此页面。',
  'account.preferences.readOnly': '当前版本仅支持查看资料偏好。',
  'account.action.unavailable': '当前版本暂不支持此操作。',
  'account.cache.failed': '未能清除资料缓存，请重试。',
  'account.preferences.cachedReadOnly': '当前显示离线缓存。恢复连接并取得 SCM 最新资料后才能修改。',
  'account.preferences.noChanges': '没有需要保存的资料变化。',
  'account.preferences.saved': '资料偏好已保存，并由 SCM 重新读取确认。',
  'account.locale.zhCN': '简体中文（zh-CN）',
  'account.locale.enUS': 'English (en-US)',
  'account.identity.title': 'RSI 游戏身份',
  'account.identity.handle': '已验证 Handle',
  'account.identity.match': 'RSI 游戏身份已确认；每次进入游戏时会自动再次核对。',
  'account.identity.mismatch': '当前游戏身份与 SCM 账号记录不一致；需要确认游戏身份的操作已暂停。',
  'account.identity.awaiting': '尚未从当前游戏会话识别到身份；不会因此自动解绑。',
  'account.identity.reverify': 'SCM 要求重新验证 RSI 身份。',
  'account.identity.revoked': 'RSI 身份验证已撤销。',
  'account.identity.unknown': '暂时无法确认 RSI 身份状态。',
  'account.identity.writesAllowed': '游戏身份已确认，相关操作可用。',
  'account.identity.writesBlocked': '需要确认游戏身份的操作已暂停；资料查看与本机功能不受影响。',
  'account.session.title': '会话与本机缓存',
  'account.session.body': '缓存只保存当前账号可展示的基础资料，不保存登录凭据或权限信息。',
  'account.cache.clear': '清除资料缓存',
  'account.cache.clearing': '正在清除缓存…',
  'account.cache.cleared': '当前账号的本机资料缓存已清除。',
  'account.logout.action': '退出账号',
  'account.logout.signingOut': '正在退出…',
  'account.logout.success': '已完全退出 SCM 账号。',
  'account.compatibility.title': '旧数据兼容',
  'account.recovery.title': '找回旧账号密码',
  'account.legacyLogin.title': '旧 StarBridge 账号登录',
  'account.legacyLogin.body': '使用已有邮箱和密码登录旧账号。登录凭据在本机加密保存，不保存密码。',
  'account.legacySession.status': '已登录旧账号',
  'account.legacySession.body': '你正在使用原有 StarBridge 账号。SCM 授权可按需单独进行。',
  'account.legacySession.scmFailed': 'SCM 授权未完成，旧账号仍保持登录。需要时可以重新发起授权。',
  'account.legacySession.unavailable': '暂时无法验证旧账号会话，已保留登录凭据。请稍后刷新。',
  'account.legacySession.refresh': '刷新账号状态',
  'account.legacyLogin.password': '旧账号密码',
  'account.legacyLogin.submit': '登录旧账号',
  'account.legacyLogin.skip': '继续浏览',
  'account.legacyLogin.retry': '稍后重试',
  'account.legacyLogin.verified': '旧账号已验证，登录凭据已加密保存。',
  'account.legacyLogin.rejected': '邮箱或密码不正确，请检查后重试。',
  'account.legacyLogin.invalidInput': '请输入旧账号邮箱和密码。',
  'account.legacyLogin.throttled': '尝试次数过多，请等待倒计时结束后再试。',
  'account.legacyLogin.unavailable': '暂时无法确认登录结果，请稍后重试。',
  'account.legacyLogin.storageUnavailable': '旧账号验证成功，但无法保存登录凭据。请检查本机存储后重试。',
  'account.legacyLogin.busy': '另一项账号操作正在进行，请稍后重试。',
  'account.legacyLogin.sessionChanged': '账号状态已改变，请关闭此窗口并查看当前账号。',
  'account.legacyLogin.cancelled': '已停止等待。已经完成的凭据保存不会因此撤销。',
  'account.recovery.body': '仅重置旧 StarBridge 账号密码，不修改 SCM 密码。请使用旧账号的注册邮箱。',
  'account.recovery.email': '旧账号邮箱',
  'account.recovery.send': '发送验证码',
  'account.recovery.resend': '再次发送',
  'account.recovery.code': '六位邮箱验证码',
  'account.recovery.password': '新密码',
  'account.recovery.passwordHint': '8–128 个字符',
  'account.recovery.confirmPassword': '再次输入新密码',
  'account.recovery.submit': '重置旧账号密码',
  'account.recovery.close': '关闭',
  'account.recovery.codeRequested': '请求已受理，请检查旧账号邮箱的收件箱和垃圾邮件。验证码有效期为 10 分钟。',
  'account.recovery.reset': '密码已重置。下次验证旧账号时请使用新密码。',
  'account.recovery.invalidEmail': '请输入有效的旧账号邮箱。',
  'account.recovery.invalidCode': '验证码错误或已过期，请检查或重新获取。',
  'account.recovery.invalidPassword': '新密码需要 8–128 个字符。',
  'account.recovery.commonPassword': '该密码过于常见，请换用更长且独特的密码。',
  'account.recovery.mismatch': '两次输入的密码不一致。',
  'account.recovery.throttled': '请求过于频繁，请等待倒计时结束后再试。',
  'account.recovery.unavailable': '暂时无法确认操作结果，请稍后重试。若刚提交重置，也可以先尝试使用新密码验证旧账号。',
  'account.recovery.busy': '已有操作正在处理，请稍候。',
  'account.recovery.cancelled': '已停止等待。关闭窗口不会撤销已提交的密码重置。',
  'account.compatibility.body': '查看旧账号关联状态及兼容服务连接情况。',
  'account.compatibility.unavailable': '尚未读取旧数据兼容状态。',
  'account.compatibility.unlinked': '当前 SCM 账号尚未关联旧账号。此版本不开放注册。',
  'account.compatibility.linkedRelayPending': '旧账号已关联；旧舰队、好友、聊天等数据通道尚未建立。',
  'account.compatibility.ready': '旧账号会话已核对。',
  'account.compatibility.refreshAction': '刷新兼容状态',
  'account.compatibility.relayUnavailable': '旧账号已关联，但旧数据服务暂时不可用。',
  'account.compatibility.authorizationRequired': '旧数据服务拒绝了当前 SCM 授权，请重新登录后再试。',
  'account.compatibility.accountMismatch': 'SCM 关联身份与旧数据账号不一致，已阻止读取。',
  'account.compatibility.unknown': '暂时无法确认旧数据关联状态，请刷新后重试。',
  'account.compatibility.retryAction': '重试旧数据连接',
  'account.compatibility.savedCredential': '发现本机已保存的迁移凭据，可直接继续；成功后将自动清除。',
  'account.compatibility.continueSaved': '继续关联旧数据',
  'account.compatibility.verifyManually': '改用账号密码验证',
  'account.compatibility.linkAction': '关联旧账号',
  'account.compatibility.createAction': '创建兼容档案',
  'account.compatibility.cancel': '取消当前操作',
  'account.compatibility.cancelling': '正在取消…',
  'account.compatibility.cancelled': '已停止等待。若已提交关联，请刷新确认结果。',
  'account.compatibility.linked': '旧账号已关联，并已由 SCM 重新读取确认。',
  'account.compatibility.created': '兼容档案已创建，并已由 SCM 重新读取确认。',
  'account.compatibility.dialog.title': '关联旧 StarBridge 账号',
  'account.compatibility.dialog.body':
      '验证已有账号并关联到当前 SCM 账号。随后可能需要在浏览器中确认授权；本次输入不会保存。',
  'account.compatibility.dialog.accountName': '旧账号名或邮箱',
  'account.compatibility.dialog.password': '旧账号密码',
  'account.compatibility.dialog.required': '此项不能为空',
  'account.compatibility.dialog.security':
      '密码只用于本次验证，经本机 Native Host 提交；不会保存、写入日志或返回界面。',
  'account.compatibility.dialog.cancel': '取消',
  'account.compatibility.dialog.submit': '验证并关联',
  'account.compatibility.dialog.close': '关闭关联窗口',
  'account.compatibility.createDialog.title': '创建旧业务兼容档案？',
  'account.compatibility.createDialog.body':
      '这是新用户使用旧舰队、好友、聊天等兼容能力所需的内部档案，不能找回任何旧账号历史。',
  'account.compatibility.createDialog.confirm': '创建兼容档案',
  'account.error.hostUnavailable': '本机账号服务暂时不可用，无法读取账号状态。',
  'account.error.timeout': '操作超时，请刷新状态后重试。',
  'account.error.sessionChanged': '账号会话已经变化，旧操作结果已丢弃。',
  'account.error.environmentNotEnabled': '当前客户端仅开放本地联调环境，尚不能连接正式 SCM 网页。',
  'account.error.reauthorizationRequired': 'SCM 会话需要重新授权。',
  'account.error.writeForbidden': '当前账号没有资料修改权限。',
  'account.error.writeConflict': '资料已在其它位置更新，请重新载入后再保存。',
  'account.error.directoryUnavailable': '暂时无法读取 SCM 时区目录，资料没有被修改。',
  'account.error.invalidResponse': '本机账号服务返回了不兼容的资料，已安全停止处理。',
  'account.error.writeRejected': '当前资料更改不合法，未发送。',
  'account.error.unavailable': '账号资料暂时不可用，请稍后重试。',
  'account.error.compatibilityUnavailable': '暂时无法读取旧数据兼容状态。',
  'account.error.compatibilityWriteUnavailable': '暂时无法完成旧数据兼容操作，未知结果没有被当成成功。',
  'account.error.compatibilityConflict': '该旧账号或兼容档案已与其他 SCM 账号关联，未作任何更改。',
  'account.error.compatibilityExistingLinkMismatch':
      '当前 SCM 账号已有不同的旧账号关联，请先核对账号。',
  'account.error.legacyCredentialsRequired': '没有可用的迁移凭据，请输入旧账号名或邮箱和密码。',
  'account.error.legacyCredentialsRejected': '旧账号名或密码验证失败，未建立关联。',
  'account.error.operationNotInProgress': '当前没有可以取消的账号操作。',
  'overlay.scene.default': '默认场景',
  'overlay.scene.room': '房间场景',
  'overlay.scene.operation': '行动场景',
  'overlay.hostUnavailable': 'Native Host 未连接，暂时无法更改',
  'overlay.capabilityUnavailable': '浮层场景将在对应能力接入后开放',
  'status.host': '主机',
  'status.game': '游戏',
  'status.identity': '身份',
  'status.network': '网络',
  'status.connected': '已连接',
  'status.disconnected': '未连接',
  'status.notRunning': '未运行',
  'status.unconfirmed': '待确认',
  'status.confirmed': '已确认',
  'status.waitingForHost': '等待主机',
  'status.normal': '正常',
  'presence.online': '应用在线',
  'presence.away': '暂离',
  'presence.inGame': '游戏中',
  'presence.notInGame': '未运行游戏',
  'presence.gameUnknown': '游戏状态未知',
  'presence.unknown': '连接待确认',
  'presence.offline': '离线',
  'sync.current': '同步正常',
  'sync.hostUnavailable': '等待主机同步',
  'sync.cached': '使用离线缓存',
  'sync.issue': '同步需要处理',
  'connection.host.disconnected.title': '客户端连接中断',
  'connection.host.disconnected.detail': 'Native Host 暂时不可用，应用正在自动重连。',
  'connection.account.unavailable.title': '无法连接服务器',
  'connection.account.unavailable.detail': '在线功能暂时不可用，本地功能仍可继续使用。',
  'connection.account.reauthorize.title': 'SCM 登录需要更新',
  'connection.account.reauthorize.detail': '请重新登录以继续同步账号与舰队资料。',
  'connection.account.cached.title': '正在使用离线资料',
  'connection.account.cached.detail': '恢复连接后会自动读取最新 SCM 资料。',
  'connection.account.limited.title': '部分同步暂时不可用',
  'connection.account.limited.detail': '当前操作未完成，应用会保留已有资料并允许重试。',
  'connection.account.actionFailed.title': '账号操作需要处理',
  'connection.relay.unavailable.title': '旧数据兼容服务暂不可用',
  'connection.relay.unavailable.detail': 'SCM 账号及已迁移功能仍可使用；依赖旧服务的数据与在线协作暂时不可用。',
  'connection.action.retryNow': '立即重试',
  'connection.action.retrying': '正在重试…',
  'window.minimize': '最小化',
  'window.maximize': '最大化',
  'window.restore': '还原',
  'window.close': '关闭',
};
