import 'general_settings_strings.dart';
import 'notification_settings_strings.dart';
import 'notification_audio_strings.dart';
import 'profile_settings_strings.dart';
import 'official_fleet_strings.dart';
import 'party_rooms_strings.dart';
import 'friends_strings.dart';
import 'communities_strings.dart';
import 'settings_capability_strings.dart';
import 'sync_privacy_strings.dart';
import 'local_privacy_strings.dart';
import 'privacy_scope_settings_strings.dart';
import 'legacy_migration_strings.dart';
import 'local_profile_strings.dart';
import 'startup_strings.dart';
import 'gameplay_time_strings.dart';
import 'game_log_strings.dart';
import 'help_support_strings.dart';
import 'overlay_settings_strings.dart';
import 'home_strings.dart';

const traditionalAppStrings = <String, String>{
  'app.name': '星海艦橋',
  'navigation.home': '首頁',
  'navigation.home.description': '目前態勢與下一步',
  'navigation.rooms': '房間',
  'navigation.rooms.description': '隨性組隊與即時協作',
  'navigation.operations': '行動',
  'navigation.operations.description': '組織與艦隊的目標性協作',
  'navigation.officialFleet': '主艦隊',
  'navigation.officialFleet.description': 'RSI 官網主艦隊工作區',
  'navigation.marketplace': '交易大廳',
  'navigation.marketplace.description': '交易與服務入口（首發暫未開放）',
  'navigation.communities': '社區組織',
  'navigation.communities.description': '跨艦隊長期協作組織',
  'navigation.hangar': '個人機庫',
  'navigation.hangar.description': '艦船、配置與共享範圍',
  'navigation.overlay': '浮層',
  'navigation.overlay.description': '遊戲內資訊場景與佈局',
  'navigation.tools': '工具',
  'navigation.tools.description': '個人輔助工具（首發暫未開放）',
  'navigation.settings': '設定',
  'navigation.settings.description': '明暗、語言與客戶端偏好',
  'navigation.friends': '好友',
  'navigation.friends.description': '好友、私訊與最近玩過',
  'navigation.notifications': '通知',
  'navigation.notifications.description': '系統與協作更新',
  'navigation.account': '帳號',
  'navigation.account.description': '身分與個人資料',
  'navigation.profile': '個人頁面',
  'navigation.profile.description': '公開資料與主頁展示',
  'navigation.personal': '個人空間',
  'deferredFeature.title': '此入口尚未開放',
  'deferredFeature.marketplace.body': '交易與服務功能將在 Flutter 客戶端穩定後接入；首發僅保留這個固定入口。',
  'deferredFeature.tools.body': '個人輔助工具將在後續階段逐項接入；首發不會提供無效按鈕或模擬功能。',
  'top.overlayScene': '浮層場景',
  'top.friends': '好友',
  'top.notifications': '通知',
  'top.account': '帳號',
  'exampleScene.open': '開啟範例場景',
  'exampleScene.compact': '範例',
  'exampleScene.exit': '離開範例',
  'exampleScene.notice.title': '目前為範例場景',
  'exampleScene.notice.body': '示範帳號與範例資料僅供檢查介面，不會讀取或修改真實帳號。',
  ...traditionalProfileSettingsStrings,
  ...traditionalGeneralSettingsStrings,
  ...traditionalNotificationSettingsStrings,
  ...audioTw,
  ...traditionalSettingsCapabilityStrings,
  ...traditionalSyncPrivacyStrings,
  ...traditionalLocalPrivacyStrings,
  ...traditionalPrivacyScopeSettingsStrings,
  ...traditionalOfficialFleetStrings,
  ...traditionalPartyRoomsStrings,
  ...friendsZhTw,
  ...communitiesZhTw,
  ...traditionalLegacyMigrationStrings,
  ...traditionalLocalProfileStrings,
  ...traditionalStartupStrings,
  ...gameplayTimeZhTw,
  ...gameLogZhTw,
  ...helpSupportZhTw,
  ...overlaySettingsZhTw,
  ...homeZhTw,
  'account.notSignedIn': '未登入',
  'account.loading': '正在讀取帳號狀態…',
  'account.signedOut.title': '使用 SCM 帳號繼續',
  'account.signedOut.body': '授權會在系統瀏覽器中完成。登入憑證由本機帳號服務安全保管，不會進入介面頁面。',
  'account.credentialUnavailable.title': 'SCM 暫時無法使用',
  'account.credentialUnavailable.body':
      '偵測到本機登入憑證仍安全保留，但目前無法連線 SCM。不會刪除憑證，也不會自動啟用舊帳號。',
  'account.credentialUnavailable.retry': '重新檢查連線',
  'account.credentialUnavailable.checking': '正在重新檢查 SCM 連線…',
  'account.reauthorization.title': '重新授權 SCM 帳號',
  'account.reauthorization.body':
      'SCM 已拒絕或撤銷本機原有登入憑證。StarBridge 已停止使用無效憑證；重新授權前，帳號資料與敏感操作保持暫停。',
  'account.reauthorization.action': '重新授權 SCM 帳號',
  'account.login.action': '使用 SCM 帳號登入',
  'account.login.menu': '登入',
  'account.login.waiting': '請在瀏覽器中完成授權；返回應用程式後會自動繼續。',
  'account.login.cancel': '取消登入',
  'account.login.cancelling': '正在取消登入…',
  'account.login.cancelled': '登入已取消，可以隨時重試。',
  'account.login.success': 'SCM 帳號已連線。',
  'account.action.refresh': '重新整理帳號資料',
  'account.action.retry': '重試',
  'account.value.notSet': '未設定',
  'account.email.notShared': 'SCM 未提供電子郵件',
  'account.source.live': 'SCM 最新',
  'account.source.cached': '離線快取',
  'account.source.unavailable': '資料無法使用',
  'account.preferences.title': '資料偏好',
  'account.preferences.body': '僅同步 SCM 目前支援的語言偏好與標準時區；客戶端介面語言仍可單獨選擇。',
  'account.preferences.locale': 'SCM 語言偏好',
  'account.preferences.timeZone': 'SCM 時區',
  'account.preferences.save': '儲存變更',
  'account.preferences.draft': '有未儲存的變更；切換頁面時會保留，登出帳號後清除。',
  'account.preferences.discard': '放棄變更',
  'account.preferences.saving': '正在儲存…',
  'account.preferences.authorizing': '請在瀏覽器中完成授權，完成後將繼續儲存。',
  'account.preferences.cancelled': '已取消儲存，你的選擇仍保留在此頁面。',
  'account.preferences.readOnly': '目前版本僅支援查看資料偏好。',
  'account.action.unavailable': '目前版本暫不支援此操作。',
  'account.cache.failed': '未能清除資料快取，請重試。',
  'account.preferences.cachedReadOnly': '目前顯示離線快取。恢復連線並取得 SCM 最新資料後才能修改。',
  'account.preferences.noChanges': '沒有需要儲存的資料變更。',
  'account.preferences.saved': '資料偏好已儲存，並由 SCM 重新讀取確認。',
  'account.locale.zhCN': '簡體中文（zh-CN）',
  'account.locale.enUS': 'English (en-US)',
  'account.identity.title': 'RSI 遊戲身分',
  'account.identity.handle': '已驗證 Handle',
  'account.identity.match': 'RSI 遊戲身分已確認；每次進入遊戲時會自動再次核對。',
  'account.identity.mismatch': '目前遊戲身分與 SCM 帳號記錄不一致；需要確認遊戲身分的操作已暫停。',
  'account.identity.awaiting': '尚未從目前遊戲工作階段識別到身分；不會因此自動解除綁定。',
  'account.identity.reverify': 'SCM 要求重新驗證 RSI 身分。',
  'account.identity.revoked': 'RSI 身分驗證已撤銷。',
  'account.identity.unknown': '暫時無法確認 RSI 身分狀態。',
  'account.identity.writesAllowed': '遊戲身分已確認，相關操作可用。',
  'account.identity.writesBlocked': '需要確認遊戲身分的操作已暫停；資料檢視與本機功能不受影響。',
  'account.session.title': '工作階段與本機快取',
  'account.session.body': '快取只儲存目前帳號可顯示的基本資料，不儲存登入憑證或權限資訊。',
  'account.cache.clear': '清除資料快取',
  'account.cache.clearing': '正在清除快取…',
  'account.cache.cleared': '目前帳號的本機資料快取已清除。',
  'account.logout.action': '登出帳號',
  'account.logout.signingOut': '正在登出…',
  'account.logout.success': '已完整登出 SCM 帳號。',
  'account.compatibility.title': '舊資料相容',
  'account.recovery.title': '找回舊帳號密碼',
  'account.legacyLogin.title': '舊 StarBridge 帳號登入',
  'account.legacyLogin.body': '使用既有信箱和密碼登入舊帳號。登入憑證在本機加密儲存，不儲存密碼。',
  'account.legacySession.status': '已登入舊帳號',
  'account.legacySession.body': '你正在使用原有 StarBridge 帳號。SCM 授權可按需單獨進行。',
  'account.legacySession.scmFailed': 'SCM 授權未完成，舊帳號仍保持登入。需要時可以重新發起授權。',
  'account.legacySession.unavailable': '暫時無法驗證舊帳號工作階段，已保留登入憑證。請稍後重新整理。',
  'account.legacySession.refresh': '重新整理帳號狀態',
  'account.legacyLogin.password': '舊帳號密碼',
  'account.legacyLogin.submit': '登入舊帳號',
  'account.legacyLogin.skip': '繼續瀏覽',
  'account.legacyLogin.retry': '稍後重試',
  'account.legacyLogin.verified': '舊帳號已驗證，登入憑證已加密儲存。',
  'account.legacyLogin.rejected': '信箱或密碼不正確，請檢查後重試。',
  'account.legacyLogin.invalidInput': '請輸入舊帳號信箱和密碼。',
  'account.legacyLogin.throttled': '嘗試次數過多，請等倒數結束後再試。',
  'account.legacyLogin.unavailable': '暫時無法確認登入結果，請稍後重試。',
  'account.legacyLogin.storageUnavailable': '舊帳號驗證成功，但無法儲存登入憑證。請檢查本機儲存後重試。',
  'account.legacyLogin.busy': '另一項帳號操作正在進行，請稍後重試。',
  'account.legacyLogin.sessionChanged': '帳號狀態已改變，請關閉此視窗並查看目前帳號。',
  'account.legacyLogin.cancelled': '已停止等待。已完成的憑證儲存不會因此撤銷。',
  'account.recovery.body': '僅重設舊 StarBridge 帳號密碼，不修改 SCM 密碼。請使用舊帳號的註冊信箱。',
  'account.recovery.email': '舊帳號信箱',
  'account.recovery.send': '傳送驗證碼',
  'account.recovery.resend': '再次傳送',
  'account.recovery.code': '六位信箱驗證碼',
  'account.recovery.password': '新密碼',
  'account.recovery.passwordHint': '8–128 個字元',
  'account.recovery.confirmPassword': '再次輸入新密碼',
  'account.recovery.submit': '重設舊帳號密碼',
  'account.recovery.close': '關閉',
  'account.recovery.codeRequested': '請求已受理，請檢查舊帳號信箱的收件匣和垃圾郵件。驗證碼有效期為 10 分鐘。',
  'account.recovery.reset': '密碼已重設。下次驗證舊帳號時請使用新密碼。',
  'account.recovery.invalidEmail': '請輸入有效的舊帳號信箱。',
  'account.recovery.invalidCode': '驗證碼錯誤或已過期，請檢查或重新取得。',
  'account.recovery.invalidPassword': '新密碼需要 8–128 個字元。',
  'account.recovery.commonPassword': '該密碼過於常見，請改用更長且獨特的密碼。',
  'account.recovery.mismatch': '兩次輸入的密碼不一致。',
  'account.recovery.throttled': '請求過於頻繁，請等待倒數結束後再試。',
  'account.recovery.unavailable': '暫時無法確認操作結果，請稍後重試。若剛提交重設，也可以先嘗試使用新密碼驗證舊帳號。',
  'account.recovery.busy': '已有操作正在處理，請稍候。',
  'account.recovery.cancelled': '已停止等待。關閉視窗不會撤銷已提交的密碼重設。',
  'account.compatibility.body': '查看舊帳號關聯狀態及相容服務連線情況。',
  'account.compatibility.unavailable': '尚未讀取舊資料相容狀態。',
  'account.compatibility.unlinked': '目前 SCM 帳號尚未關聯舊帳號。此版本不開放註冊。',
  'account.compatibility.linkedRelayPending': '舊帳號已關聯；舊艦隊、好友、聊天等資料通道尚未建立。',
  'account.compatibility.ready': '舊帳號工作階段已核對。',
  'account.compatibility.refreshAction': '重新整理相容狀態',
  'account.compatibility.relayUnavailable': '舊帳號已關聯，但舊資料服務暫時無法使用。',
  'account.compatibility.authorizationRequired': '舊資料服務拒絕了目前的 SCM 授權，請重新登入後再試。',
  'account.compatibility.accountMismatch': 'SCM 關聯身分與舊資料帳號不一致，已阻止讀取。',
  'account.compatibility.unknown': '暫時無法確認舊資料關聯狀態，請重新整理後再試。',
  'account.compatibility.retryAction': '重試舊資料連線',
  'account.compatibility.savedCredential': '發現本機已儲存的遷移憑證，可直接繼續；成功後將自動清除。',
  'account.compatibility.continueSaved': '繼續關聯舊資料',
  'account.compatibility.verifyManually': '改用帳號密碼驗證',
  'account.compatibility.linkAction': '關聯舊帳號',
  'account.compatibility.createAction': '建立相容檔案',
  'account.compatibility.cancel': '取消目前操作',
  'account.compatibility.cancelling': '正在取消…',
  'account.compatibility.cancelled': '已停止等待。若已提交關聯，請重新整理確認結果。',
  'account.compatibility.linked': '舊帳號已關聯，並已由 SCM 重新讀取確認。',
  'account.compatibility.created': '相容檔案已建立，並已由 SCM 重新讀取確認。',
  'account.compatibility.dialog.title': '關聯舊 StarBridge 帳號',
  'account.compatibility.dialog.body':
      '驗證已有帳號並關聯到目前的 SCM 帳號。隨後可能需要在瀏覽器中確認授權；本次輸入不會儲存。',
  'account.compatibility.dialog.accountName': '舊帳號名稱或電子郵件',
  'account.compatibility.dialog.password': '舊帳號密碼',
  'account.compatibility.dialog.required': '此欄不能留空',
  'account.compatibility.dialog.security':
      '密碼只用於本次驗證，經本機 Native Host 提交；不會儲存、寫入記錄或傳回介面。',
  'account.compatibility.dialog.cancel': '取消',
  'account.compatibility.dialog.submit': '驗證並關聯',
  'account.compatibility.dialog.close': '關閉關聯視窗',
  'account.compatibility.createDialog.title': '建立舊業務相容檔案？',
  'account.compatibility.createDialog.body':
      '這是新使用者使用舊艦隊、好友、聊天等相容能力所需的內部檔案，不能找回任何舊帳號歷史。',
  'account.compatibility.createDialog.confirm': '建立相容檔案',
  'account.error.hostUnavailable': '本機帳號服務暫時無法使用，無法讀取帳號狀態。',
  'account.error.timeout': '操作逾時，請重新整理狀態後再試。',
  'account.error.sessionChanged': '帳號工作階段已變更，舊操作結果已捨棄。',
  'account.error.environmentNotEnabled': '目前客戶端僅開放本機聯調環境，尚不能連線正式 SCM 網頁。',
  'account.error.reauthorizationRequired': 'SCM 工作階段需要重新授權。',
  'account.error.writeForbidden': '目前帳號沒有資料修改權限。',
  'account.error.writeConflict': '資料已在其他位置更新，請重新載入後再儲存。',
  'account.error.directoryUnavailable': '暫時無法讀取 SCM 時區目錄，資料沒有被修改。',
  'account.error.invalidResponse': '本機帳號服務傳回不相容的資料，已安全停止處理。',
  'account.error.writeRejected': '目前資料變更不合法，未傳送。',
  'account.error.unavailable': '帳號資料暫時無法使用，請稍後重試。',
  'account.error.compatibilityUnavailable': '暫時無法讀取舊資料相容狀態。',
  'account.error.compatibilityWriteUnavailable': '暫時無法完成舊資料相容操作，未知結果沒有被當成成功。',
  'account.error.compatibilityConflict': '該舊帳號或相容檔案已與其他 SCM 帳號關聯，未作任何變更。',
  'account.error.compatibilityExistingLinkMismatch':
      '目前 SCM 帳號已有不同的舊帳號關聯，請先核對帳號。',
  'account.error.legacyCredentialsRequired': '沒有可用的遷移憑證，請輸入舊帳號名稱或電子郵件和密碼。',
  'account.error.legacyCredentialsRejected': '舊帳號名稱或密碼驗證失敗，未建立關聯。',
  'account.error.operationNotInProgress': '目前沒有可以取消的帳號操作。',
  'overlay.scene.default': '預設場景',
  'overlay.scene.room': '房間場景',
  'overlay.scene.operation': '行動場景',
  'overlay.hostUnavailable': 'Native Host 未連線，暫時無法變更',
  'overlay.capabilityUnavailable': '浮層場景將在對應能力接入後開放',
  'status.host': '主機',
  'status.game': '遊戲',
  'status.identity': '身分',
  'status.network': '網路',
  'status.connected': '已連線',
  'status.disconnected': '未連線',
  'status.notRunning': '未執行',
  'status.unconfirmed': '待確認',
  'status.confirmed': '已確認',
  'status.waitingForHost': '等待主機',
  'status.normal': '正常',
  'presence.online': '應用程式上線',
  'presence.away': '暫離',
  'presence.inGame': '遊戲中',
  'presence.notInGame': '未執行遊戲',
  'presence.gameUnknown': '遊戲狀態未知',
  'presence.unknown': '連線待確認',
  'presence.offline': '離線',
  'sync.current': '同步正常',
  'sync.hostUnavailable': '等待主機同步',
  'sync.cached': '使用離線快取',
  'sync.issue': '同步需要處理',
  'connection.host.disconnected.title': '用戶端連線中斷',
  'connection.host.disconnected.detail': 'Native Host 暫時不可用，應用程式正在自動重新連線。',
  'connection.account.unavailable.title': '無法連線伺服器',
  'connection.account.unavailable.detail': '線上功能暫時不可用，本機功能仍可繼續使用。',
  'connection.account.reauthorize.title': 'SCM 登入需要更新',
  'connection.account.reauthorize.detail': '請重新登入以繼續同步帳號與艦隊資料。',
  'connection.account.cached.title': '正在使用離線資料',
  'connection.account.cached.detail': '恢復連線後會自動讀取最新 SCM 資料。',
  'connection.account.limited.title': '部分同步暫時不可用',
  'connection.account.limited.detail': '目前操作未完成，應用程式會保留現有資料並允許重試。',
  'connection.account.actionFailed.title': '帳號操作需要處理',
  'connection.relay.unavailable.title': '舊資料相容服務暫時無法使用',
  'connection.relay.unavailable.detail':
      'SCM 帳號及已遷移功能仍可使用；依賴舊服務的資料與線上協作暫時無法使用。',
  'connection.action.retryNow': '立即重試',
  'connection.action.retrying': '正在重試…',
  'window.minimize': '最小化',
  'window.maximize': '最大化',
  'window.restore': '還原',
  'window.close': '關閉',
};
