const communitiesZhCn = <String, String>{
  'communities.details.title': '组织详情',
  'communities.details.about': '组织介绍',
  'communities.details.activity': '活动安排',
  'communities.card.details': '查看组织详情',
  'communities.card.application': '查看申请',
  'communities.card.notSpecified': '未公开',
  'communities.card.noRecruitingNote': '暂无招募说明',
  'communities.card.recruitingNote': '招募说明',
  'communities.card.close': '关闭',
  'communities.card.enter': '进入组织',
  'communities.tagPicker.title': '选择组织玩法标签',
  'communities.tagPicker.selected': '已选择',
  'communities.tagPicker.search': '搜索标签或说明',
  'communities.tagPicker.all': '全部分类',
  'communities.tagPicker.empty': '没有匹配的标签，请更换搜索词或分类。',
  'communities.tagPicker.clear': '清空选择',
  'communities.joinedShortcuts': '已加入组织',
  'communities.noJoinedShortcuts': '尚未加入组织',
  'communities.shortcutsUnavailable': '登录后显示已加入组织',
  'communities.shortcutsLoadFailed': '组织暂时无法加载，将自动重试',
  'communities.more': '显示更多',
  'communities.filters': '筛选条件',
  'communities.reset': '重置',
  'communities.applyFilters': '确定',
  'communities.sameZone': '与我同时区',
  'communities.periodHint': '所选时段仅匹配当前同时区的组织。',
  'communities.tagsFilter': '玩法标签',
  'communities.tagsHint': '以逗号分隔，最多 5 个',
  'communities.allTags': '同时匹配全部标签',
  'communities.sort': '排序',
  'communities.sort.recommended': '推荐排序',
  'communities.sort.recent': '资料最近更新',
  'communities.sort.members': '成员规模',
  'communities.sort.name': '组织名称',
  'communities.resultCount': '个组织',
  'communities.recruiting': '正在招募',
  'communities.mode.inviteOnly': '仅邀请加入',
  'communities.tags': '玩法',
  'communities.systems': '星系',
  'communities.filter.join': '加入方式',
  'communities.filter.status': '招募与申请',
  'communities.filter.scale': '成员规模',
  'communities.filter.targets': '招募对象',
  'communities.filter.cadence': '活动节奏',
  'communities.filter.period': '活跃时段',
  'communities.filter.days': '活动日',
  'communities.filter.ships': '公开舰船规模',
  'communities.filter.roles': '公开舰船类型',
  'communities.filter.systems': '活跃星系',
  'communities.option.join.direct': '直接加入',
  'communities.option.join.application': '申请加入',
  'communities.option.join.inviteOnly': '仅邀请',
  'communities.option.status.recruiting': '正在招募',
  'communities.option.status.pending': '申请处理中',
  'communities.option.scale.small': '小型 · 1–10 人',
  'communities.option.scale.medium': '中型 · 11–50 人',
  'communities.option.scale.large': '大型 · 51–299 人',
  'communities.option.scale.veryLarge': '超大型 · 300 人以上',
  'communities.option.targets.所有玩家': '所有玩家',
  'communities.option.targets.新手友好': '新手友好',
  'communities.option.targets.战斗玩家': '战斗玩家',
  'communities.option.targets.工业玩家': '工业玩家',
  'communities.option.targets.贸易与货运': '贸易与货运',
  'communities.option.targets.医疗与支援': '医疗与支援',
  'communities.option.cadence.休闲': '休闲',
  'communities.option.cadence.固定开黑': '固定开黑',
  'communities.option.cadence.周末行动': '周末行动',
  'communities.option.cadence.高频组织': '高频组织',
  'communities.option.cadence.大型行动前通知': '大型行动前通知',
  'communities.option.period.night': '凌晨 00:00–06:00',
  'communities.option.period.morning': '上午 06:00–12:00',
  'communities.option.period.afternoon': '下午 12:00–18:00',
  'communities.option.period.evening': '晚间 18:00–24:00',
  'communities.option.days.Mon': '周一',
  'communities.option.days.Tue': '周二',
  'communities.option.days.Wed': '周三',
  'communities.option.days.Thu': '周四',
  'communities.option.days.Fri': '周五',
  'communities.option.days.Sat': '周六',
  'communities.option.days.Sun': '周日',
  'communities.option.ships.small': '1–10 艘',
  'communities.option.ships.medium': '11–30 艘',
  'communities.option.ships.large': '31–99 艘',
  'communities.option.ships.veryLarge': '100 艘以上',
  'communities.option.roles.combat': '战斗',
  'communities.option.roles.industrial': '工业',
  'communities.option.roles.transport': '运输',
  'communities.option.roles.exploration': '探索',
  'communities.option.roles.support': '支援',
  'communities.option.roles.utility': '其他',
  'communities.option.systems.Stanton': '斯坦顿',
  'communities.option.systems.Pyro': '派罗',
  'communities.option.systems.Nyx': '尼克斯',
  'communities.title': '社区组织',
  'communities.subtitle': '长期协作，可以同时加入多个社区组织。',
  'communities.mine': '我的组织',
  'communities.discover': '寻找组织',
  'communities.refresh': '刷新',
  'communities.search': '搜索组织名称',
  'communities.searchButton': '搜索',
  'communities.details': '查看资料',
  'communities.back': '返回组织列表',
  'communities.cancel': '取消',
  'communities.retry': '重试',
  'communities.previous': '上一页',
  'communities.next': '下一页',
  'communities.loading': '正在读取社区组织…',
  'communities.language': '交流语言',
  'communities.activeTime': '活跃时间',
  'communities.members': '成员',
  'communities.relation.owner': '负责人',
  'communities.relation.member': '已加入',
  'communities.relation.pending': '申请待处理',
  'communities.relation.none': '尚未加入',
  'communities.mode.direct': '直接加入',
  'communities.mode.application': '需要申请',
  'communities.mode.unavailable': '暂未开放加入',
  'communities.action.join': '加入组织',
  'communities.action.apply': '申请加入',
  'communities.action.withdraw': '撤回申请',
  'communities.action.leave': '退出组织',
  'communities.confirm.join': '加入这个社区组织，不会退出你已加入的其他组织，也不会自动扩大隐私共享范围。',
  'communities.confirm.apply': '向这个组织提交加入申请，不影响已有组织关系。',
  'communities.confirm.withdraw': '撤回你在这个组织的加入申请。',
  'communities.confirm.leave': '退出后将失去这个组织的内部访问权限，其他组织关系保持不变。',
  'communities.done.join': '已加入组织。',
  'communities.done.apply': '已提交加入申请。',
  'communities.done.withdraw': '已撤回申请。',
  'communities.done.leave': '已退出组织。',
  'communities.empty.mine': '还没有加入社区组织，可以前往“寻找组织”。',
  'communities.empty.discover': '暂无可发现的社区组织。',
  'communities.emptySearch': '没有符合的组织，试试其他名称。',
  'communities.example': '示例场景：操作只影响示例组织。',
  'communities.ownerHint': '负责人退出需要先完成转让或解散。管理入口将在后续接入。',
  'communities.identityUnavailable': '请检查右上角账号状态，登录后重试。',
  'communities.unavailable': '暂时无法读取社区组织，请检查连接后重试。',
  'communities.upgradeRequired': '当前服务尚未支持多社区组织，请等待服务更新后重试。',
  'communities.dataInvalid': '未能读取有效的组织资料，请重试。',
  'communities.refreshRequired': '组织状态可能已变化，请核对刷新后的资料再操作。',
  'communities.outcomeUnknown': '暂时无法确认操作结果。请核对刷新后的组织状态，不要重复提交。',
};
const communitiesZhTw = <String, String>{
  'communities.details.title': '組織詳情',
  'communities.details.about': '組織介紹',
  'communities.details.activity': '活動安排',
  'communities.card.details': '查看組織詳情',
  'communities.card.application': '查看申請',
  'communities.card.notSpecified': '未公開',
  'communities.card.noRecruitingNote': '暫無招募說明',
  'communities.card.recruitingNote': '招募說明',
  'communities.card.close': '關閉',
  'communities.card.enter': '進入組織',
  'communities.tagPicker.title': '選擇組織玩法標籤',
  'communities.tagPicker.selected': '已選擇',
  'communities.tagPicker.search': '搜尋標籤或說明',
  'communities.tagPicker.all': '全部分類',
  'communities.tagPicker.empty': '沒有符合的標籤，請更換搜尋詞或分類。',
  'communities.tagPicker.clear': '清空選擇',
  'communities.joinedShortcuts': '已加入組織',
  'communities.noJoinedShortcuts': '尚未加入組織',
  'communities.shortcutsUnavailable': '登入後顯示已加入組織',
  'communities.shortcutsLoadFailed': '組織暫時無法載入，將自動重試',
  'communities.more': '顯示更多',
  'communities.filters': '篩選條件',
  'communities.reset': '重設',
  'communities.applyFilters': '確定',
  'communities.sameZone': '與我同時區',
  'communities.periodHint': '所選時段僅符合目前同時區的組織。',
  'communities.tagsFilter': '玩法標籤',
  'communities.tagsHint': '以逗號分隔，最多 5 個',
  'communities.allTags': '同時符合全部標籤',
  'communities.sort': '排序',
  'communities.sort.recommended': '推薦排序',
  'communities.sort.recent': '資料最近更新',
  'communities.sort.members': '成員規模',
  'communities.sort.name': '組織名稱',
  'communities.resultCount': '個組織',
  'communities.recruiting': '正在招募',
  'communities.mode.inviteOnly': '僅邀請加入',
  'communities.tags': '玩法',
  'communities.systems': '星系',
  'communities.filter.join': '加入方式',
  'communities.filter.status': '招募與申請',
  'communities.filter.scale': '成員規模',
  'communities.filter.targets': '招募對象',
  'communities.filter.cadence': '活動節奏',
  'communities.filter.period': '活躍時段',
  'communities.filter.days': '活動日',
  'communities.filter.ships': '公開艦船規模',
  'communities.filter.roles': '公開艦船類型',
  'communities.filter.systems': '活躍星系',
  'communities.option.join.direct': '直接加入',
  'communities.option.join.application': '申請加入',
  'communities.option.join.inviteOnly': '僅邀請',
  'communities.option.status.recruiting': '正在招募',
  'communities.option.status.pending': '申請處理中',
  'communities.option.scale.small': '小型 · 1–10 人',
  'communities.option.scale.medium': '中型 · 11–50 人',
  'communities.option.scale.large': '大型 · 51–299 人',
  'communities.option.scale.veryLarge': '超大型 · 300 人以上',
  'communities.option.targets.所有玩家': '所有玩家',
  'communities.option.targets.新手友好': '新手友善',
  'communities.option.targets.战斗玩家': '戰鬥玩家',
  'communities.option.targets.工业玩家': '工業玩家',
  'communities.option.targets.贸易与货运': '貿易與貨運',
  'communities.option.targets.医疗与支援': '醫療與支援',
  'communities.option.cadence.休闲': '休閒',
  'communities.option.cadence.固定开黑': '固定組隊',
  'communities.option.cadence.周末行动': '週末行動',
  'communities.option.cadence.高频组织': '高頻組織',
  'communities.option.cadence.大型行动前通知': '大型行動前通知',
  'communities.option.period.night': '凌晨 00:00–06:00',
  'communities.option.period.morning': '上午 06:00–12:00',
  'communities.option.period.afternoon': '下午 12:00–18:00',
  'communities.option.period.evening': '晚間 18:00–24:00',
  'communities.option.days.Mon': '週一',
  'communities.option.days.Tue': '週二',
  'communities.option.days.Wed': '週三',
  'communities.option.days.Thu': '週四',
  'communities.option.days.Fri': '週五',
  'communities.option.days.Sat': '週六',
  'communities.option.days.Sun': '週日',
  'communities.option.ships.small': '1–10 艘',
  'communities.option.ships.medium': '11–30 艘',
  'communities.option.ships.large': '31–99 艘',
  'communities.option.ships.veryLarge': '100 艘以上',
  'communities.option.roles.combat': '戰鬥',
  'communities.option.roles.industrial': '工業',
  'communities.option.roles.transport': '運輸',
  'communities.option.roles.exploration': '探索',
  'communities.option.roles.support': '支援',
  'communities.option.roles.utility': '其他',
  'communities.option.systems.Stanton': '斯坦頓',
  'communities.option.systems.Pyro': '派羅',
  'communities.option.systems.Nyx': '尼克斯',
  'communities.title': '社群組織',
  'communities.subtitle': '長期協作，可以同時加入多個社群組織。',
  'communities.mine': '我的組織',
  'communities.discover': '尋找組織',
  'communities.refresh': '重新整理',
  'communities.search': '搜尋組織名稱',
  'communities.searchButton': '搜尋',
  'communities.details': '查看資料',
  'communities.back': '返回組織清單',
  'communities.cancel': '取消',
  'communities.retry': '重試',
  'communities.previous': '上一頁',
  'communities.next': '下一頁',
  'communities.loading': '正在讀取社群組織…',
  'communities.language': '交流語言',
  'communities.activeTime': '活躍時間',
  'communities.members': '成員',
  'communities.relation.owner': '負責人',
  'communities.relation.member': '已加入',
  'communities.relation.pending': '申請待處理',
  'communities.relation.none': '尚未加入',
  'communities.mode.direct': '直接加入',
  'communities.mode.application': '需要申請',
  'communities.mode.unavailable': '暫未開放加入',
  'communities.action.join': '加入組織',
  'communities.action.apply': '申請加入',
  'communities.action.withdraw': '撤回申請',
  'communities.action.leave': '退出組織',
  'communities.confirm.join': '加入這個社群組織，不會退出已加入的其他組織，也不會自動擴大隱私共享範圍。',
  'communities.confirm.apply': '向這個組織提交加入申請，不影響已有組織關係。',
  'communities.confirm.withdraw': '撤回你在這個組織的加入申請。',
  'communities.confirm.leave': '退出後將失去這個組織的內部存取權限，其他組織關係保持不變。',
  'communities.done.join': '已加入組織。',
  'communities.done.apply': '已提交加入申請。',
  'communities.done.withdraw': '已撤回申請。',
  'communities.done.leave': '已退出組織。',
  'communities.empty.mine': '還沒有加入社群組織，可以前往「尋找組織」。',
  'communities.empty.discover': '暫無可發現的社群組織。',
  'communities.emptySearch': '沒有符合的組織，試試其他名稱。',
  'communities.example': '示例場景：操作只影響示例組織。',
  'communities.ownerHint': '負責人退出需要先完成轉讓或解散。管理入口將在後續接入。',
  'communities.identityUnavailable': '請檢查右上角帳號狀態，登入後重試。',
  'communities.unavailable': '暫時無法讀取社群組織，請檢查連線後重試。',
  'communities.upgradeRequired': '目前服務尚未支援多社群組織，請等待服務更新後重試。',
  'communities.dataInvalid': '未能讀取有效的組織資料，請重試。',
  'communities.refreshRequired': '組織狀態可能已變更，請核對重新整理後的資料再操作。',
  'communities.outcomeUnknown': '暫時無法確認操作結果。請核對重新整理後的組織狀態，不要重複提交。',
};
const communitiesEn = <String, String>{
  'communities.details.title': 'Organization details',
  'communities.details.about': 'About the organization',
  'communities.details.activity': 'Activity schedule',
  'communities.card.details': 'View organization',
  'communities.card.application': 'View application',
  'communities.card.notSpecified': 'Not shared',
  'communities.card.noRecruitingNote': 'No recruitment note',
  'communities.card.recruitingNote': 'Recruitment note',
  'communities.card.close': 'Close',
  'communities.card.enter': 'Open workspace',
  'communities.tagPicker.title': 'Choose organization activity tags',
  'communities.tagPicker.selected': 'Selected',
  'communities.tagPicker.search': 'Search tags or descriptions',
  'communities.tagPicker.all': 'All categories',
  'communities.tagPicker.empty':
      'No matching tags. Try another search or category.',
  'communities.tagPicker.clear': 'Clear selection',
  'communities.joinedShortcuts': 'Joined organizations',
  'communities.noJoinedShortcuts': 'No joined organizations',
  'communities.shortcutsUnavailable': 'Sign in to view your organizations',
  'communities.shortcutsLoadFailed':
      'Organizations unavailable. Retrying automatically.',
  'communities.more': 'Show more',
  'communities.filters': 'Filters',
  'communities.reset': 'Reset',
  'communities.applyFilters': 'Apply',
  'communities.sameZone': 'Same time zone as me',
  'communities.periodHint':
      'Hours match organizations with the same current UTC offset.',
  'communities.tagsFilter': 'Activity tags',
  'communities.tagsHint': 'Comma separated, up to 5',
  'communities.allTags': 'Match all tags',
  'communities.sort': 'Sort',
  'communities.sort.recommended': 'Recommended',
  'communities.sort.recent': 'Recently updated',
  'communities.sort.members': 'Member count',
  'communities.sort.name': 'Organization name',
  'communities.resultCount': 'organizations',
  'communities.recruiting': 'Recruiting',
  'communities.mode.inviteOnly': 'Invitation only',
  'communities.tags': 'Activities',
  'communities.systems': 'Systems',
  'communities.filter.join': 'Joining',
  'communities.filter.status': 'Recruitment and applications',
  'communities.filter.scale': 'Member size',
  'communities.filter.targets': 'Who they recruit',
  'communities.filter.cadence': 'Activity schedule',
  'communities.filter.period': 'Active hours',
  'communities.filter.days': 'Active days',
  'communities.filter.ships': 'Public ship count',
  'communities.filter.roles': 'Public ship roles',
  'communities.filter.systems': 'Active systems',
  'communities.option.join.direct': 'Direct join',
  'communities.option.join.application': 'Apply to join',
  'communities.option.join.inviteOnly': 'Invitation only',
  'communities.option.status.recruiting': 'Recruiting',
  'communities.option.status.pending': 'Application pending',
  'communities.option.scale.small': 'Small · 1–10',
  'communities.option.scale.medium': 'Medium · 11–50',
  'communities.option.scale.large': 'Large · 51–299',
  'communities.option.scale.veryLarge': 'Very large · 300+',
  'communities.option.targets.所有玩家': 'All players',
  'communities.option.targets.新手友好': 'New players',
  'communities.option.targets.战斗玩家': 'Combat',
  'communities.option.targets.工业玩家': 'Industry',
  'communities.option.targets.贸易与货运': 'Trade and cargo',
  'communities.option.targets.医疗与支援': 'Medical and support',
  'communities.option.cadence.休闲': 'Casual',
  'communities.option.cadence.固定开黑': 'Regular groups',
  'communities.option.cadence.周末行动': 'Weekends',
  'communities.option.cadence.高频组织': 'Frequent activity',
  'communities.option.cadence.大型行动前通知': 'Major event announcements',
  'communities.option.period.night': 'Night 00:00–06:00',
  'communities.option.period.morning': 'Morning 06:00–12:00',
  'communities.option.period.afternoon': 'Afternoon 12:00–18:00',
  'communities.option.period.evening': 'Evening 18:00–24:00',
  'communities.option.days.Mon': 'Monday',
  'communities.option.days.Tue': 'Tuesday',
  'communities.option.days.Wed': 'Wednesday',
  'communities.option.days.Thu': 'Thursday',
  'communities.option.days.Fri': 'Friday',
  'communities.option.days.Sat': 'Saturday',
  'communities.option.days.Sun': 'Sunday',
  'communities.option.ships.small': '1–10',
  'communities.option.ships.medium': '11–30',
  'communities.option.ships.large': '31–99',
  'communities.option.ships.veryLarge': '100+',
  'communities.option.roles.combat': 'Combat',
  'communities.option.roles.industrial': 'Industry',
  'communities.option.roles.transport': 'Transport',
  'communities.option.roles.exploration': 'Exploration',
  'communities.option.roles.support': 'Support',
  'communities.option.roles.utility': 'Other',
  'communities.option.systems.Stanton': 'Stanton',
  'communities.option.systems.Pyro': 'Pyro',
  'communities.option.systems.Nyx': 'Nyx',
  'communities.title': 'Communities',
  'communities.subtitle':
      'Long-term collaboration. Join more than one community.',
  'communities.mine': 'My organizations',
  'communities.discover': 'Find organizations',
  'communities.refresh': 'Refresh',
  'communities.search': 'Search community names',
  'communities.searchButton': 'Search',
  'communities.details': 'View details',
  'communities.back': 'Back to communities',
  'communities.cancel': 'Cancel',
  'communities.retry': 'Retry',
  'communities.previous': 'Previous',
  'communities.next': 'Next',
  'communities.loading': 'Loading communities…',
  'communities.language': 'Languages',
  'communities.activeTime': 'Active hours',
  'communities.members': 'Members',
  'communities.relation.owner': 'Owner',
  'communities.relation.member': 'Joined',
  'communities.relation.pending': 'Application pending',
  'communities.relation.none': 'Not joined',
  'communities.mode.direct': 'Open admission',
  'communities.mode.application': 'Application required',
  'communities.mode.unavailable': 'Admission unavailable',
  'communities.action.join': 'Join community',
  'communities.action.apply': 'Apply to join',
  'communities.action.withdraw': 'Withdraw application',
  'communities.action.leave': 'Leave community',
  'communities.confirm.join': 'Joining does not leave your other communities or expand your privacy sharing audience.',
  'communities.confirm.apply':
      'Apply to this community without changing your existing memberships.',
  'communities.confirm.withdraw':
      'Withdraw your application to this community.',
  'communities.confirm.leave': 'You will lose access to this community’s internal content. Other memberships stay unchanged.',
  'communities.done.join': 'Community joined.',
  'communities.done.apply': 'Application submitted.',
  'communities.done.withdraw': 'Application withdrawn.',
  'communities.done.leave': 'Community left.',
  'communities.empty.mine':
      'No communities yet. Open Find organizations to get started.',
  'communities.empty.discover': 'No discoverable communities.',
  'communities.emptySearch': 'No matching communities. Try another name.',
  'communities.example':
      'Example scene: actions only affect sample communities.',
  'communities.ownerHint': 'Owners must transfer ownership or disband before leaving. Management will be available in a later update.',
  'communities.identityUnavailable':
      'Check your account at the top right, sign in, then retry.',
  'communities.unavailable':
      'Could not load communities. Check your connection and retry.',
  'communities.upgradeRequired': 'This service does not support multiple communities yet. Retry after the service is updated.',
  'communities.dataInvalid': 'Could not read valid community details. Retry.',
  'communities.refreshRequired': 'The community may have changed. Check the refreshed details before acting.',
  'communities.outcomeUnknown': 'The result is unconfirmed. Check the refreshed community state before submitting again.',
};
