const directSendZhCn = <String, String>{
  'direct.sendingHint': '支持发送文字。已读同步尚未开放，查看不会清除未读。',
  'direct.send.input': '输入消息',
  'direct.send.action': '发送',
  'direct.send.sending': '正在发送…',
  'direct.send.shortcut': 'Enter 发送 · Shift+Enter 换行',
  'direct.send.sent': '已发送',
  'direct.send.request_sent': '消息已发送。对方回复前最多可发送 3 条。',
  'direct.send.notAllowed': '已发送 3 条消息，请等待对方回复。',
  'direct.send.outcome_unknown': '发送结果待确认，输入已保留。请刷新消息核对，暂不重复发送。',
  'direct.send.rejected': '消息未发送，输入已保留，请检查后重试。',
  'direct.send.unavailable': '暂时无法发送，输入已保留，请稍后重试。',
  'direct.send.busy': '另一项操作仍在进行，请稍后重试。',
  'direct.send.limit': '本次会话操作已达上限，请保存其他工作后重启客户端。',
  'direct.send.invalid_request': '请检查消息内容后重试。',
  'direct.send.data_invalid': '无法确认会话状态，请刷新消息后重试。',
  'direct.send.forbidden': '当前无法向此用户发送消息，输入已保留。',
  'direct.send.identity_unavailable': '当前账号暂不可用，请检查登录状态。',
  'direct.send.target_changed': '会话已失效，请刷新会话列表。',
  'direct.send.rate_limited': '发送过于频繁，输入已保留，请稍后重试。',
  'direct.send.request_pending': '已发送 3 条消息，请等待对方回复。',
  'direct.send.tooLong': '消息不能超过 1000 字。',
  'direct.send.leaveTitle': '放弃当前输入？',
  'direct.send.leaveBody': '离开后将清除这段尚未发送的文字。',
  'direct.send.leaveUnknown': '消息可能已经送达。离开将清除保留的输入，请勿重新发送相同内容，稍后查看历史确认。',
  'direct.send.keep': '留在会话',
  'direct.send.discard': '放弃输入并离开',
};

const directSendZhTw = <String, String>{
  'direct.sendingHint': '支援傳送文字。已讀同步尚未開放，查看不會清除未讀。',
  'direct.send.input': '輸入訊息',
  'direct.send.action': '傳送',
  'direct.send.sending': '正在傳送…',
  'direct.send.shortcut': 'Enter 傳送 · Shift+Enter 換行',
  'direct.send.sent': '已傳送',
  'direct.send.request_sent': '訊息已傳送。對方回覆前最多可傳送 3 條。',
  'direct.send.notAllowed': '已傳送 3 條訊息，請等待對方回覆。',
  'direct.send.outcome_unknown': '傳送結果待確認，輸入已保留。請重新整理訊息核對，暫不重複傳送。',
  'direct.send.rejected': '訊息未傳送，輸入已保留，請檢查後重試。',
  'direct.send.unavailable': '暫時無法傳送，輸入已保留，請稍後重試。',
  'direct.send.busy': '另一項操作仍在進行，請稍後重試。',
  'direct.send.limit': '本次對話操作已達上限，請儲存其他工作後重新啟動用戶端。',
  'direct.send.invalid_request': '請檢查訊息內容後重試。',
  'direct.send.data_invalid': '無法確認對話狀態，請重新整理訊息後重試。',
  'direct.send.forbidden': '目前無法向此使用者傳送訊息，輸入已保留。',
  'direct.send.identity_unavailable': '目前帳號暫不可用，請檢查登入狀態。',
  'direct.send.target_changed': '對話已失效，請重新整理對話清單。',
  'direct.send.rate_limited': '傳送過於頻繁，輸入已保留，請稍後重試。',
  'direct.send.request_pending': '已傳送 3 條訊息，請等待對方回覆。',
  'direct.send.tooLong': '訊息不能超過 1000 字。',
  'direct.send.leaveTitle': '放棄目前輸入？',
  'direct.send.leaveBody': '離開後將清除這段尚未傳送的文字。',
  'direct.send.leaveUnknown': '訊息可能已經送達。離開將清除保留的輸入，請勿重新傳送相同內容，稍後查看歷史確認。',
  'direct.send.keep': '留在對話',
  'direct.send.discard': '放棄輸入並離開',
};

const directSendEn = <String, String>{
  'direct.sendingHint': 'Text messaging is available. Read receipts are not yet synced; viewing keeps messages unread.',
  'direct.send.input': 'Message',
  'direct.send.action': 'Send',
  'direct.send.sending': 'Sending…',
  'direct.send.shortcut': 'Enter: send · Shift+Enter: new line',
  'direct.send.sent': 'Sent',
  'direct.send.request_sent':
      'Message sent. You can send up to 3 before they reply.',
  'direct.send.notAllowed':
      'You have sent 3 messages. Wait for a reply to continue.',
  'direct.send.outcome_unknown': 'Delivery is unconfirmed. Your text is kept. Refresh messages to check before sending again.',
  'direct.send.rejected':
      'Message not sent. Your text is kept; check and try again.',
  'direct.send.unavailable':
      'Sending is unavailable. Your text is kept; try again later.',
  'direct.send.busy': 'Another action is in progress. Try again shortly.',
  'direct.send.limit': 'This session has reached its action limit. Save your other work and restart the app.',
  'direct.send.invalid_request': 'Check your message and try again.',
  'direct.send.data_invalid': 'Conversation status could not be confirmed. Refresh messages and try again.',
  'direct.send.forbidden':
      'You cannot message this user right now. Your text is kept.',
  'direct.send.identity_unavailable':
      'Your account is unavailable. Check your sign-in status.',
  'direct.send.target_changed':
      'This conversation has expired. Refresh the conversation list.',
  'direct.send.rate_limited': 'Messages are being sent too quickly. Your text is kept; try again later.',
  'direct.send.request_pending':
      'You have sent 3 messages. Wait for a reply to continue.',
  'direct.send.tooLong': 'Messages are limited to 1,000 characters.',
  'direct.send.leaveTitle': 'Discard this input?',
  'direct.send.leaveBody': 'Leaving clears this unsent text.',
  'direct.send.leaveUnknown': 'The message may have arrived. Leaving clears the retained text. Do not resend it; check the history later.',
  'direct.send.keep': 'Stay in conversation',
  'direct.send.discard': 'Discard and leave',
};
