import 'direct_send_strings.dart';

const directZhCn = <String, String>{
  'direct.readingHint': '仅你与对方可见，看到的消息会同步为已读。',
  'direct.readFailed': '已读状态暂未同步，请刷新消息后重试。',
  ...directSendZhCn,
  'direct.title': '私信',
  'direct.backFriends': '返回好友',
  'direct.backList': '返回会话',
  'direct.readOnly': '目前可查看会话与历史；发送和已读同步尚未开放，查看不会清除未读。',
  'direct.refresh': '刷新会话',
  'direct.requests': '消息请求',
  'direct.conversations': '会话',
  'direct.empty': '暂无会话',
  'direct.emptyHistory': '暂无消息',
  'direct.loading': '正在读取…',
  'direct.refreshHint': '请刷新后重试。',
  'direct.select': '选择会话查看历史',
  'direct.unread': '未读',
  'direct.refreshMessages': '刷新消息',
  'direct.moreNew': '继续读取新消息',
  'direct.latest': '回到最新',
  'direct.older': '加载更早消息',
  'direct.start': '已到最早消息',
  'direct.me': '我',
  'direct.state.friend': '好友会话',
  'direct.state.accepted': '已建立会话',
  'direct.state.request_incoming': '收到的消息请求 · 回复后建立会话',
  'direct.state.request_outgoing': '等待对方回复',
  'direct.state.none': '尚未建立会话',
  'direct.state.unknown': '会话状态暂不可用',
  'direct.attachment.overlay_preset': '浮层预设',
  'direct.attachment.party_room_invitation': '房间邀请',
  'direct.attachment.fleet_invitation': '组织邀请',
  'direct.viewInvite': '查看邀请',
  'direct.inviteExpired': '名片已过期，请查看最新邀请状态。',
  'direct.attachment.unknown': '附件',
  'direct.attachmentReadOnly': '暂不支持打开此卡片',
  'direct.error.unavailable': '暂时无法读取私信，请稍后刷新。',
  'direct.error.identity_unavailable': '当前账号暂无法读取私信，请检查登录与账号状态。',
  'direct.error.forbidden': '当前无法访问此会话，消息已清除。',
  'direct.error.target_changed': '会话已失效，请刷新会话列表。',
  'direct.error.data_invalid': '收到的消息数据不完整，请刷新后重试。',
  'direct.error.limit': '已达到本次历史浏览上限，请回到最新消息。',
};
const directZhTw = <String, String>{
  'direct.readingHint': '僅你與對方可見，看到的訊息會同步為已讀。',
  'direct.readFailed': '已讀狀態暫未同步，請重新整理訊息後重試。',
  ...directSendZhTw,
  'direct.title': '私訊',
  'direct.backFriends': '返回好友',
  'direct.backList': '返回對話',
  'direct.readOnly': '目前可查看對話與歷史；傳送和已讀同步尚未開放，查看不會清除未讀。',
  'direct.refresh': '重新整理對話',
  'direct.requests': '訊息請求',
  'direct.conversations': '對話',
  'direct.empty': '暫無對話',
  'direct.emptyHistory': '暫無訊息',
  'direct.loading': '正在讀取…',
  'direct.refreshHint': '請重新整理後重試。',
  'direct.select': '選擇對話查看歷史',
  'direct.unread': '未讀',
  'direct.refreshMessages': '重新整理訊息',
  'direct.moreNew': '繼續讀取新訊息',
  'direct.latest': '回到最新',
  'direct.older': '載入更早訊息',
  'direct.start': '已到最早訊息',
  'direct.me': '我',
  'direct.state.friend': '好友對話',
  'direct.state.accepted': '已建立對話',
  'direct.state.request_incoming': '收到的訊息請求 · 回覆後建立對話',
  'direct.state.request_outgoing': '等待對方回覆',
  'direct.state.none': '尚未建立對話',
  'direct.state.unknown': '對話狀態暫不可用',
  'direct.attachment.overlay_preset': '浮層預設',
  'direct.attachment.party_room_invitation': '房間邀請',
  'direct.attachment.fleet_invitation': '組織邀請',
  'direct.viewInvite': '查看邀請',
  'direct.inviteExpired': '名片已過期，請查看最新邀請狀態。',
  'direct.attachment.unknown': '附件',
  'direct.attachmentReadOnly': '暫不支援開啟此卡片',
  'direct.error.unavailable': '暫時無法讀取私訊，請稍後重新整理。',
  'direct.error.identity_unavailable': '目前帳號暫無法讀取私訊，請檢查登入與帳號狀態。',
  'direct.error.forbidden': '目前無法存取此對話，訊息已清除。',
  'direct.error.target_changed': '對話已失效，請重新整理對話清單。',
  'direct.error.data_invalid': '收到的訊息資料不完整，請重新整理後重試。',
  'direct.error.limit': '已達到本次歷史瀏覽上限，請回到最新訊息。',
};
const directEn = <String, String>{
  'direct.readingHint': 'Only you and the recipient can see this conversation. Viewed messages are marked as read.',
  'direct.readFailed': 'Read status could not sync. Refresh messages to retry.',
  ...directSendEn,
  'direct.title': 'Direct messages',
  'direct.backFriends': 'Back to friends',
  'direct.backList': 'Conversations',
  'direct.readOnly': 'Read-only for now. Sending and read receipts are not available; viewing keeps messages unread.',
  'direct.refresh': 'Refresh conversations',
  'direct.requests': 'Message requests',
  'direct.conversations': 'Conversations',
  'direct.empty': 'No conversations',
  'direct.emptyHistory': 'No messages',
  'direct.loading': 'Loading…',
  'direct.refreshHint': 'Refresh to try again.',
  'direct.select': 'Select a conversation to view its history',
  'direct.unread': 'Unread',
  'direct.refreshMessages': 'Refresh messages',
  'direct.moreNew': 'Load more new messages',
  'direct.latest': 'Back to latest',
  'direct.older': 'Load older messages',
  'direct.start': 'Beginning of conversation',
  'direct.me': 'Me',
  'direct.state.friend': 'Friend conversation',
  'direct.state.accepted': 'Conversation established',
  'direct.state.request_incoming':
      'Incoming message request · Reply to continue',
  'direct.state.request_outgoing': 'Waiting for a reply',
  'direct.state.none': 'No conversation yet',
  'direct.state.unknown': 'Conversation status unavailable',
  'direct.attachment.overlay_preset': 'Overlay preset',
  'direct.attachment.party_room_invitation': 'Room invitation',
  'direct.attachment.fleet_invitation': 'Organization invitation',
  'direct.viewInvite': 'View invitation',
  'direct.inviteExpired':
      'This card has expired. Check the latest invitation status.',
  'direct.attachment.unknown': 'Attachment',
  'direct.attachmentReadOnly': 'Opening this card is not supported yet',
  'direct.error.unavailable': 'Messages are unavailable. Refresh to try again.',
  'direct.error.identity_unavailable': 'Messages are unavailable for this account. Check your sign-in and account status.',
  'direct.error.forbidden':
      'This conversation is no longer accessible. Messages have been cleared.',
  'direct.error.target_changed':
      'This conversation has expired. Refresh the conversation list.',
  'direct.error.data_invalid':
      'Message data is incomplete. Refresh to try again.',
  'direct.error.limit':
      'History limit reached for this view. Return to the latest messages.',
};
