import 'friend_action_strings.dart';
import 'direct_message_strings.dart';

const friendsZhCn = <String, String>{
  'avatar.menu': '头像菜单',
  'avatar.sendMessage': '发消息',
  'avatar.viewProfile': '查看资料',
  'avatar.profileUnavailable': '暂时无法查看这份资料。',
  ...directZhCn,
  ...friendActionsZhCn,
  'friends.title': '好友',
  'friends.recent': '最近私聊',
  'friends.readOnly': '目前可查看好友与申请、搜索用户；添加、处理申请和私信将在后续开放。',
  'friends.friends': '好友',
  'friends.incoming': '收到的申请',
  'friends.outgoing': '发出的申请',
  'friends.blocked': '已屏蔽',
  'friends.search': '搜索用户',
  'friends.searchHint': '呼号或游戏 ID',
  'friends.searchButton': '搜索',
  'friends.clear': '清除搜索',
  'friends.refresh': '刷新',
  'friends.retry': '重试',
  'friends.loading': '正在读取好友…',
  'friends.searchLimit': '搜索最多显示 20 个匹配用户，可细化关键词。',
  'friends.queryLength': '请输入至少 2 个字符后搜索。',
  'friends.submitSearch': '按 Enter 或点击搜索。',
  'friends.signedOut': '请通过右上角登录 SCM 账号后重试。',
  'friends.identityUnavailable': '当前账号暂时无法读取好友。请检查账号状态后重试。',
  'friends.forbidden': '当前账号无权读取这些好友信息。',
  'friends.hostUnavailable': '好友读取暂不可用，请检查客户端连接后重试。',
  'friends.unavailable': '暂时无法读取好友，请检查连接后重试。',
  'friends.invalidResponse': '未能读取有效的好友数据，请重试。',
  'friends.noResults': '没有匹配的用户，试试其他呼号或游戏 ID。',
  'friends.empty.friends': '暂无好友。',
  'friends.empty.incoming': '没有待处理的好友申请。',
  'friends.empty.outgoing': '没有发出的好友申请。',
  'friends.empty.blocked': '没有已屏蔽的用户。',
  'friends.unnamed': '未提供名称',
  'friends.relation.friend': '好友',
  'friends.relation.incoming': '等待你处理',
  'friends.relation.outgoing': '等待对方处理',
  'friends.relation.blocked': '已屏蔽',
  'friends.relation.none': '尚未建立好友关系',
  'friends.relation.unknown': '关系状态暂不可用',
};
const friendsZhTw = <String, String>{
  'avatar.menu': '頭像選單',
  'avatar.sendMessage': '傳送訊息',
  'avatar.viewProfile': '查看資料',
  'avatar.profileUnavailable': '暫時無法查看這份資料。',
  ...directZhTw,
  ...friendActionsZhTw,
  'friends.title': '好友',
  'friends.recent': '最近私聊',
  'friends.readOnly': '目前可查看好友與申請、搜尋使用者；新增、處理申請和私訊將於後續開放。',
  'friends.friends': '好友',
  'friends.incoming': '收到的申請',
  'friends.outgoing': '發出的申請',
  'friends.blocked': '已封鎖',
  'friends.search': '搜尋使用者',
  'friends.searchHint': '呼號或遊戲 ID',
  'friends.searchButton': '搜尋',
  'friends.clear': '清除搜尋',
  'friends.refresh': '重新整理',
  'friends.retry': '重試',
  'friends.loading': '正在讀取好友…',
  'friends.searchLimit': '搜尋最多顯示 20 個符合的使用者，可縮小關鍵字範圍。',
  'friends.queryLength': '請輸入至少 2 個字元後搜尋。',
  'friends.submitSearch': '按 Enter 或點擊搜尋。',
  'friends.signedOut': '請透過右上角登入 SCM 帳號後重試。',
  'friends.identityUnavailable': '目前帳號暫時無法讀取好友。請檢查帳號狀態後重試。',
  'friends.forbidden': '目前帳號無權讀取這些好友資訊。',
  'friends.hostUnavailable': '好友讀取暫不可用，請檢查用戶端連線後重試。',
  'friends.unavailable': '暫時無法讀取好友，請檢查連線後重試。',
  'friends.invalidResponse': '未能讀取有效的好友資料，請重試。',
  'friends.noResults': '沒有符合的使用者，試試其他呼號或遊戲 ID。',
  'friends.empty.friends': '暫無好友。',
  'friends.empty.incoming': '沒有待處理的好友申請。',
  'friends.empty.outgoing': '沒有發出的好友申請。',
  'friends.empty.blocked': '沒有已封鎖的使用者。',
  'friends.unnamed': '未提供名稱',
  'friends.relation.friend': '好友',
  'friends.relation.incoming': '等待你處理',
  'friends.relation.outgoing': '等待對方處理',
  'friends.relation.blocked': '已封鎖',
  'friends.relation.none': '尚未建立好友關係',
  'friends.relation.unknown': '關係狀態暫不可用',
};
const friendsEn = <String, String>{
  'avatar.menu': 'Avatar menu',
  'avatar.sendMessage': 'Send message',
  'avatar.viewProfile': 'View profile',
  'avatar.profileUnavailable': 'This profile is not available yet.',
  ...directEn,
  ...friendActionsEn,
  'friends.title': 'Friends',
  'friends.recent': 'Recent messages',
  'friends.readOnly': 'View friends and requests, or search for users. Adding friends, handling requests and messaging are not available yet.',
  'friends.friends': 'Friends',
  'friends.incoming': 'Received requests',
  'friends.outgoing': 'Sent requests',
  'friends.blocked': 'Blocked',
  'friends.search': 'Find a user',
  'friends.searchHint': 'Callsign or game ID',
  'friends.searchButton': 'Search',
  'friends.clear': 'Clear search',
  'friends.refresh': 'Refresh',
  'friends.retry': 'Retry',
  'friends.loading': 'Loading friends…',
  'friends.searchLimit':
      'Search shows up to 20 matches. Refine your query if needed.',
  'friends.queryLength': 'Enter at least 2 characters to search.',
  'friends.submitSearch': 'Press Enter or select Search.',
  'friends.signedOut': 'Sign in to SCM at the top right, then retry.',
  'friends.identityUnavailable': 'This account cannot read friends right now. Check your account status, then retry.',
  'friends.forbidden':
      'This account does not have permission to read these friends.',
  'friends.hostUnavailable':
      'Friends are unavailable. Check the client connection, then retry.',
  'friends.unavailable':
      'Could not load friends. Check your connection, then retry.',
  'friends.invalidResponse': 'Could not read valid friend data. Please retry.',
  'friends.noResults': 'No matching users. Try another callsign or game ID.',
  'friends.empty.friends': 'No friends yet.',
  'friends.empty.incoming': 'No pending friend requests.',
  'friends.empty.outgoing': 'No sent friend requests.',
  'friends.empty.blocked': 'No blocked users.',
  'friends.unnamed': 'Name unavailable',
  'friends.relation.friend': 'Friend',
  'friends.relation.incoming': 'Waiting for you',
  'friends.relation.outgoing': 'Waiting for a response',
  'friends.relation.blocked': 'Blocked',
  'friends.relation.none': 'Not friends',
  'friends.relation.unknown': 'Relationship unavailable',
};
