const friendActionsZhCn = <String, String>{
  'friends.manageHint': '查看好友、处理申请或搜索用户；私信将在后续开放。',
  'friends.exampleActions': '示例场景：操作仅改变本页示例，不影响真实好友。',
  'friends.action.send': '添加好友',
  'friends.action.accept': '接受',
  'friends.action.reject': '拒绝',
  'friends.action.cancel': '撤回申请',
  'friends.action.remove': '删除好友',
  'friends.action.block': '屏蔽用户',
  'friends.action.unblock': '解除屏蔽',
  'friends.confirm.remove': '删除后双方将不再出现在好友列表中，之后仍可重新申请。不会改变对方资料或舰队关系。',
  'friends.confirm.block': '现有好友或申请关系会被移除，对方将无法再向你发送好友申请。之后可在已屏蔽列表解除屏蔽。',
  'friends.keep.remove': '保留好友',
  'friends.keep.block': '取消',
  'friends.success.send': '好友申请已发送。',
  'friends.success.accept': '已添加为好友。',
  'friends.success.reject': '已拒绝好友申请。',
  'friends.success.cancel': '好友申请已撤回。',
  'friends.success.remove': '好友已删除。',
  'friends.success.block': '用户已屏蔽。',
  'friends.success.unblock': '已解除屏蔽。',
  'friends.outcomeUnknown': '尚未确认操作结果，请先刷新核对，不要重复提交。',
  'friends.targetChanged': '这条关系已变化或页面已过期，请刷新后再操作。',
  'friends.refreshRequired': '请刷新关系列表后再操作。',
  'friends.cooldown': '暂时不能再次发送申请，请稍后再试。',
  'friends.tooManyPending': '待处理的申请过多，请先撤回部分发出的申请。',
  'friends.rateLimited': '操作过于频繁，请稍后刷新重试。',
  'friends.rejected': '服务器未接受这次操作，请刷新核对当前关系。',
  'friends.busy': '另一项好友操作仍在处理中，请稍后刷新。',
};
const friendActionsZhTw = <String, String>{
  'friends.manageHint': '查看好友、處理申請或搜尋使用者；私訊將於後續開放。',
  'friends.exampleActions': '範例場景：操作僅改變本頁範例，不影響真實好友。',
  'friends.action.send': '新增好友',
  'friends.action.accept': '接受',
  'friends.action.reject': '拒絕',
  'friends.action.cancel': '撤回申請',
  'friends.action.remove': '刪除好友',
  'friends.action.block': '封鎖使用者',
  'friends.action.unblock': '解除封鎖',
  'friends.confirm.remove': '刪除後雙方將不再出現在好友列表中，之後仍可重新申請。不會改變對方資料或艦隊關係。',
  'friends.confirm.block': '現有好友或申請關係會被移除，對方將無法再向你傳送好友申請。之後可在已封鎖清單解除封鎖。',
  'friends.keep.remove': '保留好友',
  'friends.keep.block': '取消',
  'friends.success.send': '好友申請已傳送。',
  'friends.success.accept': '已新增為好友。',
  'friends.success.reject': '已拒絕好友申請。',
  'friends.success.cancel': '好友申請已撤回。',
  'friends.success.remove': '好友已刪除。',
  'friends.success.block': '使用者已封鎖。',
  'friends.success.unblock': '已解除封鎖。',
  'friends.outcomeUnknown': '尚未確認操作結果，請先重新整理核對，不要重複提交。',
  'friends.targetChanged': '這筆關係已變更或頁面已過期，請重新整理後再操作。',
  'friends.refreshRequired': '請重新整理關係清單後再操作。',
  'friends.cooldown': '暫時無法再次傳送申請，請稍後再試。',
  'friends.tooManyPending': '待處理的申請過多，請先撤回部分發出的申請。',
  'friends.rateLimited': '操作過於頻繁，請稍後重新整理再試。',
  'friends.rejected': '伺服器未接受這次操作，請重新整理核對目前關係。',
  'friends.busy': '另一項好友操作仍在處理中，請稍後重新整理。',
};
const friendActionsEn = <String, String>{
  'friends.manageHint': 'View friends, manage requests or search for people. Messaging is coming later.',
  'friends.exampleActions':
      'Example mode: actions change this preview only, never real friendships.',
  'friends.action.send': 'Add friend',
  'friends.action.accept': 'Accept',
  'friends.action.reject': 'Decline',
  'friends.action.cancel': 'Withdraw request',
  'friends.action.remove': 'Remove friend',
  'friends.action.block': 'Block user',
  'friends.action.unblock': 'Unblock',
  'friends.confirm.remove': 'You will be removed from each other’s friend lists. You can send a new request later. Profiles and fleet membership will not change.',
  'friends.confirm.block': 'This removes any friendship or pending request and prevents new friend requests from this person. You can unblock them from the Blocked list.',
  'friends.keep.remove': 'Keep friend',
  'friends.keep.block': 'Cancel',
  'friends.success.send': 'Friend request sent.',
  'friends.success.accept': 'Friend request accepted.',
  'friends.success.reject': 'Friend request declined.',
  'friends.success.cancel': 'Friend request withdrawn.',
  'friends.success.remove': 'Friend removed.',
  'friends.success.block': 'User blocked.',
  'friends.success.unblock': 'User unblocked.',
  'friends.outcomeUnknown':
      'The result is unconfirmed. Refresh to check before submitting again.',
  'friends.targetChanged':
      'This relationship changed or the page expired. Refresh before acting.',
  'friends.refreshRequired':
      'Refresh the relationship list before another action.',
  'friends.cooldown': 'You cannot send another request yet. Try again later.',
  'friends.tooManyPending':
      'Too many requests are pending. Withdraw some outgoing requests first.',
  'friends.rateLimited': 'Too many actions. Wait, then refresh and try again.',
  'friends.rejected': 'The server rejected this action. Refresh to check the current relationship.',
  'friends.busy': 'Another friend action is in progress. Refresh shortly.',
};
