const gameplayTimeZhCn = <String, String>{
  'gameplay.reset': '正在核对重置状态…',
  'gameplay.resetConfirmation': '等待确认重置。',
  'gameplay.reset.action': '重置账号时长',
  'gameplay.reset.title': '重置此账号的游玩时长？',
  'gameplay.reset.body':
      '将清除累计时长和公开汇总，其他设备联网后也会同步清零。记录许可和展示设置不变。重置后可重新导入一次 LIVE 历史。此操作无法撤销。',
  'gameplay.reset.keep': '保留时长',
  'gameplay.reset.checking': '正在核对账号时长…',
  'gameplay.reset.completed': '账号时长已重置。',
  'gameplay.reset.pending': '正在确认重置结果，请勿重复操作。应用会自动检查。',
  'gameplay.reset.conflict': '账号时长已变化，请重新确认。',
  'gameplay.reset.previewExpired': '确认已失效，请重新打开。',
  'gameplay.reset.unavailable': '暂时无法完成重置，请稍后再试。',
  'gameplay.explanationTitle': '查看记录说明',
  'gameplay.explanationBody': '应用运行期间，根据此电脑上检测到的 Star Citizen 运行状态累计时长。无法确认游戏状态时暂停累计，不补算休眠或应用关闭期间的时间。\n\n关闭记录会保留已有时长，再次开启后继续累计。是否在个人主页显示，由单独的展示开关控制。\n\n历史导入会先显示可识别时长的预览，确认后才保存。日志可能不完整，估算不代表全部游戏时间。',
  'gameplay.title': '游戏时长',
  'gameplay.duration': '{hours} 小时 {minutes} 分钟',
  'gameplay.description': '应用运行期间记录 Star Citizen 的运行时长，保存在此电脑。',
  'gameplay.off': '尚未开启记录',
  'gameplay.stopped': '已停止记录',
  'gameplay.recording': '正在记录',
  'gameplay.waiting': '等待游戏运行',
  'gameplay.gameUnknown': '游戏状态待确认',
  'gameplay.loading': '正在读取或保存…',
  'gameplay.error': '记录已暂停。请关闭其他应用副本后重试，并检查此电脑的可用空间。',
  'gameplay.readError': '暂时无法读取记录状态，请重试。',
  'gameplay.unsaved': '最近一段时长尚未保存，请重试保存。',
  'gameplay.stopError': '停止记录尚未保存，请重试。重启应用后可能恢复原设置。',
  'gameplay.unsupported': '当前版本暂不支持记录，请更新应用。',
  'gameplay.allow': '允许记录',
  'gameplay.resume': '继续记录',
  'gameplay.stop': '停止记录',
  'gameplay.retry': '重试',
  'gameplay.recordSwitch': '记录游戏时长',
  'gameplay.profileSwitch': '在个人主页显示时长',
  'gameplay.localTotal': '本机累计',
  'gameplay.remoteTotal': '已有历史时长',
  'gameplay.importedTotal': '其中日志导入',
  'gameplay.stats': '正在读取或保存…',
  'gameplay.checking': '正在检查导入资格…',
  'gameplay.choosing': '请选择游戏日志…',
  'gameplay.previewing': '正在读取日志…',
  'gameplay.confirming': '正在导入…',
  'gameplay.visibilityError': '显示设置尚未确认保存，请重试。',
  'gameplay.historyTitle': '导入历史时长',
  'gameplay.checkImport': '检查并导入',
  'gameplay.previewTitle': '确认导入历史时长',
  'gameplay.previewCounts':
      '{sessions} 段游戏记录 · {incomplete} 段不完整 · 跳过 {skipped} 个文件',
  'gameplay.previewCaveat': '日志可能不完整，只能计算其中可识别的时长，不代表全部游戏时间。',
  'gameplay.previewOnce': '每个账号当前仅可导入一次 LIVE 历史时长。',
  'gameplay.cancel': '取消',
  'gameplay.confirm': '导入时长',
  'gameplay.retryConfirm': '重试导入',
  'gameplay.history.unchecked': '仅从 LIVE 正式服历史日志补录时长。先检查导入资格，再预览并确认。',
  'gameplay.history.recordingRequired': '请先开启游戏时长记录，再补录历史时长。',
  'gameplay.history.available': '此账号可导入一次。选择 LIVE 目录中的 Game.log 查看预览，不计入测试服时长。',
  'gameplay.history.imported': '此账号已完成历史时长导入。',
  'gameplay.history.unavailable': '暂时无法确认补录资格，请重试。',
  'gameplay.history.identityRequired': '请先确认游戏身份，再检查导入资格。',
  'gameplay.history.overlapUnknown': '无法确认日志与已有时长是否重复，暂时不能导入。',
  'gameplay.history.busy': '正在处理另一项操作，请稍后重试。',
  'gameplay.history.empty': '日志中没有可导入的时长，请选择其他日志。',
  'gameplay.history.path': '请选择 LIVE 目录中的 Game.log；不支持测试服日志。',
  'gameplay.history.limit': '日志超出可处理范围，请选择其他日志。',
  'gameplay.history.previewExpired': '预览已过期，请重新选择日志。',
  'gameplay.history.accountChanged': '账号已变化，请重新检查导入资格。',
  'gameplay.history.cancelled': '导入已取消，可重新选择日志。',
  'gameplay.history.confirmUncertain': '暂时无法确认导入结果。重试可查询并完成本次导入。',
};
const gameplayTimeZhTw = <String, String>{
  'gameplay.reset': '正在核對重設狀態…',
  'gameplay.resetConfirmation': '等待確認重設。',
  'gameplay.reset.action': '重設帳號時長',
  'gameplay.reset.title': '重設此帳號的遊玩時長？',
  'gameplay.reset.body':
      '將清除累計時長與公開彙總，其他裝置連線後也會同步歸零。記錄許可與顯示設定不變。重設後可重新匯入一次 LIVE 歷史。此操作無法復原。',
  'gameplay.reset.keep': '保留時長',
  'gameplay.reset.checking': '正在核對帳號時長…',
  'gameplay.reset.completed': '帳號時長已重設。',
  'gameplay.reset.pending': '正在確認重設結果，請勿重複操作。應用程式會自動檢查。',
  'gameplay.reset.conflict': '帳號時長已變更，請重新確認。',
  'gameplay.reset.previewExpired': '確認已失效，請重新開啟。',
  'gameplay.reset.unavailable': '暫時無法完成重設，請稍後再試。',
  'gameplay.explanationTitle': '查看記錄說明',
  'gameplay.explanationBody': '應用程式執行期間，根據此電腦上偵測到的 Star Citizen 執行狀態累計時長。無法確認遊戲狀態時暫停累計，不補算休眠或應用程式關閉期間的時間。\n\n關閉記錄會保留既有時長，再次開啟後繼續累計。是否在個人主頁顯示，由獨立的顯示開關控制。\n\n歷史匯入會先顯示可辨識時長的預覽，確認後才儲存。日誌可能不完整，估算不代表全部遊戲時間。',
  'gameplay.title': '遊戲時長',
  'gameplay.duration': '{hours} 小時 {minutes} 分鐘',
  'gameplay.description': '應用程式執行期間記錄 Star Citizen 的執行時長，儲存在此電腦。',
  'gameplay.off': '尚未開啟記錄',
  'gameplay.stopped': '已停止記錄',
  'gameplay.recording': '正在記錄',
  'gameplay.waiting': '等待遊戲執行',
  'gameplay.gameUnknown': '遊戲狀態待確認',
  'gameplay.loading': '正在讀取或儲存…',
  'gameplay.error': '記錄已暫停。請關閉其他應用程式副本後重試，並檢查此電腦的可用空間。',
  'gameplay.readError': '暫時無法讀取記錄狀態，請重試。',
  'gameplay.unsaved': '最近一段時長尚未儲存，請重試儲存。',
  'gameplay.stopError': '停止記錄尚未儲存，請重試。重新啟動後可能恢復原設定。',
  'gameplay.unsupported': '目前版本暫不支援記錄，請更新應用程式。',
  'gameplay.allow': '允許記錄',
  'gameplay.resume': '繼續記錄',
  'gameplay.stop': '停止記錄',
  'gameplay.retry': '重試',
  'gameplay.recordSwitch': '記錄遊戲時長',
  'gameplay.profileSwitch': '在個人主頁顯示時長',
  'gameplay.localTotal': '本機累計',
  'gameplay.remoteTotal': '既有歷史時長',
  'gameplay.importedTotal': '其中日誌匯入',
  'gameplay.stats': '正在讀取或儲存…',
  'gameplay.checking': '正在檢查匯入資格…',
  'gameplay.choosing': '請選擇遊戲日誌…',
  'gameplay.previewing': '正在讀取日誌…',
  'gameplay.confirming': '正在匯入…',
  'gameplay.visibilityError': '顯示設定尚未確認儲存，請重試。',
  'gameplay.historyTitle': '匯入歷史時長',
  'gameplay.checkImport': '檢查並匯入',
  'gameplay.previewTitle': '確認匯入歷史時長',
  'gameplay.previewCounts':
      '{sessions} 段遊戲記錄 · {incomplete} 段不完整 · 略過 {skipped} 個檔案',
  'gameplay.previewCaveat': '日誌可能不完整，只能計算其中可辨識的時長，不代表全部遊戲時間。',
  'gameplay.previewOnce': '每個帳號目前僅可匯入一次 LIVE 歷史時數。',
  'gameplay.cancel': '取消',
  'gameplay.confirm': '匯入時長',
  'gameplay.retryConfirm': '重試匯入',
  'gameplay.history.unchecked': '僅從 LIVE 正式服歷史日誌補錄時長。先檢查匯入資格，再預覽並確認。',
  'gameplay.history.recordingRequired': '請先開啟遊戲時長記錄，再補錄歷史時長。',
  'gameplay.history.available': '此帳號可匯入一次。選擇 LIVE 目錄中的 Game.log 查看預覽，不計入測試服時長。',
  'gameplay.history.imported': '此帳號已完成歷史時長匯入。',
  'gameplay.history.unavailable': '暫時無法確認補錄資格，請重試。',
  'gameplay.history.identityRequired': '請先確認遊戲身分，再檢查匯入資格。',
  'gameplay.history.overlapUnknown': '無法確認日誌與既有時長是否重複，暫時不能匯入。',
  'gameplay.history.busy': '正在處理另一項操作，請稍後重試。',
  'gameplay.history.empty': '日誌中沒有可匯入的時長，請選擇其他日誌。',
  'gameplay.history.path': '請選擇 LIVE 目錄中的 Game.log；不支援測試服日誌。',
  'gameplay.history.limit': '日誌超出可處理範圍，請選擇其他日誌。',
  'gameplay.history.previewExpired': '預覽已過期，請重新選擇日誌。',
  'gameplay.history.accountChanged': '帳號已變更，請重新檢查匯入資格。',
  'gameplay.history.cancelled': '匯入已取消，可重新選擇日誌。',
  'gameplay.history.confirmUncertain': '暫時無法確認匯入結果。重試可查詢並完成本次匯入。',
};
const gameplayTimeEn = <String, String>{
  'gameplay.reset': 'Checking reset status…',
  'gameplay.resetConfirmation': 'Awaiting reset confirmation.',
  'gameplay.reset.action': 'Reset account playtime',
  'gameplay.reset.title': 'Reset playtime for this account?',
  'gameplay.reset.body': 'This clears accumulated playtime and the public summary. Other devices will reset when they connect. Recording and visibility settings stay unchanged. You can import LIVE history once again after resetting. This cannot be undone.',
  'gameplay.reset.keep': 'Keep playtime',
  'gameplay.reset.checking': 'Checking account playtime…',
  'gameplay.reset.completed': 'Account playtime reset.',
  'gameplay.reset.pending': 'Confirming the reset. Do not submit it again. The app will check automatically.',
  'gameplay.reset.conflict':
      'Account playtime changed. Please review the reset again.',
  'gameplay.reset.previewExpired':
      'Confirmation expired. Please open it again.',
  'gameplay.reset.unavailable':
      'Reset is temporarily unavailable. Please try again later.',
  'gameplay.explanationTitle': 'How time recording works',
  'gameplay.explanationBody': 'While this app is open, time is counted from the Star Citizen running state detected on this PC. Counting pauses when the game state is unknown. Time spent asleep or with this app closed is not added.\n\nTurning recording off keeps existing time. Turning it on resumes counting. Profile visibility is controlled separately.\n\nHistory import shows a preview of recognizable time before you confirm saving. Logs may be incomplete, so the estimate is not your full game history.',
  'gameplay.title': 'Game time',
  'gameplay.duration': '{hours} hr {minutes} min',
  'gameplay.description': 'Record how long Star Citizen runs while this app is open. Saved on this PC.',
  'gameplay.off': 'Recording is off',
  'gameplay.stopped': 'Recording stopped',
  'gameplay.recording': 'Recording',
  'gameplay.waiting': 'Waiting for the game',
  'gameplay.gameUnknown': 'Game status unknown',
  'gameplay.loading': 'Reading or saving…',
  'gameplay.error': 'Recording paused. Close other copies of the app, check free disk space, then retry.',
  'gameplay.readError': 'Recording status is unavailable. Retry to check it.',
  'gameplay.unsaved':
      'The latest playtime has not been saved. Retry to save it.',
  'gameplay.stopError': 'The stop setting has not been saved. Retry before restarting, or the previous setting may return.',
  'gameplay.unsupported':
      'Recording is unavailable in this version. Update the app.',
  'gameplay.allow': 'Allow recording',
  'gameplay.resume': 'Resume recording',
  'gameplay.stop': 'Stop recording',
  'gameplay.retry': 'Retry',
  'gameplay.recordSwitch': 'Record game time',
  'gameplay.profileSwitch': 'Show game time on my profile',
  'gameplay.localTotal': 'Total on this PC',
  'gameplay.remoteTotal': 'Existing historical playtime',
  'gameplay.importedTotal': 'Of which imported from logs',
  'gameplay.stats': 'Reading or saving…',
  'gameplay.checking': 'Checking import eligibility…',
  'gameplay.choosing': 'Choose a game log…',
  'gameplay.previewing': 'Reading the log…',
  'gameplay.confirming': 'Importing…',
  'gameplay.visibilityError':
      'The display setting has not been confirmed saved. Retry.',
  'gameplay.historyTitle': 'Import past playtime',
  'gameplay.checkImport': 'Check and import',
  'gameplay.previewTitle': 'Import past playtime?',
  'gameplay.previewCounts':
      '{sessions} sessions · {incomplete} incomplete · {skipped} files skipped',
  'gameplay.previewCaveat': 'Logs may be incomplete. This estimate covers only the time found in the log, not all your game time.',
  'gameplay.previewOnce':
      'Each account currently has one LIVE history import opportunity.',
  'gameplay.cancel': 'Cancel',
  'gameplay.confirm': 'Import playtime',
  'gameplay.retryConfirm': 'Retry import',
  'gameplay.history.unchecked': 'Import past playtime from LIVE logs only. Check eligibility, then preview and confirm.',
  'gameplay.history.recordingRequired':
      'Turn on game time recording before importing past playtime.',
  'gameplay.history.available': 'This account can import once. Choose Game.log in LIVE to preview. Test-server time is excluded.',
  'gameplay.history.imported':
      'This account has already imported past playtime.',
  'gameplay.history.unavailable':
      'Import eligibility is unconfirmed. Please retry.',
  'gameplay.history.identityRequired':
      'Confirm your game identity, then check again.',
  'gameplay.history.overlapUnknown': 'We cannot verify whether this overlaps with existing playtime. Import is unavailable.',
  'gameplay.history.busy':
      'Another operation is in progress. Try again shortly.',
  'gameplay.history.empty': 'No playtime was found. Choose another log.',
  'gameplay.history.path':
      'Choose Game.log in LIVE. Test-server logs are not supported.',
  'gameplay.history.limit':
      'This log exceeds the processing limit. Choose another log.',
  'gameplay.history.previewExpired':
      'The preview expired. Choose the log again.',
  'gameplay.history.accountChanged':
      'Your account changed. Check import eligibility again.',
  'gameplay.history.cancelled': 'Import cancelled. You can choose another log.',
  'gameplay.history.confirmUncertain': 'The import result is unconfirmed. Retry to check and complete this import.',
};
