const gameLogZhCn = <String, String>{
  'gameLog.lastChecked': '最近检查',
  'gameLog.sessionSignIn': '登录账号后显示本机游戏识别信息。',
  'gameLog.sessionAccountUnavailable': '账号连接暂不可用，恢复连接后会自动继续识别。',
  'gameLog.title': '本机游戏识别',
  'gameLog.description': '选择版本目录中的 Game.log，应用会使用它的上一级文件夹作为版本名称。日志仅在本机读取。',
  'gameLog.version': '游戏版本',
  'gameLog.LIVE': 'LIVE 正式版',
  'gameLog.PTU': 'PTU 测试版',
  'gameLog.addVersion': '添加版本',
  'gameLog.versionReady': '此版本已确认，可在游戏运行时展示。',
  'gameLog.versionPending': '请启动此版本并进入游戏；确认 Handle 后才会展示版本名称。',
  'gameLog.removeVersionTitle': '移除 {version}？',
  'gameLog.removeVersionDetail':
      '只会从这里移除该版本，不会删除游戏文件。再次使用时需要重新选择 Game.log 并完成一次身份确认。',
  'gameLog.keepVersion': '保留',
  'gameLog.removeVersion': '移除版本',
  'gameLog.cancel': '取消',
  'gameLog.add': '添加并使用',
  'gameLog.automatic': '自动选择日志',
  'gameLog.manual': '手动选择的日志',
  'gameLog.find': '自动查找',
  'gameLog.select': '选择 Game.log',
  'gameLog.stop': '停止识别',
  'gameLog.resume': '开始识别',
  'gameLog.retry': '重新检查',
  'gameLog.busy': '正在检查…',
  'gameLog.expected': '应用已验证 Handle',
  'gameLog.detected': '游戏内 Handle',
  'gameLog.sessionTitle': '当前游戏',
  'gameLog.sessionDescription': '自动显示此电脑上的游戏状态；进入服务器后会补充地点与舰船。',
  'gameLog.sessionState': '游戏状态',
  'gameLog.sessionVersion': '游戏版本',
  'gameLog.sessionIdentity': '游戏账号',
  'gameLog.sessionLoading': '正在读取',
  'gameLog.sessionPlaying': '游戏中',
  'gameLog.sessionNotRunning': '游戏未启动',
  'gameLog.sessionStopped': '识别已停止',
  'gameLog.sessionDetecting': '正在识别',
  'gameLog.sessionNotConfigured': '等待设置',
  'gameLog.sessionNeedsAttention': '需要检查',
  'gameLog.sessionUnavailable': '暂时无法读取',
  'gameLog.versionUnknown': '等待版本信息',
  'gameLog.versionConfirmed': '已确认',
  'gameLog.versionUnconfirmed': '待确认',
  'gameLog.identityWaiting': '等待游戏账号',
  'gameLog.identityMatched': '已匹配',
  'gameLog.identityMismatch': '与应用账号不同',
  'gameLog.server': '所在服务器',
  'gameLog.serverArea': '服务器区域',
  'gameLog.serverAreaUnknown': '等待区域代码',
  'gameLog.serverUnknown': '等待服务器信息',
  'gameLog.serverConnected': '已进入服务器',
  'gameLog.serverNotConnected': '尚未进入服务器',
  'gameLog.regionUS': '美服',
  'gameLog.regionEU': '欧服',
  'gameLog.regionAU': '澳服',
  'gameLog.regionASIA': '亚服',
  'gameLog.location': '当前位置',
  'gameLog.locationUnknown': '等待地点信息',
  'gameLog.locationConfirmed': '已确认',
  'gameLog.locationLikely': '较可信',
  'gameLog.locationPossible': '上次确认',
  'gameLog.ship': '当前舰船',
  'gameLog.shipUnknown': '等待舰船信息',
  'gameLog.shipConfirmed': '已确认',
  'gameLog.shipLikely': '较可信',
  'gameLog.shipPossible': '可能',
  'gameLog.notSelected': '正在查找所选版本的日志…',
  'gameLog.stopped': '已停止识别。',
  'gameLog.notRunning': '等待游戏启动。',
  'gameLog.unknown': '暂时无法确认游戏状态，请稍后重新检查。',
  'gameLog.waiting': '正在读取日志，等待游戏账号信息。请进入游戏。',
  'gameLog.reading': '正在读取已有日志，请稍候…',
  'gameLog.identified': '已识别游戏账号。',
  'gameLog.match': '游戏账号与应用身份一致。',
  'gameLog.mismatch': '游戏账号与应用身份不同，请切换到对应的账号。',
  'gameLog.ambiguous': '日志包含冲突的账号信息，请重新启动游戏后检查。',
  'gameLog.unreadable': '无法读取日志，请检查文件位置或重新选择。',
  'gameLog.differentInstallation': '当前游戏使用另一份日志，请自动查找或重新选择。',
  'gameLog.unsupported': '当前版本暂不支持本机识别。',
  'gameLog.notFound': '未找到所选版本的日志。请启动该版本一次，或手动选择 Game.log。',
  'gameLog.multipleLogs': '找到多份日志。请启动要使用的游戏，或手动选择对应的 Game.log。',
  'gameLog.otherVersion': '当前运行的是另一个版本。请切换上方游戏版本，或启动所选版本。',
  'gameLog.path': '无法使用此文件，请选择本机的 Game.log。',
  'gameLog.storage': '无法保存或读取识别设置，请重新检查。原设置已保留。',
  'gameLog.accountChanged': '账号已变化，请重新检查。',
  'gameLog.picker': '无法打开文件选择窗口，请重试。',
  'gameLog.unavailable': '暂时无法读取识别状态，请重新检查。',
};
const gameLogZhTw = <String, String>{
  'gameLog.lastChecked': '最近檢查',
  'gameLog.sessionSignIn': '登入帳號後顯示本機遊戲識別資訊。',
  'gameLog.sessionAccountUnavailable': '帳號連線暫不可用，恢復連線後會自動繼續識別。',
  'gameLog.title': '本機遊戲識別',
  'gameLog.description': '選擇版本目錄中的 Game.log，應用程式會使用它的上一層資料夾作為版本名稱。日誌僅在本機讀取。',
  'gameLog.version': '遊戲版本',
  'gameLog.LIVE': 'LIVE 正式版',
  'gameLog.PTU': 'PTU 測試版',
  'gameLog.addVersion': '新增版本',
  'gameLog.versionReady': '此版本已確認，可在遊戲執行時顯示。',
  'gameLog.versionPending': '請啟動此版本並進入遊戲；確認 Handle 後才會顯示版本名稱。',
  'gameLog.removeVersionTitle': '移除 {version}？',
  'gameLog.removeVersionDetail':
      '只會從這裡移除該版本，不會刪除遊戲檔案。再次使用時需要重新選擇 Game.log 並完成一次身分確認。',
  'gameLog.keepVersion': '保留',
  'gameLog.removeVersion': '移除版本',
  'gameLog.cancel': '取消',
  'gameLog.add': '新增並使用',
  'gameLog.automatic': '自動選擇日誌',
  'gameLog.manual': '手動選擇的日誌',
  'gameLog.find': '自動尋找',
  'gameLog.select': '選擇 Game.log',
  'gameLog.stop': '停止識別',
  'gameLog.resume': '開始識別',
  'gameLog.retry': '重新檢查',
  'gameLog.busy': '正在檢查…',
  'gameLog.expected': '應用程式已驗證 Handle',
  'gameLog.detected': '遊戲內 Handle',
  'gameLog.sessionTitle': '目前遊戲',
  'gameLog.sessionDescription': '自動顯示此電腦上的遊戲狀態；進入伺服器後會補充地點與艦船。',
  'gameLog.sessionState': '遊戲狀態',
  'gameLog.sessionVersion': '遊戲版本',
  'gameLog.sessionIdentity': '遊戲帳號',
  'gameLog.sessionLoading': '正在讀取',
  'gameLog.sessionPlaying': '遊戲中',
  'gameLog.sessionNotRunning': '遊戲未啟動',
  'gameLog.sessionStopped': '識別已停止',
  'gameLog.sessionDetecting': '正在識別',
  'gameLog.sessionNotConfigured': '等待設定',
  'gameLog.sessionNeedsAttention': '需要檢查',
  'gameLog.sessionUnavailable': '暫時無法讀取',
  'gameLog.versionUnknown': '等待版本資訊',
  'gameLog.versionConfirmed': '已確認',
  'gameLog.versionUnconfirmed': '待確認',
  'gameLog.identityWaiting': '等待遊戲帳號',
  'gameLog.identityMatched': '已配對',
  'gameLog.identityMismatch': '與應用程式帳號不同',
  'gameLog.server': '所在伺服器',
  'gameLog.serverArea': '伺服器區域',
  'gameLog.serverAreaUnknown': '等待區域代碼',
  'gameLog.serverUnknown': '等待伺服器資訊',
  'gameLog.serverConnected': '已進入伺服器',
  'gameLog.serverNotConnected': '尚未進入伺服器',
  'gameLog.regionUS': '美服',
  'gameLog.regionEU': '歐服',
  'gameLog.regionAU': '澳服',
  'gameLog.regionASIA': '亞服',
  'gameLog.location': '目前位置',
  'gameLog.locationUnknown': '等待地點資訊',
  'gameLog.locationConfirmed': '已確認',
  'gameLog.locationLikely': '較可信',
  'gameLog.locationPossible': '上次確認',
  'gameLog.ship': '目前艦船',
  'gameLog.shipUnknown': '等待艦船資訊',
  'gameLog.shipConfirmed': '已確認',
  'gameLog.shipLikely': '較可信',
  'gameLog.shipPossible': '可能',
  'gameLog.notSelected': '正在尋找所選版本的日誌…',
  'gameLog.stopped': '已停止識別。',
  'gameLog.notRunning': '等待遊戲啟動。',
  'gameLog.unknown': '暫時無法確認遊戲狀態，請稍後重新檢查。',
  'gameLog.waiting': '正在讀取日誌，等待遊戲帳號資訊。請進入遊戲。',
  'gameLog.reading': '正在讀取既有日誌，請稍候…',
  'gameLog.identified': '已識別遊戲帳號。',
  'gameLog.match': '遊戲帳號與應用程式身分一致。',
  'gameLog.mismatch': '遊戲帳號與應用程式身分不同，請切換到對應的帳號。',
  'gameLog.ambiguous': '日誌包含衝突的帳號資訊，請重新啟動遊戲後檢查。',
  'gameLog.unreadable': '無法讀取日誌，請檢查檔案位置或重新選擇。',
  'gameLog.differentInstallation': '目前遊戲使用另一份日誌，請自動尋找或重新選擇。',
  'gameLog.unsupported': '目前版本暫不支援本機識別。',
  'gameLog.notFound': '未找到所選版本的日誌。請啟動該版本一次，或手動選擇 Game.log。',
  'gameLog.multipleLogs': '找到多份日誌。請啟動要使用的遊戲，或手動選擇對應的 Game.log。',
  'gameLog.otherVersion': '目前執行的是另一個版本。請切換上方遊戲版本，或啟動所選版本。',
  'gameLog.path': '無法使用此檔案，請選擇本機的 Game.log。',
  'gameLog.storage': '無法儲存或讀取識別設定，請重新檢查。原設定已保留。',
  'gameLog.accountChanged': '帳號已變更，請重新檢查。',
  'gameLog.picker': '無法開啟檔案選擇視窗，請重試。',
  'gameLog.unavailable': '暫時無法讀取識別狀態，請重新檢查。',
};
const gameLogEn = <String, String>{
  'gameLog.lastChecked': 'Last checked',
  'gameLog.sessionSignIn': 'Sign in to view local game detection information.',
  'gameLog.sessionAccountUnavailable': 'The account connection is unavailable. Detection resumes automatically when it reconnects.',
  'gameLog.title': 'Local game detection',
  'gameLog.description': 'Choose Game.log inside a version folder. Its parent folder becomes the version name. Logs stay on this computer.',
  'gameLog.version': 'Game version',
  'gameLog.LIVE': 'LIVE · Public release',
  'gameLog.PTU': 'PTU · Test version',
  'gameLog.addVersion': 'Add version',
  'gameLog.versionReady':
      'This version is confirmed and can appear while the game is running.',
  'gameLog.versionPending': 'Start this version and enter the game. Its name appears after your Handle is confirmed.',
  'gameLog.removeVersionTitle': 'Remove {version}?',
  'gameLog.removeVersionDetail': 'This only removes the version from this list. Game files are not deleted. To use it again, choose Game.log and confirm your identity once.',
  'gameLog.keepVersion': 'Keep',
  'gameLog.removeVersion': 'Remove version',
  'gameLog.cancel': 'Cancel',
  'gameLog.add': 'Add and use',
  'gameLog.automatic': 'Automatic log selection',
  'gameLog.manual': 'Manually selected log',
  'gameLog.find': 'Find automatically',
  'gameLog.select': 'Select Game.log',
  'gameLog.stop': 'Stop detection',
  'gameLog.resume': 'Start detection',
  'gameLog.retry': 'Check again',
  'gameLog.busy': 'Checking…',
  'gameLog.expected': 'Verified app Handle',
  'gameLog.detected': 'In-game Handle',
  'gameLog.sessionTitle': 'Current game',
  'gameLog.sessionDescription': 'Shows this computer\'s game status automatically, then adds location and ship details after you join a server.',
  'gameLog.sessionState': 'Game status',
  'gameLog.sessionVersion': 'Game version',
  'gameLog.sessionIdentity': 'Game account',
  'gameLog.sessionLoading': 'Loading',
  'gameLog.sessionPlaying': 'In game',
  'gameLog.sessionNotRunning': 'Game not running',
  'gameLog.sessionStopped': 'Detection stopped',
  'gameLog.sessionDetecting': 'Detecting',
  'gameLog.sessionNotConfigured': 'Setup required',
  'gameLog.sessionNeedsAttention': 'Check required',
  'gameLog.sessionUnavailable': 'Temporarily unavailable',
  'gameLog.versionUnknown': 'Waiting for version details',
  'gameLog.versionConfirmed': 'Confirmed',
  'gameLog.versionUnconfirmed': 'Not confirmed',
  'gameLog.identityWaiting': 'Waiting for game account',
  'gameLog.identityMatched': 'Matched',
  'gameLog.identityMismatch': 'Different from app account',
  'gameLog.server': 'Server',
  'gameLog.serverArea': 'Server area',
  'gameLog.serverAreaUnknown': 'Waiting for area code',
  'gameLog.serverUnknown': 'Waiting for server details',
  'gameLog.serverConnected': 'Connected to a server',
  'gameLog.serverNotConnected': 'Not in a server',
  'gameLog.regionUS': 'US',
  'gameLog.regionEU': 'Europe',
  'gameLog.regionAU': 'Australia',
  'gameLog.regionASIA': 'Asia',
  'gameLog.location': 'Current location',
  'gameLog.locationUnknown': 'Waiting for location details',
  'gameLog.locationConfirmed': 'Confirmed',
  'gameLog.locationLikely': 'Likely',
  'gameLog.locationPossible': 'Last confirmed',
  'gameLog.ship': 'Current ship',
  'gameLog.shipUnknown': 'Waiting for ship details',
  'gameLog.shipConfirmed': 'Confirmed',
  'gameLog.shipLikely': 'Likely',
  'gameLog.shipPossible': 'Possible',
  'gameLog.notSelected': 'Finding the log for the selected version…',
  'gameLog.stopped': 'Detection stopped.',
  'gameLog.notRunning': 'Waiting for the game to start.',
  'gameLog.unknown': 'Game status is unavailable. Check again shortly.',
  'gameLog.waiting':
      'Reading the log and waiting for account details. Enter the game.',
  'gameLog.reading': 'Reading the existing log. Please wait…',
  'gameLog.identified': 'Game account detected.',
  'gameLog.match': 'Your game account matches your app identity.',
  'gameLog.mismatch': 'Your game account differs from your app identity. Switch to the matching account.',
  'gameLog.ambiguous': 'The log contains conflicting account details. Restart the game and check again.',
  'gameLog.unreadable':
      'Cannot read the log. Check its location or select it again.',
  'gameLog.differentInstallation': 'The running game uses another log. Find it automatically or select it again.',
  'gameLog.unsupported': 'Local detection is unavailable in this version.',
  'gameLog.notFound':
      'No log found for this version. Start it once or select Game.log.',
  'gameLog.multipleLogs': 'Multiple logs found. Start the game you want to use or select its Game.log.',
  'gameLog.otherVersion': 'A different version is running. Change the version above or start the selected version.',
  'gameLog.path': 'Cannot use this file. Select Game.log on this computer.',
  'gameLog.storage': 'Cannot read or save detection settings. Check again. Previous settings are kept.',
  'gameLog.accountChanged': 'Your account changed. Check again.',
  'gameLog.picker': 'Cannot open the file picker. Try again.',
  'gameLog.unavailable': 'Detection status is unavailable. Check again.',
};
