const simplifiedGeneralSettingsStrings = <String, String>{
  'settings.sections.title': '设置分类',
  'settings.sectionPicker': '选择设置分类',
  'settings.accountIdentity': '账号与识别',
  'settings.accountIdentity.description': 'SCM 账号、RSI 身份与本机识别',
  'settings.generalData': '常规与数据',
  'settings.generalData.description': '界面语言、明暗模式与动态效果',
  'settings.syncPrivacy': '同步与隐私',
  'settings.syncPrivacy.description': '跨端同步、可见范围与缓存策略',
  'settings.notifications': '提醒设置',
  'settings.notifications.description': '应用内、提示音、Windows 与浮层提醒',
  'settings.diagnostics': '诊断与维护',
  'settings.diagnostics.description': '运行状态、日志、更新与修复',
  'settings.deferred.status': '暂未开放',
  'settings.deferred.title': '这个分类已经预留',
  'settings.deferred.body': '相关能力接入后，设置会在这里开放。当前不会展示或保存尚未接线的选项。',
  'settings.aboutLegal': '帮助与支持',
  'settings.aboutLegal.description': '游戏识别、说明、更新与问题反馈',
  'settings.general.title': '把客户端调到顺手',
  'settings.general.description':
      '管理这台设备上的界面语言、明暗模式和动态效果。账号资料与游戏内浮层拥有各自设置，不在此处重复。',
  'settings.general.language.title': '界面语言',
  'settings.general.language.description':
      '只改变 StarBridge 客户端；不会覆盖 SCM 账号的语言偏好。',
  'settings.general.language.zhCN': '简体中文',
  'settings.general.language.zhTW': '繁體中文',
  'settings.general.language.enUS': 'English',
  'settings.general.appearance.title': '明暗模式',
  'settings.general.appearance.description': '实时切换，不需要重新启动客户端。',
  'settings.general.appearance.dark': '深色',
  'settings.general.appearance.darkDescription': '适合夜间以及与游戏同时运行',
  'settings.general.appearance.light': '浅色',
  'settings.general.appearance.lightDescription': '适合白天、阅读与高环境亮度',
  'settings.general.motion.title': '动画体验',
  'settings.general.motion.description': '减少非必要过渡，同时保留状态变化和操作结果。',
  'settings.general.motion.reduce': '减少动态效果',
  'settings.general.motion.reduceDescription':
      '收敛页面切换、水波和非必要位移；系统已要求减少动画时仍会优先遵循系统。',
  'settings.general.behavior.title': '启动与后台',
  'settings.general.behavior.description': '控制登录 Windows 后的启动方式，以及关闭主窗口后的应用行为。',
  'settings.general.behavior.closeSummary.tray': '关闭窗口后：继续在系统托盘运行',
  'settings.general.behavior.closeSummary.exit': '关闭窗口后：完全退出应用',
  'settings.general.behavior.startupSummary.disabled': '登录 Windows 后：不自动启动',
  'settings.general.behavior.startupSummary.window': '登录 Windows 后：打开主窗口',
  'settings.general.behavior.startupSummary.background': '登录 Windows 后：直接进入后台',
  'settings.general.behavior.launch.title': '开机自启动',
  'settings.general.behavior.launch.description': '登录 Windows 后自动启动星海舰桥。',
  'settings.general.behavior.close.title': '关闭窗口时',
  'settings.general.behavior.close.description': '选择进入系统托盘或完全退出应用。首次关闭时也会明确询问。',
  'settings.general.behavior.close.tray': '进入系统托盘',
  'settings.general.behavior.close.exit': '完全退出',
  'settings.general.behavior.startup.title': '自动启动后',
  'settings.general.behavior.startup.description': '关闭开机自启动时，此选项不会生效。',
  'settings.general.behavior.startup.window': '打开主窗口',
  'settings.general.behavior.startup.background': '进入系统托盘',
  'settings.lifecycle.close.title': '将 StarBridge 收起到托盘？',
  'settings.lifecycle.close.body': '为保持游戏内浮层、快捷键和通知继续工作，关闭窗口后 StarBridge 将在系统托盘运行。选择完全退出会停止这些后台能力。你可以随时在应用设置中更改关闭行为。',
  'settings.lifecycle.close.background': '收起到托盘',
  'settings.lifecycle.close.exit': '完全退出',
  'settings.lifecycle.close.saveFailed': '关闭行为未能保存，请检查后台连接后重试。',
  'settings.lifecycle.startup.title': '随 Windows 启动 StarBridge',
  'settings.lifecycle.startup.body':
      'StarBridge 可在登录 Windows 后静默启动到托盘，以便准备游戏内浮层、快捷键和通知。你可以随时在设置中关闭。',
  'settings.lifecycle.startup.option': '随 Windows 启动（推荐）',
  'settings.lifecycle.startup.continue': '继续',
  'settings.lifecycle.startup.saveFailed': '启动设置未能保存，请检查后台连接后重试。',
  'settings.general.deviceNotice': '界面与启动偏好保存在本机；时长同步与公开展示按上方设置执行。',
  'settings.general.loading': '正在读取当前设备设置…',
  'settings.general.unavailable.title': '暂时无法读取应用设置',
  'settings.general.retry': '重新读取',
  'settings.general.error.hostUnavailable':
      '客户端后台服务暂时不可用。重新连接后再试，临时选择不会被当成已保存。',
  'settings.general.error.timeout': '操作等待超时。已保留上一次确认的设置，请重试。',
  'settings.general.error.invalidResponse': '设置响应格式不兼容，客户端没有使用不完整数据。',
  'settings.general.error.invalidValue': '这项选择不受当前版本支持，原设置保持不变。',
  'settings.general.error.recoveredDefaults': '设置文件已损坏，客户端已安全恢复为默认值；请重新确认当前选择。',
  'settings.general.error.readFailed': '无法读取当前设备设置，已保留上一次确认的外观；请重试。',
  'settings.general.error.saveFailed': '设置未能写入当前设备，原设置保持不变。',
  'settings.general.error.revisionConflict': '设置已在其他位置更新，客户端已重新读取最新值。',
  'settings.general.error.outcomeUncertain':
      '连接中断，无法确认这次更改是否写入；已恢复上一次确认值，重连后会重新核对。',
  'settings.general.error.startupRegistrationFailed':
      'Windows 拒绝更新开机启动项，原设置与注册项均已保留。',
  'settings.general.error.unavailable': '当前设备设置暂时不可用，请检查连接后重试。',
};

const traditionalGeneralSettingsStrings = <String, String>{
  'settings.sections.title': '設定分類',
  'settings.sectionPicker': '選擇設定分類',
  'settings.accountIdentity': '帳號與識別',
  'settings.accountIdentity.description': 'SCM 帳號、RSI 身分與本機識別',
  'settings.generalData': '一般與資料',
  'settings.generalData.description': '介面語言、明暗模式與動態效果',
  'settings.syncPrivacy': '同步與隱私',
  'settings.syncPrivacy.description': '跨端同步、可見範圍與快取策略',
  'settings.notifications': '提醒設定',
  'settings.notifications.description': '應用程式內、提示音、Windows 與浮層提醒',
  'settings.diagnostics': '診斷與維護',
  'settings.diagnostics.description': '執行狀態、記錄、更新與修復',
  'settings.deferred.status': '暫未開放',
  'settings.deferred.title': '這個分類已經預留',
  'settings.deferred.body': '相關能力接入後，設定會在這裡開放。目前不會顯示或儲存尚未接線的選項。',
  'settings.aboutLegal': '幫助與支援',
  'settings.aboutLegal.description': '遊戲識別、說明、更新與問題回報',
  'settings.general.title': '把客戶端調到順手',
  'settings.general.description':
      '管理這台裝置上的介面語言、明暗模式和動態效果。帳號資料與遊戲內浮層擁有各自設定，不在此處重複。',
  'settings.general.language.title': '介面語言',
  'settings.general.language.description':
      '只改變 StarBridge 客戶端；不會覆蓋 SCM 帳號的語言偏好。',
  'settings.general.language.zhCN': '简体中文',
  'settings.general.language.zhTW': '繁體中文',
  'settings.general.language.enUS': 'English',
  'settings.general.appearance.title': '明暗模式',
  'settings.general.appearance.description': '即時切換，不需要重新啟動客戶端。',
  'settings.general.appearance.dark': '深色',
  'settings.general.appearance.darkDescription': '適合夜間以及與遊戲同時執行',
  'settings.general.appearance.light': '淺色',
  'settings.general.appearance.lightDescription': '適合白天、閱讀與高環境亮度',
  'settings.general.motion.title': '動畫體驗',
  'settings.general.motion.description': '減少非必要過渡，同時保留狀態變化和操作結果。',
  'settings.general.motion.reduce': '減少動態效果',
  'settings.general.motion.reduceDescription':
      '收斂頁面切換、水波和非必要位移；系統已要求減少動畫時仍會優先遵循系統。',
  'settings.general.behavior.title': '啟動與背景執行',
  'settings.general.behavior.description':
      '控制登入 Windows 後的啟動方式，以及關閉主視窗後的應用程式行為。',
  'settings.general.behavior.closeSummary.tray': '關閉視窗後：繼續在系統匣執行',
  'settings.general.behavior.closeSummary.exit': '關閉視窗後：完全結束應用程式',
  'settings.general.behavior.startupSummary.disabled': '登入 Windows 後：不自動啟動',
  'settings.general.behavior.startupSummary.window': '登入 Windows 後：開啟主視窗',
  'settings.general.behavior.startupSummary.background': '登入 Windows 後：直接進入背景',
  'settings.general.behavior.launch.title': '開機自動啟動',
  'settings.general.behavior.launch.description': '登入 Windows 後自動啟動星海艦橋。',
  'settings.general.behavior.close.title': '關閉視窗時',
  'settings.general.behavior.close.description':
      '選擇進入系統匣或完全結束應用程式。首次關閉時也會明確詢問。',
  'settings.general.behavior.close.tray': '進入系統匣',
  'settings.general.behavior.close.exit': '完全結束',
  'settings.general.behavior.startup.title': '自動啟動後',
  'settings.general.behavior.startup.description': '關閉開機自動啟動時，此選項不會生效。',
  'settings.general.behavior.startup.window': '開啟主視窗',
  'settings.general.behavior.startup.background': '進入系統匣',
  'settings.lifecycle.close.title': '將 StarBridge 收進系統匣？',
  'settings.lifecycle.close.body': '為了讓遊戲內浮層、快捷鍵和通知繼續運作，關閉視窗後 StarBridge 將在系統匣執行。選擇完全結束會停止這些背景能力。你可以隨時在應用程式設定中更改關閉行為。',
  'settings.lifecycle.close.background': '收進系統匣',
  'settings.lifecycle.close.exit': '完全結束',
  'settings.lifecycle.close.saveFailed': '關閉行為未能儲存，請檢查背景連線後再試。',
  'settings.lifecycle.startup.title': '隨 Windows 啟動 StarBridge',
  'settings.lifecycle.startup.body':
      'StarBridge 可在登入 Windows 後靜默啟動至系統匣，以便準備遊戲內浮層、快捷鍵和通知。你可以隨時在設定中關閉。',
  'settings.lifecycle.startup.option': '隨 Windows 啟動（建議）',
  'settings.lifecycle.startup.continue': '繼續',
  'settings.lifecycle.startup.saveFailed': '啟動設定未能儲存，請檢查背景連線後再試。',
  'settings.general.deviceNotice': '介面與啟動偏好儲存在本機；時數同步與公開展示依上方設定執行。',
  'settings.general.loading': '正在讀取目前裝置設定…',
  'settings.general.unavailable.title': '暫時無法讀取應用程式設定',
  'settings.general.retry': '重新讀取',
  'settings.general.error.hostUnavailable':
      '客戶端背景服務暫時無法使用。重新連線後再試，暫時選擇不會被當成已儲存。',
  'settings.general.error.timeout': '操作等待逾時。已保留上一次確認的設定，請重試。',
  'settings.general.error.invalidResponse': '設定回應格式不相容，客戶端沒有使用不完整資料。',
  'settings.general.error.invalidValue': '這項選擇不受目前版本支援，原設定保持不變。',
  'settings.general.error.recoveredDefaults': '設定檔已損壞，客戶端已安全恢復為預設值；請重新確認目前選擇。',
  'settings.general.error.readFailed': '無法讀取目前裝置設定，已保留上一次確認的外觀；請重試。',
  'settings.general.error.saveFailed': '設定未能寫入目前裝置，原設定保持不變。',
  'settings.general.error.revisionConflict': '設定已在其他位置更新，客戶端已重新讀取最新值。',
  'settings.general.error.outcomeUncertain':
      '連線中斷，無法確認這次變更是否寫入；已恢復上一次確認值，重新連線後會再次核對。',
  'settings.general.error.startupRegistrationFailed':
      'Windows 拒絕更新開機啟動項目，原設定與登錄項目均已保留。',
  'settings.general.error.unavailable': '目前裝置設定暫時無法使用，請檢查連線後再試。',
};

const englishGeneralSettingsStrings = <String, String>{
  'settings.sections.title': 'Settings sections',
  'settings.sectionPicker': 'Choose a settings section',
  'settings.accountIdentity': 'Account & identity',
  'settings.accountIdentity.description':
      'SCM account, RSI identity, and local recognition',
  'settings.generalData': 'General & data',
  'settings.generalData.description':
      'Interface language, light or dark appearance, and motion',
  'settings.syncPrivacy': 'Sync & privacy',
  'settings.syncPrivacy.description':
      'Cross-device sync, visibility, and cache policy',
  'settings.notifications': 'Notifications',
  'settings.notifications.description':
      'In-app, sound, Windows, and overlay alerts',
  'settings.diagnostics': 'Diagnostics & maintenance',
  'settings.diagnostics.description':
      'Runtime status, logs, updates, and repair',
  'settings.deferred.status': 'Not available yet',
  'settings.deferred.title': 'This section is reserved',
  'settings.deferred.body': 'Settings will appear here when the related capability is connected. Unavailable options are not shown or saved.',
  'settings.aboutLegal': 'Help & support',
  'settings.aboutLegal.description':
      'Game detection, notices, updates, and feedback',
  'settings.general.title': 'Make the client feel right',
  'settings.general.description': 'Manage the interface language, light or dark appearance, and motion on this device. Account details and the in-game overlay keep their own settings.',
  'settings.general.language.title': 'Interface language',
  'settings.general.language.description': 'Changes the StarBridge client only and does not overwrite your SCM account language preference.',
  'settings.general.language.zhCN': '简体中文',
  'settings.general.language.zhTW': '繁體中文',
  'settings.general.language.enUS': 'English',
  'settings.general.appearance.title': 'Light and dark mode',
  'settings.general.appearance.description':
      'Switch immediately without restarting the client.',
  'settings.general.appearance.dark': 'Dark',
  'settings.general.appearance.darkDescription':
      'For night use and running alongside the game',
  'settings.general.appearance.light': 'Light',
  'settings.general.appearance.lightDescription':
      'For daylight, reading, and bright rooms',
  'settings.general.motion.title': 'Motion',
  'settings.general.motion.description': 'Reduce non-essential transitions while preserving state changes and outcomes.',
  'settings.general.motion.reduce': 'Reduce motion',
  'settings.general.motion.reduceDescription': 'Limits page movement, ripples, and non-essential transitions. A system reduce-motion request still takes priority.',
  'settings.general.behavior.title': 'Startup & background',
  'settings.general.behavior.description': 'Control what happens after Windows sign-in and when the main window closes.',
  'settings.general.behavior.closeSummary.tray':
      'After closing: keep running in the system tray',
  'settings.general.behavior.closeSummary.exit':
      'After closing: exit the application',
  'settings.general.behavior.startupSummary.disabled':
      'After Windows sign-in: do not start automatically',
  'settings.general.behavior.startupSummary.window':
      'After Windows sign-in: open the main window',
  'settings.general.behavior.startupSummary.background':
      'After Windows sign-in: start in the background',
  'settings.general.behavior.launch.title': 'Start with Windows',
  'settings.general.behavior.launch.description':
      'Start StarBridge automatically after Windows sign-in.',
  'settings.general.behavior.close.title': 'When closing the window',
  'settings.general.behavior.close.description': 'Choose whether to keep running in the system tray or exit. The first close asks explicitly too.',
  'settings.general.behavior.close.tray': 'System tray',
  'settings.general.behavior.close.exit': 'Exit',
  'settings.general.behavior.startup.title': 'After automatic startup',
  'settings.general.behavior.startup.description':
      'This has no effect while Start with Windows is off.',
  'settings.general.behavior.startup.window': 'Open window',
  'settings.general.behavior.startup.background': 'System tray',
  'settings.lifecycle.close.title': 'Send StarBridge to the system tray?',
  'settings.lifecycle.close.body': 'StarBridge can keep the in-game overlay, shortcuts, and notifications working from the system tray after the window closes. Exiting stops those background capabilities. You can change this later in Application settings.',
  'settings.lifecycle.close.background': 'Send to tray',
  'settings.lifecycle.close.exit': 'Exit completely',
  'settings.lifecycle.close.saveFailed': 'The close behavior could not be saved. Check the background connection and try again.',
  'settings.lifecycle.startup.title': 'Start StarBridge with Windows',
  'settings.lifecycle.startup.body': 'StarBridge can start quietly in the system tray after Windows sign-in so the in-game overlay, shortcuts, and notifications are ready. You can turn this off later in Settings.',
  'settings.lifecycle.startup.option': 'Start with Windows (recommended)',
  'settings.lifecycle.startup.continue': 'Continue',
  'settings.lifecycle.startup.saveFailed': 'The startup setting could not be saved. Check the background connection and try again.',
  'settings.general.deviceNotice': 'Appearance and startup preferences stay on this device. Playtime syncing and public visibility follow the settings above.',
  'settings.general.loading': 'Reading settings for this device…',
  'settings.general.unavailable.title':
      'Application settings are temporarily unavailable',
  'settings.general.retry': 'Read again',
  'settings.general.error.hostUnavailable': 'The client background service is temporarily unavailable. Reconnect and try again; temporary choices are not treated as saved.',
  'settings.general.error.timeout': 'The operation timed out. The last confirmed settings remain active; try again.',
  'settings.general.error.invalidResponse': 'The settings response is incompatible, so the client did not use incomplete data.',
  'settings.general.error.invalidValue': 'This choice is not supported by the current version. Existing settings were kept.',
  'settings.general.error.recoveredDefaults': 'The settings file was damaged, so the client safely recovered defaults. Review the current choices before continuing.',
  'settings.general.error.readFailed': 'Settings for this device could not be read. The last confirmed appearance was kept; try again.',
  'settings.general.error.saveFailed': 'Settings could not be written to this device. Existing settings were kept.',
  'settings.general.error.revisionConflict':
      'Settings changed elsewhere. The client has read the latest values.',
  'settings.general.error.outcomeUncertain': 'The connection ended before the change could be confirmed. The last confirmed values were restored and will be checked after reconnecting.',
  'settings.general.error.startupRegistrationFailed': 'Windows refused to update the startup entry. The previous setting and registration were kept.',
  'settings.general.error.unavailable': 'Settings for this device are temporarily unavailable. Check the connection and try again.',
};
