const homeZhCn = <String, String>{
  'home.moreInDevelopment': '更多功能开发中',
  'home.greeting.morning': '早上好',
  'home.greeting.noon': '中午好',
  'home.greeting.afternoon': '下午好',
  'home.greeting.evening': '晚上好',
  'home.greeting.fallbackName': '旅行者',
  'home.title.captain': '舰长',
  'home.title.navigator': '领航员',
  'home.title.pathfinder': '开拓者',
  'home.title.voyager': '远航者',
  'home.scene.location': 'Crusader · Orison',
  'home.room.title': '当前房间',
  'home.room.loading': '正在读取房间…',
  'home.room.signedOut': '登录后即可查看当前房间。',
  'home.room.unavailable': '暂时无法读取房间。',
  'home.room.empty': '你还没有加入房间。',
  'home.room.emptyHint': '浏览正在招募的房间，找到下一段航程。',
  'home.room.open': '进入房间',
  'home.room.browse': '浏览房间',
  'home.room.members': '成员',
  'home.fortune.title': '今日星海运势',
  'home.fortune.unobserved': '今日星象尚未观测',
  'home.fortune.observe': '开始观测',
  'home.fortune.againTomorrow': '明日可再次观测',
  'home.fortune.clear.title': '航路清晰',
  'home.fortune.clear.body': '适合主动联络队友，把搁置的计划向前推进一步。',
  'home.fortune.tailwind.title': '顺风航行',
  'home.fortune.tailwind.body': '今天的临时决定可能带来意外收获，给探索留一点余地。',
  'home.fortune.rendezvous.title': '适合相聚',
  'home.fortune.rendezvous.body': '熟悉的呼号会带来好消息，适合发起一次轻松的组队。',
  'home.fortune.steady.title': '稳定巡航',
  'home.fortune.steady.body': '不必追赶所有目标，完成手边最确定的一件事就很好。',
  'home.fortune.signal.title': '捕获信号',
  'home.fortune.signal.body': '多留意一条消息或一个邀请，机会可能来自不起眼的方向。',
  'home.fortune.harbor.title': '宜作整备',
  'home.fortune.harbor.body': '适合整理舰队与装备，为下一次出发减少一点阻力。',
};

const homeZhTw = <String, String>{
  'home.moreInDevelopment': '更多功能開發中',
  'home.greeting.morning': '早安',
  'home.greeting.noon': '中午好',
  'home.greeting.afternoon': '下午好',
  'home.greeting.evening': '晚上好',
  'home.greeting.fallbackName': '旅行者',
  'home.title.captain': '艦長',
  'home.title.navigator': '領航員',
  'home.title.pathfinder': '開拓者',
  'home.title.voyager': '遠航者',
  'home.scene.location': 'Crusader · Orison',
  'home.room.title': '目前房間',
  'home.room.loading': '正在讀取房間…',
  'home.room.signedOut': '登入後即可查看目前房間。',
  'home.room.unavailable': '暫時無法讀取房間。',
  'home.room.empty': '你還沒有加入房間。',
  'home.room.emptyHint': '瀏覽正在招募的房間，找到下一段航程。',
  'home.room.open': '進入房間',
  'home.room.browse': '瀏覽房間',
  'home.room.members': '成員',
  'home.fortune.title': '今日星海運勢',
  'home.fortune.unobserved': '今日星象尚未觀測',
  'home.fortune.observe': '開始觀測',
  'home.fortune.againTomorrow': '明日可再次觀測',
  'home.fortune.clear.title': '航路清晰',
  'home.fortune.clear.body': '適合主動聯絡隊友，把擱置的計畫向前推進一步。',
  'home.fortune.tailwind.title': '順風航行',
  'home.fortune.tailwind.body': '今天的臨時決定可能帶來意外收穫，給探索留一點餘地。',
  'home.fortune.rendezvous.title': '適合相聚',
  'home.fortune.rendezvous.body': '熟悉的呼號會帶來好消息，適合發起一次輕鬆的組隊。',
  'home.fortune.steady.title': '穩定巡航',
  'home.fortune.steady.body': '不必追趕所有目標，完成手邊最確定的一件事就很好。',
  'home.fortune.signal.title': '捕獲訊號',
  'home.fortune.signal.body': '多留意一則訊息或一個邀請，機會可能來自不起眼的方向。',
  'home.fortune.harbor.title': '宜作整備',
  'home.fortune.harbor.body': '適合整理艦隊與裝備，為下一次出發減少一點阻力。',
};

const homeEn = <String, String>{
  'home.moreInDevelopment': 'More features in development',
  'home.greeting.morning': 'Good morning',
  'home.greeting.noon': 'Good afternoon',
  'home.greeting.afternoon': 'Good afternoon',
  'home.greeting.evening': 'Good evening',
  'home.greeting.fallbackName': 'traveler',
  'home.title.captain': 'Captain',
  'home.title.navigator': 'Navigator',
  'home.title.pathfinder': 'Pathfinder',
  'home.title.voyager': 'Voyager',
  'home.scene.location': 'Crusader · Orison',
  'home.room.title': 'Current room',
  'home.room.loading': 'Loading your room…',
  'home.room.signedOut': 'Sign in to see your current room.',
  'home.room.unavailable': 'Your room is temporarily unavailable.',
  'home.room.empty': 'You have not joined a room yet.',
  'home.room.emptyHint': 'Browse recruiting rooms and find your next voyage.',
  'home.room.open': 'Open room',
  'home.room.browse': 'Browse rooms',
  'home.room.members': 'Members',
  'home.fortune.title': "Today's outlook",
  'home.fortune.unobserved': "Today's sky has not been observed",
  'home.fortune.observe': 'Observe now',
  'home.fortune.againTomorrow': 'Observe again tomorrow',
  'home.fortune.clear.title': 'Clear passage',
  'home.fortune.clear.body':
      'Reach out to your crew and move one waiting plan forward.',
  'home.fortune.tailwind.title': 'Following winds',
  'home.fortune.tailwind.body':
      'A spontaneous choice may reward you today. Leave room to explore.',
  'home.fortune.rendezvous.title': 'Good company',
  'home.fortune.rendezvous.body':
      'A familiar callsign may bring good news. Start a relaxed session.',
  'home.fortune.steady.title': 'Steady cruise',
  'home.fortune.steady.body':
      'You do not need every objective. Finish the clearest one in reach.',
  'home.fortune.signal.title': 'Signal acquired',
  'home.fortune.signal.body':
      'Watch one quiet message or invitation; opportunity may arrive softly.',
  'home.fortune.harbor.title': 'Time to prepare',
  'home.fortune.harbor.body':
      'Organize your fleet and equipment before the next departure.',
};
