const simplifiedLegacyMigrationStrings = <String, String>{
  'migration.title': "旧账号资料迁移",
  'migration.scope': "将旧账号的个人主页和游戏统计一次性迁入当前账号。机库、好友、聊天及自定义图片暂不支持迁移。",
  'migration.completedBody': "个人资料已迁入当前账号，之后直接使用当前账号即可。",
  'migration.organizationPending': "旧组织将迁为社区组织，迁移入口稍后开放。组织及成员关系暂时保留。",
  'migration.notStarted': "先预览旧资料，再确认迁移。",
  'migration.credentialRequired': "验证旧账号后，可以预览待迁移资料。",
  'migration.credentialRejected': "账号或密码不正确，请重新输入。",
  'migration.verificationRateLimited': "尝试次数过多，请 10 分钟后再试。",
  'migration.sourceNotConfigured': "资料迁移暂未开放。",
  'migration.profileNotFound': "这个旧账号没有可迁移的主页资料，请核对账号。",
  'migration.previewed': "请核对以下资料，并在 15 分钟内确认迁移。",
  'migration.completed': "个人主页和游戏统计已迁移。",
  'migration.sourceUnavailable': "暂时无法读取旧资料，请稍后重试。",
  'migration.linkRequired': "请先验证旧账号，再预览资料。",
  'migration.accountMismatch': "这个旧账号已用于其他迁移，请核对账号或联系支持。",
  'migration.authorizationRequired': "登录已失效，请重新登录后继续。",
  'migration.unsupportedData': "暂不支持这份旧资料，请联系支持。",
  'migration.previewRequired': "请重新预览旧资料，再确认迁移。",
  'migration.previewExpired': "预览已过期，请重新预览。",
  'migration.replacementRequired': "当前主页已有资料，请确认是否替换。",
  'migration.targetChanged': "当前主页已有新的修改，请重新预览后确认。",
  'migration.loading': "正在读取迁移状态…",
  'migration.previewLoading': "正在验证并读取旧资料…",
  'migration.importing': "请在浏览器中确认授权，完成后将继续迁移。",
  'migration.preview': "预览旧资料",
  'migration.confirm': "确认迁移",
  'migration.cancel': "暂不迁移",
  'migration.retryStatus': "刷新状态",
  'migration.verifyFirst': "请先验证旧账号。",
  'migration.oldProfile': "待迁移资料",
  'migration.newProfile': "当前主页",
  'migration.ownerConsent': "这是我的旧账号，我同意将这些资料迁入当前账号。",
  'migration.replaceConsent': "替换当前呼号、简介、模块内容和游戏统计。",
  'migration.preserved': "保留当前背景、头像和可见范围。本次迁移不会删除旧账号资料。",
  'migration.counts': "主页模块 {modules} · 最爱舰船 {favorites} · 游戏时长 {hours} 小时",
  'migration.dialogTitle': "验证旧账号",
  'migration.dialogBody': "输入旧版星海舰桥的账号和密码。",
  'migration.passwordNotice': "密码仅用于本次验证，不会保存。",
  'migration.verifyPreview': "验证并预览",
};

const traditionalLegacyMigrationStrings = <String, String>{
  'migration.title': "舊帳號資料遷移",
  'migration.scope': "將舊帳號的個人主頁和遊戲統計一次性遷入目前帳號。機庫、好友、聊天及自訂圖片暫不支援遷移。",
  'migration.completedBody': "個人資料已遷入目前帳號，之後直接使用目前帳號即可。",
  'migration.organizationPending': "舊組織將遷為社群組織，遷移入口稍後開放。組織及成員關係暫時保留。",
  'migration.notStarted': "先預覽舊資料，再確認遷移。",
  'migration.credentialRequired': "驗證舊帳號後，可以預覽待遷移資料。",
  'migration.credentialRejected': "帳號或密碼不正確，請重新輸入。",
  'migration.verificationRateLimited': "嘗試次數過多，請 10 分鐘後再試。",
  'migration.sourceNotConfigured': "資料遷移暫未開放。",
  'migration.profileNotFound': "這個舊帳號沒有可遷移的主頁資料，請核對帳號。",
  'migration.previewed': "請核對以下資料，並在 15 分鐘內確認遷移。",
  'migration.completed': "個人主頁和遊戲統計已遷移。",
  'migration.sourceUnavailable': "暫時無法讀取舊資料，請稍後重試。",
  'migration.linkRequired': "請先驗證舊帳號，再預覽資料。",
  'migration.accountMismatch': "這個舊帳號已用於其他遷移，請核對帳號或聯絡支援。",
  'migration.authorizationRequired': "登入已失效，請重新登入後繼續。",
  'migration.unsupportedData': "暫不支援這份舊資料，請聯絡支援。",
  'migration.previewRequired': "請重新預覽舊資料，再確認遷移。",
  'migration.previewExpired': "預覽已過期，請重新預覽。",
  'migration.replacementRequired': "目前主頁已有資料，請確認是否替換。",
  'migration.targetChanged': "目前主頁已有新的修改，請重新預覽後確認。",
  'migration.loading': "正在讀取遷移狀態…",
  'migration.previewLoading': "正在驗證並讀取舊資料…",
  'migration.importing': "請在瀏覽器中確認授權，完成後將繼續遷移。",
  'migration.preview': "預覽舊資料",
  'migration.confirm': "確認遷移",
  'migration.cancel': "暫不遷移",
  'migration.retryStatus': "重新整理狀態",
  'migration.verifyFirst': "請先驗證舊帳號。",
  'migration.oldProfile': "待遷移資料",
  'migration.newProfile': "目前主頁",
  'migration.ownerConsent': "這是我的舊帳號，我同意將這些資料遷入目前帳號。",
  'migration.replaceConsent': "替換目前呼號、簡介、模組內容和遊戲統計。",
  'migration.preserved': "保留目前背景、頭像和可見範圍。本次遷移不會刪除舊帳號資料。",
  'migration.counts': "主頁模組 {modules} · 最愛艦船 {favorites} · 遊戲時長 {hours} 小時",
  'migration.dialogTitle': "驗證舊帳號",
  'migration.dialogBody': "輸入舊版星海艦橋的帳號和密碼。",
  'migration.passwordNotice': "密碼僅用於本次驗證，不會儲存。",
  'migration.verifyPreview': "驗證並預覽",
};

const englishLegacyMigrationStrings = <String, String>{
  'migration.title': "Import old profile",
  'migration.scope': "Import your old profile and play statistics into your current account once. Hangar, friends, chat and custom images are not supported yet.",
  'migration.completedBody': "Your profile is now in your current account. Continue using this account.",
  'migration.organizationPending': "Old organizations will become community organizations. Organization import is coming later; organizations and memberships are preserved for now.",
  'migration.notStarted': "Preview your old profile, then confirm the import.",
  'migration.credentialRequired':
      "Verify your old account to preview its profile.",
  'migration.credentialRejected':
      "Incorrect account or password. Please try again.",
  'migration.verificationRateLimited':
      "Too many attempts. Try again in 10 minutes.",
  'migration.sourceNotConfigured': "Profile import is not available yet.",
  'migration.profileNotFound': "No profile was found for this old account. Check that you chose the right account.",
  'migration.previewed':
      "Review the profile below and confirm within 15 minutes.",
  'migration.completed': "Your profile and play statistics have been imported.",
  'migration.sourceUnavailable':
      "Unable to read your old profile right now. Please try again later.",
  'migration.linkRequired':
      "Verify your old account before previewing its profile.",
  'migration.accountMismatch': "This old account is already assigned to another import. Check the account or contact support.",
  'migration.authorizationRequired':
      "Your session has expired. Sign in again to continue.",
  'migration.unsupportedData':
      "This old profile is not supported yet. Please contact support.",
  'migration.previewRequired':
      "Preview your old profile again before confirming.",
  'migration.previewExpired':
      "This preview has expired. Preview the profile again.",
  'migration.replacementRequired':
      "Your current profile already has data. Confirm whether to replace it.",
  'migration.targetChanged':
      "Your current profile has changed. Preview again before confirming.",
  'migration.loading': "Checking import status…",
  'migration.previewLoading': "Verifying and reading your old profile…",
  'migration.importing':
      "Confirm access in your browser to continue the import.",
  'migration.preview': "Preview old profile",
  'migration.confirm': "Confirm import",
  'migration.cancel': "Not now",
  'migration.retryStatus': "Refresh status",
  'migration.verifyFirst': "Verify your old account first.",
  'migration.oldProfile': "Profile to import",
  'migration.newProfile': "Current profile",
  'migration.ownerConsent': "This is my old account. I agree to import this profile into my current account.",
  'migration.replaceConsent': "Replace my current call sign, introduction, modules and play statistics.",
  'migration.preserved': "Keep my current background, avatar and visibility. This import will not delete the old account's data.",
  'migration.counts':
      "{modules} modules · {favorites} favorite ships · {hours} hours played",
  'migration.dialogTitle': "Verify old account",
  'migration.dialogBody':
      "Enter your account and password from the old StarBridge client.",
  'migration.passwordNotice':
      "Your password is only used for this verification and will not be saved.",
  'migration.verifyPreview': "Verify and preview",
};
