import 'profile_collaboration_strings.dart';
import 'profile_module_strings.dart';

const simplifiedLocalProfileStrings = <String, String>{
  'profile.visitor.notVisible': '对方尚未公开个人页面，或当前可见范围不包含你。',
  'profile.visitor.refreshMembers': '成员资料已更新。请返回并刷新列表后重试。',
  'profile.visibility.related': '舰队、组织与好友可见',
  'profile.visibility.title': '个人页面可见度',
  'profile.visibility.scopeNote': '调整在线个人页面的访问范围。本机未发布的编辑内容不会随此操作上传；机库共享设置保持不变。',
  'profile.visibility.failed': '暂时无法确认可见度。请刷新后查看当前设置。',
  'profile.visibility.cancel': '取消',
  'profile.visibility.save': '保存可见度',
  ...simplifiedProfileCollaborationStrings,
  ...simplifiedProfileModuleStrings,
  'profile.local.category.combat': '战斗',
  'profile.local.category.transport': '运输',
  'profile.local.category.industrial': '工业',
  'profile.local.category.exploration': '探索',
  'profile.local.category.support': '支援',
  'profile.local.category.utility': '通用',
  'profile.local.category.competition': '竞赛',
  'profile.local.category.multi-role': '多用途',
  'profile.local.category.ground-combat': '地面战斗',
  'profile.local.category.ground-transport': '地面运输',
  'profile.local.category.ground-industrial': '地面工业',
  'profile.local.category.ground-exploration': '地面探索',
  'profile.local.category.ground-support': '地面支援',
  'profile.local.category.ground-competition': '地面竞赛',
  'profile.local.size.ground-small': '轻型载具',
  'profile.local.size.ground-medium': '中型载具',
  'profile.local.size.ground-large': '重型载具',
  'profile.local.category.unknown': '未知用途',
  'profile.local.size.small': '小型',
  'profile.local.size.medium': '中型',
  'profile.local.size.large': '大型',
  'profile.local.size.capital': '旗舰级',
  'profile.local.catalogPrice': '历史目录参考价 · USD',
  'profile.local.estimatedValue': '机库估值',
  'profile.local.knownValue': '已知估值',
  'profile.local.unpriced': '艘未计价',
  'profile.local.save': '保存到本机',
  'profile.local.label': '本机个人页面',
  'profile.local.description': '这些修改保存在本机，不会更新已公开的页面。',
  'profile.local.remoteUnavailable': '在线资料暂时无法读取，你仍可编辑并保存本机页面。',
  'profile.local.create': '创建个人页面',
  'profile.local.noCallSign': '未设置呼号',
  'profile.local.firstSteps': '先设置呼号、背景和展示模块，再保存到本机。',
  'profile.local.failed': '本机资料操作未完成，请重试。',
  'profile.local.readFailed': '本机资料无法读取，原资料已保留。请重试或检查本机存储。',
  'profile.local.hangarChanged': '机库已变化，请刷新页面后重新选择舰船。',
  'profile.local.favorites': '选择最爱舰船',
  'profile.local.selected': '已选',
  'profile.local.search': '搜索舰船或制造商',
  'profile.local.noHangar': '请先在个人机库读取并保存舰船，再选择最爱舰船。',
  'profile.local.noResults': '没有符合条件的舰船。',
  'profile.local.unavailableSelection': '部分已选舰船暂未在机库找到。',
  'profile.local.removeUnavailable': '移除失效选择',
  'profile.local.hangarSource': '本机已保存机库',
  'profile.local.hangarPartial': '本机机库（部分物品类别待核对）',
  'profile.local.unknown': '待确认',
};
const traditionalLocalProfileStrings = <String, String>{
  'profile.visitor.notVisible': '對方尚未公開個人頁面，或目前可見範圍不包含你。',
  'profile.visitor.refreshMembers': '成員資料已更新。請返回並重新整理清單後重試。',
  'profile.visibility.related': '艦隊、組織與好友可見',
  'profile.visibility.title': '個人頁面可見度',
  'profile.visibility.scopeNote': '調整線上個人頁面的存取範圍。本機未發布的編輯內容不會隨此操作上傳；機庫共享設定保持不變。',
  'profile.visibility.failed': '暫時無法確認可見度。請重新整理後查看目前設定。',
  'profile.visibility.cancel': '取消',
  'profile.visibility.save': '儲存可見度',
  ...traditionalProfileCollaborationStrings,
  ...traditionalProfileModuleStrings,
  'profile.local.category.combat': '戰鬥',
  'profile.local.category.transport': '運輸',
  'profile.local.category.industrial': '工業',
  'profile.local.category.exploration': '探索',
  'profile.local.category.support': '支援',
  'profile.local.category.utility': '通用',
  'profile.local.category.competition': '競賽',
  'profile.local.category.multi-role': '多用途',
  'profile.local.category.ground-combat': '地面戰鬥',
  'profile.local.category.ground-transport': '地面運輸',
  'profile.local.category.ground-industrial': '地面工業',
  'profile.local.category.ground-exploration': '地面探索',
  'profile.local.category.ground-support': '地面支援',
  'profile.local.category.ground-competition': '地面競賽',
  'profile.local.size.ground-small': '輕型載具',
  'profile.local.size.ground-medium': '中型載具',
  'profile.local.size.ground-large': '重型載具',
  'profile.local.category.unknown': '未知用途',
  'profile.local.size.small': '小型',
  'profile.local.size.medium': '中型',
  'profile.local.size.large': '大型',
  'profile.local.size.capital': '旗艦級',
  'profile.local.catalogPrice': '歷史目錄參考價 · USD',
  'profile.local.estimatedValue': '機庫估值',
  'profile.local.knownValue': '已知估值',
  'profile.local.unpriced': '艘未計價',
  'profile.local.save': '儲存至本機',
  'profile.local.label': '本機個人頁面',
  'profile.local.description': '這些修改儲存在本機，不會更新已公開的頁面。',
  'profile.local.remoteUnavailable': '線上資料暫時無法讀取，你仍可編輯並儲存本機頁面。',
  'profile.local.create': '建立個人頁面',
  'profile.local.noCallSign': '尚未設定呼號',
  'profile.local.firstSteps': '先設定呼號、背景和展示模組，再儲存至本機。',
  'profile.local.failed': '本機資料操作未完成，請重試。',
  'profile.local.readFailed': '本機資料無法讀取，原資料已保留。請重試或檢查本機儲存。',
  'profile.local.hangarChanged': '機庫已變更，請重新整理頁面後重新選擇艦船。',
  'profile.local.favorites': '選擇最愛艦船',
  'profile.local.selected': '已選',
  'profile.local.search': '搜尋艦船或製造商',
  'profile.local.noHangar': '請先在個人機庫讀取並儲存艦船，再選擇最愛艦船。',
  'profile.local.noResults': '沒有符合條件的艦船。',
  'profile.local.unavailableSelection': '部分已選艦船暫未在機庫找到。',
  'profile.local.removeUnavailable': '移除失效選擇',
  'profile.local.hangarSource': '本機已儲存機庫',
  'profile.local.hangarPartial': '本機機庫（部分物品類別待核對）',
  'profile.local.unknown': '待確認',
};
const englishLocalProfileStrings = <String, String>{
  'profile.visitor.notVisible': 'This profile is not published or is not shared with you.',
  'profile.visitor.refreshMembers': 'Member details have changed. Go back, refresh the list, and try again.',
  'profile.visibility.related': 'Fleet, organizations and friends',
  'profile.visibility.title': 'Profile visibility',
  'profile.visibility.scopeNote': 'Change access to your online profile. Unpublished local edits will not be uploaded. Hangar sharing stays unchanged.',
  'profile.visibility.failed': 'Visibility could not be confirmed. Refresh to check the current setting.',
  'profile.visibility.cancel': 'Cancel',
  'profile.visibility.save': 'Save visibility',
  ...englishProfileCollaborationStrings,
  ...englishProfileModuleStrings,
  'profile.local.category.combat': 'Combat',
  'profile.local.category.transport': 'Transport',
  'profile.local.category.industrial': 'Industrial',
  'profile.local.category.exploration': 'Exploration',
  'profile.local.category.support': 'Support',
  'profile.local.category.utility': 'Utility',
  'profile.local.category.competition': 'Competition',
  'profile.local.category.multi-role': 'Multi-role',
  'profile.local.category.ground-combat': 'Ground combat',
  'profile.local.category.ground-transport': 'Ground transport',
  'profile.local.category.ground-industrial': 'Ground industrial',
  'profile.local.category.ground-exploration': 'Ground exploration',
  'profile.local.category.ground-support': 'Ground support',
  'profile.local.category.ground-competition': 'Ground competition',
  'profile.local.size.ground-small': 'Light vehicle',
  'profile.local.size.ground-medium': 'Medium vehicle',
  'profile.local.size.ground-large': 'Heavy vehicle',
  'profile.local.category.unknown': 'Unknown role',
  'profile.local.size.small': 'Small',
  'profile.local.size.medium': 'Medium',
  'profile.local.size.large': 'Large',
  'profile.local.size.capital': 'Capital',
  'profile.local.catalogPrice': 'Historical catalog price · USD',
  'profile.local.estimatedValue': 'Estimated value',
  'profile.local.knownValue': 'Known value',
  'profile.local.unpriced': 'ships unpriced',
  'profile.local.save': 'Save on this device',
  'profile.local.label': 'Local personal page',
  'profile.local.description':
      'Changes stay on this device and do not update your published page.',
  'profile.local.remoteUnavailable': 'Online details are unavailable. You can still edit and save your local page.',
  'profile.local.create': 'Create personal page',
  'profile.local.noCallSign': 'No call sign yet',
  'profile.local.firstSteps':
      'Set your call sign, background and modules, then save on this device.',
  'profile.local.failed': 'The local operation did not finish. Please retry.',
  'profile.local.readFailed': 'Cannot read local details. Your data is preserved. Retry or check local storage.',
  'profile.local.hangarChanged':
      'Your hangar changed. Refresh the page and select ships again.',
  'profile.local.favorites': 'Choose favorite ships',
  'profile.local.selected': 'Selected',
  'profile.local.search': 'Search ships or manufacturers',
  'profile.local.noHangar':
      'Read and save your personal hangar before choosing favorite ships.',
  'profile.local.noResults': 'No matching ships.',
  'profile.local.unavailableSelection':
      'Some selected ships are currently missing from your hangar.',
  'profile.local.removeUnavailable': 'Remove missing selections',
  'profile.local.hangarSource': 'Saved local hangar',
  'profile.local.hangarPartial': 'Local hangar (some item types need review)',
  'profile.local.unknown': 'Unknown',
};
