const simplifiedLocalPrivacyStrings = <String, String>{
  'privacy.local.locationConfidence': '仅共享已确认的位置',
  'privacy.local.locationConfidenceDescription': '关闭后，组织和房间也可看到推测位置。好友仍只可看到已确认的位置。各自的位置共享范围保持不变。',
  'privacy.first.organizationsPending': '组织：逐个确认共享范围后开启。主舰队功能暂未开放。',
  'privacy.community.title': '组织共享范围',
  'privacy.community.body': '选择向这个组织共享哪些实时信息。之后可在“共享与隐私”中单独调整；机库与事件分享不受影响。',
  'privacy.community.none': '不共享',
  'privacy.community.confirm': '确认范围',
  'privacy.community.failed': '未能保存选择，请稍后再试。',
  'privacy.first.scope': '启用后的共享范围',
  'privacy.first.excluded': '本次不授权机库、事件或好友在线共享。',
  'privacy.first.adjust': '调整共享范围',
  'privacy.first.selectedGroups': '已选可见组（{count}）',
  'privacy.first.none': '不共享',
  'privacy.first.organizations': '舰队',
  'privacy.first.separator': '、',
  'privacy.first.scopeLine': '{audience}：{scope}',
  'privacy.first.title': '启用状态共享',
  'privacy.first.body': '状态共享让组织和房间中的成员了解你的游戏状态，方便协同行动。是否使用此功能？',
  'privacy.first.remember':
      '你可以随时在“设置 → 同步与隐私”调整共享范围或关闭此功能。本机会记住当前账号的选择；重启、重连自动恢复，隐身时暂停。',
  'privacy.first.decline': '暂不开启',
  'privacy.first.accept': '启用状态共享',
  'privacy.first.failed': '尚未确认保存成功，请稍后重试。',
  'privacy.local.liveTitle': '实时状态共享',
  'privacy.local.liveScope': '当前可应用在线、飞船、位置和服务器设置。机库与事件分享暂只保留本机选择；好友及游戏 ID 可见性不在本次应用范围。服务器按双方关系决定实际可见信息。',
  'privacy.local.publicationLiveHint': '应用共享后，保存会更新实时共享策略；关闭并保存将撤回实时信息。',
  'privacy.local.localChoiceOnly': '暂只保存选择，尚未接入对外共享',
  'privacy.local.savedLocal': '设置已保存到本机',
  'privacy.local.leaveLiveBody': '保存当前设置？若已确认共享，保存后也会更新实时共享范围。',
  'privacy.local.apply': '应用实时共享',
  'privacy.local.stop': '停止并撤回',
  'privacy.local.applyTitle': '应用已保存的实时共享设置？',
  'privacy.local.applyBody': '按已保存的舰队与房间范围共享实时状态。本机将记住当前账号的确认，重启或断线后自动恢复，后续保存会更新共享范围。隐身时暂停；关闭共享或停止并撤回会取消自动恢复。不会上传机库或事件，也不启用好友在线共享。',
  'privacy.local.live.inactive': '首次共享需要确认一次，之后会自动恢复。仅保存设置不会启用共享。',
  'privacy.local.live.identityRequired': '等待游戏身份核对。已确认过的共享会在身份确认后自动恢复。',
  'privacy.local.live.publishing': '正在应用共享策略…',
  'privacy.local.live.pending': '已有新设置，正在等待服务器确认。',
  'privacy.local.live.reconnecting': '连接暂时中断，正在自动恢复共享，无需手动刷新。',
  'privacy.local.live.applied': '服务器已确认实时共享策略。',
  'privacy.local.live.withdrawn': '服务器已确认撤回实时信息。',
  'privacy.local.live.failed': '未能确认应用结果。请检查连接与账号权限后重试。',
  'privacy.local.live.withdrawalPending': '尚未确认撤回。恢复连接后会继续尝试撤回，不会恢复共享。',
  'privacy.local.title': '共享与隐私',
  'privacy.local.description': '分别选择舰队与房间中可共享的信息。',
  'privacy.local.localOnlyTitle': '目前仅保存到本机',
  'privacy.local.localOnlyBody':
      '尚未启用对外状态同步。本页不会改变其他玩家目前看到的信息，也不会清除旧客户端已共享的信息。',
  'privacy.local.publication': '允许共享状态',
  'privacy.local.publicationHint': '保存共享意愿；关闭后保留下方选择。目前不会对外发布或撤回信息。',
  'privacy.local.fleet': '舰队',
  'privacy.local.room': '房间',
  'privacy.local.fleetHint': '舰队的共享范围，与房间分别设置。',
  'privacy.local.roomHint': '房间成员的共享范围，不沿用舰队选择。',
  'privacy.local.audience': '共享给谁',
  'privacy.local.fields': '共享哪些信息',
  'privacy.local.allMembers': '所有成员',
  'privacy.local.administrators': '舰队管理员',
  'privacy.local.groups': '自定义可见组尚未接入，已保留 {count} 个已有选择。',
  'privacy.local.presence': '在线状态',
  'privacy.local.ship': '当前飞船',
  'privacy.local.location': '当前位置',
  'privacy.local.server': '服务器信息',
  'privacy.local.hangar': '个人机库',
  'privacy.local.events': '事件分享',
  'privacy.local.separateSettings': '游戏 ID 可见性、好友在线状态及具体事件类别将分别接入，不受本页设置替代。',
  'privacy.local.save': '保存到本机',
  'privacy.local.discard': '放弃更改',
  'privacy.local.saved': '已保存到本机 · 尚未对外生效',
  'privacy.local.defaults': '默认选择 · 尚未保存',
  'privacy.local.dirty': '有未保存的更改',
  'privacy.local.saving': '正在保存…',
  'privacy.local.loading': '正在读取隐私设置',
  'privacy.local.retry': '重新检查',
  'privacy.local.reload': '重新读取',
  'privacy.local.readFailed': '无法读取隐私设置。已有设置未被覆盖，请重试。',
  'privacy.local.saveFailed': '未能确认保存成功，更改仍保留在本页。请重试保存。',
  'privacy.local.conflict': '设置已发生变化，请重新读取后再编辑。',
  'privacy.local.accountChanged': '请先确认账号登录状态，再重新读取隐私设置。',
  'privacy.local.leaveTitle': '保存隐私设置？',
  'privacy.local.leaveBody': '当前更改尚未保存。保存只记录到本机，不会启用对外共享。',
  'privacy.local.stay': '继续编辑',
};
const traditionalLocalPrivacyStrings = <String, String>{
  'privacy.local.locationConfidence': '僅分享已確認的位置',
  'privacy.local.locationConfidenceDescription': '關閉後，組織和房間也可看到推測位置。好友仍只可看到已確認的位置。各自的位置分享範圍保持不變。',
  'privacy.first.organizationsPending': '組織：逐個確認共享範圍後開啟。主艦隊功能暫未開放。',
  'privacy.community.title': '組織共享範圍',
  'privacy.community.body': '選擇向這個組織共享哪些即時資訊。之後可在「共享與隱私」中單獨調整；機庫與事件分享不受影響。',
  'privacy.community.none': '不共享',
  'privacy.community.confirm': '確認範圍',
  'privacy.community.failed': '未能儲存選擇，請稍後再試。',
  'privacy.first.scope': '啟用後的共享範圍',
  'privacy.first.excluded': '此次不授權機庫、事件或好友在線共享。',
  'privacy.first.adjust': '調整共享範圍',
  'privacy.first.selectedGroups': '已選可見組（{count}）',
  'privacy.first.none': '不共享',
  'privacy.first.organizations': '艦隊',
  'privacy.first.separator': '、',
  'privacy.first.scopeLine': '{audience}：{scope}',
  'privacy.first.title': '啟用狀態共享',
  'privacy.first.body': '狀態共享讓組織和房間中的成員了解你的遊戲狀態，方便協同行動。是否使用此功能？',
  'privacy.first.remember':
      '你可以隨時在「設定 → 同步與隱私」調整共享範圍或關閉此功能。本機會記住目前帳號的選擇；重新啟動、重連自動恢復，隱身時暫停。',
  'privacy.first.decline': '暫不開啟',
  'privacy.first.accept': '啟用狀態共享',
  'privacy.first.failed': '尚未確認儲存成功，請稍後重試。',
  'privacy.local.liveTitle': '即時狀態共享',
  'privacy.local.liveScope': '目前可套用在線、飛船、位置和伺服器設定。機庫與事件分享暫只保留本機選擇；好友及遊戲 ID 可見性不在此次範圍。伺服器按雙方關係決定實際可見資訊。',
  'privacy.local.publicationLiveHint': '套用共享後，儲存會更新即時共享策略；關閉並儲存將撤回即時資訊。',
  'privacy.local.localChoiceOnly': '暫只儲存選擇，尚未接入對外共享',
  'privacy.local.savedLocal': '設定已儲存到本機',
  'privacy.local.leaveLiveBody': '儲存目前設定？若已確認共享，儲存後也會更新即時共享範圍。',
  'privacy.local.apply': '套用即時共享',
  'privacy.local.stop': '停止並撤回',
  'privacy.local.applyTitle': '套用已儲存的即時共享設定？',
  'privacy.local.applyBody': '依已儲存的艦隊與房間範圍共享即時狀態。本機將記住目前帳號的確認，重新啟動或斷線後自動恢復，後續儲存會更新共享範圍。隱身時暫停；關閉共享或停止並撤回會取消自動恢復。不會上傳機庫或事件，也不啟用好友在線共享。',
  'privacy.local.live.inactive': '首次共享需要確認一次，之後會自動恢復。僅儲存設定不會啟用共享。',
  'privacy.local.live.identityRequired': '等待遊戲身分核對。已確認過的共享會在身分確認後自動恢復。',
  'privacy.local.live.publishing': '正在套用共享策略…',
  'privacy.local.live.pending': '已有新設定，正在等待伺服器確認。',
  'privacy.local.live.reconnecting': '連線暫時中斷，正在自動恢復共享，無需手動重新整理。',
  'privacy.local.live.applied': '伺服器已確認即時共享策略。',
  'privacy.local.live.withdrawn': '伺服器已確認撤回即時資訊。',
  'privacy.local.live.failed': '未能確認套用結果。請檢查連線與帳號權限後重試。',
  'privacy.local.live.withdrawalPending': '尚未確認撤回。恢復連線後會繼續嘗試撤回，不會恢復共享。',
  'privacy.local.title': '共享與隱私',
  'privacy.local.description': '分別選擇艦隊與房間中可共享的資訊。',
  'privacy.local.localOnlyTitle': '目前僅儲存到本機',
  'privacy.local.localOnlyBody':
      '尚未啟用對外狀態同步。本頁不會改變其他玩家目前看到的資訊，也不會清除舊客戶端已共享的資訊。',
  'privacy.local.publication': '允許共享狀態',
  'privacy.local.publicationHint': '儲存共享意願；關閉後保留下方選擇。目前不會對外發佈或撤回資訊。',
  'privacy.local.fleet': '艦隊',
  'privacy.local.room': '房間',
  'privacy.local.fleetHint': '艦隊的共享範圍，與房間分別設定。',
  'privacy.local.roomHint': '房間成員的共享範圍，不沿用艦隊選擇。',
  'privacy.local.audience': '共享給誰',
  'privacy.local.fields': '共享哪些資訊',
  'privacy.local.allMembers': '所有成員',
  'privacy.local.administrators': '艦隊管理員',
  'privacy.local.groups': '自訂可見群組尚未接入，已保留 {count} 個已有選擇。',
  'privacy.local.presence': '在線狀態',
  'privacy.local.ship': '目前飛船',
  'privacy.local.location': '目前位置',
  'privacy.local.server': '伺服器資訊',
  'privacy.local.hangar': '個人機庫',
  'privacy.local.events': '事件分享',
  'privacy.local.separateSettings': '遊戲 ID 可見性、好友在線狀態及具體事件類別將分別接入，不受本頁設定替代。',
  'privacy.local.save': '儲存到本機',
  'privacy.local.discard': '放棄變更',
  'privacy.local.saved': '已儲存到本機 · 尚未對外生效',
  'privacy.local.defaults': '預設選擇 · 尚未儲存',
  'privacy.local.dirty': '有未儲存的變更',
  'privacy.local.saving': '正在儲存…',
  'privacy.local.loading': '正在讀取隱私設定',
  'privacy.local.retry': '重新檢查',
  'privacy.local.reload': '重新讀取',
  'privacy.local.readFailed': '無法讀取隱私設定。已有設定未被覆蓋，請重試。',
  'privacy.local.saveFailed': '未能確認儲存成功，變更仍保留在本頁。請重試儲存。',
  'privacy.local.conflict': '設定已發生變化，請重新讀取後再編輯。',
  'privacy.local.accountChanged': '請先確認帳號登入狀態，再重新讀取隱私設定。',
  'privacy.local.leaveTitle': '儲存隱私設定？',
  'privacy.local.leaveBody': '目前變更尚未儲存。儲存只記錄到本機，不會啟用對外共享。',
  'privacy.local.stay': '繼續編輯',
};
const englishLocalPrivacyStrings = <String, String>{
  'privacy.local.locationConfidence': 'Share confirmed locations only',
  'privacy.local.locationConfidenceDescription': 'When off, organizations and rooms may also see inferred locations. Friends still see confirmed locations only. Each audience’s location sharing scope stays unchanged.',
  'privacy.first.organizationsPending': 'Organizations: confirm each sharing scope separately. Main fleet is not available yet.',
  'privacy.community.title': 'Organization sharing',
  'privacy.community.body': 'Choose which live information to share with this organization. You can change its scope in Sharing & privacy later. Hangar and event sharing are separate.',
  'privacy.community.none': 'Do not share',
  'privacy.community.confirm': 'Confirm scope',
  'privacy.community.failed': 'Could not save your choice. Please try again.',
  'privacy.first.scope': 'What enabling will share',
  'privacy.first.excluded':
      'This does not authorize hangar, event or friend presence sharing.',
  'privacy.first.adjust': 'Adjust sharing scope',
  'privacy.first.selectedGroups': 'Selected visibility groups ({count})',
  'privacy.first.none': 'Not shared',
  'privacy.first.organizations': 'Fleet',
  'privacy.first.separator': ', ',
  'privacy.first.scopeLine': '{audience}: {scope}',
  'privacy.first.title': 'Enable status sharing',
  'privacy.first.body': 'Share your game status with organization and room members to coordinate activities. Would you like to use this feature?',
  'privacy.first.remember': 'Adjust the scope or turn sharing off anytime in Settings → Sync & Privacy. This device remembers your account’s choice. Sharing resumes after restart or reconnection and pauses while invisible.',
  'privacy.first.decline': 'Not now',
  'privacy.first.accept': 'Enable status sharing',
  'privacy.first.failed':
      'Saving has not been confirmed. Please try again shortly.',
  'privacy.local.liveTitle': 'Live status sharing',
  'privacy.local.liveScope': 'Applies presence, ship, location and server choices. Hangar and event choices are local only. Friend presence and Game ID visibility have separate controls. Actual visibility is decided by the server.',
  'privacy.local.publicationLiveHint': 'After applying, saving updates live sharing. Turning this off and saving withdraws live information.',
  'privacy.local.localChoiceOnly':
      'Saved locally only; sharing is not connected yet',
  'privacy.local.savedLocal': 'Settings saved on this device',
  'privacy.local.leaveLiveBody': 'Save these settings? If sharing was confirmed, saving also updates the live sharing scope.',
  'privacy.local.apply': 'Apply live sharing',
  'privacy.local.stop': 'Stop and withdraw',
  'privacy.local.applyTitle': 'Apply saved live sharing settings?',
  'privacy.local.applyBody': 'Share live status with the saved fleet and room audiences. This device remembers your confirmation for this account and resumes after restarts or connection loss. Later saves update the sharing scope. Invisible pauses sharing; turning sharing off or stopping it cancels automatic recovery. Hangar, events and friend presence are not shared.',
  'privacy.local.live.inactive': 'Confirm sharing once to enable automatic recovery. Saving settings alone does not start sharing.',
  'privacy.local.live.identityRequired': 'Waiting for game identity verification. Previously confirmed sharing resumes automatically once verified.',
  'privacy.local.live.publishing': 'Applying sharing policy…',
  'privacy.local.live.reconnecting': 'Connection interrupted. Sharing will recover automatically; no refresh needed.',
  'privacy.local.live.pending':
      'New settings are waiting for server confirmation.',
  'privacy.local.live.applied': 'Server confirmed the live sharing policy.',
  'privacy.local.live.withdrawn':
      'Server confirmed withdrawal of live information.',
  'privacy.local.live.failed': 'Could not confirm the result. Check your connection and account permissions, then retry.',
  'privacy.local.live.withdrawalPending': 'Withdrawal is not confirmed. Reconnection retries withdrawal without resuming sharing.',
  'privacy.local.title': 'Sharing and privacy',
  'privacy.local.description':
      'Choose shared information separately for your fleet and room.',
  'privacy.local.localOnlyTitle': 'Saved on this device only',
  'privacy.local.localOnlyBody': 'Outgoing status sync is not available yet. These choices do not change what other players currently see or clear information shared by the old client.',
  'privacy.local.publication': 'Allow status sharing',
  'privacy.local.publicationHint': 'Save your sharing preference. Turning this off preserves the choices below. Nothing is published or withdrawn yet.',
  'privacy.local.fleet': 'Fleet',
  'privacy.local.room': 'Room',
  'privacy.local.fleetHint': 'Fleet sharing is separate from room sharing.',
  'privacy.local.roomHint':
      'Choose what room members may see, independently of your fleet.',
  'privacy.local.audience': 'Who to share with',
  'privacy.local.fields': 'What to share',
  'privacy.local.allMembers': 'All members',
  'privacy.local.administrators': 'Fleet administrators',
  'privacy.local.groups': 'Custom visibility groups are not connected yet. {count} existing selections are preserved.',
  'privacy.local.presence': 'Online status',
  'privacy.local.ship': 'Current ship',
  'privacy.local.location': 'Current location',
  'privacy.local.server': 'Server information',
  'privacy.local.hangar': 'Personal hangar',
  'privacy.local.events': 'Shared events',
  'privacy.local.separateSettings': 'Game ID visibility, friend presence and individual event categories will be connected separately. These choices do not replace them.',
  'privacy.local.save': 'Save on this device',
  'privacy.local.discard': 'Discard changes',
  'privacy.local.saved': 'Saved locally · Not applied to sharing',
  'privacy.local.defaults': 'Default choices · Not saved',
  'privacy.local.dirty': 'Unsaved changes',
  'privacy.local.saving': 'Saving…',
  'privacy.local.loading': 'Reading privacy settings',
  'privacy.local.retry': 'Check again',
  'privacy.local.reload': 'Reload settings',
  'privacy.local.readFailed': 'Could not read privacy settings. Existing settings were not overwritten. Try again.',
  'privacy.local.saveFailed': 'Could not confirm the save. Your changes remain on this page. Try saving again.',
  'privacy.local.conflict':
      'Settings have changed. Reload them before editing again.',
  'privacy.local.accountChanged':
      'Check that you are signed in, then reload privacy settings.',
  'privacy.local.leaveTitle': 'Save privacy settings?',
  'privacy.local.leaveBody': 'You have unsaved changes. Saving records them on this device only; it does not enable outgoing sharing.',
  'privacy.local.stay': 'Keep editing',
};
