import 'menu_screenshot_strings.dart';
import 'menu_workspace_strings.dart';

const menuProductZhCn = <String, String>{
  ...menuWorkspaceZhCn,
  ...menuScreenshotZhCn,
  'menu.image.regionZoom': '局部放大',
  'menu.image.cancelRegion': '取消框选',
  'menu.image.applyRegion': '放大选区',
  'menu.image.regionHint': '拖动框选要查看的区域，再点击“放大选区”。按 Esc 取消；不会裁掉图片。',
  'menu.image.crop': '裁剪',
  'menu.image.cancelCrop': '取消裁剪',
  'menu.image.applyCrop': '应用裁剪',
  'menu.image.undo': '撤销',
  'menu.image.reset': '恢复原图',
  'menu.image.cropHint': '拖动框选保留区域，再点击“应用裁剪”。按 Esc 取消；原文件不会改变。',
  'menu.image.editApplied': '图片已调整，原文件未改变。可撤销或恢复原图。',
  'menu.image.editFailed': '调整未完成，当前图片和固定画面仍保留。请重试。',
  'menu.image.restoreEditFailed': '图片已打开，但裁剪恢复失败。当前显示完整原图，可重新裁剪。',
  'menu.image.title': '参考图默认显示',
  'menu.image.hint': '用于新图片；开启调整记忆时，优先恢复本次运行中的调整。不会重置当前图片或影响截图。',
  'menu.image.remember': '记住本次运行中的图片调整',
  'menu.image.rememberHint':
      '重新选择未变更的同一文件时，恢复裁剪、旋转、缩放、不透明度、显示模式和固定状态。保留最近32张图片的调整；关闭后立即忘记，不改变当前图片。',
  'menu.image.pinned': '新图片默认固定到游戏',
  'menu.image.pinnedHint':
      '图片显示完成后固定当前视图，只在Star Citizen前台显示且鼠标可穿透。已有调整优先恢复；也可手动取消固定。',
  'menu.image.restored': '已恢复本次运行中的图片调整。',
  'menu.image.identityUnavailable': '图片已打开，但暂时无法识别为同一文件；重新选择后无法恢复本次调整。',
  'menu.image.openMode': '打开图片时',
  'menu.image.edit': '编辑模式',
  'menu.image.imageOnly': '纯图片模式',
  'menu.image.modeHint': '纯图片模式收起图片工具；随时可点击“显示图片工具”继续调整。窗口标题与关闭按钮仍保留。',
  'menu.image.scaleMode': '初始显示比例',
  'menu.image.fit': '适应窗口',
  'menu.image.actualSize': '实际大小',
  'menu.image.actualHint': '实际大小按载入后的图片像素显示；大图可拖动查看。',
  'menu.image.opacity': '默认不透明度',
  'menu.image.opacityValue': '不透明度',
  'menu.image.editHint': '双击进入纯图片模式',
  'menu.image.privacy': '只在这台电脑保存显示设置，不保存图片、路径或单张图片的调整。',
  'menu.image.failed': '参考图设置未保存。请重新读取后再试；当前调整会保留。',
  'menu.image.dirty': '尚未保存，当前图片不会改变。',
  'menu.image.saved': '已保存，下次选择图片时生效。',
  'menu.image.save': '保存参考图设置',
  'menu.image.busy': '正在处理…',
  'menu.image.reload': '重新读取',
  'menu.image.showTools': '显示图片工具',
  'menu.image.pureHint': '双击显示工具 · 滚轮缩放 · 拖动移动图片',
  'menu.image.hideTools': '收起图片工具',
  'menu.browser.title': '浏览器',
  'menu.browser.hint': '只调整菜单浏览器，不影响默认浏览器或其他应用。',
  'menu.browser.provider': '搜索引擎',
  'menu.browser.bing-cn': '必应中国',
  'menu.browser.baidu': '百度',
  'menu.browser.google': 'Google',
  'menu.browser.duckduckgo': 'DuckDuckGo',
  'menu.browser.bing-global': '必应国际',
  'menu.browser.tabLimit': '同时打开的标签页上限',
  'menu.browser.limitHint': '降低上限不会关闭已有页面；超过上限时，先关闭多余页面才能新建。',
  'menu.browser.links': '在新标签页打开网页的新窗口链接',
  'menu.browser.linksHint': '关闭后，此类链接在当前标签页打开。普通链接仍按网页原有方式打开。',
  'menu.browser.pause': '隐藏时暂停网页',
  'menu.browser.pauseHint': '切换到其他工具或隐藏菜单时，尝试暂停网页以减少占用；返回后继续。网页正在加载时可能无法立即暂停。',
  'menu.browser.privacy': '这些浏览行为设置不保存网址或历史。恢复上次网页需单独开启；网页设备权限和下载仍受限制。',
  'menu.browser.resume.title': '恢复上次网页',
  'menu.browser.resume.privacy': '默认开启。仅在这台电脑加密保存当前账号最后查看的一个网页地址，不保存浏览历史，也不上传。地址可能包含搜索词或访问参数；关闭并保存后会清除记住的网址。',
  'menu.browser.resume.enabled': '打开浏览器时恢复上次网页',
  'menu.browser.resume.hint': '仅用于空白浏览器，不替换已打开的页面。关闭后清除已保存的地址；不会自动打开浏览器。',
  'menu.browser.resume.busy': '正在读取或保存设置…',
  'menu.browser.resume.failed': '未能读取或确认保存结果。请重新读取设置；已有网页不受影响。',
  'menu.browser.resume.unavailable': '暂时无法读取此账号的设置。',
  'menu.browser.resume.on': '已开启，仅在本机保存当前账号的上次网页。',
  'menu.browser.resume.off': '已关闭，没有保存的网页地址。',
  'menu.browser.resume.reload': '重新读取设置',
  'menu.browser.resume.runtimeFailed': '暂时无法读取或保存上次网页。你仍可正常浏览；请在菜单设置中重新读取该选项。',
  'menu.browser.failed': '浏览器设置未保存。请重新读取后再试；当前调整会保留。',
  'menu.browser.dirty': '尚未保存。保存后，下次打开菜单时使用这些设置。',
  'menu.browser.saved': '已保存，下次打开菜单时生效。',
  'menu.browser.save': '保存浏览器设置',
  'menu.browser.busy': '正在处理…',
  'menu.browser.reload': '重新读取',
  'menu.browser.applyFailed': '浏览器设置暂未应用，请重试；已有页面会保留。',
  'menu.restore.title': '窗口恢复',
  'menu.restore.safeNext': '下次启动应用时使用基础菜单',
  'menu.restore.safeHint':
      '仅下次运行：暂停自动恢复窗口，减少菜单动效。原设置与布局保留；需要的工具可手动打开。保存后重启应用生效。',
  'menu.startup.safe': '本次使用基础菜单：自动恢复已暂停，动效已减少，原设置与布局保留。可手动打开需要的工具。',
  'menu.startup.unverified': '启动设置未确认，暂不自动恢复窗口。原布局保留；可手动打开工具，稍后重启应用重试。',
  'menu.restore.session': '重开菜单时恢复窗口',
  'menu.restore.sessionHint': '本次运行中，保留未关闭的窗口、位置、大小和前后顺序。',
  'menu.restore.restart': '重启应用后恢复窗口',
  'menu.restore.restartHint': '下次启动应用后首次打开菜单时，恢复上次的窗口布局；异常结束后按下方选择处理。',
  'menu.restore.focus': '恢复上次使用的窗口焦点',
  'menu.restore.focusHint': '恢复窗口后，将键盘焦点交给上次使用的窗口。关闭后按常规工具顺序选择。',
  'menu.restore.crash': '异常结束后',
  'menu.restore.ask': '先询问我',
  'menu.restore.restore': '直接恢复窗口',
  'menu.restore.startClean': '仅打开菜单',
  'menu.restore.crashHint': '仅在已开启窗口恢复且有保存窗口时生效。状态无法确认或保存失败时仍先询问，原布局会保留。',
  'menu.restore.privacy': '只保存窗口布局，不保存聊天正文、草稿、截图或参考图。重启后浏览器为空白页。',
  'menu.restore.failed': '恢复设置未保存。请重新读取后再试；当前调整会保留。',
  'menu.restore.dirty': '尚未保存。保存后，基础菜单选项需重启应用，其余设置在下次打开菜单时生效。',
  'menu.restore.saved': '已保存。基础菜单选项需重启应用，其余设置在下次打开菜单时生效。',
  'menu.restore.save': '保存恢复设置',
  'menu.restore.busy': '正在处理…',
  'menu.restore.reload': '重新读取',
  'menu.display.title': '菜单显示与交互',
  'menu.display.appearance': '外观与操作提示',
  'menu.social.title': '好友与提醒',
  'menu.social.notifications': '显示菜单社交提醒',
  'menu.social.sound': '菜单打开时播放社交提示音',
  'menu.social.showAvatars': '显示好友与私聊头像',
  'menu.social.avatarHint':
      '仅影响菜单好友与私聊。关闭后显示名称占位，不改变客户端或个人页面的头像，也不阻止客户端接收头像数据。',
  'menu.social.soundHint': '复用通知音量和提示音。全局声音关闭、来源静音或系统勿扰时仍保持安静；保存后生效。',
  'menu.social.preview': '提醒内容',
  'menu.social.fullContent': '显示发送者与内容',
  'menu.social.sourceOnly': '仅显示发送者',
  'menu.social.hiddenDetails': '隐藏详细内容',
  'menu.social.privacyHint': '仅控制菜单内的好友与私聊提示，不影响收消息或未读计数。全局通知关闭或隐藏内容时，以全局设置为准。',
  'menu.social.hint': '好友排序仅影响菜单列表，在线与离线好友仍分组显示。',
  'menu.social.friendSort': '组内排序',
  'menu.social.onlineFirst': '优先显示游戏中的好友',
  'menu.social.alphabetical': '按名称排序',
  'menu.social.save': '保存好友与提醒设置',
  'menu.social.saved': '已保存，下次打开菜单时生效。',
  'menu.social.dirty': '有尚未保存的调整。',
  'menu.social.failed': '未能保存或读取设置。请重新读取后再试，当前调整会保留。',
  'menu.social.busy': '正在处理…',
  'menu.social.reload': '重新读取',
  'menu.display.privacy': '菜单隐私',
  'menu.display.streamerPrivacy': '隐藏菜单位置和房间码',
  'menu.display.privacyHint':
      '隐藏菜单状态栏的位置和房间内的房间码及复制按钮。不会隐藏聊天、成员资料或信息浮层，也不会改变共享权限。关闭后恢复各项显示设置。',
  'menu.display.showRoomCode': '显示房间码',
  'menu.display.hint': '调整菜单外观，不改变你的在线状态或共享设置。',
  'menu.display.time': '本机时间',
  'menu.display.textScale': '菜单文字大小',
  'menu.display.reduceMotion': '减少动态效果',
  'menu.display.highContrast': '增强菜单边界',
  'menu.display.tooltipDelay': '按钮提示延迟',
  'menu.display.tooltipDelayHint': '鼠标停在按钮上多久后显示说明。',
  'menu.display.highContrastHint': '让边框和选中位置更清晰，不改变网页和图片颜色。',
  'menu.display.reduceMotionHint': '减少菜单动画，不影响消息接收或网页动画。系统已开启此选项时，菜单也会减少动画。',
  'menu.display.interfaceScale': '菜单栏大小',
  'menu.display.interfaceScaleHint': '缩放时钟和上下工具栏，窗口大小与位置不变。',
  'menu.display.textScaleHint': '调整菜单文字，不影响网页和信息浮层。',
  'menu.display.showClock': '显示时间',
  'menu.display.showDate': '显示日期',
  'menu.display.clockFormat': '时间格式',
  'menu.display.system': '跟随系统',
  'menu.display.twentyFourHour': '24 小时制',
  'menu.display.twelveHour': '12 小时制',
  'menu.display.showPresence': '显示我的在线状态',
  'menu.display.context': '协作与游戏状态',
  'menu.display.showContext': '显示状态栏',
  'menu.display.showScene': '显示当前协作',
  'menu.display.showMembers': '显示成员人数',
  'menu.display.showShip': '显示当前飞船',
  'menu.display.showLocation': '显示所在位置',
  'menu.display.showServer': '显示服务器',
  'menu.display.sceneLabel': '当前协作',
  'menu.display.membersLabel': '成员',
  'menu.display.shipLabel': '当前飞船',
  'menu.display.locationLabel': '所在位置',
  'menu.display.serverLabel': '服务器',
  'menu.display.noScene': '暂无协作场景',
  'menu.display.failed': '显示设置未保存。请重新读取后再试；当前调整会保留。',
  'menu.display.dirty': '尚未保存，下次打开菜单时使用保存后的设置。',
  'menu.display.saved': '已保存，下次打开菜单时生效。',
  'menu.display.save': '保存显示设置',
  'menu.display.busy': '正在处理…',
  'menu.display.reload': '重新读取',
  'menu.tools.hud': '信息浮层',
  'menu.tools.organizations': '组织',
  'menu.tools.friends': '好友',
  'menu.tools.comms': '通讯',
  'menu.tools.rooms': '房间',
  'menu.tools.screenshot': '全屏截屏',
  'menu.tools.image': '参考图',
  'menu.tools.browser': '浏览器',
  'menu.toolbar.title': '工具栏',
  'menu.toolbar.showUnreadBadges': '显示未读和请求提醒',
  'menu.toolbar.attention': '{count} 项未读或待处理',
  'menu.toolbar.hint': '拖动右侧手柄调整顺序，也可点击向上箭头。隐藏工具不会关闭已经打开的窗口。',
  'menu.toolbar.density': '工具栏密度',
  'menu.toolbar.compact': '紧凑',
  'menu.toolbar.standard': '标准',
  'menu.toolbar.comfortable': '宽松',
  'menu.toolbar.labels': '工具标签',
  'menu.toolbar.auto': '图标与名称',
  'menu.toolbar.iconsOnly': '仅图标',
  'menu.toolbar.alwaysVisible': '始终显示',
  'menu.toolbar.earlier': '向前移动',
  'menu.toolbar.move': '拖动排序',
  'menu.toolbar.reset': '恢复默认工具栏',
  'menu.toolbar.failed': '设置未保存。请重新读取后再试；当前调整会保留。',
  'menu.toolbar.dirty': '尚未保存，下次打开菜单时使用保存后的设置。',
  'menu.toolbar.saved': '已保存，下次打开菜单时生效。',
  'menu.toolbar.save': '保存工具栏',
  'menu.toolbar.busy': '正在处理…',
  'menu.toolbar.reload': '重新读取',
  'menu.shortcut.title': '菜单快捷键',
  'menu.shortcut.hint': '只在游戏位于前台时打开菜单。设置保存在这台电脑上，不改变信息浮层快捷键。',
  'menu.shortcut.enabled': '启用菜单快捷键',
  'menu.shortcut.close': '再次按快捷键关闭菜单',
  'menu.shortcut.dirty': '尚未保存；当前仍使用上次生效的设置。',
  'menu.shortcut.ready': '已保存并启用。',
  'menu.shortcut.disabled': '快捷键已关闭，仍可通过按钮打开菜单。',
  'menu.shortcut.conflict': '与信息浮层快捷键相同，请更换组合后保存。',
  'menu.shortcut.invalid': '此组合不可用。请选择修饰键加字母/数字，或 F1–F12；不要使用系统保留组合。',
  'menu.shortcut.unavailable': '未能确认快捷键状态。请确认已登录并连接本机服务，再重新读取。',
  'menu.shortcut.changed': '另一处设置已更新。请重新读取后再保存；当前输入会保留。',
  'menu.shortcut.save': '保存快捷键',
  'menu.shortcut.busy': '正在处理…',
  'menu.shortcut.reload': '重新读取',
  'menu.product.description': '在游戏中查看消息、与队友协作，也可使用浏览器、参考图和截图工具。',
  'menu.product.open': '打开菜单浮层',
  'menu.product.closeHint': '拖动标题移动窗口，拖动右下角调整大小。按 Esc 或点击返回按钮关闭菜单。',
  'menu.product.unavailable': '菜单浮层暂不可用。请确认已登录并连接本机服务后重试。',
  'menu.product.social.title': '消息与协作',
  'menu.product.social.body': '在同一个工作区打开好友、通讯、组织和房间，查看资料与聊天。',
  'menu.product.images.title': '参考图与截图',
  'menu.product.images.body': '调整参考图并固定到游戏；截取屏幕、裁剪和旋转，再复制或保存。',
  'menu.product.browser.title': '浏览器',
  'menu.product.browser.body': '输入网址或搜索内容，通过多个标签页对照资料。',
  'menu.product.settings.title': '窗口与显示设置',
  'menu.product.settings.body': '打开菜单后，点击右上角“设置”，可调整背景压暗、时钟、状态栏、窗口吸附和布局恢复。',
  'menu.product.privacy':
      '阅读可见消息会标记已读。截图与参考图不会自动上传；关闭菜单保留内存中的图片，退出应用或账号会话结束后清除。',
};

const menuProductZhTw = <String, String>{
  ...menuWorkspaceZhTw,
  ...menuScreenshotZhTw,
  'menu.image.regionZoom': '局部放大',
  'menu.image.cancelRegion': '取消框選',
  'menu.image.applyRegion': '放大選區',
  'menu.image.regionHint': '拖曳框選要查看的區域，再點擊「放大選區」。按 Esc 取消；不會裁掉圖片。',
  'menu.image.crop': '裁剪',
  'menu.image.cancelCrop': '取消裁剪',
  'menu.image.applyCrop': '套用裁剪',
  'menu.image.undo': '復原',
  'menu.image.reset': '恢復原圖',
  'menu.image.cropHint': '拖曳框選保留區域，再點擊「套用裁剪」。按 Esc 取消；原檔案不會改變。',
  'menu.image.editApplied': '圖片已調整，原檔案未改變。可復原或恢復原圖。',
  'menu.image.editFailed': '調整未完成，目前圖片和固定畫面仍保留。請重試。',
  'menu.image.restoreEditFailed': '圖片已開啟，但裁剪恢復失敗。目前顯示完整原圖，可重新裁剪。',
  'menu.image.title': '參考圖預設顯示',
  'menu.image.hint': '用於新圖片；開啟調整記憶時，優先恢復本次執行中的調整。不會重設目前圖片或影響截圖。',
  'menu.image.remember': '記住本次執行中的圖片調整',
  'menu.image.rememberHint':
      '重新選擇未變更的同一檔案時，恢復裁剪、旋轉、縮放、不透明度、顯示模式和固定狀態。保留最近32張圖片的調整；關閉後立即忘記，不改變目前圖片。',
  'menu.image.pinned': '新圖片預設固定到遊戲',
  'menu.image.pinnedHint':
      '圖片顯示完成後固定目前視圖，只在Star Citizen前景顯示且滑鼠可穿透。已有調整優先恢復；也可手動取消固定。',
  'menu.image.restored': '已恢復本次執行中的圖片調整。',
  'menu.image.identityUnavailable': '圖片已開啟，但暫時無法識別為同一檔案；重新選擇後無法恢復本次調整。',
  'menu.image.openMode': '開啟圖片時',
  'menu.image.edit': '編輯模式',
  'menu.image.imageOnly': '純圖片模式',
  'menu.image.modeHint': '純圖片模式收起圖片工具；隨時可點擊「顯示圖片工具」繼續調整。視窗標題與關閉按鈕仍保留。',
  'menu.image.scaleMode': '初始顯示比例',
  'menu.image.fit': '適應視窗',
  'menu.image.actualSize': '實際大小',
  'menu.image.actualHint': '實際大小按載入後的圖片像素顯示；大圖可拖曳查看。',
  'menu.image.opacity': '預設不透明度',
  'menu.image.opacityValue': '不透明度',
  'menu.image.editHint': '按兩下進入純圖片模式',
  'menu.image.privacy': '只在這台電腦儲存顯示設定，不儲存圖片、路徑或單張圖片的調整。',
  'menu.image.failed': '參考圖設定未儲存。請重新讀取後再試；目前調整會保留。',
  'menu.image.dirty': '尚未儲存，目前圖片不會改變。',
  'menu.image.saved': '已儲存，下次選擇圖片時生效。',
  'menu.image.save': '儲存參考圖設定',
  'menu.image.busy': '正在處理…',
  'menu.image.reload': '重新讀取',
  'menu.image.showTools': '顯示圖片工具',
  'menu.image.pureHint': '按兩下顯示工具 · 滾輪縮放 · 拖動移動圖片',
  'menu.image.hideTools': '收起圖片工具',
  'menu.browser.title': '瀏覽器',
  'menu.browser.hint': '只調整選單瀏覽器，不影響預設瀏覽器或其他應用程式。',
  'menu.browser.provider': '搜尋引擎',
  'menu.browser.bing-cn': 'Bing 中國',
  'menu.browser.baidu': '百度',
  'menu.browser.google': 'Google',
  'menu.browser.duckduckgo': 'DuckDuckGo',
  'menu.browser.bing-global': 'Bing 國際',
  'menu.browser.tabLimit': '同時開啟的分頁上限',
  'menu.browser.limitHint': '降低上限不會關閉現有頁面；超過上限時，先關閉多餘頁面才能新增。',
  'menu.browser.links': '在新分頁開啟網頁的新視窗連結',
  'menu.browser.linksHint': '關閉後，這類連結在目前分頁開啟。一般連結仍依網頁原有方式開啟。',
  'menu.browser.pause': '隱藏時暫停網頁',
  'menu.browser.pauseHint': '切換至其他工具或隱藏選單時，嘗試暫停網頁以減少資源使用；返回後繼續。網頁載入中可能無法立即暫停。',
  'menu.browser.privacy': '這些瀏覽行為設定不儲存網址或歷史。還原上次網頁需單獨開啟；網頁裝置權限和下載仍受限制。',
  'menu.browser.resume.title': '還原上次網頁',
  'menu.browser.resume.privacy': '預設開啟。僅在這台電腦加密儲存目前帳號最後查看的一個網頁網址，不儲存瀏覽歷史，也不上傳。網址可能包含搜尋詞或存取參數；關閉並儲存後會清除記住的網址。',
  'menu.browser.resume.enabled': '開啟瀏覽器時還原上次網頁',
  'menu.browser.resume.hint': '僅用於空白瀏覽器，不取代已開啟的頁面。關閉後清除已儲存的網址；不會自動開啟瀏覽器。',
  'menu.browser.resume.busy': '正在讀取或儲存設定…',
  'menu.browser.resume.failed': '未能讀取或確認儲存結果。請重新讀取設定；已有網頁不受影響。',
  'menu.browser.resume.unavailable': '暫時無法讀取此帳號的設定。',
  'menu.browser.resume.on': '已開啟，僅在本機儲存目前帳號的上次網頁。',
  'menu.browser.resume.off': '已關閉，沒有儲存的網頁網址。',
  'menu.browser.resume.reload': '重新讀取設定',
  'menu.browser.resume.runtimeFailed': '暫時無法讀取或儲存上次網頁。你仍可正常瀏覽；請在選單設定中重新讀取該選項。',
  'menu.browser.failed': '瀏覽器設定未儲存。請重新讀取後再試；目前調整會保留。',
  'menu.browser.dirty': '尚未儲存。儲存後，下次開啟選單時使用這些設定。',
  'menu.browser.saved': '已儲存，下次開啟選單時生效。',
  'menu.browser.save': '儲存瀏覽器設定',
  'menu.browser.busy': '正在處理…',
  'menu.browser.reload': '重新讀取',
  'menu.browser.applyFailed': '瀏覽器設定尚未套用，請重試；現有頁面會保留。',
  'menu.restore.title': '視窗恢復',
  'menu.restore.safeNext': '下次啟動應用程式時使用基本選單',
  'menu.restore.safeHint':
      '僅下次執行：暫停自動恢復視窗，減少選單動效。原設定與配置保留；需要的工具可手動開啟。儲存後重新啟動應用程式生效。',
  'menu.startup.safe': '本次使用基本選單：自動恢復已暫停，動效已減少，原設定與配置保留。可手動開啟需要的工具。',
  'menu.startup.unverified': '啟動設定未確認，暫不自動恢復視窗。原配置保留；可手動開啟工具，稍後重新啟動應用程式重試。',
  'menu.restore.session': '重開選單時恢復視窗',
  'menu.restore.sessionHint': '本次執行中，保留未關閉的視窗、位置、大小及前後順序。',
  'menu.restore.restart': '重新啟動應用程式後恢復視窗',
  'menu.restore.restartHint': '下次啟動應用程式後首次開啟選單時，恢復上次的視窗配置；異常結束後依下方選擇處理。',
  'menu.restore.focus': '恢復上次使用的視窗焦點',
  'menu.restore.focusHint': '恢復視窗後，將鍵盤焦點交給上次使用的視窗。關閉後依一般工具順序選擇。',
  'menu.restore.crash': '異常結束後',
  'menu.restore.ask': '先詢問我',
  'menu.restore.restore': '直接恢復視窗',
  'menu.restore.startClean': '僅開啟選單',
  'menu.restore.crashHint': '僅在已開啟視窗恢復且有儲存視窗時生效。狀態無法確認或儲存失敗時仍先詢問，原配置會保留。',
  'menu.restore.privacy': '只儲存視窗配置，不儲存聊天內容、草稿、截圖或參考圖。重新啟動後瀏覽器為空白頁。',
  'menu.restore.failed': '恢復設定未儲存。請重新讀取後再試；目前調整會保留。',
  'menu.restore.dirty': '尚未儲存。儲存後，基本選單選項需重新啟動應用程式，其餘設定在下次開啟選單時生效。',
  'menu.restore.saved': '已儲存。基本選單選項需重新啟動應用程式，其餘設定在下次開啟選單時生效。',
  'menu.restore.save': '儲存恢復設定',
  'menu.restore.busy': '正在處理…',
  'menu.restore.reload': '重新讀取',
  'menu.display.title': '選單顯示與互動',
  'menu.display.appearance': '外觀與操作提示',
  'menu.social.title': '好友與提醒',
  'menu.social.notifications': '顯示選單社交提醒',
  'menu.social.sound': '選單開啟時播放社交提示音',
  'menu.social.showAvatars': '顯示好友與私訊頭像',
  'menu.social.avatarHint':
      '僅影響選單好友與私訊。關閉後顯示名稱佔位，不改變客戶端或個人頁面的頭像，也不阻止客戶端接收頭像資料。',
  'menu.social.soundHint': '沿用通知音量與提示音。全域聲音關閉、來源靜音或系統勿擾時仍保持安靜；儲存後生效。',
  'menu.social.preview': '提醒內容',
  'menu.social.fullContent': '顯示傳送者與內容',
  'menu.social.sourceOnly': '僅顯示傳送者',
  'menu.social.hiddenDetails': '隱藏詳細內容',
  'menu.social.privacyHint': '僅控制選單內的好友與私訊提示，不影響收訊息或未讀計數。全域通知關閉或隱藏內容時，以全域設定為準。',
  'menu.social.hint': '好友排序僅影響選單清單，線上與離線好友仍分組顯示。',
  'menu.social.friendSort': '組內排序',
  'menu.social.onlineFirst': '優先顯示遊戲中的好友',
  'menu.social.alphabetical': '依名稱排序',
  'menu.social.save': '儲存好友與提醒設定',
  'menu.social.saved': '已儲存，下次開啟選單時生效。',
  'menu.social.dirty': '有尚未儲存的調整。',
  'menu.social.failed': '未能儲存或讀取設定。請重新讀取後再試，目前調整會保留。',
  'menu.social.busy': '正在處理…',
  'menu.social.reload': '重新讀取',
  'menu.display.privacy': '選單隱私',
  'menu.display.streamerPrivacy': '隱藏選單位置和房間碼',
  'menu.display.privacyHint':
      '隱藏選單狀態列的位置和房間內的房間碼及複製按鈕。不會隱藏聊天、成員資料或資訊浮層，也不會改變分享權限。關閉後恢復各項顯示設定。',
  'menu.display.showRoomCode': '顯示房間碼',
  'menu.display.hint': '調整選單外觀，不改變你的上線狀態或分享設定。',
  'menu.display.time': '本機時間',
  'menu.display.textScale': '選單文字大小',
  'menu.display.reduceMotion': '減少動態效果',
  'menu.display.highContrast': '增強選單邊界',
  'menu.display.tooltipDelay': '按鈕提示延遲',
  'menu.display.tooltipDelayHint': '滑鼠停在按鈕上多久後顯示說明。',
  'menu.display.highContrastHint': '讓邊框和選取位置更清晰，不改變網頁和圖片色彩。',
  'menu.display.reduceMotionHint': '減少選單動畫，不影響訊息接收或網頁動畫。系統已開啟此選項時，選單也會減少動畫。',
  'menu.display.interfaceScale': '選單列大小',
  'menu.display.interfaceScaleHint': '縮放時鐘和上下工具列，視窗大小與位置不變。',
  'menu.display.textScaleHint': '調整選單文字，不影響網頁和資訊浮層。',
  'menu.display.showClock': '顯示時間',
  'menu.display.showDate': '顯示日期',
  'menu.display.clockFormat': '時間格式',
  'menu.display.system': '跟隨系統',
  'menu.display.twentyFourHour': '24 小時制',
  'menu.display.twelveHour': '12 小時制',
  'menu.display.showPresence': '顯示我的線上狀態',
  'menu.display.context': '協作與遊戲狀態',
  'menu.display.showContext': '顯示狀態列',
  'menu.display.showScene': '顯示目前協作',
  'menu.display.showMembers': '顯示成員人數',
  'menu.display.showShip': '顯示目前飛船',
  'menu.display.showLocation': '顯示所在位置',
  'menu.display.showServer': '顯示伺服器',
  'menu.display.sceneLabel': '目前協作',
  'menu.display.membersLabel': '成員',
  'menu.display.shipLabel': '目前飛船',
  'menu.display.locationLabel': '所在位置',
  'menu.display.serverLabel': '伺服器',
  'menu.display.noScene': '暫無協作場景',
  'menu.display.failed': '顯示設定未儲存。請重新讀取後再試；目前調整會保留。',
  'menu.display.dirty': '尚未儲存，下次開啟選單時使用儲存後的設定。',
  'menu.display.saved': '已儲存，下次開啟選單時生效。',
  'menu.display.save': '儲存顯示設定',
  'menu.display.busy': '正在處理…',
  'menu.display.reload': '重新讀取',
  'menu.tools.hud': '資訊浮層',
  'menu.tools.organizations': '組織',
  'menu.tools.friends': '好友',
  'menu.tools.comms': '通訊',
  'menu.tools.rooms': '房間',
  'menu.tools.screenshot': '全螢幕截圖',
  'menu.tools.image': '參考圖',
  'menu.tools.browser': '瀏覽器',
  'menu.toolbar.title': '工具列',
  'menu.toolbar.showUnreadBadges': '顯示未讀和請求提醒',
  'menu.toolbar.attention': '{count} 項未讀或待處理',
  'menu.toolbar.hint': '拖曳右側把手調整順序，也可點擊向上箭頭。隱藏工具不會關閉已開啟的視窗。',
  'menu.toolbar.density': '工具列密度',
  'menu.toolbar.compact': '緊湊',
  'menu.toolbar.standard': '標準',
  'menu.toolbar.comfortable': '寬鬆',
  'menu.toolbar.labels': '工具標籤',
  'menu.toolbar.auto': '圖示與名稱',
  'menu.toolbar.iconsOnly': '僅圖示',
  'menu.toolbar.alwaysVisible': '始終顯示',
  'menu.toolbar.earlier': '向前移動',
  'menu.toolbar.move': '拖曳排序',
  'menu.toolbar.reset': '恢復預設工具列',
  'menu.toolbar.failed': '設定未儲存。請重新讀取後再試；目前調整會保留。',
  'menu.toolbar.dirty': '尚未儲存，下次開啟選單時使用儲存後的設定。',
  'menu.toolbar.saved': '已儲存，下次開啟選單時生效。',
  'menu.toolbar.save': '儲存工具列',
  'menu.toolbar.busy': '正在處理…',
  'menu.toolbar.reload': '重新讀取',
  'menu.shortcut.title': '選單快捷鍵',
  'menu.shortcut.hint': '僅在遊戲位於前景時開啟選單。設定儲存在這台電腦，不改變資訊浮層快捷鍵。',
  'menu.shortcut.enabled': '啟用選單快捷鍵',
  'menu.shortcut.close': '再次按快捷鍵關閉選單',
  'menu.shortcut.dirty': '尚未儲存；目前仍使用上次生效的設定。',
  'menu.shortcut.ready': '已儲存並啟用。',
  'menu.shortcut.disabled': '快捷鍵已關閉，仍可透過按鈕開啟選單。',
  'menu.shortcut.conflict': '與資訊浮層快捷鍵相同，請更換組合後儲存。',
  'menu.shortcut.invalid': '此組合不可用。請選擇修飾鍵加字母/數字，或 F1–F12；不要使用系統保留組合。',
  'menu.shortcut.unavailable': '未能確認快捷鍵狀態。請確認已登入並連接本機服務，再重新讀取。',
  'menu.shortcut.changed': '另一處設定已更新。請重新讀取後再儲存；目前輸入會保留。',
  'menu.shortcut.save': '儲存快捷鍵',
  'menu.shortcut.busy': '正在處理…',
  'menu.shortcut.reload': '重新讀取',
  'menu.product.description': '在遊戲中查看訊息、與隊友協作，也可使用瀏覽器、參考圖和截圖工具。',
  'menu.product.open': '開啟選單浮層',
  'menu.product.closeHint': '拖曳標題移動視窗，拖曳右下角調整大小。按 Esc 或點擊返回按鈕關閉選單。',
  'menu.product.unavailable': '選單浮層暫不可用。請確認已登入並連接本機服務後重試。',
  'menu.product.social.title': '訊息與協作',
  'menu.product.social.body': '在同一個工作區開啟好友、通訊、組織和房間，查看資料與聊天。',
  'menu.product.images.title': '參考圖與截圖',
  'menu.product.images.body': '調整參考圖並固定到遊戲；擷取螢幕、裁剪和旋轉，再複製或儲存。',
  'menu.product.browser.title': '瀏覽器',
  'menu.product.browser.body': '輸入網址或搜尋內容，透過多個分頁對照資料。',
  'menu.product.settings.title': '視窗與顯示設定',
  'menu.product.settings.body': '開啟選單後，點擊右上角「設定」，可調整背景調暗、時鐘、狀態列、視窗吸附和版面配置恢復。',
  'menu.product.privacy':
      '閱讀可見訊息會標記已讀。截圖與參考圖不會自動上傳；關閉選單保留記憶體中的圖片，退出應用程式或帳號工作階段結束後清除。',
};

const menuProductEn = <String, String>{
  ...menuWorkspaceEn,
  ...menuScreenshotEn,
  'menu.image.regionZoom': 'Zoom to region',
  'menu.image.cancelRegion': 'Cancel selection',
  'menu.image.applyRegion': 'Zoom to selection',
  'menu.image.regionHint': 'Drag to select the area to view, then choose Zoom to selection. Press Esc to cancel. No part of the image is removed.',
  'menu.image.crop': 'Crop',
  'menu.image.cancelCrop': 'Cancel crop',
  'menu.image.applyCrop': 'Apply crop',
  'menu.image.undo': 'Undo',
  'menu.image.reset': 'Restore original',
  'menu.image.cropHint': 'Drag to select the area to keep, then choose Apply crop. Press Esc to cancel. The original file is unchanged.',
  'menu.image.editApplied': 'Image adjusted. The original file is unchanged. You can undo or restore the original.',
  'menu.image.editFailed': 'Adjustment failed. The current image and pinned view are unchanged. Try again.',
  'menu.image.restoreEditFailed': 'Image opened, but its crop could not be restored. The full original is shown; you can crop it again.',
  'menu.image.title': 'Reference image defaults',
  'menu.image.hint': 'Defaults for new images. Remembered adjustments from this run take priority. Your current image and screenshots are unchanged.',
  'menu.image.remember': 'Remember image adjustments for this run',
  'menu.image.rememberHint': 'Reselect an unchanged file to restore crop, rotation, zoom, opacity, display mode and pin state. Keeps the last 32 images’ adjustments. Turning this off forgets them immediately without changing the current image.',
  'menu.image.pinned': 'Pin new images to the game by default',
  'menu.image.pinnedHint': 'Pins the current view after the image is ready. Visible only while Star Citizen is in the foreground, with click-through input. Remembered adjustments take priority; you can also unpin manually.',
  'menu.image.restored': 'Image adjustments from this run restored.',
  'menu.image.identityUnavailable': 'Image opened, but this file cannot be identified reliably. Its adjustments cannot be restored when you select it again.',
  'menu.image.openMode': 'When opening an image',
  'menu.image.edit': 'Editing mode',
  'menu.image.imageOnly': 'Image-only mode',
  'menu.image.modeHint': 'Image-only mode hides the image tools. Use “Show image tools” to adjust the image again. The window title and close button remain available.',
  'menu.image.scaleMode': 'Initial scale',
  'menu.image.fit': 'Fit to window',
  'menu.image.actualSize': 'Actual size',
  'menu.image.actualHint': 'Actual size shows loaded image pixels at screen pixel size. Drag to explore larger images.',
  'menu.image.opacity': 'Default opacity',
  'menu.image.privacy': 'Only display settings are saved on this computer, not images, file paths or individual image adjustments.',
  'menu.image.failed': 'Reference image settings were not saved. Reload and try again; your changes are kept.',
  'menu.image.dirty': 'Unsaved changes. Your current image is unchanged.',
  'menu.image.saved': 'Saved. Applied to the next image you select.',
  'menu.image.save': 'Save reference image settings',
  'menu.image.busy': 'Working…',
  'menu.image.reload': 'Reload',
  'menu.image.showTools': 'Show image tools',
  'menu.image.opacityValue': 'Opacity',
  'menu.image.editHint': 'Double-click to enter image-only mode',
  'menu.image.pureHint':
      'Double-click for tools · Scroll to zoom · Drag to move image',
  'menu.image.hideTools': 'Hide image tools',
  'menu.browser.title': 'Browser',
  'menu.browser.hint': 'Applies only to the menu browser, not your default browser or other apps.',
  'menu.browser.provider': 'Search engine',
  'menu.browser.bing-cn': 'Bing China',
  'menu.browser.baidu': 'Baidu',
  'menu.browser.google': 'Google',
  'menu.browser.duckduckgo': 'DuckDuckGo',
  'menu.browser.bing-global': 'Bing Global',
  'menu.browser.tabLimit': 'Maximum open tabs',
  'menu.browser.limitHint': 'Lowering the limit keeps existing pages. Close extra tabs before opening more.',
  'menu.browser.links': 'Open new-window links in a new tab',
  'menu.browser.linksHint': 'When off, these links open in the current tab. Ordinary links follow the page’s own behavior.',
  'menu.browser.pause': 'Pause pages when hidden',
  'menu.browser.pauseHint': 'Try to pause pages when switching tools or hiding the menu; resume on return. Loading pages may not pause immediately.',
  'menu.browser.privacy': 'These browsing settings save no URLs or history. Restoring the last page is a separate opt-in. Website device permissions and downloads remain restricted.',
  'menu.browser.resume.title': 'Restore the last page',
  'menu.browser.resume.privacy': 'On by default. The last viewed page URL is encrypted on this computer for the current account. No browsing history is saved or uploaded. The URL may contain search terms or access parameters. Turning this off and saving clears the remembered URL.',
  'menu.browser.resume.enabled':
      'Restore the last page when opening the browser',
  'menu.browser.resume.hint': 'Only applies to a blank browser, never replaces an open page. Turning this off clears the saved URL. The browser will not open automatically.',
  'menu.browser.resume.busy': 'Reading or saving settings…',
  'menu.browser.resume.failed': 'Could not read settings or confirm the save. Reload settings; open pages are unaffected.',
  'menu.browser.resume.unavailable':
      'Settings for this account are temporarily unavailable.',
  'menu.browser.resume.on':
      'Enabled. The last page is saved locally for the current account only.',
  'menu.browser.resume.off': 'Disabled. No page URL is saved.',
  'menu.browser.resume.reload': 'Reload settings',
  'menu.browser.resume.runtimeFailed': 'The last page could not be read or saved. You can still browse. Reload this option in menu settings.',
  'menu.browser.failed': 'Browser settings were not saved. Reload and try again; your changes are kept.',
  'menu.browser.dirty':
      'Not saved. After saving, these settings apply next time the menu opens.',
  'menu.browser.saved': 'Saved. Applies next time the menu opens.',
  'menu.browser.save': 'Save browser settings',
  'menu.browser.busy': 'Working…',
  'menu.browser.reload': 'Reload',
  'menu.browser.applyFailed':
      'Browser settings have not been applied. Retry; existing pages are kept.',
  'menu.restore.title': 'Window restoration',
  'menu.restore.safeNext': 'Use a basic menu on the next app start',
  'menu.restore.safeHint': 'Next session only: pause automatic window restoration and reduce menu effects. Keep your settings and layout. Open tools manually as needed. Save, then restart the app.',
  'menu.startup.safe': 'Basic menu this session: automatic restoration is paused and effects are reduced. Your settings and layout are kept. Open tools manually as needed.',
  'menu.startup.unverified': 'Startup settings could not be confirmed. Automatic restoration is paused and your layout is kept. Open tools manually, or restart the app later to retry.',
  'menu.restore.session': 'Restore windows when reopening the menu',
  'menu.restore.sessionHint': 'Keep unclosed windows, positions, sizes and stacking order during this app session.',
  'menu.restore.restart': 'Restore windows after restarting the app',
  'menu.restore.restartHint': 'Restore the previous layout when you first open the menu after restarting. Interrupted sessions use the choice below.',
  'menu.restore.focus': 'Restore the last window focus',
  'menu.restore.focusHint': 'Give keyboard focus to the last used window when restoring. When off, use the normal tool order.',
  'menu.restore.crash': 'After an interruption',
  'menu.restore.ask': 'Ask me',
  'menu.restore.restore': 'Restore windows',
  'menu.restore.startClean': 'Menu only',
  'menu.restore.crashHint': 'Applies only when restoration is enabled and windows are saved. If the session cannot be checked or saving fails, ask and keep the original layout.',
  'menu.restore.privacy': 'Only window layout is saved, not chats, drafts, screenshots or reference images. The browser starts blank after a restart.',
  'menu.restore.failed': 'Restoration settings were not saved. Reload and try again; your changes are kept.',
  'menu.restore.dirty': 'Unsaved. After saving, the basic menu option needs an app restart. Other changes apply next time the menu opens.',
  'menu.restore.saved': 'Saved. The basic menu option needs an app restart. Other changes apply next time the menu opens.',
  'menu.restore.save': 'Save restoration settings',
  'menu.restore.busy': 'Working…',
  'menu.restore.reload': 'Reload',
  'menu.display.title': 'Menu display and interaction',
  'menu.display.appearance': 'Appearance and tooltips',
  'menu.social.title': 'Friends and alerts',
  'menu.social.notifications': 'Show menu social alerts',
  'menu.social.sound': 'Play social sounds while the menu is open',
  'menu.social.showAvatars': 'Show friend and private-chat avatars',
  'menu.social.avatarHint': 'Only affects menu friends and private chats. When off, name placeholders remain. Client and profile avatars are unchanged; the client may still receive avatar data.',
  'menu.social.soundHint': 'Uses the notification sound and volume. Global mute, source mute and system quiet mode still apply. Takes effect after saving.',
  'menu.social.preview': 'Alert details',
  'menu.social.fullContent': 'Sender and content',
  'menu.social.sourceOnly': 'Sender only',
  'menu.social.hiddenDetails': 'Hide details',
  'menu.social.privacyHint': 'Only changes friend and private-message alerts inside the menu, not delivery or unread counts. Global notification and privacy restrictions still apply.',
  'menu.social.hint': 'Sorting only affects the menu list. Online and offline friends stay grouped.',
  'menu.social.friendSort': 'Sort within groups',
  'menu.social.onlineFirst': 'In-game friends first',
  'menu.social.alphabetical': 'By name',
  'menu.social.save': 'Save friends and alert settings',
  'menu.social.saved': 'Saved. Applies next time you open the menu.',
  'menu.social.dirty': 'You have unsaved changes.',
  'menu.social.failed': 'Could not save or load settings. Reload and try again; your edits will be kept.',
  'menu.social.busy': 'Working…',
  'menu.social.reload': 'Reload',
  'menu.display.privacy': 'Menu privacy',
  'menu.display.streamerPrivacy': 'Hide menu location and room code',
  'menu.display.privacyHint': 'Hides the location in the menu status bar, the room code and its copy button. Does not hide chat, member profiles or the information overlay, or change sharing permissions. Turning this off restores individual display settings.',
  'menu.display.showRoomCode': 'Show room code',
  'menu.display.hint': 'Customize the menu without changing your online status or sharing settings.',
  'menu.display.time': 'Local time',
  'menu.display.textScale': 'Menu text size',
  'menu.display.reduceMotion': 'Reduce motion',
  'menu.display.highContrast': 'Stronger menu outlines',
  'menu.display.tooltipDelay': 'Button tooltip delay',
  'menu.display.tooltipDelayHint':
      'How long to hover over a button before its description appears.',
  'menu.display.highContrastHint': 'Make borders and selections clearer without changing web or image colors.',
  'menu.display.reduceMotionHint': 'Reduce menu animations without affecting messages or web animations. Also follows your system reduced-motion setting.',
  'menu.display.interfaceScale': 'Menu bar size',
  'menu.display.interfaceScaleHint':
      'Resize the clock and toolbars without moving or resizing windows.',
  'menu.display.textScaleHint':
      'Resize menu text without changing web pages or the information overlay.',
  'menu.display.showClock': 'Show time',
  'menu.display.showDate': 'Show date',
  'menu.display.clockFormat': 'Time format',
  'menu.display.system': 'Use system format',
  'menu.display.twentyFourHour': '24-hour',
  'menu.display.twelveHour': '12-hour',
  'menu.display.showPresence': 'Show my presence',
  'menu.display.context': 'Collaboration and game status',
  'menu.display.showContext': 'Show status bar',
  'menu.display.showScene': 'Show collaboration',
  'menu.display.showMembers': 'Show member count',
  'menu.display.showShip': 'Show current ship',
  'menu.display.showLocation': 'Show location',
  'menu.display.showServer': 'Show server',
  'menu.display.sceneLabel': 'Collaboration',
  'menu.display.membersLabel': 'Members',
  'menu.display.shipLabel': 'Current ship',
  'menu.display.locationLabel': 'Location',
  'menu.display.serverLabel': 'Server',
  'menu.display.noScene': 'No collaboration scene',
  'menu.display.failed': 'Display settings were not saved. Reload and try again; your changes are kept.',
  'menu.display.dirty':
      'Unsaved changes. The menu uses saved settings next time it opens.',
  'menu.display.saved': 'Saved. Changes apply next time the menu opens.',
  'menu.display.save': 'Save display settings',
  'menu.display.busy': 'Working…',
  'menu.display.reload': 'Reload',
  'menu.tools.hud': 'Information overlay',
  'menu.tools.organizations': 'Organizations',
  'menu.tools.friends': 'Friends',
  'menu.tools.comms': 'Messages',
  'menu.tools.rooms': 'Rooms',
  'menu.tools.screenshot': 'Screenshot',
  'menu.tools.image': 'Reference image',
  'menu.tools.browser': 'Browser',
  'menu.toolbar.title': 'Toolbar',
  'menu.toolbar.showUnreadBadges': 'Show unread and request badges',
  'menu.toolbar.attention': '{count} unread or pending',
  'menu.toolbar.hint': 'Drag a handle or use the up arrow to reorder. Hiding a tool keeps its open window.',
  'menu.toolbar.density': 'Toolbar density',
  'menu.toolbar.compact': 'Compact',
  'menu.toolbar.standard': 'Standard',
  'menu.toolbar.comfortable': 'Comfortable',
  'menu.toolbar.labels': 'Tool labels',
  'menu.toolbar.auto': 'Icons and names',
  'menu.toolbar.iconsOnly': 'Icons only',
  'menu.toolbar.alwaysVisible': 'Always visible',
  'menu.toolbar.earlier': 'Move earlier',
  'menu.toolbar.move': 'Drag to reorder',
  'menu.toolbar.reset': 'Reset toolbar',
  'menu.toolbar.failed':
      'Settings were not saved. Reload and try again; your changes are kept.',
  'menu.toolbar.dirty':
      'Unsaved. Saved settings apply when you next open the menu.',
  'menu.toolbar.saved': 'Saved. Applies when you next open the menu.',
  'menu.toolbar.save': 'Save toolbar',
  'menu.toolbar.busy': 'Working…',
  'menu.toolbar.reload': 'Reload',
  'menu.shortcut.title': 'Menu shortcut',
  'menu.shortcut.hint': 'Opens the menu only while the game is in the foreground. Saved on this computer; the information overlay shortcut is unchanged.',
  'menu.shortcut.enabled': 'Enable menu shortcut',
  'menu.shortcut.close': 'Press the shortcut again to close the menu',
  'menu.shortcut.dirty': 'Unsaved. The last applied settings are still active.',
  'menu.shortcut.ready': 'Saved and enabled.',
  'menu.shortcut.disabled':
      'Shortcut disabled. You can still open the menu with its button.',
  'menu.shortcut.conflict': 'This matches the information overlay shortcut. Choose a different combination.',
  'menu.shortcut.invalid': 'Choose modifiers with a letter or number, or F1–F12. System-reserved combinations are not available.',
  'menu.shortcut.unavailable': 'Could not confirm shortcut status. Check your sign-in and local service connection, then reload.',
  'menu.shortcut.changed': 'Settings changed elsewhere. Reload before saving; your input will be kept.',
  'menu.shortcut.save': 'Save shortcut',
  'menu.shortcut.busy': 'Working…',
  'menu.shortcut.reload': 'Reload',
  'menu.product.description': 'Read messages and coordinate with your team in game, with a browser, reference images and screenshot tools.',
  'menu.product.open': 'Open menu overlay',
  'menu.product.closeHint': 'Drag a title to move a window or its lower-right corner to resize. Press Esc or use the return button to close the menu.',
  'menu.product.unavailable': 'The menu overlay is unavailable. Check that you are signed in and connected to the local service, then try again.',
  'menu.product.social.title': 'Messages and teamwork',
  'menu.product.social.body': 'Open friends, messages, organizations and rooms together to view profiles and chat.',
  'menu.product.images.title': 'Reference images and screenshots',
  'menu.product.images.body': 'Adjust and pin a reference image to the game. Capture, crop and rotate screenshots, then copy or save them.',
  'menu.product.browser.title': 'Browser',
  'menu.product.browser.body':
      'Enter a URL or search, and compare resources across tabs.',
  'menu.product.settings.title': 'Window and display settings',
  'menu.product.settings.body': 'Open the menu and choose Settings at the top right to adjust dimming, the clock, status bar, window snapping and layout restoration.',
  'menu.product.privacy': 'Visible messages are marked as read. Images are not uploaded automatically. Closing the menu keeps images in memory; exiting the app or ending the account session clears them.',
};
