const menuWorkspaceZhCn = <String, String>{
  'menu.workspace.category': '设置分类',
  'menu.workspace.display': '显示与操作',
  'menu.workspace.toolbar': '底部工具栏',
  'menu.workspace.restore': '窗口与恢复',
  'menu.workspace.social': '好友与提醒',
  'menu.workspace.browser': '浏览器',
  'menu.workspace.image': '参考图',
  'menu.workspace.screenshot': '截图',
  'menu.workspace.shortcuts': '快捷键',
  'menu.workspace.preview': '菜单预览',
  'menu.workspace.previewHint': '调整左侧设置，查看菜单外观变化。',
  'menu.workspace.previewScope': '预览仅使用示例内容，不会读取聊天或执行操作。工具行为请保存后打开菜单体验。',
  'menu.workspace.independent': '调整后，点击页面底部“保存更改”生效。',
  'menu.workspace.saved': '已保存，下次打开菜单时生效。',
  'menu.workspace.dirty': '尚未保存，预览已显示当前调整。',
  'menu.workspace.loading': '正在处理设置…',
  'menu.workspace.failed': '未能确认设置，请重新读取后再试。',
  'menu.workspace.failedDirty': '仍有更改未保存，已保留供你重试。已成功保存的项目不会撤回。',
  'menu.workspace.conflict': '同一设置已在别处更改，本页修改尚未保存。请放弃更改并重新读取后再调整。',
  'menu.workspace.save': '保存更改',
  'menu.workspace.discard': '放弃修改',
  'menu.workspace.reload': '重新读取',
  'menu.workspace.leaveTitle': '保存菜单设置？',
  'menu.workspace.leaveBody': '菜单设置有尚未保存的修改。是否保存后离开？',
  'menu.workspace.stay': '继续编辑',
  'menu.workspace.sampleFleet': '示例舰队',
  'menu.workspace.sampleShip': '示例飞船',
  'menu.workspace.sampleLocation': '示例位置',
  'menu.workspace.sampleServer': '示例服务器',
};

const menuWorkspaceZhTw = <String, String>{
  'menu.workspace.category': '設定分類',
  'menu.workspace.display': '顯示與操作',
  'menu.workspace.toolbar': '底部工具列',
  'menu.workspace.restore': '視窗與恢復',
  'menu.workspace.social': '好友與提醒',
  'menu.workspace.browser': '瀏覽器',
  'menu.workspace.image': '參考圖',
  'menu.workspace.screenshot': '截圖',
  'menu.workspace.shortcuts': '快捷鍵',
  'menu.workspace.preview': '選單預覽',
  'menu.workspace.previewHint': '調整左側設定，查看選單外觀變化。',
  'menu.workspace.previewScope': '預覽僅使用範例內容，不會讀取聊天或執行操作。工具行為請儲存後開啟選單體驗。',
  'menu.workspace.independent': '調整後，點擊頁面底部「儲存變更」生效。',
  'menu.workspace.saved': '已儲存，下次開啟選單時生效。',
  'menu.workspace.dirty': '尚未儲存，預覽已顯示目前調整。',
  'menu.workspace.loading': '正在處理設定…',
  'menu.workspace.failed': '未能確認設定，請重新讀取後再試。',
  'menu.workspace.failedDirty': '仍有變更未儲存，已保留供你重試。已成功儲存的項目不會撤回。',
  'menu.workspace.conflict': '同一設定已在別處變更，本頁修改尚未儲存。請放棄變更並重新讀取後再調整。',
  'menu.workspace.save': '儲存變更',
  'menu.workspace.discard': '放棄修改',
  'menu.workspace.reload': '重新讀取',
  'menu.workspace.leaveTitle': '儲存選單設定？',
  'menu.workspace.leaveBody': '選單設定有尚未儲存的修改。是否儲存後離開？',
  'menu.workspace.stay': '繼續編輯',
  'menu.workspace.sampleFleet': '範例艦隊',
  'menu.workspace.sampleShip': '範例飛船',
  'menu.workspace.sampleLocation': '範例位置',
  'menu.workspace.sampleServer': '範例伺服器',
};

const menuWorkspaceEn = <String, String>{
  'menu.workspace.category': 'Settings category',
  'menu.workspace.display': 'Display & interaction',
  'menu.workspace.toolbar': 'Toolbar',
  'menu.workspace.restore': 'Windows & recovery',
  'menu.workspace.social': 'Friends & notifications',
  'menu.workspace.browser': 'Browser',
  'menu.workspace.image': 'Reference images',
  'menu.workspace.screenshot': 'Screenshots',
  'menu.workspace.shortcuts': 'Shortcuts',
  'menu.workspace.preview': 'Menu preview',
  'menu.workspace.previewHint':
      'Adjust settings to preview the menu appearance.',
  'menu.workspace.previewScope': 'Preview uses sample content only, without reading chats or performing actions. Save and open the menu to try tool behavior.',
  'menu.workspace.independent':
      'Apply these options with Save changes at the bottom of the page.',
  'menu.workspace.saved': 'Saved. Applies the next time you open the menu.',
  'menu.workspace.dirty':
      'Unsaved changes. The preview reflects your adjustments.',
  'menu.workspace.loading': 'Processing settings…',
  'menu.workspace.failed': 'Could not confirm settings. Reload and try again.',
  'menu.workspace.failedDirty': 'Some changes remain unsaved and are kept for retry. Successfully saved items will not be rolled back.',
  'menu.workspace.conflict': 'The same setting changed elsewhere. Your edits are still unsaved. Discard and reload before editing again.',
  'menu.workspace.save': 'Save changes',
  'menu.workspace.discard': 'Discard changes',
  'menu.workspace.reload': 'Reload',
  'menu.workspace.leaveTitle': 'Save menu settings?',
  'menu.workspace.leaveBody':
      'There are unsaved menu settings. Save before leaving?',
  'menu.workspace.stay': 'Keep editing',
  'menu.workspace.sampleFleet': 'Example fleet',
  'menu.workspace.sampleShip': 'Example ship',
  'menu.workspace.sampleLocation': 'Example location',
  'menu.workspace.sampleServer': 'Example server',
};
