const menuScreenshotZhCn = <String, String>{
  'menu.screenshot.title': '截图设置',
  'menu.screenshot.hint': '截图先预览；点击“保存到截图目录”“另存为”或“截取并保存到目录”才会写入文件。',
  'menu.screenshot.format': '默认保存格式',
  'menu.screenshot.png': 'PNG',
  'menu.screenshot.jpeg': 'JPEG',
  'menu.screenshot.formatHint':
      'PNG 无损并保留透明度。JPEG 文件较小，透明区域会变为白色；预览不变。保存对话框中也可选格式。',
  'menu.screenshot.quality': 'JPEG 质量',
  'menu.screenshot.hideMenu': '截图时隐藏菜单',
  'menu.screenshot.hideMenuHint': '默认开启。关闭后，菜单和打开的工具可能出现在截图中。',
  'menu.screenshot.copy': '保存成功后同时复制图片',
  'menu.screenshot.copyHint': '会替换剪贴板中的内容；取消或保存失败时不复制。默认关闭。',
  'menu.screenshot.confirmation': '显示截图成功提示',
  'menu.screenshot.confirmationHint': '在截图工具中显示保存或复制成功；关闭后仍显示失败和取消结果。',
  'menu.screenshot.privacy': '截图不会上传或进入预设。截图目录只在本机保存；不会改变你的共享设置。',
  'menu.screenshot.failed': '设置未保存，当前修改仍保留。请重新读取后重试。',
  'menu.screenshot.dirty': '有未保存的修改。',
  'menu.screenshot.saved': '已保存，下次截图或保存图片时生效。',
  'menu.screenshot.save': '保存截图设置',
  'menu.screenshot.busy': '正在处理…',
  'menu.screenshot.reload': '重新读取',
  'menu.screenshot.capture': '截取当前屏幕',
  'menu.screenshot.recapture': '重新截图',
  'menu.screenshot.captureSave': '截取并保存到目录',
  'menu.screenshot.saveDirectoryAction': '保存到截图目录',
  'menu.screenshot.directoryUnavailable':
      '无法确认截图目录。预览仍保留；请在菜单设置中重新读取截图目录，或选择“另存为”。',
  'menu.screenshot.directory.title': '截图目录',
  'menu.screenshot.directory.hint':
      '“保存到截图目录”和“截取并保存到目录”使用此目录，按时间命名且不覆盖旧截图。“另存为”仍可选择其他位置。',
  'menu.screenshot.directory.default': '默认目录',
  'menu.screenshot.directory.custom': '已选择的目录',
  'menu.screenshot.directory.lastConfirmed': '上次确认的目录（请重新读取）',
  'menu.screenshot.directory.choose': '选择截图目录',
  'menu.screenshot.directory.open': '打开截图目录',
  'menu.screenshot.directory.reset': '恢复默认目录',
  'menu.screenshot.directory.reload': '重新读取',
  'menu.screenshot.directory.loading': '正在读取截图目录…',
  'menu.screenshot.directory.busy': '正在处理…',
  'menu.screenshot.directory.choosing': '正在等待你选择目录…',
  'menu.screenshot.directory.ready': '选择后立即在本机保存，下次直接保存截图时生效。',
  'menu.screenshot.directory.changed': '目录已保存，下次直接保存截图时生效。',
  'menu.screenshot.directory.cancelled': '已取消选择，原目录仍保留。',
  'menu.screenshot.directory.opened': '已打开截图目录。',
  'menu.screenshot.directory.readFailed': '无法读取截图目录。请重新读取；也可使用“另存为”。',
  'menu.screenshot.directory.chooseFailed': '无法确认目录是否已保存。请重新读取后重试。',
  'menu.screenshot.directory.resetFailed': '默认目录恢复未完成。请重新读取后重试。',
  'menu.screenshot.directory.openFailed': '目录未能打开。请检查目录或网络位置是否可用，然后重新读取并重试。',
  'menu.screenshot.directory.conflict': '截图目录已在其他位置改变。请重新读取后再操作。',
  'menu.screenshot.directory.privacy':
      '目录只保存在这台电脑，不会上传或随预设分享。选择或恢复目录不会截屏、移动旧文件；打开目录时会创建尚不存在的目录。',
  'menu.screenshot.copyAction': '复制截图',
  'menu.screenshot.saveAction': '另存为',
  'menu.screenshot.clearPreview': '清除预览',
  'menu.screenshot.previewHint': '先预览、裁剪或旋转，再复制或保存。截图不会上传。',
  'menu.screenshot.fit': '适合窗口',
  'menu.screenshot.zoomOut': '缩小',
  'menu.screenshot.zoomIn': '放大',
  'menu.screenshot.rotate': '旋转',
  'menu.screenshot.exported': '截图已保存。',
  'menu.screenshot.copied': '截图已复制，可粘贴到其他应用。',
  'menu.screenshot.savedCopied': '截图已保存并复制。',
  'menu.screenshot.savedCopyFailed': '截图已保存，但复制未完成。请点击“复制截图”重试，不必重新保存。',
  'menu.screenshot.copyFailed': '复制未完成，剪贴板可能正被使用。预览仍保留，请重试。',
  'menu.screenshot.saveFailed': '保存未完成，预览仍保留。请确认目录可写并重试。',
  'menu.screenshot.cancelled': '已取消保存，预览仍保留。',
  'menu.screenshot.extensionMismatch': '文件扩展名与所选格式不一致。请重新保存，并使用 .png 或 .jpg。',
};
const menuScreenshotZhTw = <String, String>{
  'menu.screenshot.title': '截圖設定',
  'menu.screenshot.hint': '截圖先預覽；點擊「儲存到截圖目錄」「另存新檔」或「擷取並儲存到目錄」才會寫入檔案。',
  'menu.screenshot.format': '預設儲存格式',
  'menu.screenshot.png': 'PNG',
  'menu.screenshot.jpeg': 'JPEG',
  'menu.screenshot.formatHint':
      'PNG 無損並保留透明度。JPEG 檔案較小，透明區域會變為白色；預覽不變。儲存對話框中也可選格式。',
  'menu.screenshot.quality': 'JPEG 品質',
  'menu.screenshot.copy': '儲存成功後同時複製圖片',
  'menu.screenshot.copyHint': '會取代剪貼簿中的內容；取消或儲存失敗時不複製。預設關閉。',
  'menu.screenshot.confirmation': '顯示截圖成功提示',
  'menu.screenshot.confirmationHint': '在截圖工具中顯示儲存或複製成功；關閉後仍顯示失敗及取消結果。',
  'menu.screenshot.hideMenu': '截圖時隱藏選單',
  'menu.screenshot.hideMenuHint': '預設開啟。關閉後，選單與開啟的工具可能出現在截圖中。',
  'menu.screenshot.privacy': '截圖不會上傳或加入預設。截圖目錄只在本機儲存；不會變更你的分享設定。',
  'menu.screenshot.failed': '設定未儲存，目前修改仍保留。請重新讀取後重試。',
  'menu.screenshot.dirty': '有未儲存的修改。',
  'menu.screenshot.saved': '已儲存，下次截圖或儲存圖片時生效。',
  'menu.screenshot.save': '儲存截圖設定',
  'menu.screenshot.busy': '正在處理…',
  'menu.screenshot.reload': '重新讀取',
  'menu.screenshot.capture': '擷取目前螢幕',
  'menu.screenshot.recapture': '重新擷取',
  'menu.screenshot.captureSave': '擷取並儲存到目錄',
  'menu.screenshot.saveDirectoryAction': '儲存到截圖目錄',
  'menu.screenshot.directoryUnavailable':
      '無法確認截圖目錄。預覽仍保留；請在選單設定中重新讀取截圖目錄，或選擇「另存新檔」。',
  'menu.screenshot.directory.title': '截圖目錄',
  'menu.screenshot.directory.hint':
      '「儲存到截圖目錄」和「擷取並儲存到目錄」使用此目錄，依時間命名且不覆蓋舊截圖。「另存新檔」仍可選擇其他位置。',
  'menu.screenshot.directory.default': '預設目錄',
  'menu.screenshot.directory.custom': '已選擇的目錄',
  'menu.screenshot.directory.lastConfirmed': '上次確認的目錄（請重新讀取）',
  'menu.screenshot.directory.choose': '選擇截圖目錄',
  'menu.screenshot.directory.open': '開啟截圖目錄',
  'menu.screenshot.directory.reset': '還原預設目錄',
  'menu.screenshot.directory.reload': '重新讀取',
  'menu.screenshot.directory.loading': '正在讀取截圖目錄…',
  'menu.screenshot.directory.busy': '正在處理…',
  'menu.screenshot.directory.choosing': '正在等待你選擇目錄…',
  'menu.screenshot.directory.ready': '選擇後立即在本機儲存，下次直接儲存截圖時生效。',
  'menu.screenshot.directory.changed': '目錄已儲存，下次直接儲存截圖時生效。',
  'menu.screenshot.directory.cancelled': '已取消選擇，原目錄仍保留。',
  'menu.screenshot.directory.opened': '已開啟截圖目錄。',
  'menu.screenshot.directory.readFailed': '無法讀取截圖目錄。請重新讀取；也可使用「另存新檔」。',
  'menu.screenshot.directory.chooseFailed': '無法確認目錄是否已儲存。請重新讀取後重試。',
  'menu.screenshot.directory.resetFailed': '預設目錄還原未完成。請重新讀取後重試。',
  'menu.screenshot.directory.openFailed': '目錄未能開啟。請檢查目錄或網路位置是否可用，再重新讀取並重試。',
  'menu.screenshot.directory.conflict': '截圖目錄已在其他位置變更。請重新讀取後再操作。',
  'menu.screenshot.directory.privacy':
      '目錄只儲存在這台電腦，不會上傳或隨預設分享。選擇或還原目錄不會擷取畫面、移動舊檔案；開啟目錄時會建立尚不存在的目錄。',
  'menu.screenshot.copyAction': '複製截圖',
  'menu.screenshot.saveAction': '另存新檔',
  'menu.screenshot.clearPreview': '清除預覽',
  'menu.screenshot.previewHint': '先預覽、裁剪或旋轉，再複製或儲存。截圖不會上傳。',
  'menu.screenshot.fit': '適合視窗',
  'menu.screenshot.zoomOut': '縮小',
  'menu.screenshot.zoomIn': '放大',
  'menu.screenshot.rotate': '旋轉',
  'menu.screenshot.exported': '截圖已儲存。',
  'menu.screenshot.copied': '截圖已複製，可貼到其他應用程式。',
  'menu.screenshot.savedCopied': '截圖已儲存並複製。',
  'menu.screenshot.savedCopyFailed': '截圖已儲存，但複製未完成。請點擊「複製截圖」重試，不必重新儲存。',
  'menu.screenshot.copyFailed': '複製未完成，剪貼簿可能正被使用。預覽仍保留，請重試。',
  'menu.screenshot.saveFailed': '儲存未完成，預覽仍保留。請確認目錄可寫並重試。',
  'menu.screenshot.cancelled': '已取消儲存，預覽仍保留。',
  'menu.screenshot.extensionMismatch': '副檔名與所選格式不一致。請重新儲存，並使用 .png 或 .jpg。',
};
const menuScreenshotEn = <String, String>{
  'menu.screenshot.title': 'Screenshot settings',
  'menu.screenshot.hint': 'Preview first. Files are written only when you choose Save to screenshot folder, Save as or Capture and save to folder.',
  'menu.screenshot.format': 'Default file format',
  'menu.screenshot.png': 'PNG',
  'menu.screenshot.jpeg': 'JPEG',
  'menu.screenshot.formatHint': 'PNG is lossless and keeps transparency. JPEG makes smaller files and flattens transparency to white; the preview is unchanged. You can also choose the format in the save dialog.',
  'menu.screenshot.quality': 'JPEG quality',
  'menu.screenshot.copy': 'Copy the image after saving',
  'menu.screenshot.copyHint': 'Replaces clipboard contents only after a successful save. Off by default; cancellation or failure does not copy.',
  'menu.screenshot.confirmation': 'Show screenshot success messages',
  'menu.screenshot.confirmationHint': 'Shows save or copy confirmations in the screenshot tool. Errors and cancellation remain visible when off.',
  'menu.screenshot.hideMenu': 'Hide the menu when capturing',
  'menu.screenshot.hideMenuHint': 'On by default. When off, the menu and open tools may appear in screenshots.',
  'menu.screenshot.privacy': 'Screenshots are not uploaded or included in presets. The screenshot folder is saved locally. Your sharing settings are unchanged.',
  'menu.screenshot.failed':
      'Settings were not saved. Your changes are kept. Reload and try again.',
  'menu.screenshot.dirty': 'You have unsaved changes.',
  'menu.screenshot.saved':
      'Saved. Applies when you next capture or save an image.',
  'menu.screenshot.save': 'Save screenshot settings',
  'menu.screenshot.busy': 'Working…',
  'menu.screenshot.reload': 'Reload',
  'menu.screenshot.capture': 'Capture screen',
  'menu.screenshot.recapture': 'Capture again',
  'menu.screenshot.captureSave': 'Capture and save to folder',
  'menu.screenshot.saveDirectoryAction': 'Save to screenshot folder',
  'menu.screenshot.directoryUnavailable': 'The screenshot folder could not be confirmed. Your preview is kept. Reload the folder in menu settings or choose Save as.',
  'menu.screenshot.directory.title': 'Screenshot folder',
  'menu.screenshot.directory.hint': 'Save to screenshot folder and Capture and save to folder use this location. Filenames use the capture time and never replace old screenshots. Save as can use another location.',
  'menu.screenshot.directory.default': 'Default folder',
  'menu.screenshot.directory.custom': 'Selected folder',
  'menu.screenshot.directory.lastConfirmed':
      'Last confirmed folder (reload required)',
  'menu.screenshot.directory.choose': 'Choose screenshot folder',
  'menu.screenshot.directory.open': 'Open screenshot folder',
  'menu.screenshot.directory.reset': 'Restore default folder',
  'menu.screenshot.directory.reload': 'Reload',
  'menu.screenshot.directory.loading': 'Loading screenshot folder…',
  'menu.screenshot.directory.busy': 'Working…',
  'menu.screenshot.directory.choosing': 'Waiting for you to choose a folder…',
  'menu.screenshot.directory.ready': 'Your choice is saved locally and used by the next direct screenshot save.',
  'menu.screenshot.directory.changed':
      'Folder saved. Used by the next direct screenshot save.',
  'menu.screenshot.directory.cancelled':
      'Selection cancelled. Your previous folder is kept.',
  'menu.screenshot.directory.opened': 'Screenshot folder opened.',
  'menu.screenshot.directory.readFailed':
      'The folder could not be read. Reload or use Save as.',
  'menu.screenshot.directory.chooseFailed':
      'Could not confirm whether the folder was saved. Reload and try again.',
  'menu.screenshot.directory.resetFailed':
      'The default folder could not be restored. Reload and try again.',
  'menu.screenshot.directory.openFailed': 'The folder could not be opened. Check that the folder or network location is available, then reload and try again.',
  'menu.screenshot.directory.conflict':
      'The screenshot folder changed elsewhere. Reload before trying again.',
  'menu.screenshot.directory.privacy': 'This folder is saved on this computer only, never uploaded or shared with presets. Choosing or restoring it does not capture images or move old files. Open folder creates the folder if it does not exist.',
  'menu.screenshot.copyAction': 'Copy screenshot',
  'menu.screenshot.saveAction': 'Save as',
  'menu.screenshot.clearPreview': 'Clear preview',
  'menu.screenshot.previewHint': 'Preview, crop or rotate, then copy or save. Screenshots are not uploaded.',
  'menu.screenshot.fit': 'Fit to window',
  'menu.screenshot.zoomOut': 'Zoom out',
  'menu.screenshot.zoomIn': 'Zoom in',
  'menu.screenshot.rotate': 'Rotate',
  'menu.screenshot.exported': 'Screenshot saved.',
  'menu.screenshot.copied':
      'Screenshot copied. You can paste it into another app.',
  'menu.screenshot.savedCopied': 'Screenshot saved and copied.',
  'menu.screenshot.savedCopyFailed': 'Screenshot saved, but copying failed. Choose Copy screenshot to retry; you do not need to save again.',
  'menu.screenshot.copyFailed': 'Copy failed. The clipboard may be busy. Your preview is kept; try again.',
  'menu.screenshot.saveFailed': 'Save failed. Your preview is kept. Check folder permissions and try again.',
  'menu.screenshot.cancelled': 'Save cancelled. Your preview is kept.',
  'menu.screenshot.extensionMismatch': 'The extension does not match the chosen format. Save again using .png or .jpg.',
};
