const audioZh = <String, String>{
  'audio.title': '通知声音',
  'audio.description': '调整本机提示音，并试听普通通知的声音。',
  'audio.enabled': '启用提示音',
  'audio.automatic': '启用后，客户端在后台且未运行游戏时，会为新的房间邀请和加入申请播放提示音。',
  'audio.ready': '提示音已启用',
  'audio.muted': '已静音',
  'audio.volume': '提示音音量',
  'audio.local': '只影响星海舰桥提示音，不改变 Windows 或游戏音量。',
  'audio.preview': '试听普通通知',
  'audio.stop': '停止试听',
  'audio.retry': '重新读取',
  'audio.saved': '已保存在本机',
  'audio.played': '已开始试听',
  'audio.stopped': '试听已停止',
  'audio.unavailable': '当前版本暂不支持声音设置，请重新启动客户端。',
  'audio.failed': '声音操作未完成，请重新读取后再试。',
  'audio.invalidResponse': '无法确认声音设置，请重新读取。',
  'audio.conflict': '声音设置已变化，请重新读取后再调整。',
  'audio.assets': '提示音资源不可用，请更新或修复客户端。',
  'audio.integrity': '提示音文件校验失败，已停止播放。请修复客户端。',
  'audio.output': '无法播放提示音，请检查声音输出设备。',
};
const audioTw = <String, String>{
  'audio.title': '通知聲音',
  'audio.description': '調整本機提示音，並試聽一般通知的聲音。',
  'audio.enabled': '啟用提示音',
  'audio.automatic': '啟用後，用戶端在背景且未執行遊戲時，會為新的房間邀請和加入申請播放提示音。',
  'audio.ready': '提示音已啟用',
  'audio.muted': '已靜音',
  'audio.volume': '提示音音量',
  'audio.local': '只影響星海艦橋提示音，不改變 Windows 或遊戲音量。',
  'audio.preview': '試聽一般通知',
  'audio.stop': '停止試聽',
  'audio.retry': '重新讀取',
  'audio.saved': '已儲存在本機',
  'audio.played': '已開始試聽',
  'audio.stopped': '試聽已停止',
  'audio.unavailable': '目前版本暫不支援聲音設定，請重新啟動用戶端。',
  'audio.failed': '聲音操作未完成，請重新讀取後再試。',
  'audio.invalidResponse': '無法確認聲音設定，請重新讀取。',
  'audio.conflict': '聲音設定已變更，請重新讀取後再調整。',
  'audio.assets': '提示音資源無法使用，請更新或修復用戶端。',
  'audio.integrity': '提示音檔案校驗失敗，已停止播放。請修復用戶端。',
  'audio.output': '無法播放提示音，請檢查聲音輸出裝置。',
};
const audioEn = <String, String>{
  'audio.title': 'Notification sounds',
  'audio.description':
      'Adjust sounds on this device and preview the standard notification cue.',
  'audio.enabled': 'Enable notification sounds',
  'audio.automatic': 'When enabled, new room invitations and join requests play a sound while the app is in the background and no game is running.',
  'audio.ready': 'Notification sounds enabled',
  'audio.muted': 'Muted',
  'audio.volume': 'Notification volume',
  'audio.local': 'Only affects StarBridge notification sounds, not Windows or game volume.',
  'audio.preview': 'Preview notification',
  'audio.stop': 'Stop preview',
  'audio.retry': 'Reload settings',
  'audio.saved': 'Saved on this device',
  'audio.played': 'Preview started',
  'audio.stopped': 'Preview stopped',
  'audio.unavailable':
      'Sound settings are unavailable in this version. Restart the client.',
  'audio.failed':
      'The sound action did not complete. Reload settings and try again.',
  'audio.invalidResponse':
      'Could not confirm sound settings. Reload them to continue.',
  'audio.conflict': 'Sound settings changed. Reload them before editing.',
  'audio.assets':
      'Notification audio is unavailable. Update or repair the client.',
  'audio.integrity':
      'Audio verification failed. Playback was stopped. Repair the client.',
  'audio.output': 'Could not play the sound. Check your audio output device.',
};
