const simplifiedOfficialFleetStrings = <String, String>{
  'officialFleet.members.metric.matches': '匹配成员',
  'officialFleet.members.coverage.unknown': '名单覆盖范围尚未确认。',
  'officialFleet.members.coverage.completeOfficialRoster':
      '名单来源：完整 RSI 官网成员目录。',
  'officialFleet.members.coverage.scmRegisteredMembers':
      '仅显示已注册 SCM 的成员，不代表完整官网名单。',
  'officialFleet.members.coverage.partial': '当前仅取得部分名单。',
  'officialFleet.members.coverage.restricted': '仅显示你有权查看的成员。',
  'officialFleet.members.presence.unknown': '状态未知',
  'officialFleet.members.presence.away': '暂离',
  'officialFleet.members.connection.connected': '已接入 StarBridge',
  'officialFleet.members.connection.unknown': '应用接入状态尚未确认',
  'officialFleet.members.details.title': '成员详情',
  'officialFleet.members.details.back': '返回成员列表',
  'officialFleet.loading': '正在读取 RSI 官网舰队归属…',
  'officialFleet.signedOut.title': '登录后查看官网舰队',
  'officialFleet.signedOut.body':
      '连接 SCM 账号后，StarBridge 才能通过 SCM 同步你的唯一 RSI 官网舰队归属。',
  'officialFleet.notMember.title': '尚未加入 RSI 官网舰队',
  'officialFleet.notMember.body':
      '暂未读取到 RSI 官网舰队归属。加入或更改官网舰队需要在 RSI 官网完成，返回后可在此刷新。',
  'officialFleet.unavailable.title': '暂时无法读取官网舰队',
  'officialFleet.action.retry': '重新读取',
  'officialFleet.action.refresh': '刷新舰队数据',
  'officialFleet.error.hostUnavailable': 'Native Host 未连接。恢复连接后可重新读取。',
  'officialFleet.error.scmUnavailable': 'SCM 暂时不可用，已保留本机登录状态。',
  'officialFleet.error.reauthorizationRequired': 'SCM 授权已失效，请先在账号与识别中重新授权。',
  'officialFleet.error.invalidResponse': 'SCM 返回的舰队资料不符合当前客户端合同。',
  'officialFleet.error.unavailable': 'SCM 舰队数据当前不可用，请稍后重试。',
  'officialFleet.rank.unknown': '官方职位未提供',
  'officialFleet.rank.scale': 'RSI 官方星级',
  'officialFleet.myOfficialPosition': '我的官网职位',
  'officialFleet.fresh.live': 'SCM 最新',
  'officialFleet.source': '舰队归属：RSI 官网 · 数据同步：SCM',
  'officialFleet.resourceVersion': '舰队资源版本',
  'officialFleet.tab.overview': '概览',
  'officialFleet.tab.operations': '行动',
  'officialFleet.tab.members': '成员',
  'officialFleet.tab.channel': '频道',
  'officialFleet.tab.ships': '舰船',
  'officialFleet.tab.broadcasts': '广播',
  'officialFleet.tab.profile': '资料',
  'officialFleet.overview.title': '主舰队工作区',
  'officialFleet.overview.body': '查看当前公告、主舰队快照和必须由你处理的事项。',
  'officialFleet.overview.loading': '正在读取主舰队协作概览…',
  'officialFleet.overview.unavailable.title': '协作概览暂时不可用',
  'officialFleet.overview.error.contractUnavailable':
      'StarBridge 公告、Presence、共享舰船和待处理合同尚未接入。当前不会用示例数据替代真实舰队信息。',
  'officialFleet.overview.error.unavailable': '读取协作概览失败，请稍后重试。',
  'officialFleet.overview.retry': '重新读取概览',
  'officialFleet.overview.announcement.title': '当前公告',
  'officialFleet.overview.announcement.unread': '未读',
  'officialFleet.overview.announcement.none': '主舰队当前没有公告。',
  'officialFleet.overview.announcement.body':
      'StarBridge 公告服务尚未接入。这里不会用示例公告替代真实舰队信息。',
  'officialFleet.overview.snapshot.title': '主舰队快照',
  'officialFleet.overview.snapshot.updated': '最近更新 {time}',
  'officialFleet.overview.metric.members': '官网成员',
  'officialFleet.overview.metric.online': '可见在线',
  'officialFleet.overview.metric.inGame': '游戏中',
  'officialFleet.overview.metric.ships': '可请求舰船',
  'officialFleet.overview.tasks.title': '需要处理',
  'officialFleet.overview.tasks.body': '这里只出现必须由你明确决定或完成的事项，最多显示 3 项。',
  'officialFleet.overview.tasks.empty': '目前没有需要你处理的事项。',
  'officialFleet.overview.tasks.due': '截止 {time}',
  'officialFleet.overview.operations.title': '行动入口',
  'officialFleet.overview.operations.body': '行动将保留当前官网舰队来源；完整流程将在行动专项中接入。',
  'officialFleet.overview.operations.open': '打开行动入口',
  'officialFleet.overview.data.title': '协作数据接入状态',
  'officialFleet.overview.data.body': '舰队归属、官网成员与官方职位属于 RSI 官网事实，由 SCM 同步；公告、Presence、主频道、共享舰船与待处理事项来自 StarBridge 服务。未接入字段保持未知。',
  'officialFleet.data.identity': 'RSI 舰队归属',
  'officialFleet.data.identity.ready': '已同步',
  'officialFleet.data.announcement': '公告与待处理',
  'officialFleet.data.members': '成员目录与 Presence',
  'officialFleet.data.channel': '唯一内部主频道',
  'officialFleet.data.ships': '成员共享舰船',
  'officialFleet.data.pending': '等待数据接口',
  'officialFleet.data.pending.starBridge': '等待 StarBridge 服务',
  'officialFleet.data.pending.hybrid': '等待 SCM + StarBridge 服务',
  'officialFleet.section.operations.title': '舰队行动将在后续专项接入',
  'officialFleet.section.operations.body':
      '此入口已经绑定当前官网舰队，但不会在流程尚未确认时伪造行动、席位或权限。',
  'officialFleet.section.members.title': '成员目录尚未接入',
  'officialFleet.section.members.body': '正式目录将支持上千成员的服务端分页，并保留 WPF 成员横幅中的有效信息。',
  'officialFleet.members.title': '成员目录',
  'officialFleet.members.body': '查看当前可用的舰队成员资料；在线状态和游戏信息按共享权限显示。',
  'officialFleet.members.loading': '正在读取当前页成员…',
  'officialFleet.members.unavailable.title': '成员目录暂时不可用',
  'officialFleet.members.error.contractUnavailable':
      'SCM 成员名单与 StarBridge Presence 合同尚未接入。当前不会用示例成员替代真实名单。',
  'officialFleet.members.error.unavailable': '读取成员目录失败，请稍后重试。',
  'officialFleet.members.metric.total': '成员',
  'officialFleet.members.metric.online': '在线',
  'officialFleet.members.metric.inGame': '游戏中',
  'officialFleet.members.search': '搜索呼号、游戏 ID 或官网职位',
  'officialFleet.members.search.submit': '搜索成员',
  'officialFleet.members.pageSize': '每页',
  'officialFleet.members.filter.all': '全部成员',
  'officialFleet.members.filter.online': '在线',
  'officialFleet.members.filter.inGame': '游戏中',
  'officialFleet.members.empty.title': '没有匹配的成员',
  'officialFleet.members.empty.body': '当前可用名单中没有匹配结果，可尝试调整搜索或筛选条件。',
  'officialFleet.members.column.member': '成员',
  'officialFleet.members.column.server': '服务器',
  'officialFleet.members.column.rank': 'RSI 官网职位',
  'officialFleet.members.column.ship': '舰船',
  'officialFleet.members.column.location': '位置',
  'officialFleet.members.column.presence': '状态',
  'officialFleet.members.field.unknown': '未知',
  'officialFleet.members.field.notShared': '未共享',
  'officialFleet.members.field.notInGame': '未进入游戏',
  'officialFleet.members.field.restricted': '当前不可见',
  'officialFleet.members.field.notConnected': '尚未接入 StarBridge',
  'officialFleet.members.presence.notConnected': '尚未接入',
  'officialFleet.members.presence.offline': '离线',
  'officialFleet.members.presence.online': '在线',
  'officialFleet.members.presence.inGame': '游戏中',
  'officialFleet.members.presence.invisible': '隐身',
  'officialFleet.members.arrivalPending': '待确认',
  'officialFleet.members.previousPage': '上一页',
  'officialFleet.members.nextPage': '下一页',
  'officialFleet.members.pageStatus': '第 {page} / {total} 页',
  'officialFleet.members.pageNumber': '页码',
  'officialFleet.members.jump': '跳转',
  'officialFleet.section.channel.title': '内部主频道尚未接入',
  'officialFleet.section.channel.body':
      '每个官网舰队只有一个 StarBridge 持久主频道，不扩展成多频道社交系统。',
  'officialFleet.section.ships.title': '舰队共享舰船尚未接入',
  'officialFleet.section.ships.body': '这里将展示成员授权共享且当前可请求的舰船，并服从行动占用与隐私规则。',
  'officialFleet.section.broadcasts.title': '舰队广播尚未接入',
  'officialFleet.section.broadcasts.body': '紧急广播将保留独立历史和游戏内强提示，不与公告或普通通知混合。',
  'officialFleet.profile.title': '官网舰队资料',
  'officialFleet.profile.body': '当前只展示 SCM 已提供并经过 Native Host 校验的字段。',
  'officialFleet.profile.memberCount': '{count} 名官网成员',
  'officialFleet.profile.unavailable.title': '详细舰队资料尚未接入',
  'officialFleet.profile.unavailable.body':
      '当前只确认了你的 RSI 舰队归属与官方职位。简介、关注方向、语言和招募状态将在 SCM 资料合同接入后显示。',
  'officialFleet.profile.about': '舰队介绍',
  'officialFleet.profile.rsiDescription': 'RSI 官网公开简介',
  'officialFleet.profile.scmDescription': 'SCM 补充介绍',
  'officialFleet.profile.noDescription': '该舰队暂未提供公开介绍。',
  'officialFleet.profile.focus': '关注方向与特色',
  'officialFleet.profile.primaryFocus': '主要方向',
  'officialFleet.profile.secondaryFocus': '次要方向',
  'officialFleet.profile.focusUnavailable': '该舰队暂未提供关注方向。',
  'officialFleet.profile.tags': '舰队标签',
  'officialFleet.profile.attributes': '组织属性',
  'officialFleet.profile.languages': '语言',
  'officialFleet.profile.model': '组织模式',
  'officialFleet.profile.commitment': '投入程度',
  'officialFleet.profile.roleplay': '角色扮演',
  'officialFleet.profile.archetype': '组织类型',
  'officialFleet.profile.myIdentity': '我在舰队中的身份',
  'officialFleet.profile.starBridgeRole': 'StarBridge 角色',
  'officialFleet.profile.syncSource': '资料来源与同步',
  'officialFleet.profile.observedAt': '最近确认',
  'officialFleet.profile.name': '舰队名称',
  'officialFleet.profile.sid': '舰队 SID',
  'officialFleet.profile.rank': '我的官方职位',
  'officialFleet.profile.sourceRef': '稳定来源标识',
  'officialFleet.ships.title': '主舰队舰船库',
  'officialFleet.ships.body': '只展示成员明确共享给当前主舰队的舰船；可请求不代表管理者可以直接调度。',
  'officialFleet.ships.loading': '正在读取共享舰船…',
  'officialFleet.ships.unavailable.title': '共享舰船暂时不可用',
  'officialFleet.ships.error.contractUnavailable':
      'StarBridge 舰船共享合同尚未接入。当前不会读取完整个人机库，也不会用示例舰船替代真实共享记录。',
  'officialFleet.ships.error.unavailable': '读取共享舰船失败，请稍后重试。',
  'officialFleet.ships.metric.total': '共享舰船',
  'officialFleet.ships.metric.requestable': '当前可请求',
  'officialFleet.ships.metric.owners': '共享成员',
  'officialFleet.ships.metric.value': '舰船总价值',
  'officialFleet.ships.distribution.title': '舰级构成',
  'officialFleet.ships.search': '搜索舰船、型号、角色或共享成员',
  'officialFleet.ships.search.submit': '搜索舰船',
  'officialFleet.ships.pageSize': '每页',
  'officialFleet.ships.filter.all': '全部共享',
  'officialFleet.ships.filter.requestable': '可请求',
  'officialFleet.ships.filter.mine': '我共享的',
  'officialFleet.ships.empty.title': '没有匹配的共享舰船',
  'officialFleet.ships.empty.body': '请调整服务端搜索条件或共享状态筛选。',
  'officialFleet.ships.size.capital': '旗舰级',
  'officialFleet.ships.size.large': '大型',
  'officialFleet.ships.size.medium': '中型',
  'officialFleet.ships.size.small': '小型',
  'officialFleet.ships.size.unknown': '待分类',
  'officialFleet.ships.catalog.flightReady': '可飞',
  'officialFleet.ships.catalog.concept': '概念',
  'officialFleet.ships.catalog.unknown': '状态未知',
  'officialFleet.ships.request.requestable': '可请求',
  'officialFleet.ships.request.unavailable': '当前不可用',
  'officialFleet.ships.request.mine': '由我共享',
  'officialFleet.ships.previousPage': '上一页',
  'officialFleet.ships.nextPage': '下一页',
  'officialFleet.ships.pageStatus': '第 {page} / {total} 页',
  'officialFleet.ships.pageNumber': '页码',
  'officialFleet.ships.jump': '跳转',
};

const traditionalOfficialFleetStrings = <String, String>{
  'officialFleet.members.metric.matches': '符合條件的成員',
  'officialFleet.members.coverage.unknown': '名單涵蓋範圍尚未確認。',
  'officialFleet.members.coverage.completeOfficialRoster':
      '名單來源：完整 RSI 官網成員目錄。',
  'officialFleet.members.coverage.scmRegisteredMembers':
      '僅顯示已註冊 SCM 的成員，不代表完整官網名單。',
  'officialFleet.members.coverage.partial': '目前僅取得部分名單。',
  'officialFleet.members.coverage.restricted': '僅顯示你有權查看的成員。',
  'officialFleet.members.presence.unknown': '狀態未知',
  'officialFleet.members.presence.away': '暫離',
  'officialFleet.members.connection.connected': '已接入 StarBridge',
  'officialFleet.members.connection.unknown': '應用接入狀態尚未確認',
  'officialFleet.members.details.title': '成員詳情',
  'officialFleet.members.details.back': '返回成員列表',
  'officialFleet.loading': '正在讀取 RSI 官網艦隊歸屬…',
  'officialFleet.signedOut.title': '登入後查看官網艦隊',
  'officialFleet.signedOut.body':
      '連接 SCM 帳號後，StarBridge 才能透過 SCM 同步你的唯一 RSI 官網艦隊歸屬。',
  'officialFleet.notMember.title': '尚未加入 RSI 官網艦隊',
  'officialFleet.notMember.body':
      '暫未讀取到 RSI 官網艦隊歸屬。加入或更改官網艦隊需要在 RSI 官網完成，返回後可在此重新整理。',
  'officialFleet.unavailable.title': '暫時無法讀取官網艦隊',
  'officialFleet.action.retry': '重新讀取',
  'officialFleet.action.refresh': '重新整理艦隊資料',
  'officialFleet.error.hostUnavailable': 'Native Host 未連接。恢復連接後可重新讀取。',
  'officialFleet.error.scmUnavailable': 'SCM 暫時不可用，已保留本機登入狀態。',
  'officialFleet.error.reauthorizationRequired': 'SCM 授權已失效，請先在帳號與識別中重新授權。',
  'officialFleet.error.invalidResponse': 'SCM 返回的艦隊資料不符合目前客戶端合約。',
  'officialFleet.error.unavailable': 'SCM 艦隊資料目前不可用，請稍後重試。',
  'officialFleet.rank.unknown': '官方職位未提供',
  'officialFleet.rank.scale': 'RSI 官方星級',
  'officialFleet.myOfficialPosition': '我的官網職位',
  'officialFleet.fresh.live': 'SCM 最新',
  'officialFleet.source': '艦隊歸屬：RSI 官網 · 資料同步：SCM',
  'officialFleet.resourceVersion': '艦隊資源版本',
  'officialFleet.tab.overview': '概覽',
  'officialFleet.tab.operations': '行動',
  'officialFleet.tab.members': '成員',
  'officialFleet.tab.channel': '頻道',
  'officialFleet.tab.ships': '艦船',
  'officialFleet.tab.broadcasts': '廣播',
  'officialFleet.tab.profile': '資料',
  'officialFleet.overview.title': '主艦隊工作區',
  'officialFleet.overview.body': '查看目前公告、主艦隊快照和必須由你處理的事項。',
  'officialFleet.overview.loading': '正在讀取主艦隊協作概覽…',
  'officialFleet.overview.unavailable.title': '協作概覽暫時不可用',
  'officialFleet.overview.error.contractUnavailable':
      'StarBridge 公告、Presence、共享艦船和待處理合約尚未接入。目前不會用範例資料替代真實艦隊資訊。',
  'officialFleet.overview.error.unavailable': '讀取協作概覽失敗，請稍後重試。',
  'officialFleet.overview.retry': '重新讀取概覽',
  'officialFleet.overview.announcement.title': '目前公告',
  'officialFleet.overview.announcement.unread': '未讀',
  'officialFleet.overview.announcement.none': '主艦隊目前沒有公告。',
  'officialFleet.overview.announcement.body':
      'StarBridge 公告服務尚未接入。這裡不會用範例公告替代真實艦隊資訊。',
  'officialFleet.overview.snapshot.title': '主艦隊快照',
  'officialFleet.overview.snapshot.updated': '最近更新 {time}',
  'officialFleet.overview.metric.members': '官網成員',
  'officialFleet.overview.metric.online': '可見在線',
  'officialFleet.overview.metric.inGame': '遊戲中',
  'officialFleet.overview.metric.ships': '可請求艦船',
  'officialFleet.overview.tasks.title': '需要處理',
  'officialFleet.overview.tasks.body': '這裡只出現必須由你明確決定或完成的事項，最多顯示 3 項。',
  'officialFleet.overview.tasks.empty': '目前沒有需要你處理的事項。',
  'officialFleet.overview.tasks.due': '截止 {time}',
  'officialFleet.overview.operations.title': '行動入口',
  'officialFleet.overview.operations.body': '行動將保留目前官網艦隊來源；完整流程將在行動專項中接入。',
  'officialFleet.overview.operations.open': '開啟行動入口',
  'officialFleet.overview.data.title': '協作資料接入狀態',
  'officialFleet.overview.data.body': '艦隊歸屬、官網成員與官方職位屬於 RSI 官網事實，由 SCM 同步；公告、Presence、主頻道、共享艦船與待處理事項來自 StarBridge 服務。未接入欄位保持未知。',
  'officialFleet.data.identity': 'RSI 艦隊歸屬',
  'officialFleet.data.identity.ready': '已同步',
  'officialFleet.data.announcement': '公告與待處理',
  'officialFleet.data.members': '成員目錄與 Presence',
  'officialFleet.data.channel': '唯一內部主頻道',
  'officialFleet.data.ships': '成員共享艦船',
  'officialFleet.data.pending': '等待資料介面',
  'officialFleet.data.pending.starBridge': '等待 StarBridge 服務',
  'officialFleet.data.pending.hybrid': '等待 SCM + StarBridge 服務',
  'officialFleet.section.operations.title': '艦隊行動將在後續專項接入',
  'officialFleet.section.operations.body':
      '此入口已經綁定目前官網艦隊，但不會在流程尚未確認時虛構行動、席位或權限。',
  'officialFleet.section.members.title': '成員目錄尚未接入',
  'officialFleet.section.members.body': '正式目錄將支援上千成員的服務端分頁，並保留 WPF 成員橫幅中的有效資訊。',
  'officialFleet.members.title': '成員目錄',
  'officialFleet.members.body': '查看目前可用的艦隊成員資料；在線狀態和遊戲資訊依共享權限顯示。',
  'officialFleet.members.loading': '正在讀取目前頁面的成員…',
  'officialFleet.members.unavailable.title': '成員目錄暫時不可用',
  'officialFleet.members.error.contractUnavailable':
      'SCM 成員名單與 StarBridge Presence 合約尚未接入。目前不會用範例成員替代真實名單。',
  'officialFleet.members.error.unavailable': '讀取成員目錄失敗，請稍後重試。',
  'officialFleet.members.metric.total': '成員',
  'officialFleet.members.metric.online': '在線',
  'officialFleet.members.metric.inGame': '遊戲中',
  'officialFleet.members.search': '搜尋呼號、遊戲 ID 或官網職位',
  'officialFleet.members.search.submit': '搜尋成員',
  'officialFleet.members.pageSize': '每頁',
  'officialFleet.members.filter.all': '全部成員',
  'officialFleet.members.filter.online': '在線',
  'officialFleet.members.filter.inGame': '遊戲中',
  'officialFleet.members.empty.title': '沒有符合的成員',
  'officialFleet.members.empty.body': '目前可用名單中沒有符合條件的結果，可嘗試調整搜尋或篩選條件。',
  'officialFleet.members.column.member': '成員',
  'officialFleet.members.column.server': '伺服器',
  'officialFleet.members.column.rank': 'RSI 官網職位',
  'officialFleet.members.column.ship': '艦船',
  'officialFleet.members.column.location': '位置',
  'officialFleet.members.column.presence': '狀態',
  'officialFleet.members.field.unknown': '未知',
  'officialFleet.members.field.notShared': '未共享',
  'officialFleet.members.field.notInGame': '未進入遊戲',
  'officialFleet.members.field.restricted': '目前不可見',
  'officialFleet.members.field.notConnected': '尚未接入 StarBridge',
  'officialFleet.members.presence.notConnected': '尚未接入',
  'officialFleet.members.presence.offline': '離線',
  'officialFleet.members.presence.online': '在線',
  'officialFleet.members.presence.inGame': '遊戲中',
  'officialFleet.members.presence.invisible': '隱身',
  'officialFleet.members.arrivalPending': '待確認',
  'officialFleet.members.previousPage': '上一頁',
  'officialFleet.members.nextPage': '下一頁',
  'officialFleet.members.pageStatus': '第 {page} / {total} 頁',
  'officialFleet.members.pageNumber': '頁碼',
  'officialFleet.members.jump': '跳轉',
  'officialFleet.section.channel.title': '內部主頻道尚未接入',
  'officialFleet.section.channel.body':
      '每個官網艦隊只有一個 StarBridge 持久主頻道，不擴展成多頻道社交系統。',
  'officialFleet.section.ships.title': '艦隊共享艦船尚未接入',
  'officialFleet.section.ships.body': '這裡將展示成員授權共享且目前可請求的艦船，並服從行動佔用與隱私規則。',
  'officialFleet.section.broadcasts.title': '艦隊廣播尚未接入',
  'officialFleet.section.broadcasts.body': '緊急廣播將保留獨立歷史和遊戲內強提示，不與公告或普通通知混合。',
  'officialFleet.profile.title': '官網艦隊資料',
  'officialFleet.profile.body': '目前只展示 SCM 已提供並經過 Native Host 校驗的欄位。',
  'officialFleet.profile.memberCount': '{count} 名官網成員',
  'officialFleet.profile.unavailable.title': '詳細艦隊資料尚未接入',
  'officialFleet.profile.unavailable.body':
      '目前只確認了你的 RSI 艦隊歸屬與官方職位。簡介、關注方向、語言和招募狀態將在 SCM 資料合約接入後顯示。',
  'officialFleet.profile.about': '艦隊介紹',
  'officialFleet.profile.rsiDescription': 'RSI 官網公開簡介',
  'officialFleet.profile.scmDescription': 'SCM 補充介紹',
  'officialFleet.profile.noDescription': '該艦隊暫未提供公開介紹。',
  'officialFleet.profile.focus': '關注方向與特色',
  'officialFleet.profile.primaryFocus': '主要方向',
  'officialFleet.profile.secondaryFocus': '次要方向',
  'officialFleet.profile.focusUnavailable': '該艦隊暫未提供關注方向。',
  'officialFleet.profile.tags': '艦隊標籤',
  'officialFleet.profile.attributes': '組織屬性',
  'officialFleet.profile.languages': '語言',
  'officialFleet.profile.model': '組織模式',
  'officialFleet.profile.commitment': '投入程度',
  'officialFleet.profile.roleplay': '角色扮演',
  'officialFleet.profile.archetype': '組織類型',
  'officialFleet.profile.myIdentity': '我在艦隊中的身份',
  'officialFleet.profile.starBridgeRole': 'StarBridge 角色',
  'officialFleet.profile.syncSource': '資料來源與同步',
  'officialFleet.profile.observedAt': '最近確認',
  'officialFleet.profile.name': '艦隊名稱',
  'officialFleet.profile.sid': '艦隊 SID',
  'officialFleet.profile.rank': '我的官方職位',
  'officialFleet.profile.sourceRef': '穩定來源標識',
  'officialFleet.ships.title': '主艦隊艦船庫',
  'officialFleet.ships.body': '只展示成員明確共享給目前主艦隊的艦船；可請求不代表管理者可以直接調度。',
  'officialFleet.ships.loading': '正在讀取共享艦船…',
  'officialFleet.ships.unavailable.title': '共享艦船暫時不可用',
  'officialFleet.ships.error.contractUnavailable':
      'StarBridge 艦船共享合約尚未接入。目前不會讀取完整個人機庫，也不會用範例艦船替代真實共享記錄。',
  'officialFleet.ships.error.unavailable': '讀取共享艦船失敗，請稍後重試。',
  'officialFleet.ships.metric.total': '共享艦船',
  'officialFleet.ships.metric.requestable': '目前可請求',
  'officialFleet.ships.metric.owners': '共享成員',
  'officialFleet.ships.metric.value': '艦船總價值',
  'officialFleet.ships.distribution.title': '艦級構成',
  'officialFleet.ships.search': '搜尋艦船、型號、角色或共享成員',
  'officialFleet.ships.search.submit': '搜尋艦船',
  'officialFleet.ships.pageSize': '每頁',
  'officialFleet.ships.filter.all': '全部共享',
  'officialFleet.ships.filter.requestable': '可請求',
  'officialFleet.ships.filter.mine': '我共享的',
  'officialFleet.ships.empty.title': '沒有符合的共享艦船',
  'officialFleet.ships.empty.body': '請調整伺服器搜尋條件或共享狀態篩選。',
  'officialFleet.ships.size.capital': '旗艦級',
  'officialFleet.ships.size.large': '大型',
  'officialFleet.ships.size.medium': '中型',
  'officialFleet.ships.size.small': '小型',
  'officialFleet.ships.size.unknown': '待分類',
  'officialFleet.ships.catalog.flightReady': '可飛',
  'officialFleet.ships.catalog.concept': '概念',
  'officialFleet.ships.catalog.unknown': '狀態未知',
  'officialFleet.ships.request.requestable': '可請求',
  'officialFleet.ships.request.unavailable': '目前不可用',
  'officialFleet.ships.request.mine': '由我共享',
  'officialFleet.ships.previousPage': '上一頁',
  'officialFleet.ships.nextPage': '下一頁',
  'officialFleet.ships.pageStatus': '第 {page} / {total} 頁',
  'officialFleet.ships.pageNumber': '頁碼',
  'officialFleet.ships.jump': '跳轉',
};

const englishOfficialFleetStrings = <String, String>{
  'officialFleet.members.metric.matches': 'Matching members',
  'officialFleet.members.coverage.unknown':
      'Roster coverage has not been confirmed.',
  'officialFleet.members.coverage.completeOfficialRoster':
      'Roster source: complete RSI organization directory.',
  'officialFleet.members.coverage.scmRegisteredMembers':
      'Only SCM-registered members are included, not the full RSI roster.',
  'officialFleet.members.coverage.partial':
      'Only part of the roster is available.',
  'officialFleet.members.coverage.restricted':
      'Only members you are allowed to view are included.',
  'officialFleet.members.presence.unknown': 'Status unknown',
  'officialFleet.members.presence.away': 'Away',
  'officialFleet.members.connection.connected': 'Connected to StarBridge',
  'officialFleet.members.connection.unknown':
      'Application enrollment has not been confirmed',
  'officialFleet.members.details.title': 'Member details',
  'officialFleet.members.details.back': 'Back to members',
  'officialFleet.loading': 'Reading your RSI organization membership…',
  'officialFleet.signedOut.title': 'Sign in to view your official fleet',
  'officialFleet.signedOut.body': 'Connect your SCM account so StarBridge can sync your single RSI organization membership through SCM.',
  'officialFleet.notMember.title': 'No RSI organization membership',
  'officialFleet.notMember.body': 'No RSI organization membership is currently available. Join or change it on the RSI website, then refresh here.',
  'officialFleet.unavailable.title':
      'Official fleet is temporarily unavailable',
  'officialFleet.action.retry': 'Read again',
  'officialFleet.action.refresh': 'Refresh fleet data',
  'officialFleet.error.hostUnavailable':
      'Native Host is disconnected. Read again after it reconnects.',
  'officialFleet.error.scmUnavailable':
      'SCM is temporarily unavailable. Your local sign-in state was preserved.',
  'officialFleet.error.reauthorizationRequired': 'SCM authorization has expired. Reauthorize under Account and identity first.',
  'officialFleet.error.invalidResponse':
      'SCM returned fleet data that does not match this client contract.',
  'officialFleet.error.unavailable':
      'SCM fleet data is currently unavailable. Try again later.',
  'officialFleet.rank.unknown': 'Official rank not provided',
  'officialFleet.rank.scale': 'Official RSI rank',
  'officialFleet.myOfficialPosition': 'My official position',
  'officialFleet.fresh.live': 'Latest from SCM',
  'officialFleet.source': 'Membership authority: RSI · Synced by SCM',
  'officialFleet.resourceVersion': 'Fleet resource version',
  'officialFleet.tab.overview': 'Overview',
  'officialFleet.tab.operations': 'Operations',
  'officialFleet.tab.members': 'Members',
  'officialFleet.tab.channel': 'Channel',
  'officialFleet.tab.ships': 'Ships',
  'officialFleet.tab.broadcasts': 'Broadcasts',
  'officialFleet.tab.profile': 'Profile',
  'officialFleet.overview.title': 'Main fleet workspace',
  'officialFleet.overview.body': 'Review the current announcement, main-fleet snapshot, and decisions that need you.',
  'officialFleet.overview.loading':
      'Loading the main-fleet collaboration overview…',
  'officialFleet.overview.unavailable.title':
      'Collaboration overview unavailable',
  'officialFleet.overview.error.contractUnavailable': 'StarBridge announcements, Presence, shared ships, and required-action contracts are not connected yet. Sample facts never replace live fleet data.',
  'officialFleet.overview.error.unavailable':
      'The collaboration overview could not be loaded. Try again later.',
  'officialFleet.overview.retry': 'Reload overview',
  'officialFleet.overview.announcement.title': 'Current announcement',
  'officialFleet.overview.announcement.unread': 'Unread',
  'officialFleet.overview.announcement.none':
      'The main fleet has no current announcement.',
  'officialFleet.overview.announcement.body': 'The StarBridge announcement service is not connected yet. Sample text will not replace real fleet information.',
  'officialFleet.overview.snapshot.title': 'Main-fleet snapshot',
  'officialFleet.overview.snapshot.updated': 'Updated {time}',
  'officialFleet.overview.metric.members': 'RSI members',
  'officialFleet.overview.metric.online': 'Visible online',
  'officialFleet.overview.metric.inGame': 'In game',
  'officialFleet.overview.metric.ships': 'Requestable ships',
  'officialFleet.overview.tasks.title': 'Needs your attention',
  'officialFleet.overview.tasks.body': 'Only explicit decisions or required actions appear here, up to three at a time.',
  'officialFleet.overview.tasks.empty':
      'Nothing currently needs your attention.',
  'officialFleet.overview.tasks.due': 'Due {time}',
  'officialFleet.overview.operations.title': 'Operations entry',
  'officialFleet.overview.operations.body': 'Operations will preserve this official fleet source. The complete flow belongs to the operations phase.',
  'officialFleet.overview.operations.open': 'Open operations entry',
  'officialFleet.overview.data.title': 'Collaboration data status',
  'officialFleet.overview.data.body': 'Fleet membership, official members, and official ranks are RSI facts synchronized by SCM. Announcements, presence, the main channel, shared ships, and tasks come from StarBridge services. Unconnected fields remain unknown.',
  'officialFleet.data.identity': 'RSI organization membership',
  'officialFleet.data.identity.ready': 'Synchronized',
  'officialFleet.data.announcement': 'Announcements and tasks',
  'officialFleet.data.members': 'Member directory and presence',
  'officialFleet.data.channel': 'Single internal main channel',
  'officialFleet.data.ships': 'Member-shared ships',
  'officialFleet.data.pending': 'Waiting for data interface',
  'officialFleet.data.pending.starBridge': 'Waiting for StarBridge service',
  'officialFleet.data.pending.hybrid': 'Waiting for SCM + StarBridge services',
  'officialFleet.section.operations.title':
      'Fleet operations will arrive in a dedicated phase',
  'officialFleet.section.operations.body': 'This entry is already bound to the current official fleet, but it will not invent operations, seats, or permissions before the flow is approved.',
  'officialFleet.section.members.title':
      'Member directory is not connected yet',
  'officialFleet.section.members.body': 'The production directory will use server-side pagination for thousands of members and preserve useful fields from the WPF member banner.',
  'officialFleet.members.title': 'Member directory',
  'officialFleet.members.body': 'View available fleet member details. Online status and game information follow sharing permissions.',
  'officialFleet.members.loading': 'Reading this member page…',
  'officialFleet.members.unavailable.title':
      'Member directory is temporarily unavailable',
  'officialFleet.members.error.contractUnavailable': 'The SCM roster and StarBridge presence contract is not connected yet. Sample members never replace the real roster.',
  'officialFleet.members.error.unavailable':
      'The member directory could not be read. Try again later.',
  'officialFleet.members.metric.total': 'members',
  'officialFleet.members.metric.online': 'online',
  'officialFleet.members.metric.inGame': 'in game',
  'officialFleet.members.search': 'Search callsign, game ID, or official rank',
  'officialFleet.members.search.submit': 'Search members',
  'officialFleet.members.pageSize': 'Per page',
  'officialFleet.members.filter.all': 'All members',
  'officialFleet.members.filter.online': 'Online',
  'officialFleet.members.filter.inGame': 'In game',
  'officialFleet.members.empty.title': 'No matching members',
  'officialFleet.members.empty.body': 'No matches in the available roster. Try adjusting your search or filters.',
  'officialFleet.members.column.member': 'Member',
  'officialFleet.members.column.server': 'Server',
  'officialFleet.members.column.rank': 'Official RSI rank',
  'officialFleet.members.column.ship': 'Ship',
  'officialFleet.members.column.location': 'Location',
  'officialFleet.members.column.presence': 'Status',
  'officialFleet.members.field.unknown': 'Unknown',
  'officialFleet.members.field.notShared': 'Not shared',
  'officialFleet.members.field.notInGame': 'Not in game',
  'officialFleet.members.field.restricted': 'Not visible here',
  'officialFleet.members.field.notConnected': 'Not connected to StarBridge',
  'officialFleet.members.presence.notConnected': 'Not connected',
  'officialFleet.members.presence.offline': 'Offline',
  'officialFleet.members.presence.online': 'Online',
  'officialFleet.members.presence.inGame': 'In game',
  'officialFleet.members.presence.invisible': 'Invisible',
  'officialFleet.members.arrivalPending': 'Pending',
  'officialFleet.members.previousPage': 'Previous',
  'officialFleet.members.nextPage': 'Next',
  'officialFleet.members.pageStatus': 'Page {page} / {total}',
  'officialFleet.members.pageNumber': 'Page',
  'officialFleet.members.jump': 'Go',
  'officialFleet.section.channel.title':
      'Internal main channel is not connected yet',
  'officialFleet.section.channel.body': 'Each official fleet has exactly one persistent StarBridge main channel, not a multi-channel social system.',
  'officialFleet.section.ships.title':
      'Fleet-shared ships are not connected yet',
  'officialFleet.section.ships.body': 'This area will show member-authorized ships that can currently be requested, subject to operation occupancy and privacy.',
  'officialFleet.section.broadcasts.title':
      'Fleet broadcasts are not connected yet',
  'officialFleet.section.broadcasts.body': 'Emergency broadcasts keep separate history and in-game high-attention delivery; they do not merge with announcements or notifications.',
  'officialFleet.profile.title': 'Official fleet profile',
  'officialFleet.profile.body': 'Only fields supplied by SCM and validated by Native Host are shown here.',
  'officialFleet.profile.memberCount': '{count} official members',
  'officialFleet.profile.unavailable.title':
      'Detailed fleet profile is not connected yet',
  'officialFleet.profile.unavailable.body': 'Only your RSI organization membership and official rank are confirmed. Description, focus, languages, and recruitment state will appear after the SCM profile contract is connected.',
  'officialFleet.profile.about': 'Fleet introduction',
  'officialFleet.profile.rsiDescription': 'Public RSI description',
  'officialFleet.profile.scmDescription': 'SCM supplemental introduction',
  'officialFleet.profile.noDescription':
      'This fleet has not supplied a public introduction.',
  'officialFleet.profile.focus': 'Focus and characteristics',
  'officialFleet.profile.primaryFocus': 'Primary focus',
  'officialFleet.profile.secondaryFocus': 'Secondary focus',
  'officialFleet.profile.focusUnavailable':
      'This fleet has not supplied focus information.',
  'officialFleet.profile.tags': 'Fleet tags',
  'officialFleet.profile.attributes': 'Organization attributes',
  'officialFleet.profile.languages': 'Languages',
  'officialFleet.profile.model': 'Organization model',
  'officialFleet.profile.commitment': 'Commitment',
  'officialFleet.profile.roleplay': 'Role play',
  'officialFleet.profile.archetype': 'Organization type',
  'officialFleet.profile.myIdentity': 'My fleet identity',
  'officialFleet.profile.starBridgeRole': 'StarBridge role',
  'officialFleet.profile.syncSource': 'Source and synchronization',
  'officialFleet.profile.observedAt': 'Last confirmed',
  'officialFleet.profile.name': 'Fleet name',
  'officialFleet.profile.sid': 'Fleet SID',
  'officialFleet.profile.rank': 'My official rank',
  'officialFleet.profile.sourceRef': 'Stable source reference',
  'officialFleet.ships.title': 'Main-fleet ship library',
  'officialFleet.ships.body': 'Only ships explicitly shared with this main fleet appear here. Requestable never means managers can dispatch a ship directly.',
  'officialFleet.ships.loading': 'Reading shared ships…',
  'officialFleet.ships.unavailable.title':
      'Shared ships are temporarily unavailable',
  'officialFleet.ships.error.contractUnavailable': 'The StarBridge ship-sharing contract is not connected yet. The client will not expose complete personal hangars or replace real records with sample ships.',
  'officialFleet.ships.error.unavailable':
      'Shared ships could not be loaded. Try again later.',
  'officialFleet.ships.metric.total': 'Shared ships',
  'officialFleet.ships.metric.requestable': 'Requestable now',
  'officialFleet.ships.metric.owners': 'Sharing members',
  'officialFleet.ships.metric.value': 'Total ship value',
  'officialFleet.ships.distribution.title': 'Ship-size composition',
  'officialFleet.ships.search': 'Search ship, model, role, or sharing member',
  'officialFleet.ships.search.submit': 'Search ships',
  'officialFleet.ships.pageSize': 'Per page',
  'officialFleet.ships.filter.all': 'All shared',
  'officialFleet.ships.filter.requestable': 'Requestable',
  'officialFleet.ships.filter.mine': 'Shared by me',
  'officialFleet.ships.empty.title': 'No matching shared ships',
  'officialFleet.ships.empty.body':
      'Adjust the server-side search or sharing-state filter.',
  'officialFleet.ships.size.capital': 'Capital',
  'officialFleet.ships.size.large': 'Large',
  'officialFleet.ships.size.medium': 'Medium',
  'officialFleet.ships.size.small': 'Small',
  'officialFleet.ships.size.unknown': 'Unclassified',
  'officialFleet.ships.catalog.flightReady': 'Flight ready',
  'officialFleet.ships.catalog.concept': 'Concept',
  'officialFleet.ships.catalog.unknown': 'Status unknown',
  'officialFleet.ships.request.requestable': 'Requestable',
  'officialFleet.ships.request.unavailable': 'Unavailable now',
  'officialFleet.ships.request.mine': 'Shared by me',
  'officialFleet.ships.previousPage': 'Previous',
  'officialFleet.ships.nextPage': 'Next',
  'officialFleet.ships.pageStatus': 'Page {page} / {total}',
  'officialFleet.ships.pageNumber': 'Page',
  'officialFleet.ships.jump': 'Go',
};
