const overlayScenesZhCn = <String, String>{
  'overlay.shareCard.kind': '浮层预设 · 布局示意',
  'overlay.shareCard.appearance': '外观',
  'overlay.shareCard.inspect': '查看详情并导入',
  'overlay.shareCard.previewUnavailable': '布局预览暂不可用，可查看详情后导入。',
  'overlay.source.chatTransferFallback':
      '原聊天来源均为组织，已移除这些绑定。导入后的聊天来源以上方显示为准，可在聊天设置中重新选择。',
  'overlay.source.selectChat': '选择聊天来源',
  'overlay.source.chatSelection': '已选 {count} / 8 个聊天来源',
  'overlay.source.chatHelp':
      '可同时显示房间和组织的消息，每条消息标明来源。所有浮层模块合计最多 8 个不同来源；同一来源只计一次。',
  'overlay.source.singleChat': '使用单一来源',
  'overlay.source.applyChat': '应用选择',
  'overlay.source.cancelChat': '取消',
  'overlay.source.organization': '组织',
  'overlay.source.chatMultiple': '多来源聊天',
  'overlay.source.changedAccount': '账号已更改，请关闭后重新选择。',
  'overlay.source.boundLabel': '由预设绑定：{source}',
  'overlay.source.temporaryLabel': '临时：{source}',
  'overlay.source.switchTemporarily': '临时切换到：{source}',
  'overlay.source.resumeBinding': '恢复预设绑定',
  'overlay.source.temporaryHint': '仅本次会话生效；切换预设或重启后恢复绑定。不改变共享范围。',
  'overlay.source.localName': '本地模式',
  'overlay.source.presetSettings': '预设设置',
  'overlay.source.autoSwitchRequiresBinding': '当前关闭。先将信息来源设为当前房间或具体组织，再开启自动切换。',
  'overlay.source.autoSwitch': '进入该来源时自动切换到此预设',
  'overlay.source.autoSwitchHelp': '离开来源后返回之前的预设。手动切换后，暂停自动切换，直到来源再次变化。',
  'overlay.source.replaceAutoSwitch': '将替换“{name}”的自动切换。它的其他设置保持不变。',
  'overlay.source.replace': '替换并保存',
  'overlay.source.save': '保存预设设置',
  'overlay.source.saveFailed': '未能保存预设设置。请检查名称是否重复，或关闭此面板后重试。',
  'overlay.source.followPreset': '跟随预设',
  'overlay.source.followAccount': '跟随账号选择',
  'overlay.source.displayOnly': '仅改变浮层显示，不改变共享范围。',
  'overlay.source.bindingUnavailable': '原组织绑定暂不可用，保留设置；预设将自动选择可用来源。',
  'overlay.source.moduleUnavailable': '原组织绑定暂不可用，保留设置；此模块暂不显示该组织的数据。',
  'overlay.source.limit': '来源超限，请调整来源',
  'overlay.source.adjust': '调整来源',
  'overlay.source.limitHelp':
      '同时最多使用 8 个不同来源。请减少聊天来源、将部分模块设为同一来源，或关闭不需要的模块。调整先应用于当前预览，保存后才会记住。',
  'overlay.source.done': '返回编辑器',
  'overlay.source.standby': '已记住信息来源，开启浮层时加载资料。',
  'overlay.source.title': '信息来源',
  'overlay.source.auto': '自动',
  'overlay.source.room': '当前房间',
  'overlay.source.fleet': '主舰队（即将推出）',
  'overlay.source.missing': '所选组织暂不可用',
  'overlay.source.hint': '为当前账号记住选择。仅改变浮层显示，不改变共享范围。',
  'overlay.source.ready': '已连接',
  'overlay.source.loading': '正在获取所选来源的资料…',
  'overlay.source.unavailable': '信息来源暂不可用，会自动检查恢复。',
  'overlay.source.local': '没有可用房间或组织，使用本地模式。',
  'overlay.source.signedOut': '登录后可选择组织作为信息来源。',
  'overlay.source.saving': '正在记住选择…',
};
const overlayScenesZhTw = <String, String>{
  'overlay.shareCard.kind': '浮層預設 · 配置示意',
  'overlay.shareCard.appearance': '外觀',
  'overlay.shareCard.inspect': '查看詳情並匯入',
  'overlay.shareCard.previewUnavailable': '配置預覽暫不可用，可查看詳情後匯入。',
  'overlay.source.chatTransferFallback':
      '原聊天來源均為組織，已移除這些綁定。匯入後的聊天來源以上方顯示為準，可在聊天設定中重新選擇。',
  'overlay.source.selectChat': '選擇聊天來源',
  'overlay.source.chatSelection': '已選 {count} / 8 個聊天來源',
  'overlay.source.chatHelp':
      '可同時顯示房間和組織的訊息，每條訊息標明來源。所有浮層模組合計最多 8 個不同來源；同一來源只計一次。',
  'overlay.source.singleChat': '使用單一來源',
  'overlay.source.applyChat': '套用選擇',
  'overlay.source.cancelChat': '取消',
  'overlay.source.organization': '組織',
  'overlay.source.chatMultiple': '多來源聊天',
  'overlay.source.changedAccount': '帳號已變更，請關閉後重新選擇。',
  'overlay.source.boundLabel': '由預設綁定：{source}',
  'overlay.source.temporaryLabel': '暫時：{source}',
  'overlay.source.switchTemporarily': '暫時切換至：{source}',
  'overlay.source.resumeBinding': '恢復預設綁定',
  'overlay.source.temporaryHint': '僅本次工作階段生效；切換預設或重新啟動後恢復綁定。不改變共享範圍。',
  'overlay.source.localName': '本機模式',
  'overlay.source.presetSettings': '預設設定',
  'overlay.source.autoSwitchRequiresBinding': '目前關閉。先將資訊來源設為目前房間或指定組織，再開啟自動切換。',
  'overlay.source.autoSwitch': '進入此來源時自動切換到此預設',
  'overlay.source.autoSwitchHelp': '離開來源後返回之前的預設。手動切換後，暫停自動切換，直到來源再次變更。',
  'overlay.source.replaceAutoSwitch': '將取代「{name}」的自動切換。它的其他設定保持不變。',
  'overlay.source.replace': '取代並儲存',
  'overlay.source.save': '儲存預設設定',
  'overlay.source.saveFailed': '未能儲存預設設定。請檢查名稱是否重複，或關閉此面板後重試。',
  'overlay.source.followPreset': '跟隨預設',
  'overlay.source.followAccount': '跟隨帳號選擇',
  'overlay.source.displayOnly': '僅改變浮層顯示，不改變共享範圍。',
  'overlay.source.bindingUnavailable': '原組織綁定暫不可用，保留設定；預設將自動選擇可用來源。',
  'overlay.source.moduleUnavailable': '原組織綁定暫不可用，保留設定；此模組暫不顯示該組織的資料。',
  'overlay.source.limit': '來源超限，請調整來源',
  'overlay.source.adjust': '調整來源',
  'overlay.source.limitHelp':
      '同時最多使用 8 個不同來源。請減少聊天來源、將部分模組設為同一來源，或關閉不需要的模組。調整先套用於目前預覽，儲存後才會記住。',
  'overlay.source.done': '返回編輯器',
  'overlay.source.standby': '已記住資訊來源，開啟浮層時載入資料。',
  'overlay.source.title': '資訊來源',
  'overlay.source.auto': '自動',
  'overlay.source.room': '目前房間',
  'overlay.source.fleet': '主艦隊（即將推出）',
  'overlay.source.missing': '所選組織暫不可用',
  'overlay.source.hint': '為目前帳號記住選擇。僅改變浮層顯示，不改變共享範圍。',
  'overlay.source.ready': '已連接',
  'overlay.source.loading': '正在取得所選來源的資料…',
  'overlay.source.unavailable': '資訊來源暫不可用，會自動檢查恢復。',
  'overlay.source.local': '沒有可用房間或組織，使用本地模式。',
  'overlay.source.signedOut': '登入後可選擇組織作為資訊來源。',
  'overlay.source.saving': '正在記住選擇…',
};
const overlayScenesEn = <String, String>{
  'overlay.shareCard.kind': 'Overlay preset · Sample layout',
  'overlay.shareCard.appearance': 'Appearance',
  'overlay.shareCard.inspect': 'View details and import',
  'overlay.shareCard.previewUnavailable': 'Layout preview unavailable. View details before importing.',
  'overlay.source.chatTransferFallback': 'All original chat sources were organizations; those bindings were removed. The imported chat source is shown above. You can choose sources again in chat settings.',
  'overlay.source.selectChat': 'Choose chat sources',
  'overlay.source.chatSelection': '{count} / 8 chat sources selected',
  'overlay.source.chatHelp': 'Show room and organization messages together, with a source label on each message. All overlay modules share a limit of 8 distinct sources; each source counts once.',
  'overlay.source.singleChat': 'Use a single source',
  'overlay.source.applyChat': 'Apply selection',
  'overlay.source.cancelChat': 'Cancel',
  'overlay.source.organization': 'Organization',
  'overlay.source.chatMultiple': 'Multiple chat sources',
  'overlay.source.changedAccount':
      'The account changed. Close this dialog and select again.',
  'overlay.source.boundLabel': 'Preset binding: {source}',
  'overlay.source.temporaryLabel': 'Temporary: {source}',
  'overlay.source.switchTemporarily': 'Switch temporarily to: {source}',
  'overlay.source.resumeBinding': 'Restore preset binding',
  'overlay.source.temporaryHint': 'For this session only. Switching presets or restarting restores the binding. Sharing permissions stay unchanged.',
  'overlay.source.localName': 'Local mode',
  'overlay.source.presetSettings': 'Preset settings',
  'overlay.source.autoSwitchRequiresBinding': 'Off. Select the current room or a specific organization as the source to enable automatic switching.',
  'overlay.source.autoSwitch':
      'Switch to this preset when entering this source',
  'overlay.source.autoSwitchHelp': 'Return to the previous preset when leaving. A manual preset change pauses automatic switching until the source changes again.',
  'overlay.source.replaceAutoSwitch': 'This replaces automatic switching for “{name}”. Its other settings stay unchanged.',
  'overlay.source.replace': 'Replace and save',
  'overlay.source.save': 'Save preset settings',
  'overlay.source.saveFailed': 'Could not save preset settings. Check for a duplicate name, or close this panel and try again.',
  'overlay.source.followPreset': 'Follow preset',
  'overlay.source.followAccount': 'Follow account choice',
  'overlay.source.displayOnly':
      'Changes the overlay only, not your sharing permissions.',
  'overlay.source.bindingUnavailable': 'The saved organization is unavailable. The binding is kept; this preset uses an available source automatically.',
  'overlay.source.moduleUnavailable': 'The saved organization is unavailable. The binding is kept; this module cannot display its data yet.',
  'overlay.source.limit': 'Too many sources. Adjust your sources.',
  'overlay.source.adjust': 'Adjust sources',
  'overlay.source.limitHelp': 'Use up to 8 distinct sources at once. Select fewer chat sources, give some modules the same source, or turn off modules you do not need. Changes apply to the current preview; save to keep them.',
  'overlay.source.done': 'Back to editor',
  'overlay.source.standby':
      'Info source saved. Data loads when the overlay opens.',
  'overlay.source.title': 'Info source',
  'overlay.source.auto': 'Automatic',
  'overlay.source.room': 'Current room',
  'overlay.source.fleet': 'Main fleet (coming soon)',
  'overlay.source.missing': 'Selected organization unavailable',
  'overlay.source.hint': 'Remembered for this account. Changes overlay display, not sharing permissions.',
  'overlay.source.ready': 'Connected',
  'overlay.source.loading': 'Loading data from the selected source…',
  'overlay.source.unavailable':
      'Info source unavailable. Recovery is checked automatically.',
  'overlay.source.local':
      'No available room or organization. Using local mode.',
  'overlay.source.signedOut':
      'Sign in to use an organization as the info source.',
  'overlay.source.saving': 'Saving selection…',
};
