const overlayPreviewZhCn = <String, String>{
  'overlay.editor.simulate': '模拟信息',
  'overlay.sample.communication': '通讯事件',
  'overlay.sample.roomCommunication': '房间通讯',
  'overlay.sample.notice': '已接入舰队频道，等待指挥同步',
  'overlay.sample.roomReady': '房间已就绪，等待队友加入',
  'overlay.sample.room': '房间概况',
  'overlay.sample.roomObjective': '当前目标：等待房主发布行动',
  'overlay.sample.online': '在线',
  'overlay.sample.inGame': '游戏中',
  'overlay.sample.sameShard': '与你同分线',
  'overlay.sample.usServer': '美服',
  'overlay.sample.peopleSuffix': ' 人',
  'overlay.sample.atLocation': '该地点',
  'overlay.sample.orison': '奥里森',
  'overlay.sample.self': '我',
  'overlay.sample.sender': '发送者',
  'overlay.sample.appOnline': '应用在线',
  'overlay.sample.offline': '离线',
  'overlay.sample.notInGame': '未进入游戏',
  'overlay.sample.locationLabel': '地点',
  'overlay.sample.shipLabel': '飞船',
  'overlay.sample.communicationMessage': '通讯消息',
  'overlay.sample.chat1': '准备完成，正在前往集合点。',
  'overlay.sample.chat2': '收到，进入服务器后同步服务器信息。',
  'overlay.sample.barrage1': '这是聊天弹幕',
  'overlay.sample.barrage2': '弹幕会从右向左移动',
  'overlay.sample.barrage3': '这里用于预览密度和位置',
  'overlay.sample.memberOnline': '成员上线',
  'overlay.sample.memberEnteredGame': '成员已进入游戏',
};

const overlayPreviewZhTw = <String, String>{
  'overlay.editor.simulate': '模擬資訊',
  'overlay.sample.communication': '通訊事件',
  'overlay.sample.roomCommunication': '房間通訊',
  'overlay.sample.notice': '已接入艦隊頻道，等待指揮同步',
  'overlay.sample.roomReady': '房間已就緒，等待隊友加入',
  'overlay.sample.room': '房間概況',
  'overlay.sample.roomObjective': '目前目標：等待房主發佈行動',
  'overlay.sample.online': '線上',
  'overlay.sample.inGame': '遊戲中',
  'overlay.sample.sameShard': '與你同分線',
  'overlay.sample.usServer': '美服',
  'overlay.sample.peopleSuffix': ' 人',
  'overlay.sample.atLocation': '該地點',
  'overlay.sample.orison': '奧里森',
  'overlay.sample.self': '我',
  'overlay.sample.sender': '發送者',
  'overlay.sample.appOnline': '應用線上',
  'overlay.sample.offline': '離線',
  'overlay.sample.notInGame': '未進入遊戲',
  'overlay.sample.locationLabel': '地點',
  'overlay.sample.shipLabel': '飛船',
  'overlay.sample.communicationMessage': '通訊訊息',
  'overlay.sample.chat1': '準備完成，正在前往集合點。',
  'overlay.sample.chat2': '收到，進入伺服器後同步伺服器資訊。',
  'overlay.sample.barrage1': '這是聊天彈幕',
  'overlay.sample.barrage2': '彈幕會從右向左移動',
  'overlay.sample.barrage3': '這裡用於預覽密度和位置',
  'overlay.sample.memberOnline': '成員上線',
  'overlay.sample.memberEnteredGame': '成員已進入遊戲',
};

const overlayPreviewEn = <String, String>{
  'overlay.editor.simulate': 'Simulated information',
  'overlay.sample.communication': 'COMMUNICATION EVENT',
  'overlay.sample.roomCommunication': 'PARTY COMMS',
  'overlay.sample.notice': 'Fleet channel connected. Awaiting command.',
  'overlay.sample.roomReady': 'Room ready. Waiting for teammates.',
  'overlay.sample.room': 'Party overview',
  'overlay.sample.roomObjective': 'Current objective: awaiting host action',
  'overlay.sample.online': 'Online',
  'overlay.sample.inGame': 'In game',
  'overlay.sample.sameShard': 'Same shard as you',
  'overlay.sample.usServer': 'US',
  'overlay.sample.peopleSuffix': '',
  'overlay.sample.atLocation': 'At location',
  'overlay.sample.orison': 'Orison',
  'overlay.sample.self': 'Me',
  'overlay.sample.sender': 'Sender',
  'overlay.sample.appOnline': 'App online',
  'overlay.sample.offline': 'Offline',
  'overlay.sample.notInGame': 'Not in game',
  'overlay.sample.locationLabel': 'Location',
  'overlay.sample.shipLabel': 'Ship',
  'overlay.sample.communicationMessage': 'Communication message',
  'overlay.sample.chat1': 'Ready and moving to the rendezvous.',
  'overlay.sample.chat2': 'Copy. Share server information after joining.',
  'overlay.sample.barrage1': 'This is a chat barrage preview',
  'overlay.sample.barrage2': 'Messages move from right to left',
  'overlay.sample.barrage3': 'Previewing density and placement',
  'overlay.sample.memberOnline': 'Member online',
  'overlay.sample.memberEnteredGame': 'A member entered the game',
};
