const overlayWorkspaceEn = <String, String>{
  'overlay.workspace.description': 'Set notices, members, events, chat, and the crosshair. Arrange the screen layout in the preview. Changes stay on this device.',
  'overlay.runtime.open': 'Information overlay is visible',
  'overlay.runtime.closed': 'Information overlay is closed',
  'overlay.runtime.failed': 'Information overlay could not open',
  'overlay.runtime.unavailable': 'Information overlay is currently unavailable',
  'overlay.runtime.checking': 'Checking the information overlay…',
  'overlay.runtime.opening': 'Opening the information overlay…',
  'overlay.runtime.closing': 'Closing the information overlay…',
  'overlay.runtime.retrying': 'Retrying…',
  'overlay.runtime.openDescription': 'The overlay follows the Star Citizen window and lets mouse input pass through.',
  'overlay.runtime.closedDescription':
      'Open it here or use the shortcut you set.',
  'overlay.runtime.failedDescription': 'You can keep using the app. Try again; if it still will not open, check Diagnostics and maintenance.',
  'overlay.runtime.timeoutDescription':
      'Opening took too long and stopped safely. Try again.',
  'overlay.runtime.permissionDescription': 'Windows did not allow the overlay to appear. Check its permissions and try again.',
  'overlay.runtime.openAction': 'Open overlay',
  'overlay.runtime.saveAndOpenAction': 'Save and open overlay',
  'overlay.runtime.closeAction': 'Close overlay',
  'overlay.runtime.retryAction': 'Try again',
  'overlay.runtime.checkAction': 'Check again',
  'overlay.runtime.skinFallback': 'The selected appearance is unavailable, so Fleet Standard is being used.',
  'overlay.runtime.hotkey.registered': 'Shortcut: enabled',
  'overlay.runtime.hotkey.gameCompatibleOnly': 'Shortcut: available in game',
  'overlay.runtime.hotkey.desktopOnly': 'Shortcut: available on desktop',
  'overlay.runtime.hotkey.conflict': 'Shortcut: used by another app',
  'overlay.runtime.hotkey.invalid': 'Shortcut: needs to be set again',
  'overlay.runtime.hotkey.disabled': 'Shortcut: off',
  'overlay.runtime.hotkey.failed': 'Shortcut: temporarily unavailable',
  'overlay.runtime.hotkey.unavailable': 'Shortcut: waiting for check',
  'overlay.runtime.follow.followingGame': 'Follow game: active',
  'overlay.runtime.follow.gameInBackground':
      'Follow game: waiting for the game window',
  'overlay.runtime.follow.waitingForGame':
      'Follow game: waiting for the game to start',
  'overlay.runtime.follow.manual': 'Follow game: manual',
  'overlay.runtime.follow.unavailable': 'Follow game: waiting for check',
  'overlay.workspace.currentPreset': 'Current: {name}',
  'overlay.workspace.preset': 'Overlay preset',
  'overlay.workspace.quickPresets': 'Scene shortcuts',
  'overlay.workspace.quickPresetsHelp':
      'Each preset keeps its default scene. Select one to switch immediately.',
  'overlay.workspace.addPreset': 'Add preset',
  'overlay.workspace.addPresetDefault': 'Uses default settings',
  'overlay.workspace.newPresetName': 'New preset',
  'overlay.workspace.currentPresetName': 'Current preset name',
  'overlay.workspace.renamePresetHint':
      'Enter a name, then press Enter or save',
  'overlay.workspace.savePresetName': 'Save name',
  'overlay.workspace.appearance.current': 'Current appearance',
  'overlay.workspace.appearance.available': 'Available',
  'overlay.workspace.appearance.requiresQualification':
      'Qualification required',
  'overlay.workspace.appearance.unknown': 'Waiting for catalog',
  'overlay.workspace.appearance.back': 'Back to overlay settings',
  'overlay.workspace.appearance.centerTitle': 'Appearance center',
  'overlay.workspace.appearance.centerDescription': 'Browse overlay appearances and manage the visual style used by this preset.',
  'overlay.workspace.appearance.forPreset': 'Applies to current preset: {name}',
  'overlay.workspace.appearance.catalog': 'Overlay appearances',
  'overlay.workspace.appearance.catalogHelp': 'Browse real modules and motion. A preview does not mean an appearance is available to use.',
  'overlay.workspace.appearance.inUse': 'In use',
  'overlay.workspace.appearance.inDevelopment': 'In development',
  'overlay.workspace.appearance.previewOnly': 'Preview only',
  'overlay.workspace.appearance.palette': 'Color policy',
  'overlay.workspace.appearance.fixedPaletteShort': 'Fixed palette',
  'overlay.workspace.appearance.flexiblePalette': 'Adjustable theme color',
  'overlay.workspace.appearance.transition': 'Bound startup effect',
  'overlay.workspace.appearance.apply': 'Use this appearance',
  'overlay.workspace.appearance.normalAccountLocked':
      'Unavailable for this account',
  'overlay.workspace.appearance.notReleased': 'Not yet available to use',
  'overlay.workspace.appearance.previewUnavailable':
      'This appearance is still in development. Preview is unavailable.',
  'overlay.workspace.managePresets': 'Manage presets',
  'overlay.workspace.copy': 'Duplicate',
  'overlay.workspace.rename': 'Rename',
  'overlay.workspace.reset': 'Restore defaults',
  'overlay.workspace.delete': 'Delete',
  'overlay.workspace.import': 'Import',
  'overlay.workspace.export': 'Export',
  'overlay.workspace.presetName': 'Preset name',
  'overlay.workspace.copyTitle': 'Duplicate preset',
  'overlay.workspace.renameTitle': 'Rename preset',
  'overlay.workspace.importTitle': 'Import overlay preset',
  'overlay.workspace.importLabel': 'Paste preset content',
  'overlay.workspace.importHelp': 'The import creates a new preset and does not overwrite existing presets.',
  'overlay.workspace.importInvalid':
      'This preset could not be imported. Check its contents and try again.',
  'overlay.workspace.exported':
      'Preset copied. Paste it on another device to import it.',
  'overlay.workspace.confirmTitle': 'Confirm action',
  'overlay.workspace.switchConfirm':
      'Discard unsaved changes and switch presets?',
  'overlay.workspace.resetConfirm':
      'Restore the current preset settings and layout?',
  'overlay.workspace.deleteConfirm':
      'Delete the current preset? Other presets are not affected.',
  'overlay.workspace.cancel': 'Cancel',
  'overlay.workspace.confirm': 'Confirm',
  'overlay.workspace.continue': 'Continue',
  'overlay.workspace.dirty': 'You have unsaved changes',
  'overlay.workspace.saved': 'All changes are saved',
  'overlay.workspace.undo': 'Undo',
  'overlay.workspace.redo': 'Redo',
  'overlay.workspace.discard': 'Discard changes',
  'overlay.workspace.save': 'Save changes',
  'overlay.workspace.leave.title': 'Save overlay changes?',
  'overlay.workspace.leave.body': 'The current overlay preset has unsaved changes. Save before leaving, or discard them.',
  'overlay.workspace.leave.cancel': 'Keep editing',
  'overlay.workspace.colorHelp': 'Use a #RRGGBB color value',
  'overlay.workspace.appearanceBoundValue':
      'Automatically follows the active appearance',
  'overlay.workspace.fixedPalette': 'The active appearance uses a fixed palette. Its color scheme cannot be changed separately.',
  'overlay.workspace.experience.title': 'Motion experience',
  'overlay.workspace.experience.Smooth': 'Smooth',
  'overlay.workspace.experience.Balanced': 'Balanced',
  'overlay.workspace.experience.ReducedMotion': 'Reduced motion',
  'overlay.workspace.experience.Custom': 'Custom',
  'overlay.workspace.durationDefault': 'Use default',
  'overlay.workspace.durationSecondsSuffix': 'sec',
  'overlay.workspace.default': 'Default',
  'overlay.workspace.seconds': '{count} sec',
  'overlay.workspace.hotkey': 'Overlay shortcut',
  'overlay.workspace.hotkeyHelp': 'Use a modifier with a letter or number, or press F1–F12 alone. Esc cancels.',
  'overlay.workspace.hotkeyRecord': 'Set shortcut',
  'overlay.workspace.hotkeyReset': 'Restore default',
  'overlay.workspace.hotkeyCapturing': 'Press the new shortcut…',
  'overlay.workspace.hotkeyCaptureInvalid':
      'Use a modifier with a letter or number, or press F1–F12.',
  'overlay.workspace.hotkeyEnabled': 'Enable global shortcut',
  'overlay.workspace.hotkey.registered': 'Shortcut enabled',
  'overlay.workspace.hotkey.conflict': 'Another app is using this shortcut',
  'overlay.workspace.hotkey.invalid': 'Shortcut format is invalid',
  'overlay.workspace.hotkey.disabled': 'Shortcut disabled',
  'overlay.workspace.hotkey.pending':
      'Takes effect when the overlay runtime is available',
  'overlay.workspace.layout.locked': 'Position locked',
  'overlay.workspace.layout.lockPositionSize': 'Lock position and size',
  'overlay.workspace.layout.adjustable': 'Position and size can be adjusted',
  'overlay.workspace.layout.horizontalAnchor': 'Horizontal anchor',
  'overlay.workspace.layout.verticalAnchor': 'Vertical anchor',
  'overlay.workspace.layout.x': 'Horizontal position',
  'overlay.workspace.layout.y': 'Vertical position',
  'overlay.workspace.layout.width': 'Width',
  'overlay.workspace.layout.height': 'Height',
  'overlay.workspace.layout.textOpacity': 'Text opacity',
  'overlay.workspace.layout.backgroundOpacity': 'Background opacity',
  'overlay.workspace.layout.decorationOpacity': 'Appearance decoration opacity',
  'overlay.workspace.layout.grid': 'Grid snapping',
  'overlay.workspace.layout.gridOff': 'Off',
  'overlay.workspace.layout.smartSnap': 'Snap to edges and modules',
  'overlay.workspace.layout.nudgeStep': 'Nudge step',
  'overlay.workspace.layout.dragHelp': 'Drag a module to move it, or drag its lower-right corner to resize it. Lock it to prevent accidental changes.',
  'overlay.workspace.layout.lockedShort': 'Locked',
  'overlay.workspace.layout.hiddenShort': 'Hidden',
  'overlay.workspace.layout.left': 'Move left',
  'overlay.workspace.layout.right': 'Move right',
  'overlay.workspace.layout.up': 'Move up',
  'overlay.workspace.layout.down': 'Move down',
  'overlay.workspace.layout.narrower': 'Narrower',
  'overlay.workspace.layout.wider': 'Wider',
  'overlay.workspace.layout.shorter': 'Shorter',
  'overlay.workspace.layout.taller': 'Taller',
  'overlay.workspace.group.notice': 'Notice',
  'overlay.workspace.group.fleetOverview': 'Fleet overview',
  'overlay.workspace.group.members': 'Members',
  'overlay.workspace.group.appearance': 'Appearance settings',
  'overlay.workspace.group.crosshair': 'Crosshair',
  'overlay.workspace.group.startup': 'Startup and game behavior',
  'overlay.workspace.group.events': 'Event notifications',
  'overlay.workspace.group.chat': 'Chat',
  'overlay.workspace.group.layout': 'Screen layout',
  'overlay.workspace.module.Notice': 'Notice',
  'overlay.workspace.module.Squads': 'Fleet overview',
  'overlay.workspace.module.Members': 'Members',
  'overlay.workspace.module.Chat': 'Chat',
  'overlay.workspace.anchor.Left': 'Left',
  'overlay.workspace.anchor.Center': 'Center',
  'overlay.workspace.anchor.Right': 'Right',
  'overlay.workspace.anchor.Top': 'Top',
  'overlay.workspace.anchor.Middle': 'Middle',
  'overlay.workspace.anchor.Bottom': 'Bottom',
  'overlay.workspace.option.Default': 'Default',
  'overlay.workspace.option.Auto': 'Automatic',
  'overlay.workspace.option.Off': 'Off',
  'overlay.workspace.option.Standard': 'Standard',
  'overlay.workspace.option.Strong': 'Strong',
  'overlay.workspace.option.Light': 'Light',
  'overlay.workspace.option.Left': 'Left',
  'overlay.workspace.option.Right': 'Right',
  'overlay.workspace.option.Compact': 'Compact',
  'overlay.workspace.option.Detailed': 'Detailed',
  'overlay.workspace.option.Self': 'Self',
  'overlay.workspace.option.SquadCommander': 'Squad commander',
  'overlay.workspace.option.CurrentSquad': 'Current squad',
  'overlay.workspace.option.AllFleet': 'Entire fleet',
  'overlay.workspace.option.OtherSquads': 'Other squads',
  'overlay.workspace.option.Fleet': 'Fleet',
  'overlay.workspace.option.PartyRoom': 'Party room',
  'overlay.workspace.option.CallsignAndGameName': 'Callsign and game name',
  'overlay.workspace.option.CallsignOnly': 'Callsign only',
  'overlay.workspace.option.GameNameOnly': 'Game name only',
  'overlay.workspace.option.Cross': 'Cross',
  'overlay.workspace.option.Dot': 'Dot',
  'overlay.workspace.option.Circle': 'Circle',
  'overlay.workspace.option.TShape': 'T shape',
  'overlay.workspace.option.Slow': 'Slow',
  'overlay.workspace.option.Normal': 'Normal',
  'overlay.workspace.option.Fast': 'Fast',
  'overlay.workspace.option.MessageList': 'Message list',
  'overlay.workspace.option.FullScreenBarrage': 'Full-screen barrage',
  'overlay.workspace.option.Upper': 'Upper area',
  'overlay.workspace.option.UpperMiddle': 'Upper half',
  'overlay.workspace.option.FullScreen': 'Full screen',
  'overlay.workspace.option.Sparse': 'Sparse',
  'overlay.workspace.option.Dense': 'Dense',
  'overlay.workspace.option.BridgeTerminal': 'Bridge terminal',
  'overlay.workspace.option.NightShadowFlowField': 'Night Shadow flow field',
  'overlay.workspace.option.NightShadowSilentAssassination':
      'Night Shadow silent strike',
  'overlay.workspace.option.NightShadowBlackCurtainTear':
      'Night Shadow curtain tear',
  'overlay.workspace.option.NightShadowBladeCurtainUnfold':
      'Night Shadow blade curtain',
  'overlay.workspace.option.NightShadowCrimsonFold':
      'Night Shadow crimson fold',
  'overlay.workspace.option.LagrangeWeaveEquilibrium':
      'Lagrange Weave equilibrium',
  'overlay.workspace.option.VerdictProtocol': 'Verdict protocol',
  'overlay.workspace.option.NightShadow': 'Night Shadow',
  'overlay.workspace.option.LagrangeWeave': 'Lagrange Weave',
  'overlay.workspace.option.Verdict': 'Verdict',
  'overlay.workspace.option.eventNotificationMaxVisibleCount.1': '1 item',
  'overlay.workspace.option.eventNotificationMaxVisibleCount.2': '2 items',
  'overlay.workspace.option.eventNotificationMaxVisibleCount.3': '3 items',
  'overlay.workspace.option.eventNotificationMaxVisibleCount.4': '4 items',
  'overlay.workspace.option.eventNotificationMaxVisibleCount.5': '5 items',
  'overlay.workspace.option.chatDurationSeconds.6': 'Very fast',
  'overlay.workspace.option.chatDurationSeconds.8': 'Fast',
  'overlay.workspace.option.chatDurationSeconds.12': 'Standard',
  'overlay.workspace.option.chatDurationSeconds.16': 'Slow',
  'overlay.workspace.option.chatDurationSeconds.20': 'Very slow',
  'overlay.workspace.option.chatBarrageFontSize.14': 'Small',
  'overlay.workspace.option.chatBarrageFontSize.16': 'Standard',
  'overlay.workspace.option.chatBarrageFontSize.20': 'Large',
  'overlay.workspace.option.chatBarrageFontSize.24': 'Extra large',
  'overlay.workspace.event.1': 'Member online and offline',
  'overlay.workspace.event.2': 'Member server change',
  'overlay.workspace.event.4': 'Joined same server',
  'overlay.workspace.event.8': 'Ship change',
  'overlay.workspace.event.16': 'Location change',
  'overlay.workspace.event.128': 'Online member summary',
  'overlay.workspace.event.256': 'Primary server change',
  'overlay.workspace.event.512': 'Death and respawn',
  'overlay.workspace.event.1024': 'Local play reminder',
  'overlay.workspace.duration.memberPresence': 'Member online and offline',
  'overlay.workspace.duration.memberServer': 'Member server change',
  'overlay.workspace.duration.sameServer': 'Joined same server',
  'overlay.workspace.duration.shipChange': 'Ship change',
  'overlay.workspace.duration.locationChange': 'Location change',
  'overlay.workspace.duration.onlineSummary': 'Online member summary',
  'overlay.workspace.duration.primaryServer': 'Primary server change',
  'overlay.workspace.duration.deathAndRespawn': 'Death and respawn',
  'overlay.workspace.duration.localPlayReminder': 'Local play reminder',
  'overlay.workspace.field.memberNameMode': 'Member names',
  'overlay.workspace.field.hideOfflineMembers': 'Hide offline members',
  'overlay.workspace.field.hideSquadIcons': 'Hide squad icons',
  'overlay.workspace.field.enableTrayMode': 'Enable tray mode',
  'overlay.workspace.field.opacity': 'Overall overlay opacity',
  'overlay.workspace.field.showNotice': 'Show notice',
  'overlay.workspace.field.showSquads': 'Show fleet overview',
  'overlay.workspace.field.showMembers': 'Show members',
  'overlay.workspace.field.hideMemberOnlineStatus': 'Hide member online status',
  'overlay.workspace.field.squadStatusDisplayMode': 'Squad status display',
  'overlay.workspace.field.hideSelfMember':
      'Hide yourself from the member list',
  'overlay.workspace.field.memberPriorityMode': 'Member sorting priority',
  'overlay.workspace.field.memberScopeMode': 'Member display scope',
  'overlay.workspace.field.memberNameColumnRatio': 'Member name column width',
  'overlay.workspace.field.scenePreference': 'Default information scene',
  'overlay.workspace.field.skin': 'Interface skin',
  'overlay.workspace.field.theme': 'Theme color',
  'overlay.workspace.field.autoThemeByShip': 'Match theme to current ship',
  'overlay.workspace.field.nightShadowBloom': 'Bloom intensity',
  'overlay.workspace.field.animationFrameRate': 'Overlay animation frame rate',
  'overlay.workspace.field.requestedSkin': 'Preferred skin',
  'overlay.workspace.field.showCrosshair': 'Show crosshair',
  'overlay.workspace.field.crosshairMode': 'Crosshair style',
  'overlay.workspace.field.crosshairUseThemeColor':
      'Use theme color for crosshair',
  'overlay.workspace.field.crosshairColor': 'Crosshair color',
  'overlay.workspace.field.crosshairSize': 'Crosshair size',
  'overlay.workspace.field.crosshairThickness': 'Crosshair thickness',
  'overlay.workspace.field.crosshairOpacity': 'Crosshair opacity',
  'overlay.workspace.field.crosshairShowCenterMark':
      'Show crosshair center mark',
  'overlay.workspace.field.crosshairCenterMarkSize': 'Center mark size',
  'overlay.workspace.field.crosshairGap': 'Crosshair center gap',
  'overlay.workspace.field.crosshairOutlineOpacity':
      'Crosshair outline opacity',
  'overlay.workspace.field.enableStartupTransition':
      'Show overlay startup effect',
  'overlay.workspace.field.startupTransitionStyle': 'Startup effect style',
  'overlay.workspace.field.autoFocusGameWindowOnOpen':
      'Return to game after opening overlay',
  'overlay.workspace.field.startupTransitionFollowOverlayTheme':
      'Match startup effect to overlay theme',
  'overlay.workspace.field.startupTransitionFrameRate':
      'Startup effect frame rate',
  'overlay.workspace.field.autoOpenOverlayOnGameStart':
      'Open overlay when the game starts',
  'overlay.workspace.field.autoOpenOverlayOnGameForeground':
      'Open overlay when entering the game window',
  'overlay.workspace.field.autoCloseOverlayOnGameBackground':
      'Close overlay when leaving the game window',
  'overlay.workspace.field.skipStartupTransitionWhenGameForeground':
      'Skip startup effect when the game is already active',
  'overlay.workspace.field.showEventNotifications': 'Show event notifications',
  'overlay.workspace.field.eventNotificationSide': 'Notification side',
  'overlay.workspace.field.eventNotificationDurationSeconds':
      'Default notification duration',
  'overlay.workspace.field.eventNotificationY':
      'Notification vertical position',
  'overlay.workspace.field.eventNotificationTypes': 'Notification events',
  'overlay.workspace.field.eventNotificationMaxVisibleCount':
      'Visible notification limit',
  'overlay.workspace.field.eventNotificationPinImportant':
      'Keep important notifications visible',
  'overlay.workspace.field.eventNotificationAnimationSpeed':
      'Notification animation speed',
  'overlay.workspace.field.eventNotificationDurations':
      'Per-event notification duration',
  'overlay.workspace.field.eventNotificationTextOpacity':
      'Notification text opacity',
  'overlay.workspace.field.eventNotificationBackgroundOpacity':
      'Notification background opacity',
  'overlay.workspace.field.eventNotificationDecorationOpacity':
      'Notification appearance decoration opacity',
  'overlay.workspace.field.showChat': 'Show chat',
  'overlay.workspace.field.chatDisplayMode': 'Chat display mode',
  'overlay.workspace.field.chatSide': 'Chat side',
  'overlay.workspace.field.chatMaxVisibleCount': 'Visible message limit',
  'overlay.workspace.field.chatDurationSeconds': 'Message duration',
  'overlay.workspace.field.chatShowSender': 'Show sender',
  'overlay.workspace.field.chatShowTimestamp': 'Show sent time',
  'overlay.workspace.field.chatShowSystemMessages': 'Show system messages',
  'overlay.workspace.field.chatHideSelfMessages': 'Hide your own messages',
  'overlay.workspace.field.chatBarrageFontSize': 'Barrage font size',
  'overlay.workspace.field.chatBarrageRegion': 'Barrage region',
  'overlay.workspace.field.chatBarrageDensity': 'Barrage density',
  'overlay.workspace.field.chatBarrageAvoidCenter':
      'Keep barrage clear of screen center',
  'overlay.workspace.field.chatTextEdgeStrength': 'Chat text edge strength',
  'overlay.workspace.field.communicationFriendEvents': 'Show friend activity',
  'overlay.workspace.field.communicationMessagePreview':
      'Show message previews',
  'overlay.workspace.field.communicationEventDurationSeconds':
      'Communication alert duration',
  'overlay.workspace.field.fleetChatScope': 'Fleet chat scope',
};
