import 'overlay_workspace_strings.dart';
import 'overlay_preview_strings.dart';
import 'overlay_scene_strings.dart';

const overlaySettingsZhCn = <String, String>{
  'overlay.sections.info': '信息浮层',
  'overlay.sections.menu': '菜单浮层',
  'overlay.sections.menuUnavailable': '改造中，暂时无法使用',
  'overlay.menu.previewTitle': '新版菜单浮层 · 交互预览',
  'overlay.menu.previewBody': '预览好友、消息面板与底部工具栏。当前使用演示内容，不读取账号或发送消息，也不修改现有菜单与快捷键。',
  'overlay.menu.instructions': '拖动标题移动面板，拖动右下角调整大小。按 Esc 关闭并返回客户端。',
  'overlay.menu.open': '打开菜单浮层预览',
  'overlay.menu.live': '打开菜单浮层（功能验收）',
  'overlay.menu.liveBody': '使用当前账号和本机工具。各窗口可拖动、缩放并同时打开；阅读可见消息会标记已读。发送消息、好友和房间操作只在你点击后执行。',
  'overlay.menu.opening': '正在打开…',
  'overlay.menu.return': '返回客户端',
  'overlay.menu.failed': '未能显示菜单浮层，请重试。',
  ...overlayScenesZhCn,
  ...overlayWorkspaceZhCn,
  ...overlayPreviewZhCn,
  'overlay.editor.fullscreen': '全屏编辑',
  'overlay.editor.numberInvalid': '请输入不小于 0 的数字',
  'overlay.editor.resetPosition': '恢复模块默认位置与大小',
  'overlay.editor.exit': '退出全屏',
  'overlay.editor.showTools': '显示工具',
  'overlay.editor.hideTools': '收起工具',
  'overlay.editor.tools': '编辑工具 · 可拖动',
  'overlay.editor.opacityControls': '透明度 · 当前模块',
  'overlay.editor.showGrid': '显示网格',
  'overlay.editor.snapOff': '关闭网格吸附',
  'overlay.editor.lockAll': '锁定布局',
  'overlay.editor.selectModule': '选择模块',
  'overlay.editor.moduleLibrary': '显示模块 · 关闭后保留位置',
  'overlay.editor.keys': 'Esc 退出全屏 · Tab 收起工具 · 方向键微调 · Shift 加速 · Ctrl+S 保存',
  'overlay.editor.windowFailed': '无法切换编辑窗口，请重试。',
  'overlay.workspace.module.Crosshair': '准星',
  'overlay.workspace.module.Events': '事件提醒',
  'overlay.workspace.sections': '浮层系统',
  'overlay.preview.stageTitle': '实时构图',
  'overlay.preview.reference': '1920 × 1080 参考画布',
  'overlay.preview.visibleCount': '{count} 个可见元素',
  'overlay.preview.draft': '未保存的更改已显示在预览中',
  'overlay.preview.saved': '预览与已保存设置一致',
  'overlay.runtime.previewTitle': '浮层布局预览',
  'overlay.runtime.previewDescription': '布局与显示设置会同步呈现；保存后用于游戏浮层。',
  'overlay.title': '游戏内信息浮层',
  'overlay.description': '预览会按比例显示真实浮层结构与模拟信息；进入全屏可按实际大小检查。皮肤效果仅在游戏浮层中显示。',
  'overlay.status.ready': '设置已保存',
  'overlay.status.windowUnavailable': '游戏内显示暂不可用',
  'overlay.status.windowUnavailableBody': '设置会保存在这台电脑上；你仍可在下方检查实际内容与位置。',
  'overlay.settings.title': '显示设置',
  'overlay.settings.description': '这些选择只影响游戏内信息浮层。',
  'overlay.enabled': '启用信息浮层',
  'overlay.enabled.description': '保留浮层入口与显示设置。',
  'overlay.opacity': '不透明度',
  'overlay.position': '出现位置',
  'overlay.position.topLeft': '左上',
  'overlay.position.topRight': '右上',
  'overlay.position.bottomLeft': '左下',
  'overlay.position.bottomRight': '右下',
  'overlay.showTeam': '显示队友状态',
  'overlay.showTeam.description': '加入房间或行动后，在浮层中显示当前队友。',
  'overlay.preview.title': '应用内预览',
  'overlay.preview.description': '使用当前游戏信息检查显示效果。',
  'overlay.preview.disabled': '信息浮层已关闭；预览仍保留，方便你调整后重新开启。',
  'overlay.preview.waiting': '等待游戏信息',
  'overlay.preview.playing': '游戏中',
  'overlay.preview.noTeam': '当前没有可显示的队友状态',
  'overlay.preview.eventDrag': '上下拖动；拖过画布中线可切换左右',
  'overlay.workspace.layout.noticeDockHelp': '顶部公告仅贴合画布顶部或底部；拖过画布中线即可切换。',
  'overlay.retry': '重新读取',
  'overlay.loading': '正在读取浮层设置…',
  'overlay.unavailable.title': '暂时无法读取浮层设置',
  'overlay.unavailable.body': '请检查连接后重新读取。',
  'overlay.error.hostUnavailable': '本机服务暂时不可用，请重新读取。',
  'overlay.error.readFailed': '无法读取已保存的设置，请重新读取。',
  'overlay.error.writeFailed': '未能保存更改，原设置仍然保留。',
  'overlay.error.writeConflict': '设置已在其他位置更新，请重新读取后再修改。',
  'overlay.error.invalidValue': '这项设置无法使用，请调整后重试。',
  'overlay.error.invalidResponse': '暂时无法使用这份设置，请重新读取。',
};

const overlaySettingsZhTw = <String, String>{
  'overlay.sections.info': '資訊浮層',
  'overlay.sections.menu': '選單浮層',
  'overlay.sections.menuUnavailable': '改造中，暫時無法使用',
  'overlay.menu.previewTitle': '新版選單浮層 · 互動預覽',
  'overlay.menu.previewBody': '預覽好友、訊息面板與底部工具列。目前使用示範內容，不讀取帳號或傳送訊息，也不修改現有選單與快捷鍵。',
  'overlay.menu.instructions': '拖動標題移動面板，拖動右下角調整大小。按 Esc 關閉並返回用戶端。',
  'overlay.menu.open': '開啟選單浮層預覽',
  'overlay.menu.live': '開啟選單浮層（功能驗收）',
  'overlay.menu.liveBody': '使用目前帳號和本機工具。各視窗可拖曳、縮放並同時開啟；閱讀可見訊息會標記已讀。傳送訊息、好友和房間操作只在你點擊後執行。',
  'overlay.menu.opening': '正在開啟…',
  'overlay.menu.return': '返回用戶端',
  'overlay.menu.failed': '未能顯示選單浮層，請重試。',
  ...overlayScenesZhTw,
  ...overlayWorkspaceZhTw,
  ...overlayPreviewZhTw,
  'overlay.editor.fullscreen': '全螢幕編輯',
  'overlay.editor.numberInvalid': '請輸入不小於 0 的數字',
  'overlay.editor.resetPosition': '還原模組預設位置與大小',
  'overlay.editor.exit': '退出全螢幕',
  'overlay.editor.showTools': '顯示工具',
  'overlay.editor.hideTools': '收起工具',
  'overlay.editor.tools': '編輯工具 · 可拖曳',
  'overlay.editor.opacityControls': '透明度 · 目前模組',
  'overlay.editor.showGrid': '顯示格線',
  'overlay.editor.snapOff': '關閉格線吸附',
  'overlay.editor.lockAll': '鎖定配置',
  'overlay.editor.selectModule': '選擇模組',
  'overlay.editor.moduleLibrary': '顯示模組 · 關閉後保留位置',
  'overlay.editor.keys': 'Esc 退出全螢幕 · Tab 收起工具 · 方向鍵微調 · Shift 加速 · Ctrl+S 儲存',
  'overlay.editor.windowFailed': '無法切換編輯視窗，請重試。',
  'overlay.workspace.module.Crosshair': '準星',
  'overlay.workspace.module.Events': '事件提醒',
  'overlay.workspace.sections': '浮層系統',
  'overlay.preview.stageTitle': '即時構圖',
  'overlay.preview.reference': '1920 × 1080 參考畫布',
  'overlay.preview.visibleCount': '{count} 個可見元素',
  'overlay.preview.draft': '尚未儲存的變更已顯示在預覽中',
  'overlay.preview.saved': '預覽與已儲存設定一致',
  'overlay.runtime.previewTitle': '浮層配置預覽',
  'overlay.runtime.previewDescription': '配置與顯示設定會同步呈現；儲存後用於遊戲浮層。',
  'overlay.title': '遊戲內資訊浮層',
  'overlay.description': '預覽會按比例顯示真實浮層結構與模擬資訊；進入全螢幕可按實際大小檢查。外觀效果僅在遊戲浮層中顯示。',
  'overlay.status.ready': '設定已儲存',
  'overlay.status.windowUnavailable': '遊戲內顯示暫時無法使用',
  'overlay.status.windowUnavailableBody': '設定會保存在這台電腦上；你仍可在下方檢查實際內容與位置。',
  'overlay.settings.title': '顯示設定',
  'overlay.settings.description': '這些選擇只影響遊戲內資訊浮層。',
  'overlay.enabled': '啟用資訊浮層',
  'overlay.enabled.description': '保留浮層入口與顯示設定。',
  'overlay.opacity': '不透明度',
  'overlay.position': '出現位置',
  'overlay.position.topLeft': '左上',
  'overlay.position.topRight': '右上',
  'overlay.position.bottomLeft': '左下',
  'overlay.position.bottomRight': '右下',
  'overlay.showTeam': '顯示隊友狀態',
  'overlay.showTeam.description': '加入房間或行動後，在浮層中顯示目前隊友。',
  'overlay.preview.title': '應用程式內預覽',
  'overlay.preview.description': '使用目前遊戲資訊檢查顯示效果。',
  'overlay.preview.disabled': '資訊浮層已關閉；預覽仍會保留，方便你調整後重新開啟。',
  'overlay.preview.waiting': '等待遊戲資訊',
  'overlay.preview.playing': '遊戲中',
  'overlay.preview.noTeam': '目前沒有可顯示的隊友狀態',
  'overlay.preview.eventDrag': '上下拖曳；拖過畫布中線可切換左右',
  'overlay.workspace.layout.noticeDockHelp': '頂部公告僅貼合畫布頂部或底部；拖過畫布中線即可切換。',
  'overlay.retry': '重新讀取',
  'overlay.loading': '正在讀取浮層設定…',
  'overlay.unavailable.title': '暫時無法讀取浮層設定',
  'overlay.unavailable.body': '請檢查連線後重新讀取。',
  'overlay.error.hostUnavailable': '本機服務暫時無法使用，請重新讀取。',
  'overlay.error.readFailed': '無法讀取已儲存的設定，請重新讀取。',
  'overlay.error.writeFailed': '未能儲存變更，原設定仍然保留。',
  'overlay.error.writeConflict': '設定已在其他位置更新，請重新讀取後再修改。',
  'overlay.error.invalidValue': '這項設定無法使用，請調整後重試。',
  'overlay.error.invalidResponse': '暫時無法使用這份設定，請重新讀取。',
};

const overlaySettingsEn = <String, String>{
  'overlay.sections.info': 'Information overlay',
  'overlay.sections.menu': 'Menu overlay',
  'overlay.sections.menuUnavailable': 'Being rebuilt · currently unavailable',
  'overlay.menu.previewTitle': 'New menu overlay · Interactive preview',
  'overlay.menu.previewBody': 'Preview friends, message panels and the bottom toolbar with demo content. No account access or message sending; existing menus and shortcuts stay unchanged.',
  'overlay.menu.instructions': 'Drag a title to move a panel or its lower-right corner to resize. Press Esc to return to the client.',
  'overlay.menu.open': 'Open menu overlay preview',
  'overlay.menu.live': 'Open menu overlay (acceptance)',
  'overlay.menu.liveBody': 'Uses your current account and local tools. Move, resize and open windows together. Visible messages are marked as read. Sending messages and changing friends or rooms require your explicit action.',
  'overlay.menu.opening': 'Opening…',
  'overlay.menu.return': 'Return to client',
  'overlay.menu.failed': 'The menu overlay could not be displayed. Please try again.',
  ...overlayScenesEn,
  ...overlayWorkspaceEn,
  ...overlayPreviewEn,
  'overlay.editor.fullscreen': 'Edit fullscreen',
  'overlay.editor.numberInvalid': 'Enter a number of 0 or more',
  'overlay.editor.resetPosition': 'Reset module position and size',
  'overlay.editor.exit': 'Exit fullscreen',
  'overlay.editor.showTools': 'Show tools',
  'overlay.editor.hideTools': 'Hide tools',
  'overlay.editor.tools': 'Editor tools · Drag to move',
  'overlay.editor.opacityControls': 'Opacity · selected module',
  'overlay.editor.showGrid': 'Show grid',
  'overlay.editor.snapOff': 'Grid snap off',
  'overlay.editor.lockAll': 'Lock layout',
  'overlay.editor.selectModule': 'Select module',
  'overlay.editor.moduleLibrary': 'Visible modules · Positions are retained',
  'overlay.editor.keys':
      'Esc exit · Tab hide tools · Arrows move · Shift faster · Ctrl+S save',
  'overlay.editor.windowFailed':
      'Could not change the editor window. Try again.',
  'overlay.workspace.module.Crosshair': 'Crosshair',
  'overlay.workspace.module.Events': 'Event notifications',
  'overlay.workspace.sections': 'Overlay systems',
  'overlay.preview.stageTitle': 'Live composition',
  'overlay.preview.reference': '1920 × 1080 reference canvas',
  'overlay.preview.visibleCount': '{count} visible elements',
  'overlay.preview.draft': 'Unsaved changes are shown in the preview',
  'overlay.preview.saved': 'Preview matches the saved settings',
  'overlay.runtime.previewTitle': 'Overlay layout preview',
  'overlay.runtime.previewDescription':
      'Layout and visibility update here; save to apply them in game.',
  'overlay.title': 'In-game information overlay',
  'overlay.description': 'The preview scales the real overlay structure with sample data. Enter fullscreen to inspect it at actual size. Skins appear only in the in-game overlay.',
  'overlay.status.ready': 'Settings saved',
  'overlay.status.windowUnavailable': 'In-game display is not available yet',
  'overlay.status.windowUnavailableBody': 'Settings stay on this computer. You can still check the actual content and position below.',
  'overlay.settings.title': 'Display settings',
  'overlay.settings.description':
      'These choices only affect the in-game information overlay.',
  'overlay.enabled': 'Enable information overlay',
  'overlay.enabled.description':
      'Keep the overlay entry point and display settings available.',
  'overlay.opacity': 'Opacity',
  'overlay.position': 'Screen position',
  'overlay.position.topLeft': 'Top left',
  'overlay.position.topRight': 'Top right',
  'overlay.position.bottomLeft': 'Bottom left',
  'overlay.position.bottomRight': 'Bottom right',
  'overlay.showTeam': 'Show teammate status',
  'overlay.showTeam.description':
      'Show current teammates after you join a room or operation.',
  'overlay.preview.title': 'In-app preview',
  'overlay.preview.description':
      'Check the display using current game details.',
  'overlay.preview.disabled': 'The information overlay is off. The preview remains available so you can adjust it before turning it on.',
  'overlay.preview.waiting': 'Waiting for game details',
  'overlay.preview.playing': 'In game',
  'overlay.preview.noTeam': 'No teammate status is available right now',
  'overlay.preview.eventDrag':
      'Drag vertically; cross the canvas center to switch sides',
  'overlay.workspace.layout.noticeDockHelp': 'The notice docks only to the top or bottom edge; cross the canvas center to switch.',
  'overlay.retry': 'Read again',
  'overlay.loading': 'Loading overlay settings…',
  'overlay.unavailable.title': 'Overlay settings are temporarily unavailable',
  'overlay.unavailable.body':
      'Check the connection, then read the settings again.',
  'overlay.error.hostUnavailable':
      'The local service is unavailable. Read the settings again.',
  'overlay.error.readFailed': 'Saved settings could not be read. Try again.',
  'overlay.error.writeFailed':
      'Changes could not be saved. Your previous settings remain in place.',
  'overlay.error.writeConflict':
      'Settings changed elsewhere. Read them again before editing.',
  'overlay.error.invalidValue':
      'This setting cannot be used. Adjust it and try again.',
  'overlay.error.invalidResponse':
      'These settings cannot be used right now. Read them again.',
};
