import 'room_action_strings.dart';
import 'room_social_strings.dart';

const simplifiedPartyRoomsStrings = <String, String>{
  'rooms.invitationExpires': '邀请有效期至',
  'rooms.inviteSender': '邀请人',
  'rooms.inviteRecipient': '受邀人',
  'rooms.invitationDetailsUnavailable': '暂时无法读取房间资料，请关闭后重试。',
  'rooms.activity.title': '房间提醒',
  'rooms.activity.hint': '查看收到的邀请和待处理申请，前往房间处理。',
  'rooms.activity.empty': '暂无房间邀请或待处理申请。',
  'rooms.activity.invitedBy': '邀请人：',
  'rooms.activity.open': '前往房间',
  'rooms.leaderVersion': '队长游戏版本',
  'rooms.versionUnknown': '未提供版本',
  'rooms.full': '已满员',
  'rooms.roomDetails': '房间资料',
  'rooms.hideDetails': '收起资料',
  ...simplifiedRoomActionStrings,
  ...simplifiedRoomSocialStrings,
  'rooms.error.refreshRequired': '操作结果需要重新确认，请刷新房间。',
  'rooms.example.notice': '示例数据 · 不影响真实房间',
  'rooms.example.scene': '预览状态',
  'rooms.example.directory': '房间列表',
  'rooms.example.current': '已在房间',
  'rooms.example.host': '房主管理',
  'rooms.example.empty': '暂无房间',
  'rooms.example.error': '读取失败',
  'rooms.directory': '寻找房间',
  'rooms.current': '当前房间',
  'rooms.refresh': '刷新房间',
  'rooms.refreshing': '正在刷新…',
  'rooms.readOnly': '目前可查看房间与成员；创建、加入及房间聊天尚未接入。',
  'rooms.loading': '正在读取房间…',
  'rooms.signedOut': '请先在账号菜单登录，再刷新房间。',
  'rooms.empty': '当前没有可见房间，可以稍后刷新。',
  'rooms.currentHint': '你已在这个房间。离开后才可浏览其他房间。',
  'rooms.noGoal': '房主尚未填写目标。',
  'rooms.capacity': '成员 / 容量',
  'rooms.admission': '加入方式',
  'rooms.eligibility': '加入范围',
  'rooms.voice': '语音要求',
  'rooms.language': '交流语言',
  'rooms.visibility': '可见范围',
  'rooms.public': '公开',
  'rooms.unlisted': '不公开',
  'rooms.password': '房间密码',
  'rooms.required': '需要密码',
  'rooms.notRequired': '不需要密码',
  'rooms.recruitment': '招募状态',
  'rooms.closed': '已截止',
  'rooms.open': '未截止',
  'rooms.expires': '服务端解散时间',
  'rooms.members': '房间成员',
  'rooms.memberPreview': '成员预览',
  'rooms.joinRequirements': '加入要求',
  'rooms.host': '房主',
  'rooms.leaderServer': '队长当前服务器',
  'rooms.region.US': '美服',
  'rooms.region.EU': '欧服',
  'rooms.region.AU': '澳服',
  'rooms.region.ASIA': '亚服',
  'rooms.region.unknown': '暂无可见信息',
  'rooms.unnamedMember': '未设置名称',
  'rooms.presence': '状态',
  'rooms.location': '位置',
  'rooms.ship': '舰船',
  'rooms.server': '服务器',
  'rooms.notShared': '暂无可见信息',
  'rooms.observed': '上次读取',
  'rooms.unknown': '未识别的设置',
  'rooms.admission.direct': '直接加入',
  'rooms.admission.approval': '需要申请',
  'rooms.eligibility.everyone': '所有人',
  'rooms.eligibility.friends': '好友',
  'rooms.eligibility.fleet': '同舰队',
  'rooms.eligibility.invite': '仅限邀请',
  'rooms.voice.none': '无需语音',
  'rooms.voice.recommended': '建议语音',
  'rooms.voice.required': '必须语音',
  'rooms.language.zh': '中文',
  'rooms.language.en': 'English',
  'rooms.language.bilingual': '中文 / English',
  'rooms.error.unavailable': '暂时无法读取房间，请稍后刷新。',
  'rooms.error.hostUnavailable': '本机房间服务尚不可用，请重启客户端后重试。',
  'rooms.error.identityUnavailable': '房间服务暂未确认你的账号关联或登录授权。请到设置检查账号状态后重试。',
  'rooms.error.forbidden': '当前账号没有读取房间的权限，请检查账号授权后重试。',
  'rooms.error.invalidResponse': '房间数据未能正确读取，请刷新重试。',
};
const traditionalPartyRoomsStrings = <String, String>{
  'rooms.invitationExpires': '邀請有效期至',
  'rooms.inviteSender': '邀請人',
  'rooms.inviteRecipient': '受邀人',
  'rooms.invitationDetailsUnavailable': '暫時無法讀取房間資料，請關閉後重試。',
  'rooms.activity.title': '房間提醒',
  'rooms.activity.hint': '查看收到的邀請和待處理申請，前往房間處理。',
  'rooms.activity.empty': '暫無房間邀請或待處理申請。',
  'rooms.activity.invitedBy': '邀請人：',
  'rooms.activity.open': '前往房間',
  'rooms.leaderVersion': '隊長遊戲版本',
  'rooms.versionUnknown': '未提供版本',
  'rooms.full': '已滿員',
  'rooms.roomDetails': '房間資料',
  'rooms.hideDetails': '收起資料',
  ...traditionalRoomActionStrings,
  ...traditionalRoomSocialStrings,
  'rooms.error.refreshRequired': '操作結果需要重新確認，請重新整理房間。',
  'rooms.example.notice': '範例資料 · 不影響真實房間',
  'rooms.example.scene': '預覽狀態',
  'rooms.example.directory': '房間清單',
  'rooms.example.current': '已在房間',
  'rooms.example.host': '房主管理',
  'rooms.example.empty': '暫無房間',
  'rooms.example.error': '讀取失敗',
  'rooms.directory': '尋找房間',
  'rooms.current': '目前房間',
  'rooms.refresh': '重新整理房間',
  'rooms.refreshing': '正在重新整理…',
  'rooms.readOnly': '目前可查看房間與成員；建立、加入及房間聊天尚未接入。',
  'rooms.loading': '正在讀取房間…',
  'rooms.signedOut': '請先在帳號選單登入，再重新整理房間。',
  'rooms.empty': '目前沒有可見房間，可以稍後重新整理。',
  'rooms.currentHint': '你已在這個房間。離開後才可瀏覽其他房間。',
  'rooms.noGoal': '房主尚未填寫目標。',
  'rooms.capacity': '成員 / 容量',
  'rooms.admission': '加入方式',
  'rooms.eligibility': '加入範圍',
  'rooms.voice': '語音要求',
  'rooms.language': '交流語言',
  'rooms.visibility': '可見範圍',
  'rooms.public': '公開',
  'rooms.unlisted': '不公開',
  'rooms.password': '房間密碼',
  'rooms.required': '需要密碼',
  'rooms.notRequired': '不需要密碼',
  'rooms.recruitment': '招募狀態',
  'rooms.closed': '已截止',
  'rooms.open': '未截止',
  'rooms.expires': '伺服器解散時間',
  'rooms.members': '房間成員',
  'rooms.memberPreview': '成員預覽',
  'rooms.joinRequirements': '加入要求',
  'rooms.host': '房主',
  'rooms.leaderServer': '隊長目前伺服器',
  'rooms.region.US': '美服',
  'rooms.region.EU': '歐服',
  'rooms.region.AU': '澳服',
  'rooms.region.ASIA': '亞服',
  'rooms.region.unknown': '暫無可見資訊',
  'rooms.unnamedMember': '未設定名稱',
  'rooms.presence': '狀態',
  'rooms.location': '位置',
  'rooms.ship': '艦船',
  'rooms.server': '伺服器',
  'rooms.notShared': '暫無可見資訊',
  'rooms.observed': '上次讀取',
  'rooms.unknown': '未識別的設定',
  'rooms.admission.direct': '直接加入',
  'rooms.admission.approval': '需要申請',
  'rooms.eligibility.everyone': '所有人',
  'rooms.eligibility.friends': '好友',
  'rooms.eligibility.fleet': '同艦隊',
  'rooms.eligibility.invite': '僅限邀請',
  'rooms.voice.none': '無需語音',
  'rooms.voice.recommended': '建議語音',
  'rooms.voice.required': '必須語音',
  'rooms.language.zh': '中文',
  'rooms.language.en': 'English',
  'rooms.language.bilingual': '中文 / English',
  'rooms.error.unavailable': '暫時無法讀取房間，請稍後重新整理。',
  'rooms.error.hostUnavailable': '本機房間服務尚不可用，請重新啟動用戶端後重試。',
  'rooms.error.identityUnavailable': '房間服務暫未確認你的帳號關聯或登入授權。請到設定檢查帳號狀態後重試。',
  'rooms.error.forbidden': '目前帳號沒有讀取房間的權限，請檢查帳號授權後重試。',
  'rooms.error.invalidResponse': '房間資料未能正確讀取，請重新整理後重試。',
};
const englishPartyRoomsStrings = <String, String>{
  'rooms.invitationExpires': 'Invitation valid until',
  'rooms.inviteSender': 'Invited by',
  'rooms.inviteRecipient': 'Invited player',
  'rooms.invitationDetailsUnavailable':
      'Room details are unavailable. Close and reopen to retry.',
  'rooms.activity.title': 'Room reminders',
  'rooms.activity.hint':
      'Review invitations and pending requests, then open Rooms to respond.',
  'rooms.activity.empty': 'No room invitations or pending requests.',
  'rooms.activity.invitedBy': 'Invited by: ',
  'rooms.activity.open': 'Open Rooms',
  'rooms.leaderVersion': 'Host game version',
  'rooms.versionUnknown': 'Version not shared',
  'rooms.full': 'Full',
  'rooms.roomDetails': 'Room details',
  'rooms.hideDetails': 'Hide details',
  ...englishRoomActionStrings,
  ...englishRoomSocialStrings,
  'rooms.error.refreshRequired': 'Refresh rooms to confirm the result.',
  'rooms.example.notice': 'Example data · Real rooms are unchanged',
  'rooms.example.scene': 'Preview state',
  'rooms.example.directory': 'Room list',
  'rooms.example.current': 'In a room',
  'rooms.example.host': 'Room host',
  'rooms.example.empty': 'No rooms',
  'rooms.example.error': 'Read failure',
  'rooms.directory': 'Find a room',
  'rooms.current': 'Current room',
  'rooms.refresh': 'Refresh rooms',
  'rooms.refreshing': 'Refreshing…',
  'rooms.readOnly': 'Room and member details are available. Creating, joining and room chat are not connected yet.',
  'rooms.loading': 'Loading rooms…',
  'rooms.signedOut': 'Sign in from the account menu, then refresh rooms.',
  'rooms.empty': 'No rooms are visible right now. Try refreshing later.',
  'rooms.currentHint':
      'You are in this room. Leave before browsing other rooms.',
  'rooms.noGoal': 'The host has not added a goal.',
  'rooms.capacity': 'Members / capacity',
  'rooms.admission': 'Admission',
  'rooms.eligibility': 'Eligibility',
  'rooms.voice': 'Voice',
  'rooms.language': 'Language',
  'rooms.visibility': 'Visibility',
  'rooms.public': 'Public',
  'rooms.unlisted': 'Unlisted',
  'rooms.password': 'Room password',
  'rooms.required': 'Required',
  'rooms.notRequired': 'Not required',
  'rooms.recruitment': 'Recruitment',
  'rooms.closed': 'Closed',
  'rooms.open': 'Not closed',
  'rooms.expires': 'Server disband time',
  'rooms.members': 'Room members',
  'rooms.memberPreview': 'Member preview',
  'rooms.joinRequirements': 'Joining requirements',
  'rooms.host': 'Host',
  'rooms.leaderServer': 'Leader’s current server',
  'rooms.region.US': 'US',
  'rooms.region.EU': 'Europe',
  'rooms.region.AU': 'Australia',
  'rooms.region.ASIA': 'Asia',
  'rooms.region.unknown': 'No visible information',
  'rooms.unnamedMember': 'Name not set',
  'rooms.presence': 'Status',
  'rooms.location': 'Location',
  'rooms.ship': 'Ship',
  'rooms.server': 'Server',
  'rooms.notShared': 'No visible information',
  'rooms.observed': 'Last read',
  'rooms.unknown': 'Unrecognized setting',
  'rooms.admission.direct': 'Direct join',
  'rooms.admission.approval': 'Application required',
  'rooms.eligibility.everyone': 'Everyone',
  'rooms.eligibility.friends': 'Friends',
  'rooms.eligibility.fleet': 'Same fleet',
  'rooms.eligibility.invite': 'Invite only',
  'rooms.voice.none': 'Not required',
  'rooms.voice.recommended': 'Recommended',
  'rooms.voice.required': 'Required',
  'rooms.language.zh': 'Chinese',
  'rooms.language.en': 'English',
  'rooms.language.bilingual': 'Chinese / English',
  'rooms.error.unavailable':
      'Rooms could not be loaded. Try refreshing shortly.',
  'rooms.error.hostUnavailable': 'The local room service is unavailable. Restart the client and try again.',
  'rooms.error.identityUnavailable': 'The room service could not confirm your account link or authorization. Check your account in Settings, then retry.',
  'rooms.error.forbidden': 'This account does not have room read access. Check account authorization and retry.',
  'rooms.error.invalidResponse':
      'Room data could not be read correctly. Refresh to retry.',
};
