const simplifiedPrivacyScopeSettingsStrings = <String, String>{
  'privacy.notice.waiting.title': '实时共享未生效',
  'privacy.notice.waiting.body': '同步已开启，但尚未确认生效。请查看共享状态。',
  'privacy.notice.failed.title': '实时共享异常',
  'privacy.notice.failed.body': '无法确认实时状态已同步。共享范围未改变，请查看原因并处理。',
  'privacy.notice.identity.title': '实时共享等待身份确认',
  'privacy.notice.identity.body': '确认游戏身份后才能共享实时状态。',
  'privacy.notice.paused.title': '实时共享已暂停',
  'privacy.notice.paused.body': '已保存的共享范围保留，当前不会继续同步实时状态。',
  'privacy.notice.settings': '查看设置',
  'privacy.member.title': '成员可见度',
  'privacy.member.body': '未单独设置的成员沿用组织默认范围。单独设置优先；组织总开关关闭的项目，对所有成员都不可见。',
  'privacy.member.search': '搜索成员名字或游戏 ID',
  'privacy.member.changed': '账号或组织成员关系已改变，请关闭此页。',
  'privacy.member.unsupported': '当前连接暂不支持逐成员设置，已有设置保持不变。',
  'privacy.member.retrying': '成员清单暂未读完，正在自动重试。',
  'privacy.member.limit': '单独设置已达 1000 人上限。请先恢复部分成员的默认设置。',
  'privacy.member.legacy': '旧私有可见组已停用。可将其中当前成员的范围转换为单独设置。',
  'privacy.member.convert': '转换旧范围',
  'privacy.member.convertBody':
      '将旧组中当前成员的范围加入逐人设置，保留已有单独设置。不会加入其他成员，也不会扩大组织总开关。更改仍需在设置页保存。',
  'privacy.member.empty': '没有匹配的成员。',
  'privacy.member.confirm': '保留到草稿',
  'privacy.member.self': '你',
  'privacy.member.inherited': '沿用默认',
  'privacy.member.reset': '恢复默认',
  'privacy.scope.title': '同步与隐私',
  'privacy.scope.description': '分别设置房间和每个组织可以看到的实时信息。',
  'privacy.scope.loading': '正在读取共享设置…',
  'privacy.scope.unavailable.title': '暂时无法读取共享设置',
  'privacy.scope.unavailable.body': '已有设置不会被覆盖，请检查登录和连接后重试。',
  'privacy.scope.retry': '重新读取',
  'privacy.scope.global.title': '实时状态共享',
  'privacy.scope.global.body': '修改后保存生效；关闭共享仍保留下方的范围选择。',
  'privacy.scope.global.enabled': '允许共享实时状态',
  'privacy.scope.live.inactive': '尚未开启',
  'privacy.scope.live.notRunning': '共享尚未运行。已保存的范围保持不变，可重新应用。',
  'privacy.scope.live.reapply': '重新应用共享',
  'privacy.scope.live.saveFirst': '先保存或放弃当前修改，再重新应用。',
  'privacy.scope.failure.identity': '请在“账号与识别”中确认登录和游戏身份后重试。',
  'privacy.scope.failure.denied': '服务器未允许此次共享，请确认账号权限后重试。',
  'privacy.scope.failure.contract': '服务器未能确认共享范围。已暂停继续发送，请检查客户端与服务版本。',
  'privacy.scope.failure.changed': '共享设置已变化，请重新读取后再试。',
  'privacy.scope.failure.connection': '未能确认共享结果，请检查连接后重试。',
  'privacy.scope.live.identityRequired': '等待游戏身份确认',
  'privacy.scope.live.publishing': '正在应用…',
  'privacy.scope.live.pending': '等待服务器确认',
  'privacy.scope.live.reconnecting': '正在恢复连接',
  'privacy.scope.live.applied': '共享已生效',
  'privacy.scope.live.legacyApplied': '已有共享仍在生效，逐组织设置暂不可用。',
  'privacy.scope.live.withdrawn': '共享已停止',
  'privacy.scope.live.failed': '未能确认状态',
  'privacy.scope.live.withdrawalPending': '正在撤回共享',
  'privacy.scope.live.unsupported': '当前连接尚未启用对外共享',
  'privacy.scope.live.apply': '应用共享',
  'privacy.scope.live.stop': '停止共享',
  'privacy.scope.live.refresh': '刷新状态',
  'privacy.scope.live.applyTitle': '应用当前共享设置？',
  'privacy.scope.live.applyBody': '按已保存的房间和组织范围共享实时状态。本机记住当前账号的确认，重启或断线后自动恢复。隐身时暂停；关闭共享或停止共享会取消自动恢复。机库和事件不在此次授权内。',
  'privacy.scope.cancel': '取消',
  'privacy.scope.room.title': '房间',
  'privacy.scope.room.badge': '单独设置',
  'privacy.scope.room.body': '只对当前房间成员生效，不沿用任何组织设置。',
  'privacy.scope.room.members': '当前房间成员',
  'privacy.scope.room.membersBody': '加入同一房间后，按下方范围共享。',
  'privacy.scope.fleet.title': '主舰队',
  'privacy.scope.fleet.badge': '后续开放',
  'privacy.scope.fleet.body': '主舰队将拥有独立设置，不会沿用社区组织范围。',
  'privacy.scope.fleet.unavailable': '暂未开放',
  'privacy.scope.organizations.title': '社区组织',
  'privacy.scope.organizations.body': '每个组织都保留自己的共享范围，加入新组织后需要单独确认。',
  'privacy.scope.organizations.loading': '正在读取你的组织…',
  'privacy.scope.organizations.unsupported.title': '逐组织设置暂不可用',
  'privacy.scope.organizations.unsupported.body': '当前连接尚不支持逐组织范围，不会新增或扩大任何授权。',
  'privacy.scope.organizations.failed.title': '无法读取组织列表',
  'privacy.scope.organizations.failed.body': '正在自动重试，已有共享范围保持不变。',
  'privacy.scope.organizations.serviceUnavailable.title': '逐组织设置尚未上线',
  'privacy.scope.organizations.serviceUnavailable.body':
      '你的组织资料没有丢失。当前服务尚未开放这项设置，已有共享范围保持不变。',
  'privacy.scope.organizations.empty': '当前没有可设置的社区组织。',
  'privacy.scope.organizations.migrate.title': '确认旧组织设置',
  'privacy.scope.organizations.migrate.body':
      '旧版设置尚未按组织拆分。确认后只保留已明确关联的组织范围，其他组织仍不共享。',
  'privacy.scope.organizations.migrate.action': '开始逐组织设置',
  'privacy.scope.organizations.migrate.dialogTitle': '开始逐组织设置？',
  'privacy.scope.organizations.migrate.dialogBody':
      '这不会自动向其他组织开放任何信息。已有明确选择将保留。',
  'privacy.scope.organizations.migrate.confirm': '确认并继续',
  'privacy.scope.organization.badge': '社区组织',
  'privacy.scope.organization.pending': '待确认',
  'privacy.scope.organization.none': '不共享',
  'privacy.scope.organization.active': '已设置 {count} 项',
  'privacy.scope.organization.body': '此范围只属于当前成员关系，退会或重新加入后需要再次确认。',
  'privacy.scope.organization.confirmNone': '明确不共享',
  'privacy.scope.audience': '共享给谁',
  'privacy.scope.audience.all': '所有成员',
  'privacy.scope.audience.allBody': '这个组织的所有成员都可以查看。',
  'privacy.scope.audience.admins': '组织管理员',
  'privacy.scope.audience.adminsBody': '所有成员关闭时，可只向管理员开放。',
  'privacy.scope.audience.groups': '已有可见组（{count}）',
  'privacy.scope.audience.groupsBody': '已保留原有选择；可见组管理将在对应入口开放。',
  'privacy.scope.fields': '共享哪些信息',
  'privacy.scope.field.presence': '在线状态',
  'privacy.scope.field.presenceBody': '是否在线或正在游戏',
  'privacy.scope.field.ship': '当前飞船',
  'privacy.scope.field.shipBody': '当前识别到的飞船',
  'privacy.scope.field.location': '当前位置',
  'privacy.scope.field.locationBody': '已经确认的游戏位置',
  'privacy.scope.field.server': '服务器信息',
  'privacy.scope.field.serverBody': '当前游戏服务器信息',
  'privacy.scope.separate': '个人机库、事件分享、好友状态和游戏 ID 均在各自入口中管理。',
  'privacy.scope.save': '保存更改',
  'privacy.scope.discard': '放弃更改',
  'privacy.scope.saved': '设置已保存',
  'privacy.scope.defaults': '尚未保存',
  'privacy.scope.dirty': '有未保存的更改',
  'privacy.scope.saving': '正在保存…',
  'privacy.scope.saveFailed': '未能确认保存成功，更改仍保留在本页。',
  'privacy.scope.conflict': '设置已在其他位置变化，请重新读取。',
  'privacy.scope.leave.title': '保存共享设置？',
  'privacy.scope.leave.body': '当前更改尚未保存。',
  'privacy.scope.leave.stay': '继续编辑',
};

const traditionalPrivacyScopeSettingsStrings = <String, String>{
  'privacy.notice.waiting.title': '即時共享未生效',
  'privacy.notice.waiting.body': '同步已開啟，但尚未確認生效。請查看共享狀態。',
  'privacy.notice.failed.title': '即時共享異常',
  'privacy.notice.failed.body': '無法確認即時狀態已同步。共享範圍未變更，請查看原因並處理。',
  'privacy.notice.identity.title': '即時共享等待身分確認',
  'privacy.notice.identity.body': '確認遊戲身分後才能共享即時狀態。',
  'privacy.notice.paused.title': '即時共享已暫停',
  'privacy.notice.paused.body': '已儲存的共享範圍保留，目前不會繼續同步即時狀態。',
  'privacy.notice.settings': '查看設定',
  'privacy.member.title': '成員可見度',
  'privacy.member.body': '未單獨設定的成員沿用組織預設範圍。單獨設定優先；組織總開關關閉的項目，對所有成員都不可見。',
  'privacy.member.search': '搜尋成員名字或遊戲 ID',
  'privacy.member.changed': '帳號或組織成員關係已改變，請關閉此頁。',
  'privacy.member.unsupported': '目前連線暫不支援逐成員設定，已有設定保持不變。',
  'privacy.member.retrying': '成員清單暫未讀完，正在自動重試。',
  'privacy.member.limit': '單獨設定已達 1000 人上限。請先恢復部分成員的預設設定。',
  'privacy.member.legacy': '舊私有可見組已停用。可將其中目前成員的範圍轉換為單獨設定。',
  'privacy.member.convert': '轉換舊範圍',
  'privacy.member.convertBody':
      '將舊組中目前成員的範圍加入逐人設定，保留已有單獨設定。不會加入其他成員，也不會擴大組織總開關。變更仍需在設定頁儲存。',
  'privacy.member.empty': '沒有符合的成員。',
  'privacy.member.confirm': '保留至草稿',
  'privacy.member.self': '你',
  'privacy.member.inherited': '沿用預設',
  'privacy.member.reset': '恢復預設',
  'privacy.scope.title': '同步與隱私',
  'privacy.scope.description': '分別設定房間和每個組織可以看到的即時資訊。',
  'privacy.scope.loading': '正在讀取共享設定…',
  'privacy.scope.unavailable.title': '暫時無法讀取共享設定',
  'privacy.scope.unavailable.body': '現有設定不會被覆蓋，請檢查登入和連線後重試。',
  'privacy.scope.retry': '重新讀取',
  'privacy.scope.global.title': '即時狀態共享',
  'privacy.scope.global.body': '修改後儲存生效；關閉共享仍保留下方的範圍選擇。',
  'privacy.scope.global.enabled': '允許共享即時狀態',
  'privacy.scope.live.inactive': '尚未開啟',
  'privacy.scope.live.notRunning': '共享尚未執行。已儲存的範圍保持不變，可重新套用。',
  'privacy.scope.live.reapply': '重新套用共享',
  'privacy.scope.live.saveFirst': '先儲存或放棄目前修改，再重新套用。',
  'privacy.scope.failure.identity': '請在「帳號與識別」中確認登入和遊戲身分後重試。',
  'privacy.scope.failure.denied': '伺服器未允許此次共享，請確認帳號權限後重試。',
  'privacy.scope.failure.contract': '伺服器未能確認共享範圍。已暫停繼續傳送，請檢查用戶端與服務版本。',
  'privacy.scope.failure.changed': '共享設定已變更，請重新讀取後再試。',
  'privacy.scope.failure.connection': '未能確認共享結果，請檢查連線後重試。',
  'privacy.scope.live.identityRequired': '等待遊戲身分確認',
  'privacy.scope.live.publishing': '正在套用…',
  'privacy.scope.live.pending': '等待伺服器確認',
  'privacy.scope.live.reconnecting': '正在恢復連線',
  'privacy.scope.live.applied': '共享已生效',
  'privacy.scope.live.legacyApplied': '既有共享仍在生效，逐組織設定暫不可用。',
  'privacy.scope.live.withdrawn': '共享已停止',
  'privacy.scope.live.failed': '未能確認狀態',
  'privacy.scope.live.withdrawalPending': '正在撤回共享',
  'privacy.scope.live.unsupported': '目前連線尚未啟用對外共享',
  'privacy.scope.live.apply': '套用共享',
  'privacy.scope.live.stop': '停止共享',
  'privacy.scope.live.refresh': '重新整理狀態',
  'privacy.scope.live.applyTitle': '套用目前共享設定？',
  'privacy.scope.live.applyBody': '依已儲存的房間和組織範圍共享即時狀態。本機記住目前帳號的確認，重新啟動或斷線後自動恢復。隱身時暫停；關閉共享或停止共享會取消自動恢復。機庫和事件不在此次授權內。',
  'privacy.scope.cancel': '取消',
  'privacy.scope.room.title': '房間',
  'privacy.scope.room.badge': '單獨設定',
  'privacy.scope.room.body': '只對目前房間成員生效，不沿用任何組織設定。',
  'privacy.scope.room.members': '目前房間成員',
  'privacy.scope.room.membersBody': '加入同一房間後，按下方範圍共享。',
  'privacy.scope.fleet.title': '主艦隊',
  'privacy.scope.fleet.badge': '後續開放',
  'privacy.scope.fleet.body': '主艦隊將擁有獨立設定，不會沿用社區組織範圍。',
  'privacy.scope.fleet.unavailable': '暫未開放',
  'privacy.scope.organizations.title': '社區組織',
  'privacy.scope.organizations.body': '每個組織都保留自己的共享範圍，加入新組織後需要單獨確認。',
  'privacy.scope.organizations.loading': '正在讀取你的組織…',
  'privacy.scope.organizations.unsupported.title': '逐組織設定暫不可用',
  'privacy.scope.organizations.unsupported.body': '目前連線尚不支援逐組織範圍，不會新增或擴大任何授權。',
  'privacy.scope.organizations.failed.title': '無法讀取組織清單',
  'privacy.scope.organizations.failed.body': '正在自動重試，現有共享範圍保持不變。',
  'privacy.scope.organizations.serviceUnavailable.title': '逐組織設定尚未上線',
  'privacy.scope.organizations.serviceUnavailable.body':
      '你的組織資料沒有遺失。目前服務尚未開放這項設定，現有共享範圍保持不變。',
  'privacy.scope.organizations.empty': '目前沒有可設定的社區組織。',
  'privacy.scope.organizations.migrate.title': '確認舊組織設定',
  'privacy.scope.organizations.migrate.body':
      '舊版設定尚未按組織拆分。確認後只保留已明確關聯的組織範圍，其他組織仍不共享。',
  'privacy.scope.organizations.migrate.action': '開始逐組織設定',
  'privacy.scope.organizations.migrate.dialogTitle': '開始逐組織設定？',
  'privacy.scope.organizations.migrate.dialogBody':
      '這不會自動向其他組織開放任何資訊。現有明確選擇將保留。',
  'privacy.scope.organizations.migrate.confirm': '確認並繼續',
  'privacy.scope.organization.badge': '社區組織',
  'privacy.scope.organization.pending': '待確認',
  'privacy.scope.organization.none': '不共享',
  'privacy.scope.organization.active': '已設定 {count} 項',
  'privacy.scope.organization.body': '此範圍只屬於目前成員關係，退出或重新加入後需要再次確認。',
  'privacy.scope.organization.confirmNone': '明確不共享',
  'privacy.scope.audience': '共享給誰',
  'privacy.scope.audience.all': '所有成員',
  'privacy.scope.audience.allBody': '這個組織的所有成員都可以查看。',
  'privacy.scope.audience.admins': '組織管理員',
  'privacy.scope.audience.adminsBody': '所有成員關閉時，可只向管理員開放。',
  'privacy.scope.audience.groups': '已有可見組（{count}）',
  'privacy.scope.audience.groupsBody': '已保留原有選擇；可見組管理將在對應入口開放。',
  'privacy.scope.fields': '共享哪些資訊',
  'privacy.scope.field.presence': '在線狀態',
  'privacy.scope.field.presenceBody': '是否在線或正在遊戲',
  'privacy.scope.field.ship': '目前飛船',
  'privacy.scope.field.shipBody': '目前識別到的飛船',
  'privacy.scope.field.location': '目前位置',
  'privacy.scope.field.locationBody': '已經確認的遊戲位置',
  'privacy.scope.field.server': '伺服器資訊',
  'privacy.scope.field.serverBody': '目前遊戲伺服器資訊',
  'privacy.scope.separate': '個人機庫、事件分享、好友狀態和遊戲 ID 均在各自入口中管理。',
  'privacy.scope.save': '儲存變更',
  'privacy.scope.discard': '放棄變更',
  'privacy.scope.saved': '設定已儲存',
  'privacy.scope.defaults': '尚未儲存',
  'privacy.scope.dirty': '有未儲存的變更',
  'privacy.scope.saving': '正在儲存…',
  'privacy.scope.saveFailed': '未能確認儲存成功，變更仍保留在本頁。',
  'privacy.scope.conflict': '設定已在其他位置變更，請重新讀取。',
  'privacy.scope.leave.title': '儲存共享設定？',
  'privacy.scope.leave.body': '目前變更尚未儲存。',
  'privacy.scope.leave.stay': '繼續編輯',
};

const englishPrivacyScopeSettingsStrings = <String, String>{
  'privacy.notice.waiting.title': 'Live sharing is not confirmed',
  'privacy.notice.waiting.body':
      'Sync is enabled but has not taken effect. Check sharing status.',
  'privacy.notice.failed.title': 'Live sharing needs attention',
  'privacy.notice.failed.body': 'Live status sync could not be confirmed. Your sharing scope is unchanged. Check the issue in settings.',
  'privacy.notice.identity.title': 'Live sharing needs identity confirmation',
  'privacy.notice.identity.body':
      'Confirm your game identity before sharing live status.',
  'privacy.notice.paused.title': 'Live sharing is paused',
  'privacy.notice.paused.body':
      'Your saved sharing scope is retained. Live status updates are paused.',
  'privacy.notice.settings': 'View settings',
  'privacy.member.title': 'Member visibility',
  'privacy.member.body': 'Members inherit organization defaults unless individually set. Individual choices take priority; organization switches remain the upper limit for everyone.',
  'privacy.member.search': 'Search member name or game ID',
  'privacy.member.changed':
      'Your account or organization membership changed. Close this page.',
  'privacy.member.unsupported': 'This connection does not support individual settings yet. Existing settings are unchanged.',
  'privacy.member.retrying':
      'The member list is incomplete. Retrying automatically.',
  'privacy.member.limit': 'The limit is 1,000 individual settings. Restore defaults for some members first.',
  'privacy.member.legacy': 'Private visibility groups are retired. Convert their current members to individual settings.',
  'privacy.member.convert': 'Convert old scope',
  'privacy.member.convertBody': 'Add current members from the old groups as individual settings, preserving existing individual choices. No other members or organization fields are added. Save on the settings page to apply.',
  'privacy.member.empty': 'No matching members.',
  'privacy.member.confirm': 'Keep in draft',
  'privacy.member.self': 'You',
  'privacy.member.inherited': 'Use defaults',
  'privacy.member.reset': 'Restore defaults',
  'privacy.scope.title': 'Sync & privacy',
  'privacy.scope.description':
      'Choose live information separately for rooms and each organization.',
  'privacy.scope.loading': 'Reading sharing settings…',
  'privacy.scope.unavailable.title': 'Sharing settings are unavailable',
  'privacy.scope.unavailable.body': 'Existing settings were not replaced. Check your sign-in and connection, then try again.',
  'privacy.scope.retry': 'Reload',
  'privacy.scope.global.title': 'Live status sharing',
  'privacy.scope.global.body': 'Save to apply changes. Turning sharing off keeps the scope choices below.',
  'privacy.scope.global.enabled': 'Allow live status sharing',
  'privacy.scope.live.inactive': 'Not enabled',
  'privacy.scope.live.notRunning': 'Sharing is not running. Your saved scope is unchanged and can be reapplied.',
  'privacy.scope.live.reapply': 'Reapply sharing',
  'privacy.scope.live.saveFirst':
      'Save or discard your changes before reapplying.',
  'privacy.scope.failure.identity':
      'Check your sign-in and game identity in Account & identity, then retry.',
  'privacy.scope.failure.denied': 'The server did not allow sharing. Check your account permissions, then retry.',
  'privacy.scope.failure.contract': 'The server could not confirm the sharing scope. Further updates are paused. Check client and service versions.',
  'privacy.scope.failure.changed':
      'Sharing settings changed. Reload them before retrying.',
  'privacy.scope.failure.connection': 'The sharing result could not be confirmed. Check your connection and retry.',
  'privacy.scope.live.identityRequired': 'Waiting for game identity',
  'privacy.scope.live.publishing': 'Applying…',
  'privacy.scope.live.pending': 'Waiting for server confirmation',
  'privacy.scope.live.reconnecting': 'Reconnecting',
  'privacy.scope.live.applied': 'Sharing is active',
  'privacy.scope.live.legacyApplied':
      'Existing sharing is active. Per-organization settings are unavailable.',
  'privacy.scope.live.withdrawn': 'Sharing is stopped',
  'privacy.scope.live.failed': 'Status could not be confirmed',
  'privacy.scope.live.withdrawalPending': 'Withdrawing sharing',
  'privacy.scope.live.unsupported':
      'Outgoing sharing is unavailable on this connection',
  'privacy.scope.live.apply': 'Apply sharing',
  'privacy.scope.live.stop': 'Stop sharing',
  'privacy.scope.live.refresh': 'Refresh status',
  'privacy.scope.live.applyTitle': 'Apply these sharing settings?',
  'privacy.scope.live.applyBody': 'Share live status with the saved room and organization scopes. This device remembers your confirmation for this account and resumes after restarts or connection loss. Invisible pauses sharing; turning sharing off or stopping it cancels automatic recovery. Hangar and events are not included.',
  'privacy.scope.cancel': 'Cancel',
  'privacy.scope.room.title': 'Room',
  'privacy.scope.room.badge': 'Independent',
  'privacy.scope.room.body': 'Applies only to current room members and never inherits an organization scope.',
  'privacy.scope.room.members': 'Current room members',
  'privacy.scope.room.membersBody':
      'Share the fields below after joining the same room.',
  'privacy.scope.fleet.title': 'Main fleet',
  'privacy.scope.fleet.badge': 'Coming later',
  'privacy.scope.fleet.body': 'Main fleet will have an independent scope and will not inherit a community organization.',
  'privacy.scope.fleet.unavailable': 'Not available yet',
  'privacy.scope.organizations.title': 'Community organizations',
  'privacy.scope.organizations.body': 'Each organization keeps its own scope. New memberships require a separate confirmation.',
  'privacy.scope.organizations.loading': 'Reading your organizations…',
  'privacy.scope.organizations.unsupported.title':
      'Per-organization settings are unavailable',
  'privacy.scope.organizations.unsupported.body': 'This connection does not support per-organization scopes. No authorization will be added or expanded.',
  'privacy.scope.organizations.failed.title':
      'Organizations could not be loaded',
  'privacy.scope.organizations.failed.body':
      'Retrying automatically. Existing sharing scopes are unchanged.',
  'privacy.scope.organizations.serviceUnavailable.title':
      'Per-organization settings are not live yet',
  'privacy.scope.organizations.serviceUnavailable.body': 'Your organization data is intact. The service has not enabled these settings yet, and existing sharing scopes remain unchanged.',
  'privacy.scope.organizations.empty':
      'There are no community organizations to configure.',
  'privacy.scope.organizations.migrate.title':
      'Confirm previous organization settings',
  'privacy.scope.organizations.migrate.body': 'Previous settings have not been split by organization. Confirmation preserves only an explicitly linked organization; all others remain private.',
  'privacy.scope.organizations.migrate.action': 'Use per-organization settings',
  'privacy.scope.organizations.migrate.dialogTitle':
      'Use per-organization settings?',
  'privacy.scope.organizations.migrate.dialogBody': 'This will not open information to any additional organization. Existing explicit choices are preserved.',
  'privacy.scope.organizations.migrate.confirm': 'Confirm and continue',
  'privacy.scope.organization.badge': 'Community organization',
  'privacy.scope.organization.pending': 'Needs confirmation',
  'privacy.scope.organization.none': 'Not shared',
  'privacy.scope.organization.active': '{count} fields selected',
  'privacy.scope.organization.body': 'This scope belongs to the current membership. Leaving or rejoining requires confirmation again.',
  'privacy.scope.organization.confirmNone': 'Do not share',
  'privacy.scope.audience': 'Who can see it',
  'privacy.scope.audience.all': 'All members',
  'privacy.scope.audience.allBody':
      'Every member of this organization can view the selected fields.',
  'privacy.scope.audience.admins': 'Organization administrators',
  'privacy.scope.audience.adminsBody':
      'When all members is off, access can be limited to administrators.',
  'privacy.scope.audience.groups': 'Existing visibility groups ({count})',
  'privacy.scope.audience.groupsBody': 'Existing choices are preserved. Group management will open from its own entry.',
  'privacy.scope.fields': 'What to share',
  'privacy.scope.field.presence': 'Online status',
  'privacy.scope.field.presenceBody': 'Whether you are online or in game',
  'privacy.scope.field.ship': 'Current ship',
  'privacy.scope.field.shipBody': 'The currently recognized ship',
  'privacy.scope.field.location': 'Current location',
  'privacy.scope.field.locationBody': 'A confirmed game location',
  'privacy.scope.field.server': 'Server information',
  'privacy.scope.field.serverBody': 'Current game server information',
  'privacy.scope.separate': 'Personal hangar, event sharing, friend status, and Game ID are managed from their own entries.',
  'privacy.scope.save': 'Save changes',
  'privacy.scope.discard': 'Discard changes',
  'privacy.scope.saved': 'Settings saved',
  'privacy.scope.defaults': 'Not saved yet',
  'privacy.scope.dirty': 'Unsaved changes',
  'privacy.scope.saving': 'Saving…',
  'privacy.scope.saveFailed':
      'The save was not confirmed. Your changes remain on this page.',
  'privacy.scope.conflict':
      'These settings changed elsewhere. Reload before editing.',
  'privacy.scope.leave.title': 'Save sharing settings?',
  'privacy.scope.leave.body': 'You have unsaved changes.',
  'privacy.scope.leave.stay': 'Keep editing',
};
