const _sharedProfileBackgroundNames = <String, String>{
  'profile.background.sc02': 'SC 02',
  'profile.background.sc03': 'SC 03',
  'profile.background.sc04': 'SC 04',
  'profile.background.sc05': 'SC 05',
  'profile.background.sc06': 'SC 06',
  'profile.background.sc07': 'SC 07',
  'profile.background.sc08': 'SC 08',
  'profile.background.sc09': 'SC 09',
  'profile.background.sc11': 'SC 11',
  'profile.background.sc13': 'SC 13',
  'profile.background.sc14': 'SC 14',
  'profile.background.sc15': 'SC 15',
  'profile.background.sc16': 'SC 16',
  'profile.background.sc18': 'SC 18',
  'profile.background.sc19': 'SC 19',
  'profile.background.sc20': 'SC 20',
  'profile.background.sc21': 'SC 21',
  'profile.background.sc22': 'SC 22',
  'profile.background.sc23': 'SC 23',
  'profile.background.sc25': 'SC 25',
  'profile.background.sc26': 'SC 26',
  'profile.background.sc27': 'SC 27',
  'profile.background.sc28': 'SC 28',
  'profile.background.sc29': 'SC 29',
  'profile.background.sc30': 'SC 30',
  'profile.background.sc31': 'SC 31',
  'profile.background.sc33': 'SC 33',
  'profile.background.sc34': 'SC 34',
  'profile.background.sc35': 'SC 35',
  'profile.background.sc36': 'SC 36',
  'profile.background.sc37': 'SC 37',
  'profile.background.sc38': 'SC 38',
};

const simplifiedProfileSettingsStrings = <String, String>{
  'profile.avatar.change': '更换账号头像',
  'profile.avatar.shared': '账号头像用于个人主页、组织和聊天。更换后立即生效。',
  'profile.avatar.managed': '此头像由登录账号管理。',
  'profile.avatar.confirm': '将更换此账号在个人主页、组织和聊天中的头像。此操作会单独保存。',
  'profile.avatar.saving': '正在更换…',
  'profile.avatar.saved': '账号头像已更换。',
  'profile.avatar.failed': '暂时无法确认头像是否已更换，请刷新账号状态后再试。',
  ..._sharedProfileBackgroundNames,
  'common.cancel': '取消',
  'common.save': '保存',
  'legal.page.title': '关于与法律',
  'legal.page.description': '查看 StarBridge 使用的第三方素材、商标与发布包声明。',
  'legal.about.description': '面向 Star Citizen 玩家的非商业 Windows 协作客户端。',
  'legal.fankit.title': 'CIG Fankit 素材与商标声明',
  'legal.fankit.summary':
      '个人主页中的部分内置背景来自 CIG Fankit；StarBridge 是独立粉丝项目，不代表 CIG、RSI 或其关联公司。',
  'legal.fankit.nonCommercial':
      'StarBridge 客户端不会向用户收费；内置 Fankit 素材仅用于表达对 Star Citizen 的支持。',
  'legal.fankit.requiredNotice': '协议要求保留的英文声明',
  'legal.fankit.watermark': '原始素材自带的商标水印、品牌名称与权利标记均保持不变。',
  'legal.fankit.source': '协议来源：素材包随附的 CIG Fankit Agreement。',
  'legal.fankit.inlineAction': '素材与商标声明',
  'legal.close': '关闭声明',
  'legal.distribution.title': '发布包声明',
  'legal.distribution.body': '正式发布包同时携带 THIRD-PARTY-NOTICES.md 和 CIG-FANKIT-NOTICE.txt；这些声明不授予对素材的再许可。',
  'profile.loading': '正在读取个人页面…',
  'profile.refresh': '刷新个人页面',
  'profile.retrying': '正在重试…',
  'profile.signedOut.title': '登录后查看个人页面',
  'profile.signedOut.body': '个人页面只展示可公开的资料；账号、邮箱与身份状态仍保留在“设置 → 账号与识别”。',
  'profile.unavailable.title': '暂时无法读取个人页面',
  'profile.unavailable.retry': '重新读取',
  'profile.error.unavailable': '个人主页服务暂时不可用，请检查连接后重试。',
  'profile.error.refreshBeforeSave': '当前主页尚未读取完成或账号已变化。请重新读取个人页面后再编辑保存。',
  'profile.error.hostUnavailable': 'Native Host 当前不可用，请重新启动客户端后重试。',
  'profile.error.reauthorizationRequired': '当前 SCM 授权已失效，请前往“设置 → 账号与识别”重新登录。',
  'profile.error.compatibilityMismatch': 'SCM 关联身份与旧数据账号不一致，已阻止读取。',
  'profile.error.invalidResponse': '个人资料响应格式不兼容，客户端没有使用不完整数据。',
  'profile.error.readOnly': '当前个人页面仅支持读取。',
  'profile.readOnly.notice': '当前显示已从旧数据服务读取；编辑与背景同步将在后续写入契约完成后开放。',
  'profile.edit.action': '编辑个人页面',
  'profile.edit.title': '编辑个人页面',
  'profile.edit.description': '调整公开展示字段；模块内容与顺序会在同一页面继续编辑。',
  'profile.edit.avatar': '头像',
  'profile.edit.avatarPreserved': '沿用账号头像；本页编辑不会更换头像。',
  'profile.edit.wallpaper': '主页背景',
  'profile.edit.wallpaperDescription': '选择铺满整个个人主页的背景；会随窗口大小自适应，切换语言不会改变你的选择。',
  'profile.edit.wallpaperFankitNotice':
      '内置 Star Citizen Fankit 背景原图保留自带商标水印；选择前可查看完整声明。',
  'profile.edit.backgroundCurrent': '当前背景',
  'profile.edit.backgroundChoose': '选择背景',
  'profile.edit.backgroundPickerTitle': '选择主页背景',
  'profile.edit.backgroundPickerDescription': '背景在独立面板中选择，不会挤占其他主页设置。',
  'profile.edit.visibility': '主页可见范围',
  'profile.edit.callSign': '呼号',
  'profile.edit.about': '个人简介',
  'profile.edit.gameHandle': '游戏 ID 由账号与识别管理：',
  'profile.edit.saving': '正在保存…',
  'profile.background.none': '默认背景',
  'profile.background.formationFlight': '编队飞行',
  'profile.background.interiorCorridor': '室内 · 走廊',
  'profile.background.interiorGrdBrt': '室内 · GRD-BRT',
  'profile.background.interiorHabs': '室内 · 居住区',
  'profile.background.interiorMemorial': '室内 · 纪念馆',
  'profile.background.interiorRefinery': '室内 · 精炼站',
  'profile.background.interiorShops': '室内 · 商店',
  'profile.background.exterior01': '外景 01',
  'profile.background.exterior02': '外景 02',
  'profile.background.exterior03': '外景 03',
  'profile.background.starCitizen40': 'Star Citizen 4.0',
  'profile.page.title': '个人主页',
  'profile.page.description': '展示你愿意公开的游戏资料。',
  'profile.visibility.public': '所有人可见',
  'profile.visibility.friendsAndMainFleet': '好友与主舰队成员可见',
  'profile.visibility.friendsOnly': '仅好友可见',
  'profile.visibility.private': '仅自己可见',
  'profile.visibility.publicDescription': '所有登录用户都可以查看你的个人主页。',
  'profile.visibility.friendsAndMainFleetDescription':
      '好友以及你当前主舰队的成员可以查看；其他组织和房间成员不包含在内。',
  'profile.visibility.friendsOnlyDescription': '只有你的好友可以查看个人主页。',
  'profile.visibility.privateDescription': '只有你自己可以查看个人主页。',
  'profile.preview.action': '预览访客视角',
  'profile.preview.title': '正在预览访客视角',
  'profile.preview.body': '当前只显示其他玩家能够看到的公开内容。',
  'profile.preview.exit': '返回我的主页',
  'profile.private.title': '这个主页暂未公开',
  'profile.private.body': '访客无法查看身份介绍、协作资料和公开模块。',
  'profile.presence.availableSupport': '可提供支援',
  'profile.about.title': '个人介绍',
  'profile.about.empty': '这个人还没有填写个人简介。',
  'profile.affiliation.title': '组织归属',
  'profile.affiliation.empty': '暂未展示舰队或社区组织。',
  'profile.affiliation.position.fleetMember': '舰队成员',
  'profile.affiliation.position.operationHost': '行动组织者',
  'profile.availability.title': '通常可游玩时间',
  'profile.availability.weekdays': '工作日',
  'profile.availability.weekend': '周末',
  'profile.availability.timeZone': '所在时区',
  'profile.playtime.title': '游戏时长',
  'profile.playtime.hours': '小时',
  'profile.playtime.minutes': '分钟',
  'profile.activity.title': '活动节奏',
  'profile.activity.casual': '休闲',
  'profile.activity.regular': '规律',
  'profile.activity.intensive': '高强度',
  'profile.collaboration.title': '协作资料',
  'profile.roles.title': '擅长岗位',
  'profile.participation.title': '参与偏好',
  'profile.support.title': '支援能力',
  'profile.wishlist.title': '舰船愿望单',
  'profile.module.unavailable': '此主页模块需要更新客户端后查看',
  'profile.layout.editHint': '编辑模式：按住整个模块即可拖动，经过格位时其他模块会自动让位；布局与资料一起保存。',
  'profile.layout.addModule': '添加模块',
  'profile.layout.drag': '拖动模块',
  'profile.layout.size': '模块尺寸',
  'profile.layout.size.one': '1 格',
  'profile.layout.size.two': '2 格',
  'profile.layout.size.three': '3 格',
  'profile.layout.remove': '从主页移除',
  'profile.layout.empty': '主页暂时没有公开模块。编辑主页后可以从九宫格中添加。',
  'profile.layout.noSpace': '九宫格剩余空间不足，请先缩小、移动或移除其他模块。',
  'profile.role.expeditionCommander': '远征指挥',
  'profile.role.pilot': '驾驶员',
  'profile.role.gunner': '炮手',
  'profile.role.fighterPilot': '战斗机驾驶员',
  'profile.role.primary': '主岗位',
  'profile.playstyle.pveCombat': 'PVE 战斗',
  'profile.support.pilot': '驾驶',
  'profile.support.gunner': '炮手',
  'profile.ships.title': '最爱舰船',
  'profile.shipRole.expedition': '远征',
  'profile.shipRole.salvage': '打捞',
  'profile.shipRole.multirole': '多用途',
  'profile.ship.crew': '建议机组',
  'profile.ship.manufacturer': '制造商',
  'profile.ship.size': '尺级',
  'profile.shipData.title': '舰船资料',
  'profile.shipData.role': '定位',
  'profile.shipData.officialValue': '官网价值',
  'profile.shipData.close': '关闭舰船资料',
  'profile.shipSize.small': '小型',
  'profile.shipSize.medium': '中型',
  'profile.shipSize.large': '大型',
  'profile.hangar.title': '舰船概览',
  'profile.legacyRole.fleet-command': '舰队指挥',
  'profile.legacyRole.squad-command': '小队指挥',
  'profile.legacyRole.action-coordination': '行动协调',
  'profile.legacyRole.navigator': '领航员',
  'profile.legacyRole.pilot': '驾驶员',
  'profile.legacyRole.copilot': '副驾驶',
  'profile.legacyRole.gunner': '炮手',
  'profile.legacyRole.ship-engineer': '舰船工程师',
  'profile.legacyRole.remote-weapon-operator': '远程武器操作员',
  'profile.legacyRole.fighter-pilot': '战斗机驾驶员',
  'profile.legacyRole.interceptor-pilot': '拦截机驾驶员',
  'profile.legacyRole.bomber-pilot': '轰炸机驾驶员',
  'profile.legacyRole.carrier-pilot': '舰载机驾驶员',
  'profile.legacyRole.assault-trooper': '突击队员',
  'profile.legacyRole.sniper': '狙击手',
  'profile.legacyRole.heavy-gunner': '重武器手',
  'profile.legacyRole.boarding-specialist': '登舰队员',
  'profile.legacyRole.vehicle-driver': '载具驾驶员',
  'profile.legacyRole.scout': '侦察员',
  'profile.legacyRole.route-planner': '路径规划',
  'profile.legacyRole.scanner-operator': '扫描操作员',
  'profile.legacyRole.intel-observer': '情报观察员',
  'profile.legacyRole.mining-operator': '采矿操作员',
  'profile.legacyRole.salvage-operator': '打捞操作员',
  'profile.legacyRole.cargo-specialist': '货运专员',
  'profile.legacyRole.trader': '贸易专员',
  'profile.legacyRole.resource-processor': '资源处理员',
  'profile.legacyRole.medic': '医疗兵',
  'profile.legacyRole.search-and-rescue': '搜救人员',
  'profile.legacyRole.casualty-transport': '伤员转运',
  'profile.legacyRole.field-medic': '战地救护',
  'profile.legacyRole.supply-specialist': '补给人员',
  'profile.legacyRole.maintenance-engineer': '维修工程师',
  'profile.legacyRole.ship-dispatcher': '舰船调度',
  'profile.legacyRole.transport-driver': '运输驾驶员',
  'profile.hangar.notConnected': '机库资料待接入，舰船数量与构成暂不可用。',
  'profile.ships.pendingDetails': '已保留 {count} 艘最爱舰船，详情将在机库接入后显示。',
  'profile.ships.notConnected': '机库资料尚未接入，暂时无法显示最爱舰船。',
  'profile.ships.empty': '还没有设置最爱舰船。',
  'profile.hangar.shipCount': '舰船总数',
  'profile.hangar.manufacturerCount': '舰船厂商',
  'profile.hangar.primaryRole': '主要类型',
  'profile.hangar.estimatedValue': '机库总价值',
  'profile.hangar.composition': '舰种构成',
  'profile.hangar.category.combat': '战斗',
  'profile.hangar.category.other': '其他',
  'profile.hangar.recentlyAdded': '最近入库',
  'profile.hangar.source': '资料来源',
  'profile.hangar.source.rsiSync': 'RSI 机库同步',
  'profile.hangar.unit': '艘',
  'profile.hangar.categoryUnit': '类',
  'profile.hangar.categoryCoverage': '舰种覆盖',
  'profile.hangar.primaryType': '主力类型',
  'profile.hangar.none': '暂无',
  'profile.hangar.syncedAt': '最近同步',
  'profile.hangar.importedAt': '入库',
  'profile.position.title': '游戏定位',
  'profile.error.saveFailed': '个人页面暂时无法保存，请稍后重试。',
};

const traditionalProfileSettingsStrings = <String, String>{
  'profile.avatar.change': '更換帳號頭像',
  'profile.avatar.shared': '帳號頭像用於個人主頁、組織和聊天。更換後立即生效。',
  'profile.avatar.managed': '此頭像由登入帳號管理。',
  'profile.avatar.confirm': '將更換此帳號在個人主頁、組織和聊天中的頭像。此操作會單獨儲存。',
  'profile.avatar.saving': '正在更換…',
  'profile.avatar.saved': '帳號頭像已更換。',
  'profile.avatar.failed': '暫時無法確認頭像是否已更換，請重新整理帳號狀態後再試。',
  ..._sharedProfileBackgroundNames,
  'common.cancel': '取消',
  'common.save': '儲存',
  'legal.page.title': '關於與法律',
  'legal.page.description': '查看 StarBridge 使用的第三方素材、商標與發佈包聲明。',
  'legal.about.description': '面向 Star Citizen 玩家的非商業 Windows 協作客戶端。',
  'legal.fankit.title': 'CIG Fankit 素材與商標聲明',
  'legal.fankit.summary':
      '個人主頁中的部分內建背景來自 CIG Fankit；StarBridge 是獨立粉絲專案，不代表 CIG、RSI 或其關聯公司。',
  'legal.fankit.nonCommercial':
      'StarBridge 客戶端不會向使用者收費；內建 Fankit 素材僅用於表達對 Star Citizen 的支持。',
  'legal.fankit.requiredNotice': '協議要求保留的英文聲明',
  'legal.fankit.watermark': '原始素材自帶的商標浮水印、品牌名稱與權利標記均保持不變。',
  'legal.fankit.source': '協議來源：素材包隨附的 CIG Fankit Agreement。',
  'legal.fankit.inlineAction': '素材與商標聲明',
  'legal.close': '關閉聲明',
  'legal.distribution.title': '發佈包聲明',
  'legal.distribution.body': '正式發佈包同時攜帶 THIRD-PARTY-NOTICES.md 和 CIG-FANKIT-NOTICE.txt；這些聲明不授予對素材的再授權。',
  'profile.loading': '正在讀取個人頁面…',
  'profile.refresh': '重新整理個人頁面',
  'profile.retrying': '正在重試…',
  'profile.signedOut.title': '登入後查看個人頁面',
  'profile.signedOut.body': '個人頁面只展示可公開的資料；帳號、電子郵件與身分狀態仍保留在「設定 → 帳號與識別」。',
  'profile.unavailable.title': '暫時無法讀取個人頁面',
  'profile.unavailable.retry': '重新讀取',
  'profile.error.unavailable': '個人主頁服務暫時無法使用，請檢查連線後再試。',
  'profile.error.refreshBeforeSave': '目前主頁尚未讀取完成或帳號已變更。請重新讀取個人頁面後再編輯儲存。',
  'profile.error.hostUnavailable': 'Native Host 目前無法使用，請重新啟動客戶端後再試。',
  'profile.error.reauthorizationRequired': '目前的 SCM 授權已失效，請前往「設定 → 帳號與識別」重新登入。',
  'profile.error.compatibilityMismatch': 'SCM 關聯身分與舊資料帳號不一致，已阻止讀取。',
  'profile.error.invalidResponse': '個人資料回應格式不相容，客戶端沒有使用不完整資料。',
  'profile.error.readOnly': '目前個人頁面僅支援讀取。',
  'profile.readOnly.notice': '目前顯示的內容已從舊資料服務讀取；編輯與背景同步會在後續寫入契約完成後開放。',
  'profile.edit.action': '編輯個人頁面',
  'profile.edit.title': '編輯個人頁面',
  'profile.edit.description': '調整公開展示欄位；模組內容與順序會在同一頁面繼續編輯。',
  'profile.edit.avatar': '頭像',
  'profile.edit.avatarPreserved': '沿用帳號頭像；本頁編輯不會更換頭像。',
  'profile.edit.wallpaper': '主頁背景',
  'profile.edit.wallpaperDescription': '選擇鋪滿整個個人主頁的背景；會隨視窗大小自適應，切換語言不會改變你的選擇。',
  'profile.edit.wallpaperFankitNotice':
      '內建 Star Citizen Fankit 背景原圖保留自帶商標浮水印；選擇前可查看完整聲明。',
  'profile.edit.backgroundCurrent': '目前背景',
  'profile.edit.backgroundChoose': '選擇背景',
  'profile.edit.backgroundPickerTitle': '選擇主頁背景',
  'profile.edit.backgroundPickerDescription': '背景在獨立面板中選擇，不會擠佔其他主頁設定。',
  'profile.edit.visibility': '主頁可見範圍',
  'profile.edit.callSign': '呼號',
  'profile.edit.about': '個人簡介',
  'profile.edit.gameHandle': '遊戲 ID 由帳號與識別管理：',
  'profile.edit.saving': '正在儲存…',
  'profile.background.none': '預設背景',
  'profile.background.formationFlight': '編隊飛行',
  'profile.background.interiorCorridor': '室內 · 走廊',
  'profile.background.interiorGrdBrt': '室內 · GRD-BRT',
  'profile.background.interiorHabs': '室內 · 居住區',
  'profile.background.interiorMemorial': '室內 · 紀念館',
  'profile.background.interiorRefinery': '室內 · 精煉站',
  'profile.background.interiorShops': '室內 · 商店',
  'profile.background.exterior01': '外景 01',
  'profile.background.exterior02': '外景 02',
  'profile.background.exterior03': '外景 03',
  'profile.background.starCitizen40': 'Star Citizen 4.0',
  'profile.page.title': '個人主頁',
  'profile.page.description': '展示你願意公開的遊戲資料。',
  'profile.visibility.public': '所有人可見',
  'profile.visibility.friendsAndMainFleet': '好友與主艦隊成員可見',
  'profile.visibility.friendsOnly': '僅好友可見',
  'profile.visibility.private': '僅自己可見',
  'profile.visibility.publicDescription': '所有登入使用者都可以查看你的個人主頁。',
  'profile.visibility.friendsAndMainFleetDescription':
      '好友以及你目前主艦隊的成員可以查看；其他組織和房間成員不包含在內。',
  'profile.visibility.friendsOnlyDescription': '只有你的好友可以查看個人主頁。',
  'profile.visibility.privateDescription': '只有你自己可以查看個人主頁。',
  'profile.preview.action': '預覽訪客視角',
  'profile.preview.title': '正在預覽訪客視角',
  'profile.preview.body': '目前只顯示其他玩家能夠看到的公開內容。',
  'profile.preview.exit': '返回我的主頁',
  'profile.private.title': '這個主頁暫未公開',
  'profile.private.body': '訪客無法查看身分介紹、協作資料和公開模組。',
  'profile.presence.availableSupport': '可提供支援',
  'profile.about.title': '個人介紹',
  'profile.about.empty': '這個人還沒有填寫個人簡介。',
  'profile.affiliation.title': '組織歸屬',
  'profile.affiliation.empty': '暫未展示艦隊或社群組織。',
  'profile.affiliation.position.fleetMember': '艦隊成員',
  'profile.affiliation.position.operationHost': '行動組織者',
  'profile.availability.title': '通常可遊玩時間',
  'profile.availability.weekdays': '工作日',
  'profile.availability.weekend': '週末',
  'profile.availability.timeZone': '所在時區',
  'profile.playtime.title': '遊戲時長',
  'profile.playtime.hours': '小時',
  'profile.playtime.minutes': '分鐘',
  'profile.activity.title': '活動節奏',
  'profile.activity.casual': '休閒',
  'profile.activity.regular': '規律',
  'profile.activity.intensive': '高強度',
  'profile.collaboration.title': '協作資料',
  'profile.roles.title': '擅長崗位',
  'profile.participation.title': '參與偏好',
  'profile.support.title': '支援能力',
  'profile.wishlist.title': '艦船願望清單',
  'profile.module.unavailable': '此主頁模組需要更新客戶端後查看',
  'profile.layout.editHint': '編輯模式：按住整個模組即可拖動，經過格位時其他模組會自動讓位；版面與資料一起儲存。',
  'profile.layout.addModule': '新增模組',
  'profile.layout.drag': '拖動模組',
  'profile.layout.size': '模組尺寸',
  'profile.layout.size.one': '1 格',
  'profile.layout.size.two': '2 格',
  'profile.layout.size.three': '3 格',
  'profile.layout.remove': '從主頁移除',
  'profile.layout.empty': '主頁暫時沒有公開模組。編輯主頁後可以從九宮格中新增。',
  'profile.layout.noSpace': '九宮格剩餘空間不足，請先縮小、移動或移除其他模組。',
  'profile.role.expeditionCommander': '遠征指揮',
  'profile.role.pilot': '駕駛員',
  'profile.role.gunner': '砲手',
  'profile.role.fighterPilot': '戰鬥機駕駛員',
  'profile.role.primary': '主要崗位',
  'profile.playstyle.pveCombat': 'PVE 戰鬥',
  'profile.support.pilot': '駕駛',
  'profile.support.gunner': '砲手',
  'profile.ships.title': '最愛艦船',
  'profile.shipRole.expedition': '遠征',
  'profile.shipRole.salvage': '打撈',
  'profile.shipRole.multirole': '多用途',
  'profile.ship.crew': '建議機組',
  'profile.ship.manufacturer': '製造商',
  'profile.ship.size': '尺級',
  'profile.shipData.title': '艦船資料',
  'profile.shipData.role': '定位',
  'profile.shipData.officialValue': '官網價值',
  'profile.shipData.close': '關閉艦船資料',
  'profile.shipSize.small': '小型',
  'profile.shipSize.medium': '中型',
  'profile.shipSize.large': '大型',
  'profile.hangar.title': '艦船概覽',
  'profile.legacyRole.fleet-command': '艦隊指揮',
  'profile.legacyRole.squad-command': '小隊指揮',
  'profile.legacyRole.action-coordination': '行動協調',
  'profile.legacyRole.navigator': '領航員',
  'profile.legacyRole.pilot': '駕駛員',
  'profile.legacyRole.copilot': '副駕駛',
  'profile.legacyRole.gunner': '砲手',
  'profile.legacyRole.ship-engineer': '艦船工程師',
  'profile.legacyRole.remote-weapon-operator': '遠端武器操作員',
  'profile.legacyRole.fighter-pilot': '戰鬥機駕駛員',
  'profile.legacyRole.interceptor-pilot': '攔截機駕駛員',
  'profile.legacyRole.bomber-pilot': '轟炸機駕駛員',
  'profile.legacyRole.carrier-pilot': '艦載機駕駛員',
  'profile.legacyRole.assault-trooper': '突擊隊員',
  'profile.legacyRole.sniper': '狙擊手',
  'profile.legacyRole.heavy-gunner': '重武器手',
  'profile.legacyRole.boarding-specialist': '登艦隊員',
  'profile.legacyRole.vehicle-driver': '載具駕駛員',
  'profile.legacyRole.scout': '偵察員',
  'profile.legacyRole.route-planner': '路徑規劃',
  'profile.legacyRole.scanner-operator': '掃描操作員',
  'profile.legacyRole.intel-observer': '情報觀察員',
  'profile.legacyRole.mining-operator': '採礦操作員',
  'profile.legacyRole.salvage-operator': '打撈操作員',
  'profile.legacyRole.cargo-specialist': '貨運專員',
  'profile.legacyRole.trader': '貿易專員',
  'profile.legacyRole.resource-processor': '資源處理員',
  'profile.legacyRole.medic': '醫療兵',
  'profile.legacyRole.search-and-rescue': '搜救人員',
  'profile.legacyRole.casualty-transport': '傷員轉運',
  'profile.legacyRole.field-medic': '戰地救護',
  'profile.legacyRole.supply-specialist': '補給人員',
  'profile.legacyRole.maintenance-engineer': '維修工程師',
  'profile.legacyRole.ship-dispatcher': '艦船調度',
  'profile.legacyRole.transport-driver': '運輸駕駛員',
  'profile.hangar.notConnected': '機庫資料待接入，艦船數量與構成暫不可用。',
  'profile.ships.pendingDetails': '已保留 {count} 艘最愛艦船，詳情將在機庫接入後顯示。',
  'profile.ships.notConnected': '機庫資料尚未接入，暫時無法顯示最愛艦船。',
  'profile.ships.empty': '還沒有設定最愛艦船。',
  'profile.hangar.shipCount': '艦船總數',
  'profile.hangar.manufacturerCount': '艦船廠商',
  'profile.hangar.primaryRole': '主要類型',
  'profile.hangar.estimatedValue': '機庫總價值',
  'profile.hangar.composition': '艦種構成',
  'profile.hangar.category.combat': '戰鬥',
  'profile.hangar.category.other': '其他',
  'profile.hangar.recentlyAdded': '最近入庫',
  'profile.hangar.source': '資料來源',
  'profile.hangar.source.rsiSync': 'RSI 機庫同步',
  'profile.hangar.unit': '艘',
  'profile.hangar.categoryUnit': '類',
  'profile.hangar.categoryCoverage': '艦種覆蓋',
  'profile.hangar.primaryType': '主力類型',
  'profile.hangar.none': '暫無',
  'profile.hangar.syncedAt': '最近同步',
  'profile.hangar.importedAt': '入庫',
  'profile.position.title': '遊戲定位',
  'profile.error.saveFailed': '個人頁面暫時無法儲存，請稍後重試。',
};

const englishProfileSettingsStrings = <String, String>{
  'profile.avatar.change': 'Change account photo',
  'profile.avatar.shared': 'Used on your profile, in organizations and in chat. Changes apply immediately.',
  'profile.avatar.managed': 'This photo is managed by your sign-in account.',
  'profile.avatar.confirm': 'Change this account’s photo on your profile, in organizations and in chat? This is saved separately.',
  'profile.avatar.saving': 'Changing photo…',
  'profile.avatar.saved': 'Account photo changed.',
  'profile.avatar.failed': 'We could not confirm the change. Refresh your account status before trying again.',
  ..._sharedProfileBackgroundNames,
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'legal.page.title': 'About & legal',
  'legal.page.description': 'Review third-party assets, trademarks, and notices distributed with StarBridge.',
  'legal.about.description':
      'A non-commercial Windows collaboration client for Star Citizen players.',
  'legal.fankit.title': 'CIG Fankit asset and trademark notice',
  'legal.fankit.summary': 'Some built-in profile backgrounds come from the CIG Fankit. StarBridge is an independent fan project and does not represent CIG, RSI, or their affiliates.',
  'legal.fankit.nonCommercial': 'The StarBridge client does not charge users. Bundled Fankit assets are used only to show support for Star Citizen.',
  'legal.fankit.requiredNotice': 'Required English notice',
  'legal.fankit.watermark': 'Trademark watermarks, brand names, and ownership notices embedded in the original assets remain unchanged.',
  'legal.fankit.source': 'Agreement source: the CIG Fankit Agreement supplied with the asset pack.',
  'legal.fankit.inlineAction': 'Asset & trademark notice',
  'legal.close': 'Close notice',
  'legal.distribution.title': 'Distribution notices',
  'legal.distribution.body': 'Official packages also include THIRD-PARTY-NOTICES.md and CIG-FANKIT-NOTICE.txt. These notices do not sublicense the assets.',
  'profile.loading': 'Loading your profile…',
  'profile.refresh': 'Refresh profile',
  'profile.retrying': 'Retrying…',
  'profile.signedOut.title': 'Sign in to view your profile',
  'profile.signedOut.body': 'The profile shows public-facing information only. Account, email, and identity state remain under Settings → Account & identity.',
  'profile.unavailable.title': 'Your profile is temporarily unavailable',
  'profile.unavailable.retry': 'Read again',
  'profile.error.unavailable': 'The personal profile service is temporarily unavailable. Check your connection and retry.',
  'profile.error.refreshBeforeSave': 'The profile has not finished loading or the account has changed. Reload your personal profile before editing and saving.',
  'profile.error.hostUnavailable':
      'Native Host is unavailable. Restart the client and retry.',
  'profile.error.reauthorizationRequired': 'Your SCM authorization has expired. Sign in again under Settings → Account & identity.',
  'profile.error.compatibilityMismatch': 'The SCM-linked identity does not match the legacy account, so profile access was blocked.',
  'profile.error.invalidResponse': 'The profile response is incompatible. The client did not use incomplete data.',
  'profile.error.readOnly': 'The personal profile is currently read-only.',
  'profile.readOnly.notice': 'This profile was read from the legacy data service. Editing and background sync will open after the write contract is completed.',
  'profile.edit.action': 'Edit profile',
  'profile.edit.title': 'Edit profile',
  'profile.edit.description': 'Edit public presentation fields. Module content and order will remain on this page.',
  'profile.edit.avatar': 'Avatar',
  'profile.edit.avatarPreserved': 'Your account photo is preserved. Edits here do not change it.',
  'profile.edit.wallpaper': 'Profile background',
  'profile.edit.wallpaperDescription': 'Choose the background that fills your entire personal profile. It adapts to the window and stays the same when the language changes.',
  'profile.edit.wallpaperFankitNotice': 'Bundled Star Citizen Fankit background originals retain their trademark watermarks. Review the full notice before choosing one.',
  'profile.edit.backgroundCurrent': 'Current background',
  'profile.edit.backgroundChoose': 'Choose background',
  'profile.edit.backgroundPickerTitle': 'Choose profile background',
  'profile.edit.backgroundPickerDescription': 'Backgrounds open in a separate picker so the other profile settings stay in place.',
  'profile.edit.visibility': 'Profile visibility',
  'profile.edit.callSign': 'Call sign',
  'profile.edit.about': 'About',
  'profile.edit.gameHandle': 'Game ID is managed under Account & identity:',
  'profile.edit.saving': 'Saving…',
  'profile.background.none': 'Default background',
  'profile.background.formationFlight': 'Formation flight',
  'profile.background.interiorCorridor': 'Interior · Corridor',
  'profile.background.interiorGrdBrt': 'Interior · GRD-BRT',
  'profile.background.interiorHabs': 'Interior · Habitation',
  'profile.background.interiorMemorial': 'Interior · Memorial',
  'profile.background.interiorRefinery': 'Interior · Refinery',
  'profile.background.interiorShops': 'Interior · Shops',
  'profile.background.exterior01': 'Exterior 01',
  'profile.background.exterior02': 'Exterior 02',
  'profile.background.exterior03': 'Exterior 03',
  'profile.background.starCitizen40': 'Star Citizen 4.0',
  'profile.page.title': 'Personal profile',
  'profile.page.description': 'Show the game information you choose to share.',
  'profile.visibility.public': 'Visible to everyone',
  'profile.visibility.friendsAndMainFleet': 'Friends and main fleet members',
  'profile.visibility.friendsOnly': 'Friends only',
  'profile.visibility.private': 'Only me',
  'profile.visibility.publicDescription':
      'Every signed-in user can view your personal profile.',
  'profile.visibility.friendsAndMainFleetDescription': 'Friends and members of your current main fleet can view it. Other organizations and room members are not included.',
  'profile.visibility.friendsOnlyDescription':
      'Only your friends can view your personal profile.',
  'profile.visibility.privateDescription':
      'Only you can view your personal profile.',
  'profile.preview.action': 'Preview visitor view',
  'profile.preview.title': 'Previewing the visitor view',
  'profile.preview.body': 'Only information visible to other players is shown.',
  'profile.preview.exit': 'Return to my profile',
  'profile.private.title': 'This profile is private',
  'profile.private.body': 'Visitors cannot view identity details, collaboration information, or public modules.',
  'profile.presence.availableSupport': 'Available to support',
  'profile.about.title': 'Introduction',
  'profile.about.empty': 'This player has not added an introduction.',
  'profile.affiliation.title': 'Affiliations',
  'profile.affiliation.empty': 'No fleet or community affiliation is shown.',
  'profile.affiliation.position.fleetMember': 'Fleet member',
  'profile.affiliation.position.operationHost': 'Operation host',
  'profile.availability.title': 'Usual play time',
  'profile.availability.weekdays': 'Weekdays',
  'profile.availability.weekend': 'Weekends',
  'profile.availability.timeZone': 'Time zone',
  'profile.playtime.title': 'Play time',
  'profile.playtime.hours': 'h',
  'profile.playtime.minutes': 'min',
  'profile.activity.title': 'Activity rhythm',
  'profile.activity.casual': 'Casual',
  'profile.activity.regular': 'Regular',
  'profile.activity.intensive': 'Intensive',
  'profile.collaboration.title': 'Collaboration profile',
  'profile.roles.title': 'Skilled roles',
  'profile.participation.title': 'Participation',
  'profile.support.title': 'Support capabilities',
  'profile.wishlist.title': 'Ship wishlist',
  'profile.module.unavailable': 'Update the client to view this profile module',
  'profile.layout.editHint': 'Edit mode: drag anywhere on a module. Other modules make room as it crosses the grid; layout and profile fields save together.',
  'profile.layout.addModule': 'Add module',
  'profile.layout.drag': 'Drag module',
  'profile.layout.size': 'Module size',
  'profile.layout.size.one': '1 cell',
  'profile.layout.size.two': '2 cells',
  'profile.layout.size.three': '3 cells',
  'profile.layout.remove': 'Remove from profile',
  'profile.layout.empty': 'No public modules are shown. Edit the profile to add modules to the grid.',
  'profile.layout.noSpace': 'The grid has no suitable space. Resize, move, or remove another module first.',
  'profile.role.expeditionCommander': 'Expedition commander',
  'profile.role.pilot': 'Pilot',
  'profile.role.gunner': 'Gunner',
  'profile.role.fighterPilot': 'Fighter pilot',
  'profile.role.primary': 'Primary',
  'profile.playstyle.pveCombat': 'PVE combat',
  'profile.support.pilot': 'Piloting',
  'profile.support.gunner': 'Gunnery',
  'profile.ships.title': 'Favorite ships',
  'profile.shipRole.expedition': 'Expedition',
  'profile.shipRole.salvage': 'Salvage',
  'profile.shipRole.multirole': 'Multi-role',
  'profile.ship.crew': 'Suggested crew',
  'profile.ship.manufacturer': 'Manufacturer',
  'profile.ship.size': 'Size',
  'profile.shipData.title': 'Ship data',
  'profile.shipData.role': 'Role',
  'profile.shipData.officialValue': 'Official value',
  'profile.shipData.close': 'Close ship data',
  'profile.shipSize.small': 'Small',
  'profile.shipSize.medium': 'Medium',
  'profile.shipSize.large': 'Large',
  'profile.hangar.title': 'Hangar overview',
  'profile.legacyRole.fleet-command': 'Fleet commander',
  'profile.legacyRole.squad-command': 'Squad leader',
  'profile.legacyRole.action-coordination': 'Operations coordinator',
  'profile.legacyRole.navigator': 'Navigator',
  'profile.legacyRole.pilot': 'Pilot',
  'profile.legacyRole.copilot': 'Copilot',
  'profile.legacyRole.gunner': 'Gunner',
  'profile.legacyRole.ship-engineer': 'Ship engineer',
  'profile.legacyRole.remote-weapon-operator': 'Remote weapons operator',
  'profile.legacyRole.fighter-pilot': 'Fighter pilot',
  'profile.legacyRole.interceptor-pilot': 'Interceptor pilot',
  'profile.legacyRole.bomber-pilot': 'Bomber pilot',
  'profile.legacyRole.carrier-pilot': 'Carrier pilot',
  'profile.legacyRole.assault-trooper': 'Assault trooper',
  'profile.legacyRole.sniper': 'Sniper',
  'profile.legacyRole.heavy-gunner': 'Heavy gunner',
  'profile.legacyRole.boarding-specialist': 'Boarding specialist',
  'profile.legacyRole.vehicle-driver': 'Vehicle driver',
  'profile.legacyRole.scout': 'Scout',
  'profile.legacyRole.route-planner': 'Route planner',
  'profile.legacyRole.scanner-operator': 'Scanner operator',
  'profile.legacyRole.intel-observer': 'Intelligence observer',
  'profile.legacyRole.mining-operator': 'Mining operator',
  'profile.legacyRole.salvage-operator': 'Salvage operator',
  'profile.legacyRole.cargo-specialist': 'Cargo specialist',
  'profile.legacyRole.trader': 'Trader',
  'profile.legacyRole.resource-processor': 'Resource processor',
  'profile.legacyRole.medic': 'Medic',
  'profile.legacyRole.search-and-rescue': 'Search and rescue',
  'profile.legacyRole.casualty-transport': 'Casualty transport',
  'profile.legacyRole.field-medic': 'Field medic',
  'profile.legacyRole.supply-specialist': 'Supply specialist',
  'profile.legacyRole.maintenance-engineer': 'Maintenance engineer',
  'profile.legacyRole.ship-dispatcher': 'Ship dispatcher',
  'profile.legacyRole.transport-driver': 'Transport driver',
  'profile.hangar.notConnected': 'Hangar data is not connected yet. Ship counts and composition are unavailable.',
  'profile.ships.pendingDetails': '{count} favorite ships are saved. Details will appear when hangar data is connected.',
  'profile.ships.notConnected':
      'Favorite ships are unavailable until hangar data is connected.',
  'profile.ships.empty': 'No favorite ships selected yet.',
  'profile.hangar.shipCount': 'Ships',
  'profile.hangar.manufacturerCount': 'Manufacturers',
  'profile.hangar.primaryRole': 'Primary role',
  'profile.hangar.estimatedValue': 'Estimated value',
  'profile.hangar.composition': 'Ship composition',
  'profile.hangar.category.combat': 'Combat',
  'profile.hangar.category.other': 'Other',
  'profile.hangar.recentlyAdded': 'Recently added',
  'profile.hangar.source': 'Source',
  'profile.hangar.source.rsiSync': 'RSI hangar sync',
  'profile.hangar.unit': '',
  'profile.hangar.categoryUnit': '',
  'profile.hangar.categoryCoverage': 'Role coverage',
  'profile.hangar.primaryType': 'Primary type',
  'profile.hangar.none': 'None',
  'profile.hangar.syncedAt': 'Last sync',
  'profile.hangar.importedAt': 'Added',
  'profile.position.title': 'Gameplay profile',
  'profile.error.saveFailed':
      'The profile could not be saved. Try again later.',
};
