const simplifiedProfileCollaborationStrings = <String, String>{
  'profile.collab.schedule': '游玩时段与活动节奏',
  'profile.collab.invalid': '请检查岗位选择、日期、时间和时区后重试。',
  'profile.collab.selectionInvalid': '请移除不支持的项目，并保持在选择数量内。',
  'profile.collab.zoneHint': '时段使用所选时区；更换时区不会换算填写的时间。',
  'profile.collab.chooseZone': '请选择时区。',
  'profile.collab.chooseDays': '请至少选择一天。',
  'profile.collab.addWindow': '添加时段',
  'profile.collab.window': '时段',
  'profile.collab.remove': '移除',
  'profile.collab.start': '开始时间',
  'profile.collab.end': '结束时间',
  'profile.collab.timeInvalid': '请输入 00:00–23:59',
  'profile.collab.overnight': '结束时间在次日。',
  'profile.collab.nextDay': '次日',
  'profile.collab.everyDay': '每天',
  'profile.collab.noTimes': '暂未设置游玩时段',
  'profile.activity.weekends': '周末为主',
  'profile.activity.irregular': '不固定',
  'profile.collab.day.0': '周日',
  'profile.collab.day.1': '周一',
  'profile.collab.day.2': '周二',
  'profile.collab.day.3': '周三',
  'profile.collab.day.4': '周四',
  'profile.collab.day.5': '周五',
  'profile.collab.day.6': '周六',
  'profile.collab.interests.fleet-operations': '舰队行动',
  'profile.collab.interests.squad-missions': '小队任务',
  'profile.collab.interests.pve': 'PVE 战斗',
  'profile.collab.interests.pvp': 'PVP 战斗',
  'profile.collab.interests.bounty': '赏金任务',
  'profile.collab.interests.ground': '地面行动',
  'profile.collab.interests.trading': '跑商运输',
  'profile.collab.interests.mining': '采矿',
  'profile.collab.interests.salvage': '打捞',
  'profile.collab.interests.exploration': '探索',
  'profile.collab.interests.racing': '竞速',
  'profile.collab.interests.social': '休闲社交',
  'profile.collab.support.command': '战术指挥',
  'profile.collab.support.pilot': '驾驶',
  'profile.collab.support.gunner': '炮手',
  'profile.collab.support.medical': '医疗救援',
  'profile.collab.support.supply': '后勤补给',
  'profile.collab.support.engineering': '工程维修',
  'profile.collab.support.navigation': '侦察导航',
  'profile.collab.support.transport': '人员运输',
  'profile.collab.support.teaching': '任务教学',
  'profile.collab.support.ship-sharing': '舰船共享',
};
const traditionalProfileCollaborationStrings = <String, String>{
  'profile.collab.schedule': '遊玩時段與活動節奏',
  'profile.collab.invalid': '請檢查崗位選擇、日期、時間和時區後重試。',
  'profile.collab.selectionInvalid': '請移除不支援的項目，並保持在選擇數量內。',
  'profile.collab.zoneHint': '時段使用所選時區；更換時區不會換算填寫的時間。',
  'profile.collab.chooseZone': '請選擇時區。',
  'profile.collab.chooseDays': '請至少選擇一天。',
  'profile.collab.addWindow': '新增時段',
  'profile.collab.window': '時段',
  'profile.collab.remove': '移除',
  'profile.collab.start': '開始時間',
  'profile.collab.end': '結束時間',
  'profile.collab.timeInvalid': '請輸入 00:00–23:59',
  'profile.collab.overnight': '結束時間在次日。',
  'profile.collab.nextDay': '次日',
  'profile.collab.everyDay': '每天',
  'profile.collab.noTimes': '暫未設定遊玩時段',
  'profile.activity.weekends': '週末為主',
  'profile.activity.irregular': '不固定',
  'profile.collab.day.0': '週日',
  'profile.collab.day.1': '週一',
  'profile.collab.day.2': '週二',
  'profile.collab.day.3': '週三',
  'profile.collab.day.4': '週四',
  'profile.collab.day.5': '週五',
  'profile.collab.day.6': '週六',
  'profile.collab.interests.fleet-operations': '艦隊行動',
  'profile.collab.interests.squad-missions': '小隊任務',
  'profile.collab.interests.pve': 'PVE 戰鬥',
  'profile.collab.interests.pvp': 'PVP 戰鬥',
  'profile.collab.interests.bounty': '賞金任務',
  'profile.collab.interests.ground': '地面行動',
  'profile.collab.interests.trading': '跑商運輸',
  'profile.collab.interests.mining': '採礦',
  'profile.collab.interests.salvage': '打撈',
  'profile.collab.interests.exploration': '探索',
  'profile.collab.interests.racing': '競速',
  'profile.collab.interests.social': '休閒社交',
  'profile.collab.support.command': '戰術指揮',
  'profile.collab.support.pilot': '駕駛',
  'profile.collab.support.gunner': '砲手',
  'profile.collab.support.medical': '醫療救援',
  'profile.collab.support.supply': '後勤補給',
  'profile.collab.support.engineering': '工程維修',
  'profile.collab.support.navigation': '偵察導航',
  'profile.collab.support.transport': '人員運輸',
  'profile.collab.support.teaching': '任務教學',
  'profile.collab.support.ship-sharing': '艦船共享',
};
const englishProfileCollaborationStrings = <String, String>{
  'profile.collab.schedule': 'Availability and activity',
  'profile.collab.invalid':
      'Check your selections, days, times and time zone, then retry.',
  'profile.collab.selectionInvalid':
      'Remove unsupported selections and stay within the selection limit.',
  'profile.collab.zoneHint': 'Times use this time zone. Changing it does not convert the times you entered.',
  'profile.collab.chooseZone': 'Choose a time zone.',
  'profile.collab.chooseDays': 'Select at least one day.',
  'profile.collab.addWindow': 'Add time window',
  'profile.collab.window': 'Time window',
  'profile.collab.remove': 'Remove',
  'profile.collab.start': 'Start',
  'profile.collab.end': 'End',
  'profile.collab.timeInvalid': 'Use 00:00–23:59',
  'profile.collab.overnight': 'Ends on the following day.',
  'profile.collab.nextDay': 'next day',
  'profile.collab.everyDay': 'Every day',
  'profile.collab.noTimes': 'No time windows set',
  'profile.activity.weekends': 'Mostly weekends',
  'profile.activity.irregular': 'Varies',
  'profile.collab.day.0': 'Sun',
  'profile.collab.day.1': 'Mon',
  'profile.collab.day.2': 'Tue',
  'profile.collab.day.3': 'Wed',
  'profile.collab.day.4': 'Thu',
  'profile.collab.day.5': 'Fri',
  'profile.collab.day.6': 'Sat',
  'profile.collab.interests.fleet-operations': 'Fleet operations',
  'profile.collab.interests.squad-missions': 'Squad missions',
  'profile.collab.interests.pve': 'PVE combat',
  'profile.collab.interests.pvp': 'PVP combat',
  'profile.collab.interests.bounty': 'Bounty hunting',
  'profile.collab.interests.ground': 'Ground operations',
  'profile.collab.interests.trading': 'Trading and hauling',
  'profile.collab.interests.mining': 'Mining',
  'profile.collab.interests.salvage': 'Salvage',
  'profile.collab.interests.exploration': 'Exploration',
  'profile.collab.interests.racing': 'Racing',
  'profile.collab.interests.social': 'Casual socializing',
  'profile.collab.support.command': 'Tactical command',
  'profile.collab.support.pilot': 'Piloting',
  'profile.collab.support.gunner': 'Gunnery',
  'profile.collab.support.medical': 'Medical rescue',
  'profile.collab.support.supply': 'Resupply',
  'profile.collab.support.engineering': 'Engineering',
  'profile.collab.support.navigation': 'Recon and navigation',
  'profile.collab.support.transport': 'Personnel transport',
  'profile.collab.support.teaching': 'Mission training',
  'profile.collab.support.ship-sharing': 'Ship sharing',
};
