// Room lifecycle copy. Keep mutations and uncertain outcomes explicit.
const simplifiedRoomActionStrings = <String, String>{
  'rooms.action.create': "创建房间",
  'rooms.action.edit': '房间设置',
  'rooms.action.save': '保存设置',
  'rooms.action.close': '解散房间',
  'rooms.action.closeHint': '解散后所有成员都将离开，现有房间码将失效。此操作无法撤销。',
  'rooms.action.applications': '加入申请',
  'rooms.action.noApplications': '暂无待处理的加入申请。',
  'rooms.action.approve': '批准',
  'rooms.action.decline': '拒绝',
  'rooms.action.done': '完成',
  'rooms.action.updated': '房间设置已保存。',
  'rooms.action.approved': '已批准加入申请。',
  'rooms.action.declined': '已拒绝加入申请。',
  'rooms.action.keepPasswordHint': '密码留空将保留原密码；输入新密码会替换原密码。',
  'rooms.action.resetDurationHint': '保存后，招募时长和自动解散时间将从现在重新计时。',
  'rooms.action.notHost': '你已不是这个房间的房主，请刷新房间。',
  'rooms.action.applicationGone': '这条申请已处理或失效，请刷新房间。',
  'rooms.action.applicantMoved': '该玩家已加入其他房间，请刷新申请列表。',
  'rooms.action.capacityTooSmall': '人数上限不能低于当前成员数。',
  'rooms.action.scopeManaged': '创建或加入房间，房主可管理设置与申请。邀请和聊天暂未开放。',
  'rooms.action.join': "加入房间",
  'rooms.action.apply': "申请加入",
  'rooms.action.leave': "退出房间",
  'rooms.action.codeJoin': "输入房间码",
  'rooms.action.resolve': "查找房间",
  'rooms.action.code': "房间码",
  'rooms.action.copyCode': "复制房间码",
  'rooms.action.cancel': "取消",
  'rooms.action.working': "正在处理…",
  'rooms.action.title': "房间名称",
  'rooms.action.capacity': "人数上限",
  'rooms.action.passwordEnabled': "需要密码",
  'rooms.action.goal': "组队目标",
  'rooms.action.titleInvalid': "名称需要 2–32 个字符。",
  'rooms.action.passwordInvalid': "密码需要 4–32 个字符。",
  'rooms.action.disband': "自动解散",
  'rooms.action.hours': "小时",
  'rooms.action.minutes': "分钟",
  'rooms.action.recruitmentDuration': "招募时长",
  'rooms.action.unlimited': "不限时",
  'rooms.action.addTag': "添加房间标签",
  'rooms.action.tagsRequired': "选择 1–3 条玩法路径，附加标签最多 3 个，合计最多 5 个。",
  'rooms.action.durationInvalid': "招募截止不能晚于自动解散。",
  'rooms.action.leaveHint': "退出后可继续浏览其他房间。",
  'rooms.action.leaveHostHint': "退出后将自动移交房主；如果没有其他成员，房间将解散。",
  'rooms.action.approvalHint': "需要房主批准。提交申请后不会立即加入房间。",
  'rooms.action.joinHint': "确认后加入这个房间。",
  'rooms.action.codeRequired': "请输入房间码。",
  'rooms.action.joined': "已加入房间。",
  'rooms.action.pending': "申请已提交，等待房主批准。",
  'rooms.action.left': "已退出房间。",
  'rooms.action.closed': "房间已解散。",
  'rooms.action.resolved': "已找到房间，请确认加入。",
  'rooms.action.rejected': "未能完成操作，请刷新房间后检查加入条件。",
  'rooms.action.passwordIncorrect': "房间密码不正确。",
  'rooms.action.roomFull': "房间已满员。",
  'rooms.action.roomGone': "房间不存在或已解散。",
  'rooms.action.recruitmentClosed': "房间已停止招募。",
  'rooms.action.outcomeUnknown': "操作结果尚未确认，请先刷新房间再决定是否重试。",
  'rooms.action.refreshRequired': "操作已受理，但房间状态未能更新，请刷新确认。",
  'rooms.action.contextChanged': "账号或页面已变化，请关闭后重新打开。",
  'rooms.action.invalidInput': "请检查房间设置后重试。",
  'rooms.action.identityUnavailable': "房间服务暂未确认账号授权。",
  'rooms.action.forbidden': "当前账号无权执行此操作。",
  'rooms.action.hostUnavailable': "请更新或重启客户端后重试。",
  'rooms.action.unavailable': "暂时无法执行，请稍后重试。",
  'rooms.action.scope': "创建或加入房间。房主管理、邀请和聊天暂未开放。",
};
const traditionalRoomActionStrings = <String, String>{
  'rooms.action.create': "建立房間",
  'rooms.action.edit': '房間設定',
  'rooms.action.save': '儲存設定',
  'rooms.action.close': '解散房間',
  'rooms.action.closeHint': '解散後所有成員都將離開，現有房間碼將失效。此操作無法復原。',
  'rooms.action.applications': '加入申請',
  'rooms.action.noApplications': '暫無待處理的加入申請。',
  'rooms.action.approve': '批准',
  'rooms.action.decline': '拒絕',
  'rooms.action.done': '完成',
  'rooms.action.updated': '房間設定已儲存。',
  'rooms.action.approved': '已批准加入申請。',
  'rooms.action.declined': '已拒絕加入申請。',
  'rooms.action.keepPasswordHint': '密碼留空將保留原密碼；輸入新密碼會替換原密碼。',
  'rooms.action.resetDurationHint': '儲存後，招募時長和自動解散時間將從現在重新計時。',
  'rooms.action.notHost': '你已不是這個房間的房主，請重新整理房間。',
  'rooms.action.applicationGone': '這條申請已處理或失效，請重新整理房間。',
  'rooms.action.applicantMoved': '該玩家已加入其他房間，請重新整理申請清單。',
  'rooms.action.capacityTooSmall': '人數上限不能低於目前成員數。',
  'rooms.action.scopeManaged': '建立或加入房間，房主可管理設定與申請。邀請和聊天暫未開放。',
  'rooms.action.join': "加入房間",
  'rooms.action.apply': "申請加入",
  'rooms.action.leave': "退出房間",
  'rooms.action.codeJoin': "輸入房間碼",
  'rooms.action.resolve': "尋找房間",
  'rooms.action.code': "房間碼",
  'rooms.action.copyCode': "複製房間碼",
  'rooms.action.cancel': "取消",
  'rooms.action.working': "正在處理…",
  'rooms.action.title': "房間名稱",
  'rooms.action.capacity': "人數上限",
  'rooms.action.passwordEnabled': "需要密碼",
  'rooms.action.goal': "組隊目標",
  'rooms.action.titleInvalid': "名稱需要 2–32 個字元。",
  'rooms.action.passwordInvalid': "密碼需要 4–32 個字元。",
  'rooms.action.disband': "自動解散",
  'rooms.action.hours': "小時",
  'rooms.action.minutes': "分鐘",
  'rooms.action.recruitmentDuration': "招募時長",
  'rooms.action.unlimited': "不限時",
  'rooms.action.addTag': "新增房間標籤",
  'rooms.action.tagsRequired': "選擇 1–3 條玩法路徑，附加標籤最多 3 個，合計最多 5 個。",
  'rooms.action.durationInvalid': "招募截止不能晚於自動解散。",
  'rooms.action.leaveHint': "退出後可繼續瀏覽其他房間。",
  'rooms.action.leaveHostHint': "退出後將自動移交房主；如果沒有其他成員，房間將解散。",
  'rooms.action.approvalHint': "需要房主批准。提交申請後不會立即加入房間。",
  'rooms.action.joinHint': "確認後加入這個房間。",
  'rooms.action.codeRequired': "請輸入房間碼。",
  'rooms.action.joined': "已加入房間。",
  'rooms.action.pending': "申請已提交，等待房主批准。",
  'rooms.action.left': "已退出房間。",
  'rooms.action.closed': "房間已解散。",
  'rooms.action.resolved': "已找到房間，請確認加入。",
  'rooms.action.rejected': "未能完成操作，請重新整理房間後檢查加入條件。",
  'rooms.action.passwordIncorrect': "房間密碼不正確。",
  'rooms.action.roomFull': "房間已滿員。",
  'rooms.action.roomGone': "房間不存在或已解散。",
  'rooms.action.recruitmentClosed': "房間已停止招募。",
  'rooms.action.outcomeUnknown': "操作結果尚未確認，請先重新整理房間再決定是否重試。",
  'rooms.action.refreshRequired': "操作已受理，但房間狀態未能更新，請重新整理確認。",
  'rooms.action.contextChanged': "帳號或頁面已變更，請關閉後重新開啟。",
  'rooms.action.invalidInput': "請檢查房間設定後重試。",
  'rooms.action.identityUnavailable': "房間服務暫未確認帳號授權。",
  'rooms.action.forbidden': "目前帳號無權執行此操作。",
  'rooms.action.hostUnavailable': "請更新或重新啟動用戶端後重試。",
  'rooms.action.unavailable': "暫時無法執行，請稍後重試。",
  'rooms.action.scope': "建立或加入房間。房主管理、邀請和聊天暫未開放。",
};
const englishRoomActionStrings = <String, String>{
  'rooms.action.create': "Create room",
  'rooms.action.edit': 'Room settings',
  'rooms.action.save': 'Save settings',
  'rooms.action.close': 'Disband room',
  'rooms.action.closeHint': 'All members will leave and the room code will stop working. This cannot be undone.',
  'rooms.action.applications': 'Join requests',
  'rooms.action.noApplications': 'No pending join requests.',
  'rooms.action.approve': 'Approve',
  'rooms.action.decline': 'Decline',
  'rooms.action.done': 'Done',
  'rooms.action.updated': 'Room settings saved.',
  'rooms.action.approved': 'Join request approved.',
  'rooms.action.declined': 'Join request declined.',
  'rooms.action.keepPasswordHint': 'Leave the password blank to keep it, or enter a new password to replace it.',
  'rooms.action.resetDurationHint':
      'Saving restarts the recruitment and auto-disband timers from now.',
  'rooms.action.notHost':
      'You are no longer the host of this room. Refresh rooms.',
  'rooms.action.applicationGone':
      'This request was handled or expired. Refresh rooms.',
  'rooms.action.applicantMoved':
      'This player joined another room. Refresh the requests.',
  'rooms.action.capacityTooSmall':
      'The limit cannot be lower than the current member count.',
  'rooms.action.scopeManaged': 'Create or join a room. Hosts can manage settings and requests. Invitations and chat are not available yet.',
  'rooms.action.join': "Join room",
  'rooms.action.apply': "Request to join",
  'rooms.action.leave': "Leave room",
  'rooms.action.codeJoin': "Enter room code",
  'rooms.action.resolve': "Find room",
  'rooms.action.code': "Room code",
  'rooms.action.copyCode': "Copy room code",
  'rooms.action.cancel': "Cancel",
  'rooms.action.working': "Working…",
  'rooms.action.title': "Room name",
  'rooms.action.capacity': "Member limit",
  'rooms.action.passwordEnabled': "Require password",
  'rooms.action.goal': "Goal",
  'rooms.action.titleInvalid': "Use 2–32 characters.",
  'rooms.action.passwordInvalid': "Use 4–32 characters.",
  'rooms.action.disband': "Auto-disband after",
  'rooms.action.hours': "hours",
  'rooms.action.minutes': "minutes",
  'rooms.action.recruitmentDuration': "Recruitment duration",
  'rooms.action.unlimited': "No cutoff",
  'rooms.action.addTag': "Add room tag",
  'rooms.action.tagsRequired':
      "Choose 1–3 gameplay paths, up to 3 extra tags and 5 tags total.",
  'rooms.action.durationInvalid':
      "Recruitment must end before the room disbands.",
  'rooms.action.leaveHint': "You can browse other rooms after leaving.",
  'rooms.action.leaveHostHint': "Host ownership will transfer automatically. If nobody remains, the room will close.",
  'rooms.action.approvalHint':
      "Host approval is required. Sending a request does not join the room.",
  'rooms.action.joinHint': "Confirm to join this room.",
  'rooms.action.codeRequired': "Enter a room code.",
  'rooms.action.joined': "Joined the room.",
  'rooms.action.pending': "Request sent. Waiting for host approval.",
  'rooms.action.left': "Left the room.",
  'rooms.action.closed': "The room has closed.",
  'rooms.action.resolved': "Room found. Confirm to join.",
  'rooms.action.rejected':
      "The action was rejected. Refresh the room and check its requirements.",
  'rooms.action.passwordIncorrect': "Incorrect room password.",
  'rooms.action.roomFull': "The room is full.",
  'rooms.action.roomGone': "Room not found or closed.",
  'rooms.action.recruitmentClosed': "Recruitment has closed.",
  'rooms.action.outcomeUnknown':
      "The result is unknown. Refresh rooms before deciding whether to retry.",
  'rooms.action.refreshRequired': "The action was accepted, but room state could not refresh. Refresh to confirm.",
  'rooms.action.contextChanged':
      "The account or page changed. Close this dialog and reopen it.",
  'rooms.action.invalidInput': "Check the room settings and try again.",
  'rooms.action.identityUnavailable':
      "The room service could not confirm account authorization.",
  'rooms.action.forbidden': "This account cannot perform this action.",
  'rooms.action.hostUnavailable': "Update or restart the client and try again.",
  'rooms.action.unavailable': "Unavailable right now. Try again shortly.",
  'rooms.action.scope': "Create or join a room. Host management, invitations and chat are not available yet.",
};
