const simplifiedRoomSocialStrings = <String, String>{
  'rooms.action.sharePreset': '分享浮层预设',
  'rooms.action.sharePresetHint': '选择已保存的预设，添加到待发送消息。未保存的调整不会发送。',
  'rooms.action.importPreset': '导入为新预设',
  'rooms.action.importPresetHint': '新建一份本地预设，不覆盖或切换当前预设。外观仍需你的账号具备使用资格。',
  'rooms.action.presetImported': '已导入，可在浮层页切换：',
  'rooms.action.presetDraft': '待发送的浮层预设',
  'rooms.action.removeAttachment': '移除预设卡片',
  'rooms.action.noPresets': '暂无已保存的预设，请先在浮层页创建。',
  'rooms.action.presetChanged': '本地预设已变化，请关闭后重新选择。',
  'rooms.action.presetInvalid': '预设内容无效或版本不支持，请让发送者重新分享。',
  'rooms.action.presetImportUnknown': '未能确认导入结果。请先在浮层页检查，避免重复导入。',
  'rooms.action.refreshMessages': '刷新消息',
  'rooms.action.alreadyInvited': '已邀请',
  'rooms.action.chat': '房间聊天',
  'rooms.action.chatEmpty': '还没有消息，在这里与房间成员交流。',
  'rooms.action.send': '发送',
  'rooms.action.chatDraft': '消息（最多 300 字）',
  'rooms.action.older': '加载更早消息',
  'rooms.action.latest': '回到最新消息',
  'rooms.action.chatRejected': '消息未发送，请检查房间状态，或稍后再试。',
  'rooms.action.notMember': '你已不在这个房间，请刷新房间。',
  'rooms.action.reviewSend': '我已核对消息，允许重新发送',
  'rooms.action.refreshList': '刷新名单',
  'rooms.action.invitations': '房间邀请',
  'rooms.action.inviteFriends': '邀请好友',
  'rooms.action.invite': '邀请',
  'rooms.action.revoke': '撤回',
  'rooms.action.received': '收到的邀请',
  'rooms.action.sent': '已发送的邀请',
  'rooms.action.noInvitations': '暂无房间邀请。',
  'rooms.action.noTargets': '暂无可邀请的好友。',
  'rooms.action.inviteHint': '邀请会在房间关闭、招募结束或最长 24 小时后失效。',
  'rooms.action.invited': '邀请已发送。',
  'rooms.action.revoked': '邀请已撤回。',
  'rooms.action.invitationDeclined': '已忽略邀请。',
  'rooms.action.targetGone': '该好友已不可邀请，请刷新名单。',
  'rooms.action.invitationGone': '邀请已处理或失效，请刷新房间。',
  'rooms.action.invitationRejected': '邀请操作未完成，请刷新并检查好友关系、房间人数和邀请有效期。',
  'rooms.action.alreadyJoined': '请先退出当前房间，再接受邀请。',
  'rooms.action.acceptInvitation': '接受邀请将直接加入此房间。',
  'rooms.action.scopeSocial': '创建或加入房间，与成员即时协作。',
};
const traditionalRoomSocialStrings = <String, String>{
  'rooms.action.sharePreset': '分享浮層預設',
  'rooms.action.sharePresetHint': '選擇已儲存的預設，加入待傳送訊息。未儲存的調整不會傳送。',
  'rooms.action.importPreset': '匯入為新預設',
  'rooms.action.importPresetHint': '新增一份本機預設，不覆蓋或切換目前預設。外觀仍需你的帳號具備使用資格。',
  'rooms.action.presetImported': '已匯入，可在浮層頁切換：',
  'rooms.action.presetDraft': '待傳送的浮層預設',
  'rooms.action.removeAttachment': '移除預設卡片',
  'rooms.action.noPresets': '暫無已儲存的預設，請先在浮層頁建立。',
  'rooms.action.presetChanged': '本機預設已變更，請關閉後重新選擇。',
  'rooms.action.presetInvalid': '預設內容無效或版本不支援，請讓傳送者重新分享。',
  'rooms.action.presetImportUnknown': '未能確認匯入結果。請先在浮層頁檢查，避免重複匯入。',
  'rooms.action.refreshMessages': '重新整理訊息',
  'rooms.action.alreadyInvited': '已邀請',
  'rooms.action.chat': '房間聊天',
  'rooms.action.chatEmpty': '還沒有訊息，在這裡與房間成員交流。',
  'rooms.action.send': '傳送',
  'rooms.action.chatDraft': '訊息（最多 300 字）',
  'rooms.action.older': '載入更早訊息',
  'rooms.action.latest': '回到最新訊息',
  'rooms.action.chatRejected': '訊息未傳送，請檢查房間狀態，或稍後再試。',
  'rooms.action.notMember': '你已不在這個房間，請重新整理房間。',
  'rooms.action.reviewSend': '我已核對訊息，允許重新傳送',
  'rooms.action.refreshList': '重新整理名單',
  'rooms.action.invitations': '房間邀請',
  'rooms.action.inviteFriends': '邀請好友',
  'rooms.action.invite': '邀請',
  'rooms.action.revoke': '撤回',
  'rooms.action.received': '收到的邀請',
  'rooms.action.sent': '已傳送的邀請',
  'rooms.action.noInvitations': '暫無房間邀請。',
  'rooms.action.noTargets': '暫無可邀請的好友。',
  'rooms.action.inviteHint': '邀請會在房間關閉、招募結束或最長 24 小時後失效。',
  'rooms.action.invited': '邀請已傳送。',
  'rooms.action.revoked': '邀請已撤回。',
  'rooms.action.invitationDeclined': '已忽略邀請。',
  'rooms.action.targetGone': '該好友已不可邀請，請重新整理名單。',
  'rooms.action.invitationGone': '邀請已處理或失效，請重新整理房間。',
  'rooms.action.invitationRejected': '邀請操作未完成，請重新整理並檢查好友關係、房間人數和邀請有效期。',
  'rooms.action.alreadyJoined': '請先退出目前房間，再接受邀請。',
  'rooms.action.acceptInvitation': '接受邀請將直接加入此房間。',
  'rooms.action.scopeSocial': '建立或加入房間，與成員即時協作。',
};
const englishRoomSocialStrings = <String, String>{
  'rooms.action.sharePreset': 'Share overlay preset',
  'rooms.action.sharePresetHint': 'Choose a saved preset to attach to your message. Unsaved changes are not shared.',
  'rooms.action.importPreset': 'Import as new preset',
  'rooms.action.importPresetHint': 'Create a local preset without replacing or switching your current one. Appearance access still depends on your account.',
  'rooms.action.presetImported': 'Imported. Switch to it on the Overlay page:',
  'rooms.action.presetDraft': 'Overlay preset ready to send',
  'rooms.action.removeAttachment': 'Remove preset card',
  'rooms.action.noPresets':
      'No saved presets. Create one on the Overlay page first.',
  'rooms.action.presetChanged':
      'Local presets changed. Close and choose again.',
  'rooms.action.presetInvalid': 'This preset is invalid or unsupported. Ask the sender to share it again.',
  'rooms.action.presetImportUnknown':
      'Import result unknown. Check the Overlay page before importing again.',
  'rooms.action.refreshMessages': 'Refresh messages',
  'rooms.action.alreadyInvited': 'Invited',
  'rooms.action.chat': 'Room chat',
  'rooms.action.chatEmpty': 'No messages yet. Talk to your room members here.',
  'rooms.action.send': 'Send',
  'rooms.action.chatDraft': 'Message (up to 300 characters)',
  'rooms.action.older': 'Load older messages',
  'rooms.action.latest': 'Back to latest',
  'rooms.action.chatRejected':
      'Message not sent. Check your room status or try again later.',
  'rooms.action.notMember': 'You are no longer in this room. Refresh rooms.',
  'rooms.action.reviewSend': 'I checked the messages. Allow sending again',
  'rooms.action.refreshList': 'Refresh list',
  'rooms.action.invitations': 'Room invitations',
  'rooms.action.inviteFriends': 'Invite friends',
  'rooms.action.invite': 'Invite',
  'rooms.action.revoke': 'Revoke',
  'rooms.action.received': 'Received invitations',
  'rooms.action.sent': 'Sent invitations',
  'rooms.action.noInvitations': 'No room invitations.',
  'rooms.action.noTargets': 'No friends available to invite.',
  'rooms.action.inviteHint': 'Invitations expire when the room closes, recruitment ends, or after 24 hours at most.',
  'rooms.action.invited': 'Invitation sent.',
  'rooms.action.revoked': 'Invitation revoked.',
  'rooms.action.invitationDeclined': 'Invitation ignored.',
  'rooms.action.targetGone':
      'This friend is no longer available. Refresh the list.',
  'rooms.action.invitationGone':
      'This invitation was handled or expired. Refresh rooms.',
  'rooms.action.invitationRejected': 'Invitation action failed. Refresh and check the friendship, room capacity, and expiry.',
  'rooms.action.alreadyJoined':
      'Leave your current room before accepting an invitation.',
  'rooms.action.acceptInvitation':
      'Accepting this invitation joins the room directly.',
  'rooms.action.scopeSocial':
      'Create or join a room to coordinate with its members.',
};
