const simplifiedStartupStrings = <String, String>{
  'startup.connecting': '正在启动星海舰桥',
  'startup.preferences': '正在读取应用设置',
  'startup.account': '正在读取账号状态',
  'startup.accountUnavailable': '暂时无法确认账号状态',
  'startup.accountLabel': '账号状态',
  'startup.signedIn': '已登录',
  'startup.signedOut': '未登录',
  'startup.reauthorizationRequired': '需要重新登录',
  'startup.ready': '准备就绪',
  'startup.hostUnavailable': '暂时无法启动本机服务',
  'startup.preferencesUnavailable': '暂时无法读取应用设置',
  'startup.wait': '准备好后将自动进入。',
  'startup.failure': '请重试，或先进入应用查看可用功能。',
  'startup.host': '本机服务',
  'startup.settings': '应用设置',
  'startup.waiting': '等待中',
  'startup.loading': '正在准备',
  'startup.done': '已就绪',
  'startup.failed': '需要重试',
  'startup.retry': '重试',
  'startup.retrying': '正在重试…',
  'startup.enter': '先进入应用',
  'startup.pause': '暂停动效',
};

const traditionalStartupStrings = <String, String>{
  'startup.connecting': '正在啟動星海艦橋',
  'startup.preferences': '正在讀取應用程式設定',
  'startup.account': '正在讀取帳號狀態',
  'startup.accountUnavailable': '暫時無法確認帳號狀態',
  'startup.accountLabel': '帳號狀態',
  'startup.signedIn': '已登入',
  'startup.signedOut': '未登入',
  'startup.reauthorizationRequired': '需要重新登入',
  'startup.ready': '準備就緒',
  'startup.hostUnavailable': '暫時無法啟動本機服務',
  'startup.preferencesUnavailable': '暫時無法讀取應用程式設定',
  'startup.wait': '準備好後將自動進入。',
  'startup.failure': '請重試，或先進入應用程式查看可用功能。',
  'startup.host': '本機服務',
  'startup.settings': '應用程式設定',
  'startup.waiting': '等待中',
  'startup.loading': '正在準備',
  'startup.done': '已就緒',
  'startup.failed': '需要重試',
  'startup.retry': '重試',
  'startup.retrying': '正在重試…',
  'startup.enter': '先進入應用程式',
  'startup.pause': '暫停動效',
};

const englishStartupStrings = <String, String>{
  'startup.connecting': 'Starting StarBridge',
  'startup.preferences': 'Reading app settings',
  'startup.account': 'Checking account status',
  'startup.accountUnavailable': 'Account status could not be checked',
  'startup.accountLabel': 'Account status',
  'startup.signedIn': 'Signed in',
  'startup.signedOut': 'Signed out',
  'startup.reauthorizationRequired': 'Sign in again',
  'startup.ready': 'Ready',
  'startup.hostUnavailable': 'Local service could not start',
  'startup.preferencesUnavailable': 'App settings could not be read',
  'startup.wait': 'The app will open when ready.',
  'startup.failure': 'Retry, or enter the app to use available features.',
  'startup.host': 'Local service',
  'startup.settings': 'App settings',
  'startup.waiting': 'Waiting',
  'startup.loading': 'Preparing',
  'startup.done': 'Ready',
  'startup.failed': 'Retry needed',
  'startup.retry': 'Retry',
  'startup.retrying': 'Retrying…',
  'startup.enter': 'Enter app now',
  'startup.pause': 'Pause animation',
};
