const simplifiedSyncPrivacyStrings = <String, String>{
  'settings.privacy.page.save': '保存更改',
  'settings.privacy.page.saved': '所有更改已保存',
  'settings.privacy.page.leave': '三个标签中的更改尚未保存。保存后生效，或放弃这些更改。',
  'settings.privacy.page.failed': '部分更改未能确认保存，草稿已保留。',
  'settings.privacy.gameId.title': '游戏 ID 展示',
  'settings.privacy.gameId.help': '选择在哪里展示你的游戏 ID。保存更改后生效，不改变身份验证和共享范围。',
  'settings.privacy.gameId.required': '尚无可替代的独立呼号，游戏 ID 需要在各处展示。',
  'settings.privacy.gameId.unavailable': '暂时无法确认游戏 ID 展示设置，正在自动重新检查。',
  'settings.privacy.gameId.organization': '组织',
  'settings.privacy.gameId.room': '房间',
  'settings.privacy.gameId.friends': '好友',
  'settings.privacy.gameId.profile': '个人主页',
  'settings.privacy.events.scopeHelp':
      '分别选择向房间和每个组织共享的动态。保存更改后生效；隐身或关闭实时共享时暂停发送。',
  'settings.privacy.events.room': '房间事件共享',
  'settings.privacy.events.roomHelp': '只向当前房间成员共享，不沿用组织设置。',
  'settings.privacy.events.organizationHelp': '只对当前成员关系生效，退出后重新加入需再次确认。',
  'settings.privacy.events.active': '事件共享运行中',
  'settings.privacy.friends.active': '好友状态共享运行中',
  'settings.privacy.friends.off': '未向好友共享状态。可在下方逐项开启。',
  'settings.privacy.friends.savedPaused': '选择已保存；开启实时共享并完成身份识别后自动运行。',
  'settings.privacy.friends.unavailable': '暂时无法确认好友共享设置，正在自动重新检查。',
  'settings.privacy.friends.sameServer': '同一服务器',
  'settings.privacy.friends.otherServer': '不同服务器',
  'settings.privacy.events.savedPaused': '事件共享未运行。请确认已开启共享并完成游戏身份识别。',
  'settings.privacy.events.unavailable': '暂时无法确认事件共享状态，正在自动重新检查。未确认的修改不会重复提交。',
  'settings.privacy.title': '决定谁能看到什么',
  'settings.privacy.sections.scopes': '共享范围',
  'settings.privacy.sections.scopesDescription': '房间、主舰队与组织',
  'settings.privacy.sections.account': '好友与社交',
  'settings.privacy.events.contexts': '房间与组织',
  'settings.privacy.events.off': '尚未开启事件共享。可以分别选择房间或组织。',
  'settings.privacy.sections.accountDescription': '长期默认与联系权限',
  'settings.privacy.description':
      '长期默认、临时协作披露和活动事件彼此独立。这里显示的是账号级权威设置，不会从缺失字段猜测他人的隐私选择。',
  'settings.privacy.loading': '正在读取同步与隐私设置…',
  'settings.privacy.signedOut.title': '登录后管理隐私',
  'settings.privacy.signedOut.body': '同步与隐私设置跟随 SCM 账号跨设备保存。登录后才能读取和修改。',
  'settings.privacy.unavailable.title': '暂时无法读取同步与隐私设置',
  'settings.privacy.unavailable.value': '暂不可用',
  'settings.privacy.directMessages.signedOut': '登录后可修改此项设置。',
  'settings.privacy.directMessages.unavailable': '暂时无法读取私信接收设置。',
  'settings.privacy.directMessages.identityUnavailable': '账号状态已变化，请重新登录后再试。',
  'settings.privacy.directMessages.outcomeUnknown': '暂时无法确认是否保存成功，稍后会自动同步最新设置。',
  'settings.privacy.directMessages.invalidResponse': '读取到的私信设置无效，请稍后重试。',
  'settings.privacy.directMessages.writeFailed': '私信接收设置未保存，请稍后重试。',
  'settings.privacy.retry': '重新读取',
  'settings.privacy.error.hostUnavailable': '权威隐私服务尚未接入当前客户端。没有显示或保存任何模拟开关。',
  'settings.privacy.error.readFailed': '读取失败，现有服务端设置没有被覆盖。',
  'settings.privacy.error.writeFailed': '保存失败，界面已保留上一次确认值。',
  'settings.privacy.error.writeConflict': '设置已在其他设备更新，请重新读取后再修改。',
  'settings.privacy.error.invalidResponse': '服务返回了不兼容的数据，已安全停止处理。',
  'settings.privacy.error.unavailable': '同步与隐私服务暂时不可用，请稍后重试。',
  'settings.privacy.source.account': '账号级 · 跨设备',
  'settings.privacy.map.title': '当前可见范围',
  'settings.privacy.map.description': '先看受众，再看字段；组织关系本身不会自动获得你的长期状态。',
  'settings.privacy.map.friends': '好友',
  'settings.privacy.map.friendsBody': '全局默认开放 {count} / 6 类资料；单个好友仍可单独拒绝或允许。',
  'settings.privacy.map.collaboration': '当前房间或行动',
  'settings.privacy.map.collaborationBody': '只在有效参与期间披露协作所需的最小信息，结束后自动撤销。',
  'settings.privacy.map.others': '舰队、组织与其他玩家',
  'settings.privacy.map.othersBody': '不会仅因同舰队、同组织或同服务器获得长期状态权限。',
  'settings.privacy.map.accountDefault': '长期默认',
  'settings.privacy.map.paused': '实时同步已暂停',
  'settings.privacy.map.temporary': '临时授权',
  'settings.privacy.map.noAutomaticAccess': '不自动开放',
  'settings.privacy.realtime.title': '实时同步',
  'settings.privacy.realtime.description':
      '控制 StarBridge 是否实时收发你的协作状态；它与隐身、暂离和免打扰不是一回事。',
  'settings.privacy.realtime.enabled': '启用实时同步',
  'settings.privacy.realtime.enabledDescription': '关闭后停止实时状态收发，但不会把你改成隐身或暂离。',
  'settings.privacy.realtime.activeContext': '你当前有房间或行动上下文。暂停前请确认对协作状态的影响。',
  'settings.privacy.pauseDialog.title': '暂停实时同步？',
  'settings.privacy.pauseDialog.body':
      'StarBridge 将停止实时收发状态。此操作不会把你改成隐身，也不会自动退出行动。',
  'settings.privacy.pauseDialog.activeBody':
      '你当前有房间或行动上下文。暂停后，房间可能进入离线恢复或移除流程；行动参与与舰船占用不会自动解除。',
  'settings.privacy.pauseDialog.cancel': '继续同步',
  'settings.privacy.pauseDialog.confirm': '暂停实时同步',
  'settings.privacy.friends.title': '好友长期默认',
  'settings.privacy.friends.description': '这些是所有好友的默认可见字段。单个好友的明确拒绝始终优先。',
  'settings.privacy.field.presence': '在线与游戏中',
  'settings.privacy.field.presenceDescription': '让好友知道你是否在线或正在运行游戏，不包含舰船和位置。',
  'settings.privacy.field.serverRelation': '最小服务器关系',
  'settings.privacy.field.serverRelationDescription':
      '只表达未进入、同服务器或不同服务器，不公开内部服务器标识。',
  'settings.privacy.field.serverDetails': '服务器详情',
  'settings.privacy.field.serverDetailsDescription':
      '向好友进一步开放只读服务器信息，仍不提供加入或切换服务器动作。',
  'settings.privacy.field.ship': '当前舰船',
  'settings.privacy.field.shipDescription': '允许好友看到当前已识别舰船；没有数据时保持未知。',
  'settings.privacy.field.location': '当前位置',
  'settings.privacy.field.locationDescription':
      '允许好友看到当前已确认地点；机密行动和更高优先级规则仍会隐藏。',
  'settings.privacy.field.lastOnline': '最后在线时间',
  'settings.privacy.field.lastOnlineDescription': '只提供服务端裁剪后的相对时间，不公开原始时间戳。',
  'settings.privacy.friendExceptions.title': '按好友例外',
  'settings.privacy.friendExceptions.body':
      '在好友详情中可分别设置在线、服务器详情、舰船、位置和最后在线为“继承 / 允许 / 不允许”；本页不复制第二套管理器。',
  'settings.privacy.events.title': '协作活动事件',
  'settings.privacy.events.description': '事件播报与当前状态可见性分开控制，关闭事件不会改写好友长期默认。',
  'settings.privacy.events.enabled': '共享协作活动事件',
  'settings.privacy.events.enabledDescription': '总开关关闭时不发布下列事件，但保留各类别选择。',
  'settings.privacy.events.presence': '进入或离开游戏',
  'settings.privacy.events.presenceDescription': '发布开始游戏、结束游戏等活动变化。',
  'settings.privacy.events.server': '服务器变化',
  'settings.privacy.events.serverDescription': '发布进入、离开或变更服务器的事件。',
  'settings.privacy.events.ship': '舰船变化',
  'settings.privacy.events.shipDescription': '发布当前舰船发生变化的事件。',
  'settings.privacy.events.location': '地点变化',
  'settings.privacy.events.locationDescription': '发布已确认地点发生变化的事件。',
  'settings.privacy.events.life': '生命状态事件',
  'settings.privacy.events.lifeDescription': '发布倒地、死亡、复苏和重生等协作事件。',
  'settings.privacy.social.title': '社交隐私',
  'settings.privacy.social.description': '控制陌生人联系、最近同玩和不可靠位置的保护方式。',
  'settings.privacy.social.friendRequests': '允许非好友发送好友申请',
  'settings.privacy.social.friendRequestsDescription':
      '关闭后，其他人无法向你发送新的好友申请；已有好友和待处理申请不受影响。',
  'settings.privacy.friendRequests.signedOut': '登录后可修改此项设置。',
  'settings.privacy.friendRequests.unavailable': '暂时无法读取好友申请设置。',
  'settings.privacy.friendRequests.identityUnavailable': '账号状态已变化，请重新登录后再试。',
  'settings.privacy.friendRequests.outcomeUnknown': '暂时无法确认是否保存成功，稍后会自动同步最新设置。',
  'settings.privacy.friendRequests.invalidResponse': '读取到的好友申请设置无效，请稍后重试。',
  'settings.privacy.friendRequests.writeFailed': '好友申请设置未保存，请稍后重试。',
  'settings.privacy.recentlyPlayed.signedOut': '登录后可修改此项设置。',
  'settings.privacy.recentlyPlayed.unavailable': '暂时无法读取最近同玩设置。',
  'settings.privacy.recentlyPlayed.identityUnavailable': '账号状态已变化，请重新登录后再试。',
  'settings.privacy.recentlyPlayed.outcomeUnknown': '暂时无法确认是否保存成功，稍后会自动同步最新设置。',
  'settings.privacy.recentlyPlayed.writeConflict': '设置已在其他设备更新，请重新读取后再修改。',
  'settings.privacy.recentlyPlayed.invalidResponse': '读取到的最近同玩设置无效，请稍后重试。',
  'settings.privacy.recentlyPlayed.writeFailed': '最近同玩设置未保存，请稍后重试。',
  'settings.privacy.social.strangerMessages': '允许非好友发起私信',
  'settings.privacy.social.strangerMessagesDescription':
      '允许时，对方在你回复前最多发送 3 条私信；读取、撤回或时间经过不会重置额度。',
  'settings.privacy.social.recentlyPlayed': '允许共同参与者在“最近同玩”中找到我',
  'settings.privacy.social.recentlyPlayedDescription':
      '关闭后停止生成新记录并移除双方普通目录中的既有记录；重新开启不会恢复旧记录。',
  'settings.privacy.social.lowConfidence': '隐藏低可信位置',
  'settings.privacy.social.lowConfidenceDescription':
      '地点来源不够可靠时不对外发布，避免把猜测显示成事实。',
  'settings.privacy.boundaries.title': '其它共享边界',
  'settings.privacy.boundaries.description': '这些能力有自己的上下文和管理入口，不在本页复制控制。',
  'settings.privacy.context.title': '房间与行动的临时披露',
  'settings.privacy.context.body': '只在有效成员或参与关系内提供协作必需字段；机密行动继续隐藏全部外部线索。',
  'settings.privacy.hangar.title': '舰船共享在个人机库管理',
  'settings.privacy.hangar.body':
      '每个舰队或组织分别选择长期共享、仅行动共享或不共享；不共享会显示明确状态，不会让舰船无故消失。',
  'settings.privacy.authorityNotice':
      '所有有效可见性由服务端按查看者裁剪。Flutter 只提交语义设置并展示最终投影，不在本机自行合并权限。',
};

const traditionalSyncPrivacyStrings = <String, String>{
  'settings.privacy.page.save': '儲存變更',
  'settings.privacy.page.saved': '所有變更已儲存',
  'settings.privacy.page.leave': '三個分頁中的變更尚未儲存。儲存後生效，或放棄這些變更。',
  'settings.privacy.page.failed': '部分變更未能確認儲存，草稿已保留。',
  'settings.privacy.gameId.title': '遊戲 ID 顯示',
  'settings.privacy.gameId.help': '選擇在哪裡顯示你的遊戲 ID。儲存變更後生效，不改變身分驗證和共享範圍。',
  'settings.privacy.gameId.required': '尚無可替代的獨立呼號，遊戲 ID 需要在各處顯示。',
  'settings.privacy.gameId.unavailable': '暫時無法確認遊戲 ID 顯示設定，正在自動重新檢查。',
  'settings.privacy.gameId.organization': '組織',
  'settings.privacy.gameId.room': '房間',
  'settings.privacy.gameId.friends': '好友',
  'settings.privacy.gameId.profile': '個人主頁',
  'settings.privacy.events.scopeHelp':
      '分別選擇向房間和每個組織共享的動態。儲存變更後生效；隱身或關閉即時共享時暫停傳送。',
  'settings.privacy.events.room': '房間事件共享',
  'settings.privacy.events.roomHelp': '只向目前房間成員共享，不沿用組織設定。',
  'settings.privacy.events.organizationHelp': '只對目前成員關係生效，退出後重新加入需再次確認。',
  'settings.privacy.events.active': '事件共享運作中',
  'settings.privacy.friends.active': '好友狀態共享運作中',
  'settings.privacy.friends.off': '未向好友共享狀態。可在下方逐項開啟。',
  'settings.privacy.friends.savedPaused': '選擇已儲存；開啟即時共享並完成身分識別後自動運作。',
  'settings.privacy.friends.unavailable': '暫時無法確認好友共享設定，正在自動重新檢查。',
  'settings.privacy.friends.sameServer': '同一伺服器',
  'settings.privacy.friends.otherServer': '不同伺服器',
  'settings.privacy.events.savedPaused': '事件共享未運作。請確認已開啟共享並完成遊戲身分識別。',
  'settings.privacy.events.unavailable': '暫時無法確認事件共享狀態，正在自動重新檢查。未確認的修改不會重複提交。',
  'settings.privacy.title': '決定誰能看到什麼',
  'settings.privacy.sections.scopes': '共享範圍',
  'settings.privacy.sections.scopesDescription': '房間、主艦隊與組織',
  'settings.privacy.sections.account': '好友與社交',
  'settings.privacy.events.contexts': '房間與組織',
  'settings.privacy.events.off': '尚未開啟事件共享。可以分別選擇房間或組織。',
  'settings.privacy.sections.accountDescription': '長期預設與聯絡權限',
  'settings.privacy.description':
      '長期預設、臨時協作揭露與活動事件彼此獨立。這裡顯示帳號級權威設定，不會從缺少欄位猜測他人的隱私選擇。',
  'settings.privacy.loading': '正在讀取同步與隱私設定…',
  'settings.privacy.signedOut.title': '登入後管理隱私',
  'settings.privacy.signedOut.body': '同步與隱私設定會跟隨 SCM 帳號跨裝置儲存。登入後才能讀取和修改。',
  'settings.privacy.unavailable.title': '暫時無法讀取同步與隱私設定',
  'settings.privacy.unavailable.value': '暫時無法使用',
  'settings.privacy.directMessages.signedOut': '登入後可修改此項設定。',
  'settings.privacy.directMessages.unavailable': '暫時無法讀取私訊接收設定。',
  'settings.privacy.directMessages.identityUnavailable': '帳號狀態已變更，請重新登入後再試。',
  'settings.privacy.directMessages.outcomeUnknown': '暫時無法確認是否儲存成功，稍後會自動同步最新設定。',
  'settings.privacy.directMessages.invalidResponse': '讀取到的私訊設定無效，請稍後重試。',
  'settings.privacy.directMessages.writeFailed': '私訊接收設定未儲存，請稍後重試。',
  'settings.privacy.retry': '重新讀取',
  'settings.privacy.error.hostUnavailable': '權威隱私服務尚未接入目前客戶端。沒有顯示或儲存任何模擬開關。',
  'settings.privacy.error.readFailed': '讀取失敗，現有伺服器設定沒有被覆蓋。',
  'settings.privacy.error.writeFailed': '儲存失敗，介面已保留上一次確認值。',
  'settings.privacy.error.writeConflict': '設定已在其他裝置更新，請重新讀取後再修改。',
  'settings.privacy.error.invalidResponse': '服務傳回不相容的資料，已安全停止處理。',
  'settings.privacy.error.unavailable': '同步與隱私服務暫時無法使用，請稍後重試。',
  'settings.privacy.source.account': '帳號級 · 跨裝置',
  'settings.privacy.map.title': '目前可見範圍',
  'settings.privacy.map.description': '先看受眾，再看欄位；組織關係本身不會自動取得你的長期狀態。',
  'settings.privacy.map.friends': '好友',
  'settings.privacy.map.friendsBody': '全域預設開放 {count} / 6 類資料；單一好友仍可個別拒絕或允許。',
  'settings.privacy.map.collaboration': '目前房間或行動',
  'settings.privacy.map.collaborationBody': '只在有效參與期間揭露協作所需的最小資訊，結束後自動撤銷。',
  'settings.privacy.map.others': '艦隊、組織與其他玩家',
  'settings.privacy.map.othersBody': '不會只因同艦隊、同組織或同伺服器取得長期狀態權限。',
  'settings.privacy.map.accountDefault': '長期預設',
  'settings.privacy.map.paused': '即時同步已暫停',
  'settings.privacy.map.temporary': '臨時授權',
  'settings.privacy.map.noAutomaticAccess': '不自動開放',
  'settings.privacy.realtime.title': '即時同步',
  'settings.privacy.realtime.description':
      '控制 StarBridge 是否即時收發你的協作狀態；它與隱身、暫離及勿擾不同。',
  'settings.privacy.realtime.enabled': '啟用即時同步',
  'settings.privacy.realtime.enabledDescription': '關閉後停止即時狀態收發，但不會把你改成隱身或暫離。',
  'settings.privacy.realtime.activeContext': '你目前有房間或行動內容。暫停前請確認對協作狀態的影響。',
  'settings.privacy.pauseDialog.title': '暫停即時同步？',
  'settings.privacy.pauseDialog.body':
      'StarBridge 將停止即時收發狀態。此操作不會改成隱身，也不會自動退出行動。',
  'settings.privacy.pauseDialog.activeBody':
      '你目前有房間或行動內容。暫停後，房間可能進入離線復原或移除流程；行動參與與艦船占用不會自動解除。',
  'settings.privacy.pauseDialog.cancel': '繼續同步',
  'settings.privacy.pauseDialog.confirm': '暫停即時同步',
  'settings.privacy.friends.title': '好友長期預設',
  'settings.privacy.friends.description': '這些是所有好友的預設可見欄位。單一好友的明確拒絕永遠優先。',
  'settings.privacy.field.presence': '上線與遊戲中',
  'settings.privacy.field.presenceDescription': '讓好友知道你是否上線或正在執行遊戲，不包含艦船與位置。',
  'settings.privacy.field.serverRelation': '最小伺服器關係',
  'settings.privacy.field.serverRelationDescription':
      '只表達未進入、同伺服器或不同伺服器，不公開內部伺服器識別。',
  'settings.privacy.field.serverDetails': '伺服器詳情',
  'settings.privacy.field.serverDetailsDescription':
      '向好友進一步開放唯讀伺服器資訊，仍不提供加入或切換動作。',
  'settings.privacy.field.ship': '目前艦船',
  'settings.privacy.field.shipDescription': '允許好友看到目前已辨識艦船；沒有資料時保持未知。',
  'settings.privacy.field.location': '目前位置',
  'settings.privacy.field.locationDescription':
      '允許好友看到目前已確認地點；機密行動與更高優先級規則仍會隱藏。',
  'settings.privacy.field.lastOnline': '最後上線時間',
  'settings.privacy.field.lastOnlineDescription': '只提供伺服器裁剪後的相對時間，不公開原始時間戳。',
  'settings.privacy.friendExceptions.title': '按好友例外',
  'settings.privacy.friendExceptions.body':
      '在好友詳情可分別設定上線、伺服器詳情、艦船、位置與最後上線為「繼承 / 允許 / 不允許」；本頁不複製第二套管理器。',
  'settings.privacy.events.title': '協作活動事件',
  'settings.privacy.events.description': '事件播報與目前狀態可見性分開控制，關閉事件不會改寫好友長期預設。',
  'settings.privacy.events.enabled': '分享協作活動事件',
  'settings.privacy.events.enabledDescription': '總開關關閉時不發佈下列事件，但保留各類別選擇。',
  'settings.privacy.events.presence': '進入或離開遊戲',
  'settings.privacy.events.presenceDescription': '發佈開始遊戲、結束遊戲等活動變化。',
  'settings.privacy.events.server': '伺服器變化',
  'settings.privacy.events.serverDescription': '發佈進入、離開或變更伺服器的事件。',
  'settings.privacy.events.ship': '艦船變化',
  'settings.privacy.events.shipDescription': '發佈目前艦船發生變化的事件。',
  'settings.privacy.events.location': '地點變化',
  'settings.privacy.events.locationDescription': '發佈已確認地點發生變化的事件。',
  'settings.privacy.events.life': '生命狀態事件',
  'settings.privacy.events.lifeDescription': '發佈倒地、死亡、復甦和重生等協作事件。',
  'settings.privacy.social.title': '社交隱私',
  'settings.privacy.social.description': '控制陌生人聯絡、最近同玩和不可靠位置的保護方式。',
  'settings.privacy.social.friendRequests': '允許非好友傳送好友申請',
  'settings.privacy.social.friendRequestsDescription':
      '關閉後，其他人無法向你傳送新的好友申請；現有好友與待處理申請不受影響。',
  'settings.privacy.friendRequests.signedOut': '登入後可修改此項設定。',
  'settings.privacy.friendRequests.unavailable': '暫時無法讀取好友申請設定。',
  'settings.privacy.friendRequests.identityUnavailable': '帳號狀態已變更，請重新登入後再試。',
  'settings.privacy.friendRequests.outcomeUnknown': '暫時無法確認是否儲存成功，稍後會自動同步最新設定。',
  'settings.privacy.friendRequests.invalidResponse': '讀取到的好友申請設定無效，請稍後再試。',
  'settings.privacy.friendRequests.writeFailed': '好友申請設定未儲存，請稍後再試。',
  'settings.privacy.recentlyPlayed.signedOut': '登入後可修改此項設定。',
  'settings.privacy.recentlyPlayed.unavailable': '暫時無法讀取最近同玩設定。',
  'settings.privacy.recentlyPlayed.identityUnavailable': '帳號狀態已變更，請重新登入後再試。',
  'settings.privacy.recentlyPlayed.outcomeUnknown': '暫時無法確認是否儲存成功，稍後會自動同步最新設定。',
  'settings.privacy.recentlyPlayed.writeConflict': '設定已在其他裝置更新，請重新讀取後再修改。',
  'settings.privacy.recentlyPlayed.invalidResponse': '讀取到的最近同玩設定無效，請稍後再試。',
  'settings.privacy.recentlyPlayed.writeFailed': '最近同玩設定未儲存，請稍後再試。',
  'settings.privacy.social.strangerMessages': '允許非好友發起私訊',
  'settings.privacy.social.strangerMessagesDescription':
      '允許時，對方在你回覆前最多傳送 3 則私訊；讀取、收回或時間經過不會重設額度。',
  'settings.privacy.social.recentlyPlayed': '允許共同參與者在「最近同玩」中找到我',
  'settings.privacy.social.recentlyPlayedDescription':
      '關閉後停止產生新記錄並移除雙方一般目錄中的既有記錄；重新開啟不會復原舊記錄。',
  'settings.privacy.social.lowConfidence': '隱藏低可信位置',
  'settings.privacy.social.lowConfidenceDescription':
      '地點來源不夠可靠時不對外發佈，避免把猜測顯示成事實。',
  'settings.privacy.boundaries.title': '其他分享邊界',
  'settings.privacy.boundaries.description': '這些能力有自己的內容與管理入口，不在本頁複製控制。',
  'settings.privacy.context.title': '房間與行動的臨時揭露',
  'settings.privacy.context.body': '只在有效成員或參與關係內提供協作必需欄位；機密行動繼續隱藏全部外部線索。',
  'settings.privacy.hangar.title': '艦船分享在個人機庫管理',
  'settings.privacy.hangar.body':
      '每個艦隊或組織分別選擇長期分享、僅行動分享或不分享；不分享會顯示明確狀態，不會讓艦船無故消失。',
  'settings.privacy.authorityNotice':
      '所有有效可見性由伺服器依查看者裁剪。Flutter 只提交語意設定並顯示最終投影，不在本機自行合併權限。',
};

const englishSyncPrivacyStrings = <String, String>{
  'settings.privacy.page.save': 'Save changes',
  'settings.privacy.page.saved': 'All changes saved',
  'settings.privacy.page.leave': 'Changes across the three tabs have not been saved. Save to apply them, or discard them.',
  'settings.privacy.page.failed': 'Some changes could not be confirmed. Your draft has been kept.',
  'settings.privacy.gameId.title': 'Game ID visibility',
  'settings.privacy.gameId.help': 'Choose where your game ID appears. Save to apply changes without changing identity verification or sharing permissions.',
  'settings.privacy.gameId.required': 'Without a distinct callsign, your game ID must remain visible in all locations.',
  'settings.privacy.gameId.unavailable': 'Unable to confirm game ID visibility settings. Checking again automatically.',
  'settings.privacy.gameId.organization': 'Organizations',
  'settings.privacy.gameId.room': 'Rooms',
  'settings.privacy.gameId.friends': 'Friends',
  'settings.privacy.gameId.profile': 'Profile',
  'settings.privacy.events.scopeHelp': 'Choose which activities to share with your room and each organization. Save to apply changes. Sending pauses while invisible or realtime sharing is off.',
  'settings.privacy.events.room': 'Room event sharing',
  'settings.privacy.events.roomHelp': 'Shared only with current room members. Organization settings do not apply.',
  'settings.privacy.events.organizationHelp':
      'Applies to this membership only. Rejoining requires confirmation again.',
  'settings.privacy.events.active': 'Event sharing is running',
  'settings.privacy.friends.active': 'Friend status sharing is running',
  'settings.privacy.friends.off':
      'No status is shared with friends. Enable individual fields below.',
  'settings.privacy.friends.savedPaused': 'Choices saved. Sharing resumes automatically when realtime sharing is on and identity is verified.',
  'settings.privacy.friends.unavailable': 'Friend sharing settings could not be confirmed. Checking again automatically.',
  'settings.privacy.friends.sameServer': 'Same server',
  'settings.privacy.friends.otherServer': 'Different server',
  'settings.privacy.events.savedPaused': 'Event sharing is not running. Check that sharing is enabled and your game identity is verified.',
  'settings.privacy.events.unavailable': 'Event sharing status could not be confirmed. Checking again automatically. Unconfirmed changes are not submitted again.',
  'settings.privacy.title': 'Decide who can see what',
  'settings.privacy.sections.scopes': 'Sharing scopes',
  'settings.privacy.sections.scopesDescription':
      'Rooms, primary fleet, and organizations',
  'settings.privacy.sections.account': 'Friends and social',
  'settings.privacy.events.contexts': 'Rooms and organizations',
  'settings.privacy.events.off':
      'Event sharing is off. Choose a room or organization scope to enable it.',
  'settings.privacy.sections.accountDescription':
      'Long-term defaults and contact permissions',
  'settings.privacy.description': 'Persistent defaults, temporary collaboration disclosure, and activity events remain separate. This page shows authoritative account settings and never guesses another player’s privacy choice from missing fields.',
  'settings.privacy.loading': 'Reading sync and privacy settings…',
  'settings.privacy.signedOut.title': 'Sign in to manage privacy',
  'settings.privacy.signedOut.body': 'Sync and privacy settings follow your SCM account across devices. Sign in to read or change them.',
  'settings.privacy.unavailable.title':
      'Sync and privacy settings are unavailable',
  'settings.privacy.unavailable.value': 'Unavailable',
  'settings.privacy.directMessages.signedOut':
      'Sign in to change this setting.',
  'settings.privacy.directMessages.unavailable':
      'Direct message receiving settings are temporarily unavailable.',
  'settings.privacy.directMessages.identityUnavailable':
      'Your account changed. Sign in again and retry.',
  'settings.privacy.directMessages.outcomeUnknown': 'The save could not be confirmed. The latest setting will sync automatically.',
  'settings.privacy.directMessages.invalidResponse':
      'The direct message setting could not be read. Try again later.',
  'settings.privacy.directMessages.writeFailed':
      'The direct message setting was not saved. Try again later.',
  'settings.privacy.retry': 'Read again',
  'settings.privacy.error.hostUnavailable': 'The authoritative privacy service is not connected to this client yet. No simulated switches are shown or saved.',
  'settings.privacy.error.readFailed':
      'The read failed. Existing server settings were not replaced.',
  'settings.privacy.error.writeFailed':
      'The save failed. The last confirmed values remain visible.',
  'settings.privacy.error.writeConflict': 'These settings changed on another device. Read them again before editing.',
  'settings.privacy.error.invalidResponse':
      'The service returned incompatible data, so processing stopped safely.',
  'settings.privacy.error.unavailable':
      'The sync and privacy service is temporarily unavailable.',
  'settings.privacy.source.account': 'Account · cross-device',
  'settings.privacy.map.title': 'Current visibility map',
  'settings.privacy.map.description': 'Start with the audience, then the fields. Organization membership alone never grants long-term access to your state.',
  'settings.privacy.map.friends': 'Friends',
  'settings.privacy.map.friendsBody': '{count} of 6 categories are open by default. Each friend can still be denied or allowed explicitly.',
  'settings.privacy.map.collaboration': 'Current room or operation',
  'settings.privacy.map.collaborationBody': 'Only the minimum collaboration facts are shared during valid participation and revoked afterward.',
  'settings.privacy.map.others': 'Fleets, organizations, and others',
  'settings.privacy.map.othersBody': 'Shared membership or server presence does not grant long-term access to your state.',
  'settings.privacy.map.accountDefault': 'Persistent default',
  'settings.privacy.map.paused': 'Realtime sync paused',
  'settings.privacy.map.temporary': 'Temporary grant',
  'settings.privacy.map.noAutomaticAccess': 'No automatic access',
  'settings.privacy.realtime.title': 'Realtime sync',
  'settings.privacy.realtime.description': 'Controls whether StarBridge sends and receives collaboration state. It is separate from invisible, away, and do not disturb.',
  'settings.privacy.realtime.enabled': 'Enable realtime sync',
  'settings.privacy.realtime.enabledDescription': 'Turning this off stops realtime state exchange without changing your presence mode.',
  'settings.privacy.realtime.activeContext': 'You currently have a room or operation context. Review the collaboration impact before pausing.',
  'settings.privacy.pauseDialog.title': 'Pause realtime sync?',
  'settings.privacy.pauseDialog.body': 'StarBridge will stop realtime state exchange. This does not make you invisible or leave an operation.',
  'settings.privacy.pauseDialog.activeBody': 'You currently have a room or operation context. A room may enter offline recovery or removal, while operation participation and ship reservations remain in place.',
  'settings.privacy.pauseDialog.cancel': 'Keep syncing',
  'settings.privacy.pauseDialog.confirm': 'Pause realtime sync',
  'settings.privacy.friends.title': 'Persistent friend defaults',
  'settings.privacy.friends.description': 'These fields apply to all friends by default. An explicit per-friend denial always wins.',
  'settings.privacy.field.presence': 'Online and in game',
  'settings.privacy.field.presenceDescription': 'Lets friends know whether you are online or running the game, without ship or location details.',
  'settings.privacy.field.serverRelation': 'Minimal server relationship',
  'settings.privacy.field.serverRelationDescription': 'Only says not joined, same server, or different server. Internal server identifiers remain hidden.',
  'settings.privacy.field.serverDetails': 'Server details',
  'settings.privacy.field.serverDetailsDescription': 'Shares additional read-only server details without fake join or switch-server actions.',
  'settings.privacy.field.ship': 'Current ship',
  'settings.privacy.field.shipDescription': 'Lets friends see the currently recognized ship. Missing data remains unknown.',
  'settings.privacy.field.location': 'Current location',
  'settings.privacy.field.locationDescription': 'Lets friends see a confirmed location. Secret operations and higher-priority rules still hide it.',
  'settings.privacy.field.lastOnline': 'Last online',
  'settings.privacy.field.lastOnlineDescription':
      'Shares only a server-trimmed relative time, never a raw timestamp.',
  'settings.privacy.friendExceptions.title': 'Per-friend exceptions',
  'settings.privacy.friendExceptions.body': 'Friend details can set presence, server details, ship, location, and last online to Inherit, Allow, or Deny. This page does not duplicate that manager.',
  'settings.privacy.events.title': 'Collaboration activity events',
  'settings.privacy.events.description': 'Event broadcasts are separate from current-state visibility. Disabling events does not rewrite friend defaults.',
  'settings.privacy.events.enabled': 'Share collaboration activity events',
  'settings.privacy.events.enabledDescription': 'The master switch stops publishing these events while preserving each category choice.',
  'settings.privacy.events.presence': 'Game start and stop',
  'settings.privacy.events.presenceDescription':
      'Publishes activity changes such as starting or leaving the game.',
  'settings.privacy.events.server': 'Server changes',
  'settings.privacy.events.serverDescription':
      'Publishes server entry, exit, and change events.',
  'settings.privacy.events.ship': 'Ship changes',
  'settings.privacy.events.shipDescription':
      'Publishes a change to the current recognized ship.',
  'settings.privacy.events.location': 'Location changes',
  'settings.privacy.events.locationDescription':
      'Publishes a change to a confirmed location.',
  'settings.privacy.events.life': 'Life-state events',
  'settings.privacy.events.lifeDescription':
      'Publishes downed, death, revive, and respawn collaboration events.',
  'settings.privacy.social.title': 'Social privacy',
  'settings.privacy.social.description': 'Controls contact from strangers, Recent Players, and protection for unreliable locations.',
  'settings.privacy.social.friendRequests':
      'Allow friend requests from non-friends',
  'settings.privacy.social.friendRequestsDescription': 'When off, other people cannot send you new friend requests. Existing friends and pending requests are unchanged.',
  'settings.privacy.friendRequests.signedOut':
      'Sign in to change this setting.',
  'settings.privacy.friendRequests.unavailable':
      'Friend request settings are temporarily unavailable.',
  'settings.privacy.friendRequests.identityUnavailable':
      'Your account changed. Sign in again and retry.',
  'settings.privacy.friendRequests.outcomeUnknown': 'The save could not be confirmed. The latest setting will sync automatically.',
  'settings.privacy.friendRequests.invalidResponse':
      'The friend request setting could not be read. Try again later.',
  'settings.privacy.friendRequests.writeFailed':
      'The friend request setting was not saved. Try again later.',
  'settings.privacy.recentlyPlayed.signedOut':
      'Sign in to change this setting.',
  'settings.privacy.recentlyPlayed.unavailable':
      'Recent Players settings are temporarily unavailable.',
  'settings.privacy.recentlyPlayed.identityUnavailable':
      'Your account changed. Sign in again and retry.',
  'settings.privacy.recentlyPlayed.outcomeUnknown': 'The save could not be confirmed. The latest setting will sync automatically.',
  'settings.privacy.recentlyPlayed.writeConflict':
      'This setting changed on another device. Reload it and try again.',
  'settings.privacy.recentlyPlayed.invalidResponse':
      'The Recent Players setting could not be read. Try again later.',
  'settings.privacy.recentlyPlayed.writeFailed':
      'The Recent Players setting was not saved. Try again later.',
  'settings.privacy.social.strangerMessages':
      'Allow non-friends to start a direct message',
  'settings.privacy.social.strangerMessagesDescription': 'When allowed, the sender can send up to 3 messages before you reply. Reads, withdrawals, and elapsed time do not reset the allowance.',
  'settings.privacy.social.recentlyPlayed':
      'Let shared participants find me in Recent Players',
  'settings.privacy.social.recentlyPlayedDescription': 'Turning this off stops new records and removes existing ordinary entries for both sides. Turning it back on does not restore old records.',
  'settings.privacy.social.lowConfidence': 'Hide low-confidence locations',
  'settings.privacy.social.lowConfidenceDescription': 'Locations with insufficient confidence are not published, so guesses are never presented as facts.',
  'settings.privacy.boundaries.title': 'Other sharing boundaries',
  'settings.privacy.boundaries.description': 'These capabilities have their own context and management surface, so their controls are not duplicated here.',
  'settings.privacy.context.title': 'Temporary room and operation disclosure',
  'settings.privacy.context.body': 'Only required collaboration fields are shared inside a valid membership or participation context. Secret operations expose no outside clues.',
  'settings.privacy.hangar.title': 'Manage ship sharing in My Hangar',
  'settings.privacy.hangar.body': 'Choose persistent, operation-only, or no sharing for each fleet or organization. No sharing is shown explicitly instead of making a ship seem to vanish.',
  'settings.privacy.authorityNotice': 'The service computes effective visibility for each viewer. Flutter submits semantic settings and displays the final projection; it never merges permissions locally.',
};
