# Run with cmake -DPLUGIN_SOURCE=<upstream cpp> -DTEST_OUTPUT=<temp cpp> -P <this file>.
include("${CMAKE_CURRENT_LIST_DIR}/video_player_win_surface_fix.cmake")
if(NOT DEFINED PLUGIN_SOURCE OR NOT DEFINED TEST_OUTPUT)
  message(FATAL_ERROR "PLUGIN_SOURCE and TEST_OUTPUT are required.")
endif()
starbridge_patch_video_surface("${PLUGIN_SOURCE}" "${TEST_OUTPUT}")
file(READ "${TEST_OUTPUT}" corrected)
foreach(dimension width height)
  if(dimension STREQUAL "width")
    set(native_dimension Width)
  else()
    set(native_dimension Height)
  endif()
  string(FIND "${corrected}" "texture_buffer.visible_${dimension} = desc.${native_dimension};" position)
  if(position LESS 0)
    message(FATAL_ERROR "FAIL: visible_${dimension} is not initialized.")
  endif()
endforeach()
message(STATUS "PASS: upstream hash verified; both visible dimensions initialized.")
