<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../StarBridge.HostRuntime/StarBridge.HostRuntime.csproj" />
    <EmbeddedResource Include="Policies/wpf-0.6.6.1-files.json" LogicalName="StarBridge.WpfCleanup.0.6.6.1.json" />
    <AssemblyMetadata Include="StarBridgeEnableLegacyCleanup" Value="$(StarBridgeEnableLegacyCleanup)" />
  </ItemGroup>
</Project>
