<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\data\location-names\navigation-station-display-map.json" LogicalName="StarBridge.NavigationStationDisplay.json" />
    <EmbeddedResource Include="..\data\ship-names\ship-name-pack.json" LogicalName="StarBridge.ShipNamePack.json" />
    <EmbeddedResource Include="..\data\ship-names\hangar-official-aliases.json" LogicalName="StarBridge.HangarOfficialAliases.json" />
    <Compile Remove=".altobj\**\*.cs" />
  </ItemGroup>

</Project>
