import 'package:flutter/material.dart';

/// Standard auxiliary glyphs. Existing Material artwork is intentionally retained;
/// the custom-painted StarBridge icon family has its own renderer.
enum StandardIconSemantic {
  accountCircle,
  add,
  adminPanelSettings,
  alternateEmail,
  arrowBack,
  arrowDownward,
  arrowForward,
  attachFile,
  badge,
  brokenImage,
  campaign,
  chatBubble,
  checkCircle,
  chevronLeft,
  chevronRight,
  circle,
  circleOutline,
  close,
  copyAll,
  copy,
  dashboard,
  deleteForever,
  delete,
  edit,
  event,
  expandLess,
  expandMore,
  groupAdd,
  groups,
  history,
  hourglassTop,
  image,
  info,
  language,
  layers,
  logout,
  meetingRoom,
  moreHoriz,
  north,
  outbox,
  people,
  personAddAlt,
  person,
  personRemove,
  public,
  radioButtonChecked,
  radioButtonOff,
  radioButtonUnchecked,
  refresh,
  rocketLaunch,
  schedule,
  search,
  send,
  share,
  south,
  sportsEsports,
  swapHoriz,
  unfoldLess,
  unfoldMore,
  verifiedUser,
  visibility,
  warningAmber,
}

/// Owns glyph selection without leaking font/code-point details into features.
class StandardIcon extends StatelessWidget {
  const StandardIcon(this.semantic, {super.key, this.size, this.color,
    this.semanticLabel, this.textDirection});
  final StandardIconSemantic semantic;
  final double? size;
  final Color? color;
  final String? semanticLabel;
  final TextDirection? textDirection;

  @override
  Widget build(BuildContext context) => Icon(
    switch (semantic) {
      StandardIconSemantic.accountCircle => Icons.account_circle_outlined,
      StandardIconSemantic.add => Icons.add,
      StandardIconSemantic.adminPanelSettings => Icons.admin_panel_settings_outlined,
      StandardIconSemantic.alternateEmail => Icons.alternate_email,
      StandardIconSemantic.arrowBack => Icons.arrow_back,
      StandardIconSemantic.arrowDownward => Icons.arrow_downward,
      StandardIconSemantic.arrowForward => Icons.arrow_forward,
      StandardIconSemantic.attachFile => Icons.attach_file,
      StandardIconSemantic.badge => Icons.badge_outlined,
      StandardIconSemantic.brokenImage => Icons.broken_image_outlined,
      StandardIconSemantic.campaign => Icons.campaign_outlined,
      StandardIconSemantic.chatBubble => Icons.chat_bubble_outline,
      StandardIconSemantic.checkCircle => Icons.check_circle,
      StandardIconSemantic.chevronLeft => Icons.chevron_left,
      StandardIconSemantic.chevronRight => Icons.chevron_right,
      StandardIconSemantic.circle => Icons.circle,
      StandardIconSemantic.circleOutline => Icons.circle_outlined,
      StandardIconSemantic.close => Icons.close,
      StandardIconSemantic.copyAll => Icons.copy_all_outlined,
      StandardIconSemantic.copy => Icons.copy_outlined,
      StandardIconSemantic.dashboard => Icons.dashboard_outlined,
      StandardIconSemantic.deleteForever => Icons.delete_forever_outlined,
      StandardIconSemantic.delete => Icons.delete_outline,
      StandardIconSemantic.edit => Icons.edit_outlined,
      StandardIconSemantic.event => Icons.event_outlined,
      StandardIconSemantic.expandLess => Icons.expand_less,
      StandardIconSemantic.expandMore => Icons.expand_more,
      StandardIconSemantic.groupAdd => Icons.group_add_outlined,
      StandardIconSemantic.groups => Icons.groups_outlined,
      StandardIconSemantic.history => Icons.history_outlined,
      StandardIconSemantic.hourglassTop => Icons.hourglass_top,
      StandardIconSemantic.image => Icons.image_outlined,
      StandardIconSemantic.info => Icons.info_outline,
      StandardIconSemantic.language => Icons.language,
      StandardIconSemantic.layers => Icons.layers_outlined,
      StandardIconSemantic.logout => Icons.logout,
      StandardIconSemantic.meetingRoom => Icons.meeting_room_outlined,
      StandardIconSemantic.moreHoriz => Icons.more_horiz,
      StandardIconSemantic.north => Icons.north,
      StandardIconSemantic.outbox => Icons.outbox_outlined,
      StandardIconSemantic.people => Icons.people_outline,
      StandardIconSemantic.personAddAlt => Icons.person_add_alt_outlined,
      StandardIconSemantic.person => Icons.person_outline,
      StandardIconSemantic.personRemove => Icons.person_remove_outlined,
      StandardIconSemantic.public => Icons.public,
      StandardIconSemantic.radioButtonChecked => Icons.radio_button_checked,
      StandardIconSemantic.radioButtonOff => Icons.radio_button_off,
      StandardIconSemantic.radioButtonUnchecked => Icons.radio_button_unchecked,
      StandardIconSemantic.refresh => Icons.refresh,
      StandardIconSemantic.rocketLaunch => Icons.rocket_launch_outlined,
      StandardIconSemantic.schedule => Icons.schedule,
      StandardIconSemantic.search => Icons.search,
      StandardIconSemantic.send => Icons.send_outlined,
      StandardIconSemantic.share => Icons.share_outlined,
      StandardIconSemantic.south => Icons.south,
      StandardIconSemantic.sportsEsports => Icons.sports_esports_outlined,
      StandardIconSemantic.swapHoriz => Icons.swap_horiz,
      StandardIconSemantic.unfoldLess => Icons.unfold_less,
      StandardIconSemantic.unfoldMore => Icons.unfold_more,
      StandardIconSemantic.verifiedUser => Icons.verified_user_outlined,
      StandardIconSemantic.visibility => Icons.visibility_outlined,
      StandardIconSemantic.warningAmber => Icons.warning_amber_outlined,
    },
    size: size,
    color: color,
    semanticLabel: semanticLabel,
    textDirection: textDirection,
  );
}
