// WPF catalog snapshot from StarBridge.Core/Fleets/LegacyFleetTagCatalog.cs.
// A parity test compares every field and its order. No independent taxonomy.
import 'community_creation_port.dart';

abstract final class LegacyCommunityTagCatalog {
  static const categories = <CommunityTagCategory>[
    CommunityTagCategory("core", "玩法主轴", "#38B8F2", "舰队最核心的活动方向。"),
    CommunityTagCategory("combat", "战斗类型", "#E08A92", "舰队偏好的武装行动与战术类型。"),
    CommunityTagCategory("industry", "工业与资源", "#D6B56A", "采集、维修、补给与资源生产相关玩法。"),
    CommunityTagCategory("trade", "运输与贸易", "#8FBDEB", "货运、贸易、走私和物流组织方式。"),
    CommunityTagCategory("exploration", "探索与情报", "#75C9D6", "侦察、探索、情报和路线发现。"),
    CommunityTagCategory("support", "支援与医疗", "#7EDBA0", "医疗、救援、补给和战场支援。"),
    CommunityTagCategory("scale", "行动规模", "#A7B9C8", "舰队活动的常见人数和节奏。"),
    CommunityTagCategory("style", "组织风格", "#C99CFF", "成员协作、纪律和社群氛围。"),
    CommunityTagCategory("ship", "舰船偏好", "#9DAAB3", "舰队常用舰种和载具倾向。"),
  ];
  static const tags = <CommunityTagOption>[
    CommunityTagOption("core_combat", "战斗", "core", "以武装行动、火力对抗和战术执行为核心。"),
    CommunityTagOption("core_industry", "工业", "core", "以采集、制造、维修和资源产出为核心。"),
    CommunityTagOption(
      "core_exploration",
      "探索",
      "core",
      "以侦察、远航、地点发现和情报收集为核心。",
    ),
    CommunityTagOption("core_commerce", "商业", "core", "以交易、经营、市场和收益为核心。"),
    CommunityTagOption("core_logistics", "后勤", "core", "以运输、补给、保障和舰队支援为核心。"),
    CommunityTagOption("core_social", "社交", "core", "以休闲开黑、社区活动和成员交流为核心。"),
    CommunityTagOption("combat_pvp", "PVP", "combat", "面向玩家对抗的行动。"),
    CommunityTagOption("combat_pve", "PVE", "combat", "面向环境任务和非玩家目标的行动。"),
    CommunityTagOption("combat_fps", "FPS", "combat", "以步兵、室内和地面人员战斗为主。"),
    CommunityTagOption("combat_dogfight", "狗斗", "combat", "以小型舰机动空战为主。"),
    CommunityTagOption("combat_air", "空战", "combat", "以舰船空中或太空战斗为主。"),
    CommunityTagOption("combat_ground", "地面战斗", "combat", "以地面载具、据点和地面火力为主。"),
    CommunityTagOption(
      "combat_boarding",
      "登船作战",
      "combat",
      "以登船、清舱、夺控和船内交战为主。",
    ),
    CommunityTagOption("combat_escort", "护航", "combat", "保护运输舰、工业船、目标船或任务对象。"),
    CommunityTagOption(
      "combat_interdiction",
      "拦截",
      "combat",
      "拦截目标、封控航线或阻止敌方撤离。",
    ),
    CommunityTagOption("combat_bounty", "赏金", "combat", "以赏金目标追踪和击杀为主。"),
    CommunityTagOption("combat_security", "安保", "combat", "巡逻、护卫、区域安全和防御行动。"),
    CommunityTagOption("combat_piracy", "海盗", "combat", "偏非法或灰色地带的掠夺玩法。"),
    CommunityTagOption(
      "combat_privateering",
      "私掠",
      "combat",
      "带组织目标的武装掠夺或半合法行动。",
    ),
    CommunityTagOption(
      "combat_mercenary",
      "佣兵",
      "combat",
      "接取战斗委托或作为外包武装力量行动。",
    ),
    CommunityTagOption(
      "combat_anti_piracy",
      "反海盗",
      "combat",
      "打击海盗、护卫商队和保护民用目标。",
    ),
    CommunityTagOption("industry_mining", "采矿", "industry", "矿物采集、矿船协作和矿区行动。"),
    CommunityTagOption("industry_salvage", "打捞", "industry", "残骸回收、材料回收和清场行动。"),
    CommunityTagOption(
      "industry_manufacturing",
      "制造",
      "industry",
      "面向生产、加工和制造链路的组织活动。",
    ),
    CommunityTagOption(
      "industry_repair",
      "维修",
      "industry",
      "为舰船、载具或行动单位提供维修支持。",
    ),
    CommunityTagOption(
      "industry_resupply",
      "补给",
      "industry",
      "提供燃料、弹药、装备或行动物资。",
    ),
    CommunityTagOption(
      "industry_engineering",
      "工程",
      "industry",
      "偏工程维护、系统支持和舰队技术保障。",
    ),
    CommunityTagOption(
      "industry_gathering",
      "资源采集",
      "industry",
      "泛资源采集玩法，不限定单一职业。",
    ),
    CommunityTagOption(
      "industry_wikelo",
      "维克洛",
      "industry",
      "以物换物、交换资源或非货币交易玩法。",
    ),
    CommunityTagOption("trade_cargo", "货运", "trade", "货物运输、仓储和物流线路。"),
    CommunityTagOption("trade_trading", "贸易", "trade", "购买、出售、倒卖和市场收益玩法。"),
    CommunityTagOption("trade_smuggling", "走私", "trade", "高风险或非法货物运输。"),
    CommunityTagOption("trade_courier", "快递", "trade", "小型运输、短线投递和快速交付。"),
    CommunityTagOption(
      "trade_bulk_transport",
      "大宗运输",
      "trade",
      "大规模货物调度和多船运输。",
    ),
    CommunityTagOption("trade_personnel", "人员运输", "trade", "运送成员、乘客或任务人员。"),
    CommunityTagOption("trade_merchant_fleet", "商队", "trade", "长线贸易或多船商业行动。"),
    CommunityTagOption("trade_logistics", "物流", "trade", "物资、船只、人员和装备流转。"),
    CommunityTagOption(
      "exploration_deep_space",
      "深空探索",
      "exploration",
      "远距离探索、长线航行和未知区域活动。",
    ),
    CommunityTagOption(
      "exploration_scouting",
      "侦察",
      "exploration",
      "前出观察、目标确认和路线探测。",
    ),
    CommunityTagOption(
      "exploration_intel",
      "情报",
      "exploration",
      "收集、整理和共享行动信息。",
    ),
    CommunityTagOption(
      "exploration_route",
      "路线勘测",
      "exploration",
      "记录航线、跳点、风险点和补给路线。",
    ),
    CommunityTagOption(
      "exploration_location",
      "地点发现",
      "exploration",
      "寻找地点、据点、资源点或特殊目标。",
    ),
    CommunityTagOption(
      "exploration_beacon",
      "信标响应",
      "exploration",
      "响应求救、任务信标或临时事件。",
    ),
    CommunityTagOption(
      "exploration_expedition",
      "远征",
      "exploration",
      "长时间、多目标的探索行动。",
    ),
    CommunityTagOption(
      "exploration_infiltration",
      "渗透侦察",
      "exploration",
      "隐蔽进入、观察和情报回传。",
    ),
    CommunityTagOption(
      "exploration_data",
      "数据收集",
      "exploration",
      "记录服务器、位置、舰船、目标或行动数据。",
    ),
    CommunityTagOption("support_medical", "医疗", "support", "治疗、复活、医疗船和战场救护。"),
    CommunityTagOption("support_rescue", "救援", "support", "救人、救船、救场和紧急响应。"),
    CommunityTagOption(
      "support_search_rescue",
      "搜救",
      "support",
      "搜索失联成员、事故地点或目标对象。",
    ),
    CommunityTagOption("support_refuel", "加油", "support", "提供燃料支援和续航保障。"),
    CommunityTagOption("support_towing", "牵引", "support", "拖船、移动受损舰船或处理残骸位置。"),
    CommunityTagOption("support_rear", "后勤支援", "support", "行动后方保障、补给和人员协调。"),
    CommunityTagOption(
      "support_battlefield",
      "战场支援",
      "support",
      "在战斗中提供治疗、维修、补给或辅助。",
    ),
    CommunityTagOption(
      "support_emergency",
      "应急响应",
      "support",
      "快速处理突发状况和高优先级求助。",
    ),
    CommunityTagOption(
      "scale_solo_friendly",
      "单人友好",
      "scale",
      "单人玩家也能参与，不强制编队。",
    ),
    CommunityTagOption("scale_squad_ops", "小队行动", "scale", "以少量成员协同为主。"),
    CommunityTagOption(
      "scale_medium_fleet",
      "中型舰队",
      "scale",
      "多小队或多职责配合的行动规模。",
    ),
    CommunityTagOption("scale_large_fleet", "大型舰队", "scale", "大规模成员、舰船和指挥协作。"),
    CommunityTagOption("scale_regular", "定期活动", "scale", "有固定或较稳定的活动安排。"),
    CommunityTagOption("scale_long", "长线行动", "scale", "持续时间较长或跨阶段推进。"),
    CommunityTagOption("scale_quick", "快速任务", "scale", "短时间完成，适合临时参与。"),
    CommunityTagOption("scale_weekend", "周末活动", "scale", "主要集中在周末组织。"),
    CommunityTagOption("style_casual", "休闲", "style", "轻松开黑，不强调高压纪律。"),
    CommunityTagOption("style_hardcore", "硬核", "style", "高投入、高执行要求和高协作密度。"),
    CommunityTagOption("style_beginner", "新手友好", "style", "欢迎新玩家，并提供基础帮助。"),
    CommunityTagOption("style_training", "教学", "style", "以带新、训练和机制讲解为重点。"),
    CommunityTagOption("style_disciplined", "组织严谨", "style", "有明确纪律、流程和行动规范。"),
    CommunityTagOption("style_milsim", "军事模拟", "style", "偏拟真指挥、编制和战术执行。"),
    CommunityTagOption("style_roleplay", "角色扮演", "style", "重视角色设定、叙事和沉浸式互动。"),
    CommunityTagOption("style_freeform", "自由活动", "style", "成员可自由安排，不强制参与。"),
    CommunityTagOption("style_command", "指挥体系", "style", "有明确指挥层级和调度分工。"),
    CommunityTagOption(
      "style_squad_autonomy",
      "小队自治",
      "style",
      "小队可独立决策和组织行动。",
    ),
    CommunityTagOption("ship_small", "小型舰", "ship", "偏好小型舰、单人船或轻型行动。"),
    CommunityTagOption("ship_medium", "中型舰", "ship", "偏好中型多用途舰船和小队协作。"),
    CommunityTagOption("ship_large", "大型舰", "ship", "偏好大型舰船、多岗位和多人协作。"),
    CommunityTagOption("ship_capital", "旗舰", "ship", "拥有或围绕旗舰级舰船组织行动。"),
    CommunityTagOption("ship_carrier", "舰载机", "ship", "使用舰载机、机库和母舰协同玩法。"),
    CommunityTagOption("ship_multiship", "多船协同", "ship", "多舰种、多职责协同执行。"),
    CommunityTagOption(
      "ship_ground_vehicle",
      "地面载具",
      "ship",
      "地面车辆、登陆和地面支援参与较多。",
    ),
    CommunityTagOption(
      "ship_heavy_firepower",
      "重型火力",
      "ship",
      "偏重火力舰船、炮艇或大型火力平台。",
    ),
    CommunityTagOption("ship_specialist", "专业船队", "ship", "按职业船、工业船或专门舰种编组。"),
  ];
  static const options = CommunityCreationOptions(
    categories: categories,
    tags: tags,
    maxTags: 5,
    timeZones: [CommunityTimeZone('UTC', 'UTC')],
    defaultTimeZoneId: 'UTC',
    defaultActiveFrom: '19:00',
    defaultActiveTo: '22:00',
    defaultSystem: 'stanton',
  );
}
