file(READ "${SB_VERSION_FILE}" SB_VERSION_XML)
if(NOT SB_VERSION_XML MATCHES "<StarBridgeVersion>([0-9]+\\.[0-9]+\\.[0-9]+(\\.[0-9]+)?)</StarBridgeVersion>")
  message(FATAL_ERROR "Missing or invalid canonical StarBridge product version")
endif()
set(SB_PRODUCT_VERSION "${CMAKE_MATCH_1}")
string(REPLACE "." ";" SB_VERSION_PARTS "${SB_PRODUCT_VERSION}")
list(LENGTH SB_VERSION_PARTS SB_VERSION_COUNT)
if(SB_VERSION_COUNT EQUAL 3)
  list(APPEND SB_VERSION_PARTS 0)
endif()
foreach(SB_PART IN LISTS SB_VERSION_PARTS)
  if(SB_PART GREATER 65535)
    message(FATAL_ERROR "StarBridge version exceeds Windows version resource limits")
  endif()
endforeach()
string(REPLACE ";" "," SB_PRODUCT_VERSION_NUMBER "${SB_VERSION_PARTS}")
