cmake_minimum_required(VERSION 3.14)
set(SB_RUNTIME "${CMAKE_CURRENT_LIST_DIR}/../../cmake/native_runtime.cmake")
set(ENV{STARBRIDGE_TARGET_PLATFORM_VERSION} "")
include("${SB_RUNTIME}")
if(NOT SB_NATIVE_FRAMEWORK STREQUAL "net8.0-windows10.0.22621.0")
  message(FATAL_ERROR "Managed default framework changed")
endif()
unset(STARBRIDGE_TARGET_PLATFORM_VERSION CACHE)
unset(STARBRIDGE_TARGET_PLATFORM_VERSION)
set(ENV{STARBRIDGE_TARGET_PLATFORM_VERSION} "10.0.26100.0")
include("${SB_RUNTIME}")
if(NOT SB_NATIVE_FRAMEWORK STREQUAL "net8.0-windows10.0.26100.0" OR
   NOT SB_NATIVE_SDK_PROPERTY STREQUAL "-p:StarBridgeTargetPlatformVersion=10.0.26100.0")
  message(FATAL_ERROR "Managed build and staging SDK diverged")
endif()
message(STATUS "PASS managed SDK build/staging selection")
