cmake_minimum_required(VERSION 3.14)
get_filename_component(SB_RUNNER "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
foreach(SB_CASE empty false true other)
  set(FLUTTER_TOOL_ENVIRONMENT "")
  if(SB_CASE STREQUAL "true")
    set(FLUTTER_TOOL_ENVIRONMENT "DART_DEFINES=abc,U1RBUkJSSURHRV9FTkFCTEVfTUVOVV9PVkVSTEFZPXRydWU=,def")
  elseif(SB_CASE STREQUAL "false")
    set(FLUTTER_TOOL_ENVIRONMENT "DART_DEFINES=U1RBUkJSSURHRV9FTkFCTEVfTUVOVV9PVkVSTEFZPWZhbHNl")
  elseif(SB_CASE STREQUAL "other")
    set(FLUTTER_TOOL_ENVIRONMENT "OTHER=U1RBUkJSSURHRV9FTkFCTEVfTUVOVV9PVkVSTEFZPXRydWU=")
  endif()
  include("${SB_RUNNER}/product_features.cmake")
  if(SB_CASE STREQUAL "true")
    if(NOT STARBRIDGE_MENU_ENABLED)
      message(FATAL_ERROR "Explicit development opt-in did not enable menu")
    endif()
  elseif(STARBRIDGE_MENU_ENABLED)
    message(FATAL_ERROR "Menu enabled without exact opt-in: ${SB_CASE}")
  endif()
endforeach()
set(SB_VERSION_FILE "${SB_RUNNER}/../../../Directory.Build.props")
include("${SB_RUNNER}/product_version.cmake")
if(NOT SB_PRODUCT_VERSION STREQUAL "0.7.0.1" OR
   NOT SB_PRODUCT_VERSION_NUMBER STREQUAL "0,7,0,1")
  message(FATAL_ERROR "0.7.0.1 product version contract failed")
endif()
message(STATUS "PASS menu native build gates and canonical four-part version")
